>prot (#) default: single protein sequence description=t0373 /home/ppuser/server/work/predict_h8423
MPTNQDLQLA AHLRSQVTTL TRRLRREAQA DPVQFSQLVV LGAIDRLGGD
VTPSELAAAE RMRSSNLAAL LRELERGGLI VRHADPQDGR RTRVSLSSEG
RRNLYGNRAK REEWLVRAMH ACLDESERAL LAAAGPLLTR LAQFEEP
