>prot (#) default: single protein sequence description=t0357 /home/ppuser/server/work/predict_h26139
MVKFACRAIT RGRAEGEALV TKEYISFLGG IDKETGIVKE DCEIKGESVA
GRILVFPGGK GSTVGSYVLL NLRKNGVAPK AIINKKTETI IAVGAAMAEI
PLVEVRDEKF FEAVKTGDRV VVNADEGYVE LIELEHHHHH H
