>prot (#) default: single protein sequence description=t0381 /home/ppuser/server/work/predict_h15391
MTATEPTEKI LPSPDYVQSL ARGLAVIRCF DHRNQRRTLS DVARATDLTR
ATARRFLLTL VELGYVATDG SAFWLTPRVL ELGYSYLSSL SLPEVAQPHL
EKLSHKVHES SSVSILDGAD IVYVARVPVS RIMTVGITIG TRLPAYATSM
GRVLLAGLPD DELDAYLEKL DIQRLTERTI TARDELKAAI LAVRADGICV
LDQELEAGLR SMAAPIRGAS GLTVAAVNIS TPAARYSLED LHSDLIPSLR
VTATDIEQDL ATVNR
