>query  (#) default: single protein sequence resfilename=c8shwf63 description=peropsin /nfs/data5/users/ppuser/server/work/predict_h11992
MLRNNLGNSS DSKNEDGSVF SQTEHNIVAT YLIMAGMISI ISNIIVLGIF
IKYKELRTPT NAIIINLAVT DIGVSSIGYP MSAASDLYGS WKFGYAGCQV
YAGLNIFFGM ASIGLLTVVA VDRYLTICLP DVGRRMTTNT YIGLILGAWI
NGLFWALMPI IGWASYAPDP TGATCTINWR KNDRSFVSYT MTVIAINFIV
PLTVMFYCYY HVTLSIKHHT TSDCTESLNR DWSDQIDVTK MSVIMICMFL
VAWSPYSIVC LWASFGDPKK IPPPMAIIAP LFAKSSTFYN PCIYVVANKK
FRRAMLAMFK CQTHQTMPVT SILPMDVSQN PLASGRI
