>query
 MAHHHHHHSL NQINIEIAYA FPERYYLKSF QVDEGITVQT AITQSGILSQ
 FPEIDLSTNK IGIFSRPIKL TDVLKEGDRI EIYRPLLADP KEIRREG   
>Y395_HAEIN
 .........M NQINIEIAYA FPERYYLKSF QVDEGITVQT AITQSGILSQ
 FPEIDLSTNK IGIFSRPIKL TDVLKEGDRI EIYRPLLADP KEIRRK.   
>Q3JBU8_NITOC
 ........SV KMMTVEVAYA RPDKQVILKA SVPENTTLEA AIQASGILEQ
 FPEIDLDKNK VGIFGKLSKR DAPLCFGNRI EIYRPLIADP KQARRE.   
>Q65V45_MANSM
 .........M AQINIEITYA FPEHYYLKKF TLDEGTTVQS AILQSGILQQ
 FTDIDLRENK IGIFSRPVKL TDSLNDGDRI EIYRPLLADP KEIRRK.   
>Y646_VIBPA
 .......... DMIHVEVVYA LPHEQRVFNL VVNNHATVEE IIRQSGVLEL
 YPEIDLAKNK VGVFSRNVKL DATVRDKDRI EIYRPLLADP KEIRRK.   
>Q3SI26_THIDA
 .......... ..LNVEVVYA LPSEQPLLNV QLAEGATVED AIRASGVLEA
 FPEIDLARNK VGIFSKLVKL NEPVRDRDRV EIYRPLIADP KEVRRK.   
>Y3376_PHOLL
 .........M SDINVEVVYA LPDRQYLRTV KLAQGSTVEQ AIVASGLLTL
 RNDIDLQKNK LGVYSRPVKL TDILEEGDRV EIYRPLLADP KEMRRK.   
>Q3YYQ0_SHISS
 .......... .KIAVEVAYA LPEKQYLQRV TLQEGATVEE AIRASGLLEL
 RTDIDLTKNK VGIYSRPAKL SDSVHDGDRV EIYRPLIADP KELRRQ.   
>Q3CVZ7_ALTAT
 .......... .QINLEVAYA LPDRQALLEV VVEMGHTVEE AIKASGILQR
 FDDIDLSKSK VGIWNRTCKL SDVPQDGDRI EIYRPLIADP KEARR..   
>Q47DK5_DECAR
 .......... EMLNIEVCYA LPNKQELVRV KLPEGALVQQ ALEASGLLDK
 YPEIDLKKNK FGIWNKLSKV DSVLRDKDRV EIYLPLIADP KEVRKQ.   
>Y3462_CHRVO
 .......... EKLSVEVAYA RPDRQWLVAL TLPAGATALD AALASGILEA
 CPELDRTALK LGVFGKAAKP DAALREHDRV EIYRPLLADP KEVRRQ.   
>Y1103_YERPE
 .........M PDIRVEVVYA LSERQYLRTV SLVVGSTVED AIKASGLLEL
 RPDIDLEKNK VGIYSRPVKL GDKLNDGDRV EIYRPLIADP KELRRQ.   
>Q2NRZ8_SODGM
 .........M PDIRVEVVYA LPERQYLRQL VLEEGSTLEQ AIHASGLLAL
 RQDIDLSVNK VGIFSRPAKL EDTLSDGDRV EIYRPLLIDP KELRRQ.   
>Q603I8_METCA
 .......... ..MNVGVCYA DADRQLWLRM EMPDDSTVEQ AIRYSGILER
 FPEIDLSVQK VGIFGKLVKL DAPVKEGDRI EIYRPITADP KTVRR..   
>Q33VX3_9GAMM
 .......... DKFAVEVIYA LPTQQKRISV MVSPGTSCIE AVKQSDICRF
 FPEIDLDKVK LGIFSRAVKH DEVLEPGQRV EIYRPLIADP KDVRRQ.   
>Q5QW49_IDILO
 .......... NKLTIEVAYA TPDKQVLLTV HPQEGATVEE CIRMSDVLEQ
 FPEIDLEQQK VGIWNKTVKL NAQPRDGDRI EIYRPLIADP KAVRK..   
>Q3QJP1_9GAMM
 .........I EKFGVDVVYA LPHKQKVIHV MVSPGTTFIE AVRQSNICSF
 FPEIELDSVK LGSFSRLVKH DDQLQPGNRV EIYRPLIADP KDVRRQ.   
>Q3F2H7_9BURK
 .......... .MLSIEVCYA LPDRQTLIPV SLPEGATVRA AIDASGVLAL
 HPEIDLAHAK TGVFGKLAPL DAPLADHDRV EIYRPLIVDP KLARQ..   
>Q5P533_AZOSE
 .......... ..MKIGVAYS EPSHQVWLNL EVPDGTTVGA AIERSGILAQ
 FPHIDLTVQK VGVFAKVVKL DTPLRHGDRV EIYRPITCDP KAVRKK.   
>Q6SFV2_9BACT
 .......... ..MIVEVAYA LPDKQSLVSL EVEKGTTLKE AIEASGILDS
 FEQIDLTKDR VGIFSKFATL DTVLREKDRV EIYRPLIADP KKVRKE.   
>Q2W402_MAGMM
 .......... ..MKIGVVYA LPSRQSWLSI DVPEGTTVKE AIQKSGILNQ
 FPEIDLETQK VGIFGKAAAL DAVVEEGARI EIYRPITVDP KTVK...   
>Q34ZG1_9GAMM
 ........AE QMMTVEVAYA EPDEQVLLTV EVPEGATVEE AIERSGVLQR
 FPDIDLDVNK VGVFGKLRKR SDVLRPYDRV EIYRPLQADP KESRR..   
>Q5NYE2_AZOSE
 .......... DLINVEVTYA LPQVQELLKV RVPEGATVRD AIEASGILAK
 HPEIDLDPNK VGVFAKLSRL DTTLRDRDRV EIYRPLIADP KAVRKK.   
>Q2Y9R7_NITMU
 .......... ..IDIEVVYA LPERQVVRQM NLPEGTTVEQ AVKLSGILPR
 FPEIDLLKNK LGIYGKLVPP TTVLRDRDRI EIYRTLRVDP KEARRK.   
>Q6LUB2_PHOPR
 .......... ..IHVEVVYA LPNNQRVIKL AINFETDVQE IIEQSGILAM
 FPEIDLKKNK IGVYSRNVKL NATVRDGDRI EIYRPLLADP KEIRRK.   
>Q5NLH8_ZYMMO
 .......... ..MKISVAYA KPERQWWLEC EVKEGATIED GINASGILKR
 CPEIDLEKQK VGIFGKVAKL DAPLEEGMRI EIYRPLLVDP KTV....   
>Q6D8Y3_ERWCT
 .......... ..MQVDVVYA LPERQYLRTV KLEEGSTVEQ AIVASGLLEL
 RHDIDLQVNK IGIYSRAAKL ADVVQDGDRV EVYRPLIADP KELRRQ.   
>Y1005_NEIMA
 .......... .MLEIEIVYG LPDRQVLKTM QLAEGTTVRA AALQSGLDGI
 FEDLNLHSAP LGIFGKAVKD DTPLRDGDRI EVYRPLLIDP KEARRK.   
>Q3NZN5_9GAMM
 .......... DKFEVDVVYA LPHQQKIISV AVEPGTRFIE AVHLSQMVSF
 FPEIDLDTVK LGTFSRQVKH DDVIEPGQRV EIYRPLIADP KDVRRK.   
>Q47XI0_COLP3
 .......... DRVTIEVVYG VPHKQKILTL LVAEGSTVEQ AILDSGVITL
 FPEIDLKVNK VGVWNRAVKL SEVVNDLDRI EVYRPLIADP KDVRK..   
>Q2SWX4_BURTA
 .......... .MPKVQVCYA LPERQTLVAV DVPAGATVRD AIEASGLLAL
 HPDVDLATLK TGIFGKLAPL DAPVADGDRV ELYRPLIVDP KAARQ..   
>Q4ITA1_AZOVI
 .........M DKIAVEVVYA LADRQKLVSL SVPCGTTVRE AALRSGLDRD
 FPGLDLANSP LGVFGKVVPE ERVLEEGERV EIYRPLIADP KEIRK..   
>Q3NM11_SHEFR
 .......... EKFSVDVIYA LPKQQKIISV MVSPGTTFIE AVKQSDIIKF
 FPDINLEEVK LGVFSRQAKH DEVLVPGQRV EIYRPLIADP KDVRRK.   
>Q3IE34_PSEHT
 .......... .MIDVEVVFA LPETATSLTI EVVKGTTVEQ AVIQSGIIEK
 HPEIDATALT LGVWNRTVKP NQELKEGDRI EIYRPLIADP KDARRK.   
>Q2C7P4_9GAMM
 .......... ..IHVEVVYA LPNMQRVLKL AVVADTPIQE IIEQSGILGM
 YPDIDLKKNK VGIYSRNVKL DGTAREGDRI EIYRPLVADP REIRRK.   
>Q3XD84_METFL
 .......... .KFSIEVAYA LPSRQLILKL EVEPGTTAIE AARQSGIADH
 FEGLDIDTSR LGIFGKQVAA TTLLQAGDRV EIYRPLQADP KMARR..   
>Q2Z9T1_9GAMM
 .......... DKFVVDVIYA LPTQQKVISV SVLPGTSAID IVRQSNMVSF
 FPEIDLETVK LGVFSNVVKH DQVILPGQRV EIYRPLIADP KDVRR..   
>Q2SMN3_HAHCH
 .......... .KIQVEVAYA LPEQQKIIPL AVVEGTTAYE AVQMSGITHF
 FPQIELDSAK MGIFGKPEPK SHALREGDRV EIYRPLKIDP KQAR...   
>Q2CVX9_ECTHA
 ........SE GELGIEVVYA LPGQQTVLRV ELPAGSTAGD ALNASGVLER
 HPEIDLTRQS VGVFGQIVGL DTPLHNGDRV EVYRPLQVDP KE.....   
>YOM2_PSEAE
 .........M AEIAVEVVYA LPERQALLRL SVPAGTSARE AVLLSGIAEA
 FPGLDVQGCP LGIFGKLLAR ERVLEAGERV EIYRPLIADP KEVRKQ.   
>Q470F9_RALEJ
 .......... DMVRISVCYA RPDSVFLKEF DVLQGTTIAA AIVSSGVQQV
 CPEIDPSTMR VGIYGKLKTP DTVVRTGDRV EIYRALTADP KLARR..   
>Q3RJT8_RALME
 .......... ..VRLSVCYA RPDTVFLKEL DVPAGTTIIG VIEASGLTQA
 CPEVDPSTLR VGVYGKLKTL DTPVRQGDRV EVYRVLTADP KTARRK.   
>Y1828_HAEDU
 .......... SQIVVEIIYA YPDQYFLKKI SLDQPTTIQN VILQSGILAK
 YTEIDLRINK VGIFSRPAKL TDYVAHGDRI EIYRPLVADP KEIRRK.   
>Q47FY6_DECAR
 .......... ..MQIGVAYS EPSQQIWLNI EVPDESSVKE AIERSGILKQ
 FPHIDLSTQK VGVFGRLVKL DAALKPGDRI EIYRGIIADP ETVPR..   
>Q82X67_NITEU
 .......... ..ITIEVAFA LPQRQFLRRL QVPMGTSMYQ AIKLSGVENF
 YPGSDSTALK TGIHGKITDP ETILHQNDRI EIYRPLVIDP KEKRR..   
>Y4512_PSESM
 .......... ..IQIEVVYA TVQRQVLMTV DVPAGSSVRQ ALALCGMDRE
 FPELDLSHCP VGIFGKVVPA ARVLEAGERI EIYRPLLADP MEIRR..   
>Y244_BUCAP
 .........M NIIKVKVVYA LPDIQYIKEV HIDSNSTVKD AILASNLLNT
 VKNIQFYKNN VGIYNKLVHL NENVKNGDRI EIYRNLIIDP KERRRK.   
>Q3XNW7_9PROT
 .......... ..MRVAVTYA QPNRQLLLEF EVPEGTTAQQ AVERSGILSK
 FPDINLAEQK LGIYAKLVEN DQVLEEGDRV EIYRPAKGKP KKKER..   
>Q2BRB4_9GAMM
 .......... ..MIVEVAFA LPTEQKIISL NVPDDCTAYE AVIKSGITDI
 FPEIDPDNDP MGIFAKAIKK ETVLKEGQRV EIYRPLIADP KEARAK.   
>Q4KIH6_PSEF5
 ........AE PMISIEVAYA AVDRQALIRV QVPQGSTLRA ALQASAIGQQ
 FPELDLAACP VGIFGKQVSD PHVIQAGDRI EVYRPLLADP KEV....   
>Y1303_COXBU
 .......... .MISIIIAYA TPEKQVEIPL TVEESCTLVV AVKRSGILQQ
 FPEINLSQAI VGIHNKRTAL DAGLRDGDRI EIYRPLTMDP KQAR...   
>Q36QW9_MARHY
 .......... ..MEVEVAYA RPDKQQIVPV VVPPGTTALE AVKLSRITEI
 FPEIDPDAID MGVFGKVVKA EHVLREGDRV ELYRPLKIDP KQAR...   
>Q31FS1_THICR
 .......... ..MKIEVAYA LEDEQFLFEE DVEEGTTVDA ALKSSALLKK
 FPQLNIEH.. VGIFAQIVKP DHVLREGDRI EVYRPLKADP RDRRRK.   
>Y253_BUCAI
 .........M KIIKVTVVYA LPKIQYICQV DIALGSTVKD AILKSNLLNL
 TNDVSFHHNR IGIYNKTVHL KFKIKDGDRI EIYRNLTIDP KEWRR..   
>Q3IXC0_RHOS4
 .......... ..MIVGVAYA KPTVQVWKHV DVPEGTSARE AIERSGLLAQ
 FPEIDLAVNK VGIFGAICPL DRTLAEGDRV EIYRPI.... .......   
>Q3NCI3_9PROT
 .......... DFIIIEIVAA LTERHFIKRL QVPKGTLINQ AIKLAEMKEF
 YPEIDCSTLK IGIYGKVACS ETVLQQNDRI EIYRPLISDP KEKRK..   
>RNFH_RHOCA
 .......... ..MIVGVAYA KPTVQVWKHV DVPDTATARD AIEKSGLLDQ
 FPEIDLSTQK IGIFGQICPL EKPLKEGDRV EIYRPI.... .......   
>Q2L133_BORA1
 .......... NELRVTVCFA RQDEAWLREL LLPAGATVAD ALAASGFAQL
 FPGIDVWQAG VGIYGQRREA HTLLADGDRV EIYRALTFDP KE.....   
>Q2CRX7_ECTHA
 .......... ..LEVSVAYV EAGEHFWRCF QVPAGTNAAQ AVARSGLQQR
 FPHLDLSTLK LGVFAKPVKA DRVLEDGDRV EVYRPITADP .......   
>Q3KIA5_PSEPF
 .......... ..IEIEVVYA AVDRQVLRVI SVAEGTTVRA ALMASGIDAE
 FPELDLISCP LGIFGKVIAD PDAVQEGDRI EIYRPLLADP KEV....   
>RNFH_AZOVI
 .......... ..MRVSVVYA DPAKPLQLSC KVEDGCSVEQ AIQQSGVLRC
 CPDIDLKKQK VGVFGKFVKL DSPLKDGDRI EIYQ...... .......   
>Q5X817_LEGPA
 .......... .MVKVELVYI ANSKNCLHKM DLKQGATVEE ALIESNIYST
 CPET..RELP VGVYGKRVSV DQVLKEGDRI EIYRPLILDP KEKRRK.   
>RNFH_PSEST
 .......... ..MKISVVYA APRQPLLFDC RVAEGSSVAE AIEHSGVLRY
 CPDIDLSKQK VGVYGKFVKL DSPLKEGDRV EIYQ...... .......   
>Q6FDQ4_ACIAD
 .......... NQQNVWVAYA TQTQQFHIRV AFQQGMTAWQ AIESSGLLTQ
 V.EL.PQPYH LGIFGVRCVA DRLLEAGDRV EIYRPLTINP KDIRRK.   
>Q3FWH7_9BURK
 ........SD ARLQITVVYA RDVREVVLQL T..AGSTALQ ALQTSGLLQL
 FPALDPACLA LGVWGHKASL TQVLQDNDRL EIYRPLTVDP KVARRE.   
>Q2A444_FRATU
 .......... ..MKIEVIYA LANEQLSFFV EVDEVINVRQ SLKLSKITHK
 YPELDIESLK VGVYSQLVDL DYQLKDRDRV EIYRNLTIDP KQAR...   
>Q44DK0_CHRSL
 .......... .RIEVEVAYA EPHRQRVVAL AVVPGTSARD AVRQAALPSL
 FPERDFEQAP LGIFGQVLKA PHVLEAGDRV EVYRALALDP KQAR...   
>Q7WA39_BORPA
 .......... ..LRVTVCHA CPDGAWQRAV TLPAGATVAD AVAASGFAAA
 HRGQDPWAHG VGVFGKAQAA DAPLADGDRV EIYRGLSFDP KE.....   
>Q4B2U8_9BURK
 .......... ..MKIWLVYS PAPRQVWV.L ELAAGTTAAQ ALAVCGIFEE
 FPSLRDTRLV MGIWGRKISL GHTLNDSDRL EIYRGLEVDP KVARRE.   
>Q2P466_XANOM
 .......... ..MRIEVVLA WPDHYSAVQL DLPDGATVAD AVALSSLLEQ
 APAAHA.... ..VHGVIARP EQVLREGDRV ELLRPLLLDP KQARR..   
>Y1426_RALSO
 .......... ERIDVMVCLA TVTPPKLVQV QVSATATVAD AVRASGLLEE
 V.GLSIDACR LGVYGKRKAP DALLHAHDRV EITGPLIADP K......   
>Q3R9L9_XYLFA
 .......... ..MRVEVLIA WPDRVHCCEI MLQEGARVVD AVEMAALNGI
 EQAVGYA... ..VFGVLVTS DHVLNDGDRV ELLRPLLIDP KEARR..   
>Y234_BUCBP
 .......... .MITITIVYF TNKIQHVKKI KLNIGTPVHE ALK...ILQ.
 ...INIKKNK IGIYGELVSL NHILNNKDRL EIYRPLKINP RELRKQ.   
>Q3BVC4_XANC5
 .......... ..MRIEVVLA WPDRYSSVHL ELPEGATVAE AVAMSGLAVE
 RAPAAYA... ..VHGLIARP EQGLRDGDRV ELLRPLLLDP KEARR..   
>Q4UT05_XANC8
 .......... ..MRVEVIVA WPDRYSAVQL ELAEGATVAE AVAASGFAG.
 ......DQAL VGVHGVIATP AQVLRDGDRV ELLRPLLLDP KE.....   
>Q3GQI4_9GAMM
 .......... .MITVYLAYA EAQSQHYLTL SVADGTTLYA ALKQAGWLIQ
 FEGIDVAVPH VGIYAQKQPL NYQLQPFDRI EVYRSLSADP MSQRK..   
>Q8TTF8_METAC
 .......... .......... .......IEV DVRDPHSVQI AV..SSIIER
 FGKIDIAVNN AGITG...PA NTPLQDLD.I EIWR...... .......   
