>query
 MAMLYLIFYD ITDDNLRNRV AEFLKKKGLD RIQYSVFMGD LNSSRLKDVE
 AGLKIIGNRK KLQEDERFFI LIVPITENQF RERIVIGYSG SEREEKSNVV

>Q4J7D1_SULAC
 ..MLYVVFYD ISDDDLRGKV ADFLKKKGLV RLQFSVFFGE LNSSRVKDLT
 AGLRLYAKR. .RSEGERFNV LILPVTETQF KQRIVIGGSG EHEERDSNVL

>Q2CMX8_9EURY
 ..MLVWVIYD ISDDRTRSRV AKICKNYGLY RVQKSAFLGD LNRNESDSLA
 LEC....... ESVIEDTDSV YVFPMCEDCF DKIKLIGTGF DRE.......

>Q977B8_SULTO
 ..MLYIVFYD ISDDGMRNRV ADVLKKKGLV RVQYSVFIGD LNSARLKDVV
 ASLRVLYRSN K...EGRFSV MILPVTQAMF NQRIMIGDEF KENEDK..II

>Q8PZD6_METMA
 ..MLVWVIYD ITENRIRQKV SDCCKSYGLY RVQKSVFLGD LNSNDRDSLA
 LEC......E EWIDTEKDSV YVFPMDEQSF KQVKLIGQAF DKE.......

>O28403_ARCFU
 ..MLHLVVYD ISDDGSRARL AKLLEKFGLQ RVQYSAFRGE LNPNDREVLA
 RQV......G KFVRDDRDCI FIIPLCQRCS STAIVISNTG VELVKEKGV.

>Q2AER9_9FIRM
 ..MLVWFIYD IVEDKPRKKI ADKAIEQGLY RVQKSVFLGD IEPNLLDELL
 VYA......E ELIDPENDSV YAFPMCQEDF KKVEIIGQAF DK........

>Q2JRT7_SYNJA
 ...LYVVTYD TPCDKRRKKI ADLLEGYG.K RVQYSVFECV LDKDKFEELK
 LRLR...... KRVKPDEDSV RFYPLTSHAL DQVEIWGGPP LTAPPHSIVV

>Q2RV91_RHORT
 ...RYVICYD IVDDKRRLKV AKCLDSYG.S RVQFSVFE.. ....VLVSKP
 LMTRMVRELG ALINAKTDRI SIYPQCATCD ARRTDLGATV EKPVHEPWII

>Q2LQY0_SYNAS
 ..MNMIVAYD IADPKRIALV ARILKDYG.V RVQKSIFEVD VNGGVFAVMK
 ERVEQV.... ..IIPAEDGV KYFPLCRKCI GMVEIIGQGF YTNPDEEYYI

>Q4CFW8_CLOTM
 ..MLTWVIYD IASNKTRNNI IKKCKNAGLY RVQKSVFLGD IESNKFDELK
 LELDSI.... ..IDKDNDSV YMFTMTKAEL NKAGLLGQAF DKE.......

>Q2JVY8_SYNJA
 ..MLWLVCYD VVDDKRRHQL AKRLEQC.CQ RVQYSVFECP LDTAELEE..
 ...KLEKSWL PLLNLQEDSL RAYPLDASAK QRTKVFGGP. ..........

>Q96X74_SULTO
 .KMWVIVVYD ISDDEKRNKI ARELQRLGLS RIQRSAFVGD IDSQRFKDLV
 RIM......G KLVTGKDDIL HIIPLGLRDW ERRVVINGDS VRREAVS...

>Q97Y85_SULSO
 ..MKLLVVYD VSDDSKRNKL ANNLKKLGLE RIQRSAFEGD IDSQRVKDLV
 RVVKLI.... ..VDTNTDIV HIIPLGIRDW ERRIVIGREG LEE.......

>Q6ZEA5_SYNY3
 ...LYVIAYD IPDDRRRKKM ADLLEGYG.Q RVQYSVFECT LSKSKFNELQ
 KRLRKIYQSE E......DSL RFYPLSGHTL TQVDIWGEPP LTKPPGSVIV

>Q3M5G0_ANAVT
 ..MYLVISYD VPEDKRRTKI HKVLKSYGQW .MQYSVFECD LTPTQYAKLR
 SRL......A KLIKPDQDSI RFYHLCACCQ GKVERIGGE. ..........

>Q3E4G8_CHLAU
 MKMFTVISYD IVDDQRRTSV MKVLKGYG.V RVQYSVFEAI LDAREFHDLS
 NQLR...... KIIDPGQDSI RCYRLDQVA. AQRTVIYGIG LT........

>Q2LQY1_SYNAS
 ..MIVLITYD ITEPKRLTAL HHFLKEFGL. NTQKSVFECD IDEAGIRKIR
 AYCRNNLNIA K......DSV RIYKICSRCI NKVVLSGLGL KVTQLEYTVI

>Q7MTH8_PORGI
 ....LLVAYD ISSNRRRRKV ARILEQCGI. RINKSVFICS LRELTMDKLV
 EAVT...... .SQTAKRDKV FFLPLCQHCY TAAWMSGHPT SRRKRKSIVV

>Q8ZZL9_PYRAE
 ..MYVVVAYD ITEDEVRNKV ADALKAYGLE RIQRSVFVGR INPALLKDLV
 ERLKRITK.. ....GANADI TIFKVDRRAI DTAIRIG... ..........

>Q3IQ68_NATPD
 MTMRLAVAYD VSDDTNRRHV YRTLQRYGAW R.QYSVFELE ISKTDRVELE
 AELESHIDPS A.....GDRI RIYRLCSACQ DATTDIGN.. DPPDGQSNVI

>Q8YZS5_ANASP
 MTKLYLVCYD IPDDKRRTKL AKLIEQR.CQ RVQYSVFECP LEESVLN...
 ..YQLEKRWL PILKLSEDSL RVYPLDATAK QQTRVYGGE. ..........

>Q3MYN9_9DELT
 ..MFYVVSYD ISDDRVRYRV AKVLKAYG.V RVQKSVFECD LTEKRFLKMK
 DRL......E ALIDFTTDSV RYYRQCRGCL AQCEVSG... ..........

>Q43H30_9CHLB
 ....MLVSYD ICDIKRLPRV AKLMEGYG.V RVQYSVFECS LTQRQLMELQ
 RRLKR..... .LIKPEVDSV RFYPLCESCR DEIVILGQGT VSR.DEPYYI

>Q2CL64_9EURY
 ..MRLAVTYD ISDNRIRTRV FRILESYGAW K.QYSVFE.. LEISDVQRLE
 MEAKI..... KSVIKPGDKV RIYELCERCV GAIVEIGEKS PTR..KSNVI

>Q5X8T4_LEGPA
 ....YIVSYD IRDNSIRRTI YERLKDIGLT PVQKSVFWGY LN.......E
 PEKRYLTNFL KKELAKQDTA FITPCKLAQE YEVNLINLEL DELRKPDGHI

>Q2FL79_METHJ
 ....LIVCYD VEKTKDRNKV IKVLEYYGLI RVQYSVFMGS LTETRLHQMN
 ARIKREFTKP SI......KI LVIEVCNACM ERALLVHEEL PKVNRQFEVI

>Q7MC42_VIBVY
 ....YVICYD ISERQTRYRV EKALLGYG.E RVQYSVFECR LTTGQFFALR
 HELRRWLE.. .....DGDRV NYFRLCLHCQ RRR....... ..........

>Q3E2G4_CHLAU
 .AMQCLVIYD IPNDRARQRV ADACLDYGLQ RIQYSAFAGN LSRT......
 HQRALFGEIT RRVKGHTANV QLFVFDSKTW SDRRILEQQY DD........

>Q6ZEC6_SYNY3
 ...FWLVCYD VRDDKRRRKL AKLLEQR.CQ RVQYSVFECP LPEKVLTDLL
 HR.....RWL KELNLKEDSL RAYPLQRQSR SQAKIFG... ..........

>Q4APW2_9CHLB
 ...FILVTYD IENDRRRTKI HKILSNFG.E PVQYSVFECF ISEGDFEEMR
 KKLKKQMDP. ...NHPDDSI RYYTLCRCCV EKVLVEGN.. ..........

>Q3E5U7_CHLAU
 ..MFYLISYD ISVDQRRLKI AKLLEGYG.Q RVLESVFECD LELPAYRQLR
 QKLNRL.... .IKDEEGDRL RIYRLCASCR EQIEIIGDGP PPETSQDIYI

>P71637_MYCTU
 .KMFVLVIYD ISDNRRRASL AKILAGFG.Y RVQESAFEAM LTKGQLAKLV
 ARIDRFAI.. .....DCDNI RIYKI..... .......... ..........

>Q3VQG1_9CHLB
 ...FILVTYD IENDRRRTKI HKLLEGYGLA .VQYSVFECF VSDEEYAKMR
 MRLQKLLDPK HPI....DSV RYYVLCRNCV ERVDIDGN.. ..........

>Q8ZZU2_PYRAE
 ..MIWLAVYD IEDDGERAKA SAILQAWGFV RVQRSFYVGR MPRGKAADLL
 KILQRHVKSG H........I ALIPITDELL AKALELGRP. ..........

>Q5WBY6_BACSK
 ..MLVLITYD VQTSKRLRKV AKACQNYG.Q RVQNSVFECI VDSAQLTSLK
 LEL......S SLIDKEKDSL RIYRLGNNYK SKVEHIGAK. ..........

>Q7MC41_VIBVY
 ..MLWLISFD ISDDKRRRRA VKLLLGYG.N RTQYSVFECL LKRS......
 .QLRQIQQKM QAVIEPSDRV LYYPLCGKD. .......... ..........

>Q53VV6_THET8
 MRELYLVIYD TPDDRRRARL AKLLKGFG.E RRQYSVFEAR LTREQWAHLK
 ......GKLE ALVNKEEDVL AVYFLPPEAV GRTWRIGHEG LKRLEDPDFV

>Q48SB1_STRPM
 ..MMVLVTYD VAGRKRLRHV AKLCVDYG.Q RVQNSVFECS VTPAEFVDIK
 HRLTQI.... ..IDEKTDSI RFYLLGKNWQ RRVETLGRSD SYDPDK....

>Q72WF4_DESVH
 .AMLVLISYD VSEDRRLRRI AKACQDYG.Q RVQYSVFECV VDPAQWAKLK
 HRL......L SEMDKEKDCL RFYYLGANWR NKVEHVGAK. ..........

>Q6ZEI1_SYNY3
 ..MLYLIIYD VPANKRRTRL FDLLSGYGKW R.QFSVFECF LSVKQFAKLQ
 ......TAME KLIKLDEDAV CIYVLDENTV QRTITYGTPQ PEKP......

>Q2FQQ4_METHJ
 ...RLVITYD IRKDKIRNKL FRLLERYGAW K.QYSVFELE INP......V
 HKVELFHSIA DLIE.DTDRV RIYDLCERCQ GKITELGEVS PD........

>Q3G9E0_9FIRM
 ...LVVVIYD IVDNRRRAAF AKYLKGFG.V RVQKSAFECI LPDAKYQKLL
 KGI....... PKLIDKEDQV RVYKLTSNAD IRAW...... ..........

>Q3B3C0_PELLD
 ..MLVLVTYD VAGRRRLRRI AKTCQNYG.Q RVQFSVFECN VDPAQWVKLR
 AKLMQEMNPA ......HDSL RFYFLGSNWQ NRIE...HEG AKEPRD....

>Q423F2_DESHA
 ...LVLITYD VAGRKRLRQV AKQCVNYG.Q RVQNSVFECV LDAAKFREVQ
 HKLEQI.... ..IDTETDSL RFYMLGNNYK NKVEHIGAKP SFNVEDTLII

>Q2RL67_MOOTA
 ..MYILITYD VSTEKRLRKV AQVCKDFG.Q RVQKSVFECS VNEAQFEQLK
 HRL......L QCIDEKSDSL RIYRL..... .......... ..........

>Q72NB8_LEPIC
 ..MFIIVCYD VETRARLRKV AKTCESHG.Q RVQKSVFECQ LEPAD.....
 .YLQFEAKLS KIINSKTDNL RIYSLDAISV SKIKQFG... ..........

>Q72TS6_LEPIC
 MKHWRLVSYD IREPKRLRRV AKIMEGFG.E RIQYSVF... ....RIYSTD
 KELEKLRWKL AKVTEEEDNI FYLTLCTKC. .......... ..........

>Q5M4I9_STRT2
 .TMFCLIIYD IRSNKRRLKL SKLLEGYG.V RVQKSCFEVN LSRNDYQSLL
 KDIEGFYKA. ....DEEDSI IVY....... .......... ..........

>Q2P7D0_XANOM
 ..MMVLISYD VSTEKRLRKV AKACRDLG.Q RVQYSVFEVE VEPAQWAELR
 QRL......C DLIDPSVDSL RFYHLGAKWE ARVEHVGAK. ..........

>Q3XPZ5_9PROT
 ..MLVLISYD VASGKRLRRI AKACQDHG.Q RVQYSVFECL ITPAQWSMLR
 QRL......L DEMDADQDSL RFYFLGANWR NRVEHVGAAG YDPE......

>Q7MR71_WOLSU
 MKLFVIVSYD IEDNRNRKKL FEELKDMGLS PIQKSVFWGH LKLAEIKIL.
 .......... .......... .......... .......... ..........

>Q60B34_METCA
 ..MLILVSYD VSTERRLRHV AKVCLNYG.Q RVQKSVFECK VNLAQMETLK
 AEL......L DEIDEKEDSL RIYRITE... .......... ..........

>Q3G9T1_9FIRM
 ..MMVLITYD VNTTKRLRKV AKKCVDYG.Q RVQNSVFECL LEPAQFVMLK
 NEL......E AIIDANKDSL RYYMLGSNWK RRVEHVGAK. ..........

>Q3EH39_ACTSC
 ..MLMLITYD ISFDKRLRRI AKHCLDYG.V RTQYSVFECD VTPDQWVRLK
 AKL......L ETYDPECDSL RFYHLGSK.. .......... ..........

>Q41C11_9BACI
 ...LVLITYD VNTKKRLRHV AKLCQRYG.Q RVQNSVFECI VDQTEFMLLK
 LRLK...... EIINHERDSL RFYKLGNQYI SKVE...... ..........

>Q2RY12_RHORT
 ....YVVAYD IADPKRWRQV FKTMKGYGQW .VQLSVFQCR LDGGR.....
 .RIAMASILE SLIDRETDHV LMLDLGEDVD LAVESLGKAF ETLERQAMII

>Q3SR96_NITWN
 ..MLVLVTYD VATRERLRAV AKACRDYG.Q RVQYSVFEIE VDPAQWTRLK
 ARL......E AIIKPEFDSL RYYYLGANWQ RKVEHVGAK. ..........

>Q3FUX2_9BURK
 ..MLVLVCYD VSGRRRLRRV AKVCESTG.Q RVQKSVFECQ LDVAQFEALE
 REL......L AEIDAQQDCL RLYRI..... .......... ..........

>Q2CSN1_ECTHA
 .....LVCYD IRKPARLRRV HRLMKEWG.V PLQYSVFYCR LVPSARHQLA
 EALRRE.... ..IDERVDDV RIYAL..... .......... ..........

>Q39WR1_GEOMG
 ..MWVVVCYD VEGRRRLRRV AQACKNYG.Q RVQKSVFECQ VNEMKFEDLR
 RKLLRE.... ..INKEQDNL RFYRLTEPRE NHVETHGLT. ..........

>Q82W51_NITEU
 ..MLIIVTYD VSTEKRLRRV AKLCESIG.Q RVQKSVFECR INLMQYEELE
 RRL......L SEIDEQEDNL RLYRLTEPAE LHVKEYGN.. ..........

>Q2A2R1_FRATU
 ....YLIAYD IEDNKTRTII YKQLLAYGLK AVQKSVFWGY VSIAEFNAIK
 RLFDRSLTIS .......DKV FITRVNMHEQ K......... ..........

>Q3X6Z2_METFL
 ..MLILITYD VSGQRRLRAI ARTCLDYGM. RVQNSVFECE VTPDQYVRLK
 NELLNIY... ...DPHQDSL RFYMLGSKGR QKIEHWGAKV ..........

>pdb|pdb|1zpw
 ...LYAVAYD IPDDTRRVKL ANLLKSYG.E RVQLSVFECY ......LDER
 LLEDLRRRAR RLLDLGQDAL RIYPVA.... GQVEVLG... ..........

>Q4J7P6_SULAC
 ..MYVVVAYD ISDEKVRGKV RRLLRRYGLS FISRSVYAGR LSWNRALLIS
 ERVAKYLE.. .....ERDSV VIVPVQNVDF SRTLIVTQ.. ..........

>Q2J7N8_FRASC
 ..MDLLVTYD VPDNRRLRKV AKICEGHGI. RVQKSVFEIV CTEPQRVLLE
 HKISQV.... ..IDETLDSI RIYQMPQHTL DNVHHLGAGV ..........

>Q2RW60_RHORT
 .....LVTYD VNTRRRLRQV AKACQDYG.Q RVQNSVFEVE VDPARWVALK
 ARL......E AIIDPALDSL RYYDLGAN.W QRRV...... ..........

>Q2LX07_SYNAS
 ..MMVVVSYD VAKARRLRRI AKTCQNYG.Q RVQYSVFECI VDPAQWTLFR
 KSL......I DEINPEEDSL RFYFLGSNWR RRVEHVGAK. ..........

>Q65TX3_MANSM
 ..MMILITYD VSGERRLRHI AKHCLDYGI. RVQYSVFECE VTPAQWVELK
 DKLLNTY... ...DKETDSL RFYQLGSKWK HRVEHYGAK. ..........

>Q2SIC7_HAHCH
 ..MLVLITYD VSGQRRLRHI AKVCVDYGM. RVQNSVFECE VDPAQFTFLK
 QKLLDIYH.. ....PDEDSL RFYFLGKKGR QKVEHYGAK. ..........

>Q467D7_METBA
 ....YIVSYD IKEPTRLRQV HNTVEGFG.S PLHYSVFRCD LSKKSKVELI
 AAL......T DIINSDEDSV MIIPANKNLD KKITFIGQKP EVEEEDFIIV

>Q3GIF5_CHLVI
 ....VLVTYD VAGRRRLRRI AKTCQNFG.Q RVQFSVFECS VDPAQW..IK
 FRAKLIHE.. ..MNPEQDSL RFYFLGSNWQ HRIEHAG..T KEPRDLEGVL

>Q4EVR9_LISMO
 ..MYVILIYD ISIEKVWRNV FKICKKY.LT HVQKSVFEGE ITPALLVKLR
 MELD...... KYIRDDQDSV IVFSSRQQRW LEKEFWGLTD EK........

>Q4ISY2_AZOVI
 ..MMVLVSYD VSTEGDLRRV ARACLDYG.Q RVQYSVFEIE VDPAQWVLLK
 SRL......C ELIDPEVDSL RFYYLGRNWQ NRVEHVGAK. ..........

>Q97CJ7_THEVO
 ..MYLIVVYD V.DESRVNKV NKYLKRYLLW R.QNSVFEGE ISENLIDSMI
 KGIT...... .KIIKDEDSI IIYKFKVKSY IDNIIIGND. ..........

>Q74H35_GEOSL
 MEHLYIVSYD IRNQRRWRRL FKTMHGFGCW .LQLSVFQCR LDRIRI....
 ..IKMEAAIN EIVNHAEDHV LILDLGENVK PKVSSIGKTF D.........

>Q65S19_MANSM
 ..MRYLIGYD ITDSKRLQRI YRRMIKF.AT PLQYSVFLFN GTKEQLD...
 ...KYMQTVL RLYNKKEDDL RIYPL..... .......... ..........

>Q42A00_DESHA
 ..MFVILVYD MGE.KRVAKA LKRCRKY.LN WVQNSVFEGE ISESNLAKLK
 MELDRI.... ..IVPEEDSV IIYTLRTTRY SEREIMG... ..........

>Q7NYP3_CHRVO
 ..MMVLVSYD VTQDKRLRKV ARACRNFG.Q RAQYSVFEIE VEPAQWVLLR
 DKL......C ALIDPKQDSL RFYYLGGNWK QKVEHVGAK. ..........

>Q2D446_9FIRM
 ..MFVILVYD V.NQKRVAKV LKRCRQY.LT WVQNSVLEGE ISDVNLKKLK
 MELQ...... KIINKEEDSV IFYTMRTTNY SSRELIG... ..........

>Q2ZFG9_CALSA
 ..MFVILVYD VNE.KRVAKA LKKCRKY.LT WVQNSVFEGN ISEATLR...
 ...RLILELE KVLDLSEDSV IIYKFQNTWY SERQIIG... ..........

>Q2NFR8_METST
 ..MYIIIVYD I.NTKRVNKV KSLLRMY.LN WIQNSVFEGE IKPTQFKELK
 ......IKIT EIINKDEDSV IIYKMPPTYK PEKTIIG... ..........

>Q82XY2_NITEU
 .....IICYD ITDPRRLGRL YRYLIKR.AV PLQYSVFLFR GDDRQLE...
 ...RCIQDAI ELIDEKQDDL RVYPLPGRGL KARI...... ..........

>Q8R6X6_THETN
 ..MYVILVYD VNVNRV.NKV LKTARRY.LT WVQNSVLEGE LTEATYRALR
 NELARI.... ..IDPEEDSV LFYILGNTKY TKRELLG... ..........

>Q4CIF4_CLOTM
 ..MFVIMVYD AGE.RRNSKV LKVGRKY.LH WVQNSVFEGE LTEANYHKLK
 EEVRR..... .KVDNEEDSV IFYKFRTMKY TEREVIG... ..........

>Q82XY0_NITEU
 ...LYLVAYD ICNPRRLRQV CRYLTGY.KV SGQKSVFEIW VTPTELHTIR
 TELD...... KLMDTQADRL HILSLDPRMK PR........ ..........

>Q3AA69_CARHZ
 ..MFVILVYD V.NQKRVAKV LKTARKY.LY WVQNSVLEGE ITEANFRRLK
 GELSRI.... ..INQDEDSV LFYIFGSMKY SSRELLG... ..........

>Q3N8A7_9PROT
 ...LYLVAYD VCNPRRLYKV CRYLKRY.KV GGQKSVFELW VTSAELRTIR
 ADLD...... ELMDAQEDRL HILSLDPRMK PR........ ..........

>Q3GC76_9FIRM
 ..MLVIMVYD VE....VKRV AKVLKRKYLY WVQNSVLEGN INEGSFKKLK
 AELSRI.... ..IDHEYDSI IFYTFRTSKY SEREIMG... ..........

>Q2E6C4_BACCE
 ..MFVIITYD IGE.KRVGKA CKKLKQY.LT WTQNSVFEGE LSRTQLLKCL
 AELDQI.... ..IISSEDSI YLYEV..... .......... ..........

>Q9X2B6_THEMA
 ..MYVIMVYD VNE.KRVAKI LKIARKY.LK WVQNSVLEGE LSPGKYEKLK
 LEVSR..... .LIDEKEDSV RFYVMDS... .......... ..........

>Q3CGG7_THEET
 ..MFLILVYD VNE.KRVNKV LKTCRKY.LH WVQNSVLEGE ISEANLKKLK
 IELSRI.... ..IDKDEDSV IFYILRTTKY SEREILG... ..........

>Q5JD44_PYRKO
 ..MYIIVVYD VSVERV.NRV KKFLRQH.LH WVQNSVFEGE VTLAEFERIK
 AG......IG ELIDGDEDSV VIYKL..RSM PKREVMG... ..........

>Q3N8A5_9PROT
 .....IICYD ITHPRRLARL HRYLVKR.AV PLQYSVF... LFSGDDRQLE
 HCMQ...GAI ELIDEKVDDL RVYPLPSRGL KARI...... ..........

>Q44RX7_CHLLI
 ..MYYIAVYD VAE.KRVGKM LKIFRKY.MH HIQNSVFEGE MTPASYQKLK
 ......YEAG RLCNDETDSV IFFELNGKYM NKEIL..... ..........

>Q8RED2_FUSNN
 .KMYVVVVYD ISLDRNWRKI FGICKRY.LH HIQNSVFEGE LSEVDIQRLK
 ......YEVS KYIRDDLDSF IIFKSRNERW MEKEMLG... ..........

>Q6L364_PICTO
 ...WVILIYD IEKSRV.NKI RKICEGY.LV RVQESAFEGY ISAALLNILI
 KRLK...... KEIDESYDKI KIYSFREDRK GKIIELGD.. ..........

>Q3GF03_9FIRM
 ....VIVFYD VGK.KRVAKV FKICKQY.LK HFQKSVFRGH ITPA......
 NYLELKGKLL KVIDIDYDFV TFIQTISDAS FNEESIGNTG INPE......

>Q74N46_NANEQ
 ..MYAIVVYD V.NVSRQNQI REFLRKY.LY HVQRSVFEGE ISPSSLYYMK
 KILQSY.... ...IGETDSL IIYVLDKSCL MDKIVLGED. ..........

>Q6L318_PICTO
 ..MYIILVYD V.DEKRVSKV NKFLKRYLLW R.QNSVFEGE ITDKLLENMI
 SGV....... NKILKDQDSL IIYKFKVKSY IENIILGND. ..........

>Q65S17_MANSM
 MRDRYLIVYD ISSSKRRYYT HKYLSAY.AV GGQKSFYECW LTNRELVEFK
 QKL......I NCIDKQEDKL FIFQL..... .......... ..........

>Q5LC92_BACFN
 ..MYVIFVYD FGE.KRVSKM LRLCRRY.LN WIQNSVFEGE LSEVRLKELL
 LLAKGVMN.. ....PEEDCI IIFKGATQCS LEKEIVGKE. ..........

>Q5V7X4_HALMA
 ..MVYIIVYD VQADRT.PKF LKYLRRY.LT HVQNSVFEGE LTEGTLVEVK
 ETLQSMLEEE E.......SV MVYRMDSGSY VERSVYGDD. ..........

>Q2NH77_METST
 .....LVIYD I.KIERINKV YKFLKTYLIW .IQNSVFEGE ITKAQYK...
 ...TMIIKLK ELTDEDEDSI IIYKIPKKYL NKEVL..... ..........

>Q3CAU4_9CLOT
 ..MYIILMYD IMMDKTGAKV FKICKRY.LT HIQNSVFEGN LTELNLMKLK
 KEL......S EYIRKEQDSF IIF....... .......... ..........

>Q3W2S5_9ACTO
 ..MFVILVYD TAAERN.PLV LRTCRKY.LH WVQRSVFEGE LSAAQYRALT
 AALKTE.... ..LDLSYDSI RIYR...... .......... ..........

>Q4HBK2_9DEIO
 ....LLICYD IATRKRLRRV AKVCVAHG.Q RVQHSVFEVS VSEIQL....
 ..LTLRQKLL NILDPTEDSI RLYRL..... .......... ..........

>Q2RHR2_MOOTA
 ....MILIYD IEDNDGKRRL VKIMKRKYLS HVQKSVFEGD ITEGQISLLK
 KE......IM AIVNMKKDFV IIYSL..... .......... ..........

>Y386_METJA
 ..MYVIIVYD V.NVSRVNKI KSFLRKH.LN WVQNSVFEGE VTKAEFE...
 ...RIKDGIL RIIDEDEDSV IIYQFPLNFM PKREILGLE. ..........

>Q8U1T8_PYRFU
 ..MYIVVVYD VGVERV.NKV KKFL.RMHLN WVQNSVFEGE VTLAEFERIK
 EGLK...... KIIDENSDSV IIYKL..... .......... ..........

>Q2CSM9_ECTHA
 ...LYLAAYD VRCPRRLSRA VRVIKGY.AS GGQKSAYECW LTPAEHKALH
 TEMAQVIDPT E......... .......... .......... ..........

>Q46FQ4_METBA
 ..MYVVIVYD VGVDRV.NKV RTFLRQYMNW .VQNSVFEGE LTKAEL....
 ..LKVKSTLK ELINETSDHI IFY....... .......... ..........

>Q41NC0_METBU
 ..MYVIIVYD VG.VERLNKV RIFLKQY.LN WVQNSVLEGE LTKAEYFKIQ
 SHLKQ..... .LINKDEDSI FIYRV..... .......... ..........

>Q7MTF3_PORGI
 ..MYIILVYD IGE.KRVGKM LKLCRKY.LN WIQNSVFEGE ISEVKLLELK
 SRA......A GIMEKEEDSL IIFSSRQERW LEKEIIGKE. ..........

>Q3X5F0_9ACTN
 ....MIMVYD VNVKRVVKVL KVGRKY..LE HVQNSVLEGE LSPAQYKKLK
 HEV......E KTIDPEEDTV RFYLLRTTRY LTTEELGLPS RNEPDSS...

>Q2ZEU3_CALSA
 .......... .......NKV RKILKKY.LT WVQNSVFEGE ITYGKLEKCK
 RELFSV.... ..IEKDEDSV YFYEMEYKIV CSKKILGQE. ..........

>O30237_ARCFU
 ....VIVAYD V.NVERVNRV KKFLRRY.LN WVQNSLFEGE LSSADLEEVK
 MGLR...... EIINEDEDMV VIYRFRSADA FKREVMG... ..........

