>query  (#) CCR5 /nfs/data5/users/ppuser/server/work/predict_h13903
MDYQVSSPIY DINYYTSEPC QKINVKQIAA RLLPPLYSLV FIFGFVGNML
VILILINCKR LKSMTDIYLL NLAISDLFFL LTVPFWAHYA AAQWDFGNTM
CQLLTGLYFI GFFSGIFFII LLTIDRYLAV VHAVFALKAR TVTFGVVTSV
ITWVVAVFAS LPGIIFTRSQ KEGLHYTCSS HFPYSQYQFW KNFQTLKIVI
LGLVLPLLVM VICYSGILKT LLRCRNEKKR HRAVRLIFTI MIVYFLFWAP
YNIVLLLNTF QEFFGLNNCS SSNRLDQAMQ VTETLGMTHC CINPIIYAFV
GEKFRNYLLV FFQKHIAKRF CKCCSIFQQE APERASSVYT RSTGEQEISV
GLGTETSQVA PA
