>prot (#) default: single protein sequence description=t0386 /home/ppuser/server/work/predict_h2786
MPKAKAKTKN TEIISPHHYV YPNTTTLKNK YGIKNLNAFL EKCSHDTAKA
MINLREESLP EYFDTAYLCH IHQQLFKNTF EWAGYLRHIP FTFADGTTAA
MPEMKRTGWK NAFAIGDEIQ EGLQRLDQTL AEKNNLQGLT REEFNSEAIE
LFNSLNQLHP FREGNGRTQR LFFENLAKAA GHQLNFSLIT KERMMVASVA
VAENGDLEPM QHLFEDISNP EKIRLLKEFM HTMKNTGRNV NDRPVMVAKE
GETYTGTYRG AGLEGFALNV KGAYIIGNID HLPPEQLKIL KPGDKITFT
