>prot (#) default: single protein sequence description=t0362 /home/ppuser/server/work/predict_h31934
MNPENWLLLR RVVRFGDTDA AGVMHFHQLF RWCHESWEES LESYGLNPAD
IFPGSRKSEV TPEVALPIIH CQADFRRPIH TGDALAMELR PERLNPNSFQ
VHFEFRCEEQ IAAHALIRHL AINAQTRHRC ALPEGIDRWL EASGVGKIGS
I
