>query  (#) default: single protein sequence resfilename=asg3tyjq /nfs/data5/users/ppuser/server/work/predict_h14585
MEFYDSIILD NSSDSGSGDY DGEELCDLSV SNDFQKIFLP TVYGIIFVLG
IIGNGLVVLV MGFQKKSKNM TDKYRLHLSI ADLLFVLTLP FWAVDAVSGW
HFGGFLCVTV NMIYTLNLYS SVLILAFISL DRYLAVVRAT NSQNLRKLLA
GRVIYIGVWL PATFFTIPDL VFAKIHNSSM GTICELTYPQ EANVIWKAVF
RFQHIIIGFL LPGLIILTCY CIIISKLSKN SKGQTLKRKA LKTTVILILC
FFICWLPYCA GILVDALTML NVISHSCFLE QGLEKWIFFT EALAYFHCCL
NPILYAFLGV RFSKSARNAL SISSRSSHKM LTKKRGPISS VSTESESSSA
LTS
