>query  (#) default: single protein sequence resfilename=4cu2fygs description=l1td1 /nfs/data5/users/ppuser/server/work/predict_h23334
MSDVSTSVQS KFARLAKKKE NITYMKREQL TETDKDIAPV LDLKCKDVSA
IMNKFKVLME IQDLMFEEMR ETLKNDLKAV LGGKATIPEV KNSENSSSRT
EFQQIINLAL QKTGMVGKIE GENSKIGDDN ENLTFKLEVN ELSGKLDNTN
EYNSNDGKKL PQGESRSYEV MGSMEETLCN IDDRDGNRNV HLEFTERESR
KDGEDEFVKE MREERKFQKL KNKEEVLKAS REEKVLMDEG AVLTLVADLS
SATLDISKQW SNVFNILREN DFEPKFLCEV KLAFKCDGEI KTFSDLQSLR
KFASQKSSVK ELLKDVLPQK EEINQGGRKY GIQEKRDKTL IDSKHRAGEI
TSDGLSFLFL KEVKVAKPEE MKNLETQEEE FSELEELDEE ASGMEDDEDT
SGLEEEEEEP SGLEEEEEEE ASGLEEDEAS GLEEEEEQTS EQDSTFQGHT
LVDAKHEVEI TSDGMETTFI DSVEDSESEE EEEGKSSETG KVKTTSLTEK
KASRRQKEIP FSYLVGDSGK KKLVKHQVVH KTQEEEETAV PTSQGTGTPC
LTLCLASPSK SLEMSHDEHK KHSHTNLSIS TGVTKLKKTE EKKHRTLHTE
ELTSKEADLT EETEENLRSS VINSIREIKE EIGNLKSSHS GVLEIENSVD
DLSSRMDILE ERIDSLEDQI EEFSKDTMQM TKQIISKERQ RDIEERSRSC
NIRLIGIPEK ESYENRAEDI IKEIIDENFA ELKKGSSLEI VSACRVPSKI
DEKRLTPRHI LVKFWNSSDK EKIIRASRER REITYQGTRI RLTADLSLDT
LDARSKWSNV FKVLLEKGFN PRILYPAKMA FDFRGKTKVF LSIEEFRDYV
LHMPTLRELL GNNIP
