>prot (#) default: single protein sequence description=t0355 /home/ppuser/server/work/predict_h7658
MQTISDNAAN AIQEIFGRSK ALIGMIHCPA FPGAPRYRNA SMDAIYDACM
RDAERLIEGG MHGLIVENHG DVPFSKPDDI GPETSAFMSV VTDRIVRTAG
VPVGINVLAN APIPAFAIAK AGGAKFIRVN QWANAYVANE GFMEGRAAEA
MRYRSLLRAE HIKVFADSHV KHGAHAITAD RSIDELTRDL AFFDADGVIA
TGQRTGNSAS LEEIEEIGAA THLPLLVGSG VNEGNIVEIL KRTSGVIVAS
SLKEGGVWWN PVELARVRSF VAAARPGLEA LEHHHHHH
