>query
 MQTISDNAAN AIQEIFGRSK ALIGMIHCPA FPGAPRYRNA SMDAIYDACM
 RDAERLIEGG MHGLIVENHG DVPFSKPDDI GPETSAFMSV VTDRIVRTAG
 VPVGINVLAN APIPAFAIAK AGGAKFIRVN QWANAYVANE GFMEGRAAEA
 MRYRSLLRAE HIKVFADSHV KHGAHAITAD RSIDELTRDL AFFDADGVIA
 TGQRTGNSAS LEEIEEIGAA THLPLLVGSG VNEGNIVEIL KRTSGVIVAS
 SLKEGGVWWN PVELARVRSF VAAARPGLEA LEHHHHHH  
>Q8UBE7_AGRT5
 MQTISDNAAN AIQEIFGRSK ALIGMIHCPA FPGAPRYRNA SMDAIYDACM
 RDAERLIEGG MHGLIVENHG DVPFSKPDDI GPETSAFMSV VTDRIVRTAG
 VPVGINVLAN APIPAFAIAK AGGAKFIRVN QWANAYVANE GFMEGRAAEA
 MRYRSLLRAE HIKVFADSHV KHGAHAITAD RSIDELTRDL AFFDADGVIA
 TGQRTGNSAS LEEIEEIGAA THLPLLVGSG VNEGNIVEIL KRTSGVIVAS
 SLKEGGVWWN PVELARVRSF VAAARPGLEA ........  
>Q31K76_SYNP7
 MQRLDSDVD. .LHRIFGTTT PVIGVVHLQP LPTAARW.GG NLRAVIERAE
 QEATALAAGG VNGIIVENFF DAPFPK.NRV DPAVVSAMTL VVERLQNLVT
 IPLGLNVLRN DAHSALAIAS CTGAAFIRVN VLTGVMATDQ GLIEGEAHQL
 LRYRRELGS. SVQILADVLV KHARPLGTPN LTVDTIERGL ....ADGVIL
 SGWATGSPPS LEDLELAKAA GDVPVFIGSG ASIENIGQLL QAADGVIVSS
 SLKRQGKREQ SIDPVRVGRF VDTVRACQQR LQ......  
>Q3MFH2_ANAVT
 .......... .LYQLFKTRT PIIGVVHLLP LPTSPRW.GG SLKAVIDRAE
 QEATALASGG VDGIIVENFF DAPFTK.NQV DPAVVSAMTV VVQRIQNLVT
 LPIGLNVLRN DGKSAMAIAS CVRAQFIRVN VLTGVMATDQ GLIEGEAHEL
 LRYRRELGS. DVQILADVLV KHARPLSSPN LTVDTIERGL ....ADAVIL
 SGWATGSPPN QEDLELADAA NGTPVFIGSG ASWENIATLL QAANGVIVSS
 SLKRHGRIEQ PIDPIRVSQF VEAAH..... ........  
>Q985I4_RHILO
 .......ADD ALQSIFGRKK VVIGVVHLAP LPGAPRYDGE AVEAIYQRGL
 DDAKAYLDGG CDGVIVENHG DVPFAKPDDI GPETSAYMSV VSDRIRREIG
 RPIGINVLAN ASIPALSIAS ASGASFVRVN QWANAYVANE GFIEGEAARA
 MRFRARLRAN GIRIFADAHV KHGAHAIVGD RPVEEQVKDL VFFDADAVIA
 TGQRTGHAAD LGYIRMIKDA AGLPTLVGSG VTPENANDIL DIVDGVIVAS
 SLKHDGVWWN QVDPLRVKAF ISGLK..... ........  
>Q4C3G5_CROWT
 .......... .LTQIFNTTN PVIGVVHLLP LPTSPRW.GG SLKAVIERAE
 QEATALAAGG VDGIIVENFF DAPFTKE.KV DPVVISAMTL IVDRIKNLVV
 VPVGINLLRN DSVGAMAIAS TINAQFIRVN VLTGIMATDQ GLIEGNAYEL
 LRYRRQLDAE .VAILADVLV KHARPLGTPN LTTDTIERGL ....ADGVIL
 SGWATGSPPS LEDLELAKAA QETPVFIGSG ADWDNIGKLM TAADGVIVAS
 SLKRQGKITE TVDPIRVAQF VEAAKE.... ........  
>Q29E81_DROPS
 .......... ...KIFGQQK CVIGMIHVDA LPGTPRYAG. HWKETIEKAI
 YEANLYKRHQ LDAVLIENMH DIPYVPERLL GAEITACMTR LGQAVRDVIE
 IPCGVQVLAC GNKQALAIAK ASQLQFIRSE GFVFGHVADE GYTDACAGDL
 LRYRKLIDAE DVLIFTDLKK KHSSHAITSD VSLLETAHAA EFFLTDGIVI
 TGTATGHAAS PQDLQELSGR VKVPLLIGSG VTKDNIGLYY KDANAVIVGS
 HFKRHGSWLE EISEEAVENF MRKV...... ........  
>Q7Q946_ANOGA
 .......... ....LFAKPF PIIGMIHVGA LPGTPLYKG. HMNKLISEAQ
 AEANIYRKCG VDGVLVENMH DIPYIRPRDL GPEITSAMTR VTLAVRETIP
 IPCGVQILAG CNREALAVAK VCQLQFIRAE GFVFGHMADE GFTDACAGSL
 LRYRKQIDAE DVLVLTDIKK KHSSHAITSD VSITETAGAA EFFLSDGLIV
 TGSSTGASAE QGDLQALRGK TNLPIIIGSG LTLANFPSYW TLAHGAIVGS
 HFKENGHWSA ALCQRRVQTF MEGVE..... ........  
>Q28GZ2_XENTR
 .......... ...QLFGTVK PVIGMVHVKA LPGTPGSR.L PVAQIIEEAC
 HEAEIYKNAG IDGIMVENMH DIPYTF..NT GPEITATMAT ICTAVKQAPH
 LPLGVQILSC ANNQALAVAL AAGLDFIRAE GYVFSHVADE GFVNACAGDL
 LRYRKAIGAE HIQIFADIKK KHSSHAVTAD MSVSETAKAA EFFLADGLIL
 TGTSTGQEAD QRDLKECGQS VRIPVLIGSG VTLGNMEKYI D.ANGFIIGS
 YFKKDGHWSN SVVYDKVSSF MDKVK..... ........  
>Q8DME0_SYNEL
 .......... .LRTLFHTAT PVIGVVHLLP LPTSARW.GG SLKAVIDRAE
 QEATALASGG VNAIIVENFF DAPFSK.DRV DAAVVSAMTL VVQRLKNLVA
 LPIGLNVLRN DAFSGLAIAA CTGAQFIRVN VLTGVMATDQ GLIEGPAHQL
 LRYRRELG.Q DIKIFADVMV KHAQPLHSPN ..LATAVRDT DRGLADGVIL
 SGWATGQPPT EEDLVAARAA KGQPLFIGSG ASWDNVAQLV PYVNGVIVAS
 SLKRNGQIEQ PIDPIRVSRF VEAAHHKLQE L.......  
>Y1062_PYRAB
 .......... ........SK PLIGVVHLLP LPGSPGYRG. SIEEILDRAI
 SDAAKYQEAG FDAIILENYG DFPYSK..TI SKETLASFAV IAKEVGREIS
 IPIGINVLRN DCVASYSIAY SVRADFIRVN VLTGVAFTDQ GIIEGCAREL
 AELRARLPSR .IKVLADVHV KHATHFSSFE VALLDTV... ERGGADAVII
 TGSRTGSEVD IQELMLAKKI SPVPVIVGSG LNPRNIRLFW RYADGFIVGT
 WVKEGGKTLN EVSLERATRI AKVVK..... ........  
>Q8ZPB8_SALTY
 .......... WLKEVIGTEK AVIAMCHLRA LPGDPGFDTK GMNWVIDRAH
 DDLMALQNGG VDAVMFSNEF SLPYLTK..V RPETTAAMAR IIGQLMSEIR
 VPFGVNVLWD PVASFDLAMA TDAKFIREI. .FTGAYASDF GVWDTNVGET
 IRHQHRIGAG HVKTLFNI.. VPEAAVYLGN RDVCSIAKST VFNNPDALCV
 SGLTAGARTD SAILKRVKEV PDTVVLANTG VCLENVEEQL CIADGCVTAT
 TFKKDGVFAN FVDQARVAKF MEKVR..... ........  
>Y1115_METJA
 .......... .......KKK PLIGMVHLKP LPGSYHYND. NFDDIVDFAI
 KEAKKLEEAG FDAVMIENFG DAPFKK..EA DKITIASMAV IAKAIKEEVS
 LPLGINILRN DAIGAYSIAY VVKADFIRVN VLSGVAFTDQ GIIEGKAYEL
 AKLKKLLPSK .IKVFADVHV KHAYHFIDFE SSLDTVERGL ....ADAVII
 SGKRTGKEVD IEKLKLAKEL VDVPVIVGSG TNYNNLRILW SYADGFIIGT
 WIKKDGKANN EIDIDRAKKI VNLA...... ........  
>Q2JJF4_SYNJB
 .........N LLQHLFKTPH PVIGVVHLLP LPTSPRW.GG DLEWVIAQAE
 QAATALAAGG VDGILVENFY DAPFAK.DRV DAAVVSAMTV IVQRLKTLVS
 LPVGINVLRN DGCSALAIAA CVGAQFIRVN VLCGAMVTDQ GIIEGNAYRL
 LRYRRELGA. NIKIFADVLV KHAQPPISLD AAIDTVERGL ....ADAIIL
 SGWATGKPPL LEELELARKA PQVPLLIGSG ATAENIGSLI RRADGVIVAS
 SLKRSSRSAG MIDPIRVRQF VEALHLALR. ........  
>Q51GR9_ENTHI
 .......... .......... .IIGMVHVHA LPGTPNYSST ACRAIIEKAV
 EEATVYQQCG LDTIMIENMH DVPYLN.STA GPEITSAMSI VGYEIKRQLN
 LRVGVQILAA ANKQAMAAAF CSGCDFIRAE GFVFGHVADE GYIDSNAGEL
 LRYRKMIGAE DVLVFTDIKK KHSAHSITSD VSLIDTAKTA QYFLSDGIII
 TGTSTGVKTD PQEVRDVKKS VSIPVLVGSG VTPENVNEY. SSADALIVGS
 YFKVDGFWKN ELSKERILKL ISAVNE.... ........  
>Q61WJ0_CAEBR
 .......... .VSKLLNSSR PLVGMIHVPA LPGTPS.NTL PMSAILKKVR
 KEADVYFKNG VDGVIVENMH DVPYVKP.PA NPEIVSAMSL ASDQLVRDAH
 HPTGIQILAA ANREAIGVAY TTGLDFIRAE GFVYSHVADE GWIDGCAGGL
 LRYRSSLKAD HVAVFTDIKK KHSAHSITAD VSIQEMAKDA KFNCADGVIV
 TGSSTGSAAS TEEMSQVRGV SEFPVLIGSG INGKNARDFV K.AHGFIVGS
 DFKIGGDWKN ELEASRITKF MRHV...... ........  
>Y860_PYRFU
 .......... .......SKK PLIGVVHLKP LPGSPRY.GG DFEEVIEWAI
 RDAKTYEEAG FDGIIVENFG DSPFSK..TL PREVIPAFTV VAKAVKKEVS
 LPLGINALRN DCIVAYSIAH AVGGSFIRVN VLTGVAFTDQ GIIEGCAREL
 WNVKRIIGG. DILTLADVHV KHAVHFTNFE DAVDTVERGL ....ADGIIV
 TGRRTGESIS LEDLILAKRV SSIPVLVGSG VNPRNFRTLF KYADGFIVGT
 WVKENGKINN PVSLERAKIL VR........ ........  
>Q3DXT2_CHLAU
 .......... .LREMFRTAK PIIGMVHCWP LPGAPGYTGY GMQTIIEHAI
 RDAEALAEGG CDGLIVENMW DIPFRAGPHV PPESIAAQAV VAHAVRQAVE
 LPLGINLVHN GGVALLGIAI AAGASFIRVC MFTGAGVWDA GSWEGCAADL
 MRRRKELHAE SIKIFADVDK KHSVRFPGID LVTHEWTR.. .FFGADAIIV
 SGRMTGDAPD IAKVRQAREA GDTPILLGSG TTEQNIAAFM EVADGVIVGS
 SIKQDGEIAN PVDVNRVRRF VAAAR..... ........  
>Q7NH91_GLOVI
 .......... LLVDLFLTAK PIIGVVHLLP LPTSPRWAG. SLDAVMARAE
 QEATALATGG VDALIVENYY DAPFV.PGRV DPAVVAAMSL VVKRIIHLVP
 VPVGVNVLRN DAHAALAVAA CTGAQFIRVN ILTGTMATDQ GIIQGEAHSV
 LRYRRELGAE .TRIFADVLV KHASPLGAGD ..LFQACRDT VERGADGIIV
 SGVATGSPPR REDLVTARAA PDVPILIGSG ADPANAGDLL GLADGVIVAS
 ALKRFGKPEQ PIDPHRTRQF VDAVHLA... ........  
>Q3H2B1_9ACTO
 ........SN WLHEVFDVPK PIVGMCHLPA LPGDPGYDAG GMDKILAHAR
 QEIDALQTGG VDGILISNEF SLPYLTRTE. .PITAITMAR TIGELISEIQ
 VPFGVNVLWD GVASIDLAMA TGAAFVREV. .FTGVYASDF GMWNTDVGRA
 ARHRAQVGAG GVRLLYNI.. VPEGATYVAG RELDRMTRST VFNGADGLCV
 SGLTAGAATD TPTLKIVKEA GDVPVFVNTG VRPDTVAESL QYADGAIVGT
 WFKREGKFTN DVDAARVAEL MGVVRE.... ........  
>Y2179_PYRKO
 .......... ........RK PLIGMVHLKP LPGSYLYNG. DFDSVIEAAL
 RDAVTLEEAG FDAVMVENFG DVPFPKYAD. .KTTVASLAV VAKAIRDEVS
 LPLGVNVLRN DGIAAYSIAY AVKADFIRVN VLSGVAYTDQ GIIEGIAHEL
 AMLRKRLPSE .IKVFADVHV KHAVHFGDFE DALDTVERGL ....ADAVVV
 SGKATGRPVD VDKLALAKEI SPVPVIVGSG TSYDNLPELW KYADGFIVGT
 WIKRDGRVEN EVSLERARKL VELAKE.... ........  
>Q3GXE4_9ACTO
 .......... WLKETFGVDR PIIAMLHLKP LPGDPHYDTT GMAAVLRAAG
 EDLRALQDGG VDAVMFSNEF SLPYLTKTE. .PITAISMAR IIGELASDIR
 VPFGVNVLWD GPASIDLAAA TGAQFVREI. .FSGVYASDF GLWNTNVGLS
 ARRQRQHDAM GVRLLFNI.. VPEAAQYLAH RDLASIARTT VFNCADGLCV
 SGATAGAATD TDQLRVVKAA GDTPVFVNTG VRVATLETQL SAADGAIVGT
 AFKYDGIFEN QVDVSRVTEF MVEAR..... ........  
>Y419_ARCFU
 .......... ........EK TVIGVVHLLP LPGSPEHTDL S..AVIDKAV
 KDARAIEEGG ADALILENYG DKPFLK..EV GKETVAAMTV IACEVKRDVS
 IGLGINVLRN DAVAALAIAK AVNADFVRVN QLFFTSVSPE GILEGKAGEV
 MRYKKLVDCR AM.IFADIAV KHAVHFASLE DYCLNAERSL ....ADAVIL
 TGKTTGGEVS LEELKYAKKT LKMPVLAGSG VNAENAARIL KWCDGVIVGT
 YIKRGGL... .VDAERVRRI VRAAK..... ........  
>Q28QI3_JANSC
 .......... KFRDVFGTPK PVIAMVHLGA MPGTPLHDDA GLEGLVAAAA
 ADLSALQAAG VDAVMFGNEN DRPYEFAVDT ..ASTATMAY VIGQLRGQIT
 VPFGVNVLWD PDSTIALAAA TGAQFCREI. .FTGTYASDM GVWAPDAGRA
 LRYRKRLGRD DLAMLYNVSA EFADS..LDK RPLPDRARSA VFSSPDAVLV
 SGQITGEAAR MEDLEAVKAV PETPVLANTG VKHDTVAEVL RIADGCIVGS
 SLKVDGHTWN AVDPDRAKDF MDRARA.... ........  
>Q9HMJ2_HALSA
 .......... .....FDADT PVVGMVHLSP LPGAPGYDDG NRPAIRDAAL
 RDASRLEAGG VDALLVENFG DAPFYA.DDV PKHVVASMAA LVRDITREAE
 VPVGVNVLRN DAEAAVSIAA AADADFVRVN VHTGARLTDQ GVVGGQAAET
 VRLRDRLDAA EVSMLADIDV KHSAA..LAE RPLSEVAELL ERGHADGVIA
 SGAGTGHATD HDHLQAVVDA ADAPVFVGSG VTQETVGATL DLADGAIVGT
 ALKQNGETTA PVDGDRVRAL VDAAR..... ........  
>Q8TVC9_METKA
 .......... .......... .VVGVVHLPP LPGSPRAK.. SIEEVVERAR
 RDAARLEDGG VDAVLVENFG DTPYY.PDDV PKITVACMTR AVAEVVDTVS
 VPVGVNVLRN DGVAAVDVCA ATGASFIRVN AYVEAVATDQ GVLQPVAHMV
 WREIDRLG.V DVEVYADIRV KHGRP..LDD RPVEEVARDA VERGADAVIV
 TGSATGSPPR PEEVRKVARV VD.RVLVGSG VTPENAHVFL RAAAGFIVGT
 YFKKNGITEN PVDVDRVREL VRFIR..... ........  
>Q2RUX8_RHORT
 .......... .......RKK AVIAMAHIGA LPGTPLYDDG GMMKLIDDVV
 GDIEKLQKGG VHAIMFGNEN DRPYQFEAPI ..ASVAAMTA IISAVRPMLS
 VPFGVNYLWD PAASVAIAVA TGASFAREI. .FTGVFASDM GVWSPNAAEA
 LRLRRNLHRP DLKLLFNINA EFASS..LDS RSIGLRARSA IFSSADAILV
 SGPLTGQPAQ ASDLREVREA TEVPLFANTG VRLENVDDVL SIADGCVIGT
 HFKVDGSTWN RVDGGRVSRF MDKV...... ........  
>Q9Y937_AERPE
 .......... ....VFQRCK PLLGVVHLPP LPGSTGYKAR SLEEIIEYAV
 SEASVYEDAG FDGVILENYG DTPYPK..TP GPLQVSAMTR IVREVSSAVG
 IPVGVNMLRN GSVEALASAY SGGGSFIRVN SLCETRLSPE GILEPDAARL
 AKSLALLGER RIEILADVDV KHSQPLV..E TSIAQTVRDC IERSIAGVVL
 TGHATGGAPD ADEVVAAARE YEVKTVVGSG VSQLNLSKYW HIADGFIIGS
 SIKLGGKPWN PIDKEKARLI ASLAE..... ........  
>Q96YL8_SULTO
 .......... .......... .LIGVVHLPP LPGSFFYKGE .FEEIVDFAI
 NESKKLEVGG FDAVILENFN DKPFRKKVRV ..ETAIAMSI IAREVKKSTS
 LLVGINLLRN .SAYEAASIA SLTGDFIRVN ALCETISSPE GIIEPASVEV
 QEVLYYTKRK .ISILADINV KHASHQMNLE .SLLLDCKER GF..ADYIIV
 TGERTGKEPN PEVVKMIKNI SPLPVCVGSG MTPNNIRDY. .KVDCFIIGT
 YLKDDGK... .IRVERVKEI ANAVK..... ........  
>Q82ZM1_ENTFA
 .......... ...ELFAVEK PIIGVIHL.. .......KGK TDQEIQERAK
 KEIQIYSEHG VDAILMENYG D..YVQLEKA LQYVTSL... .......DLP
 IPIGVNVL.N VDPLGFHLAN KYHLQFLQID SVVGHVASLQ AFFD......
 .LYRAKTTAK LIG.....GV RFKYQPMLSE KSVEEDLKIA QQRC.DAIAV
 TENATGEETS LEKIKLRKQL PEFPLIVAAG LNDKSVKEQL AICDAAIVGS
 NFKDTRKDTG DIYAPYVDSF MKIVKE.... ........  
>Q8ZSW6_PYRAE
 .......... .......... .IIGVLHLLP I.DDPEF... .....FNHAV
 RNARRLEEAG ADAIIVENYY DTPF.KPYAD FP.RAVAVAA AVRDVVREVS
 IPVGVNLLRN ACRKAAVIAR YAGGRFIRCN AYTDVVLTES GLLLPQAP..
 .......YIK GVKVLADVHV KHGVYPPTLA EAVETASTRA A...PDAIVI
 TGRKTGEPPD PVEIATARAH TDLPVLAGSG IC.FNTLNLL KIVDGAIIGT
 CLKSGR.... EVDLEKAARL IKEARQVLK. ........  
>Q2CH81_9RHOB
 .......... .........R PVIGMVQLPP LAGGANYGGA PVGEVLEAAL
 EEARVLADNG IDGLMVQNLG DIPV..AHAA TAAQVAWMTR ATVEIGRIAA
 CPVGLNMLEN DVDAMFAVAS AAGADFVRIK VFVGAMVTPF GLEQGRAHAA
 ARARRGCGGG DIAILADVHD RTGTPLATSG FE.EDLDFAL RLGGADAVVV
 TGKS..HAAT LDAARARAAH PAAHVLLGGG VTAENFEETM ENASGAIVSS
 SMKDSGSAVG RFVPERVEAF M......... ........  
>Q2LUE0_SYNAS
 .......... .......... .......... .......... ..........
 .....LKEGG VDILEIG... .VPFSDPTAD GPVIQAALSR IIQDLRKIID
 LPV...VLFG YYNPIYAYGT ERFAERAKAA GVDGLLVVDL PLEEAE....
 .ELRGKTDSK GLDFITLI.. ....APTTSE ERMCRIARRA QGFIYYISIV
 TGTATPSRDN VEEIRRIRTH SDLPLVVGFG ITPEQARELA SLADGIVIGS
 AFVRL.IAEN ADSPERVSSF AREIKKAMQ. ........  
>TRPA_THEMA
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 ....TGERED LDHIKRVKER IKLPLFVGFG IRHEQVKKVW EIADGVIVGS
 ALVRIME.EN PKDEI.PRKV VEKVKELL.. ........  
>Q2CEW0_9RHOB
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........I
 TGAASARATD VGEVARIKAA TDIPVIVGFG ITPESAEAIA SVADGAVVGS
 AIVEKIAAGQ PVDLAFVRSL ADGAH..... ........  
>TRPA_SYMTH
 .......... .......... .......... .......... ..........
 ...HALAEAG VD..MVE..L GLPFSDPLAD GPVIQAASQR ALAAGANTDN
 VLELVAALRA DGLQIPLLIM TYYNLVLRVE NFCAAAAGVD GLILPDVPES
 DEIRAAAGAV GLDLIQ..FV APTSPPERIR RA.AELARGF IYAVS.STGV
 TGVRDRLPPQ LTAVEAVKAV TDTPVAVGFG IRPEQVRQVT AVADAAIVGS
 AFVRHGLPEH EL.VERVRIL AEELKAGTR. ........  
>TRPA_OCEIH
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... ....AAMTSE DRLERIAKRS EGFLY.AVSV
 TG.TTGERAQ HENLEKLKQI SHVPVLAGFG ITAERARELS AACDGVVVGS
 .......... .......... .......... ........  
>Q9FQ75_MAIZE
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ......AVGV
 TGARSNVNLR VEHLREIKKV TDKPVAVGFG VTPEHVKQIV GWADGVIVGS
 AI........ ......VKQL CEAAEEGLER LE......  
>Q30PX3_THIDN
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........I
 TGS..GKAED LQILSNIKKH TQTPIYVGFG VNKKTAKDKV KGADGVIVGS
 AF........ .......... .......... ........  
>TRPA_GEOSL
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........V
 TGARSGVEAS SSNVAAIREA ITVPVVVGFG ITPDQAAQVA ASADGVVVGS
 AIKLFERFTA AELGREVATF VSALREAI.. ........  
>Q34AM3_RHOPA
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .......VSI
 TGITGSGSAD SQAVQRIKRH TKLPVCVGFG ITPEGARDIA RHANGAVVGS
 ALKDGRATAG TVVAALVGSL AEGVHAAQQA AE......  
>Q4HRE1_CAMUP
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... ..KIEEIRAY TKLPIFVGFG INYEDVEKIH KISDGAIVGT
 SI......VN EFQNENIDEV IKNVKE.... ........  
>Q3VD58_9SPHN
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........I
 TGQQQAAQAS IDEVARLKAA TDLPVAVGFG VTPDQAAQIA RVADGVVVGS
 AFIDHGDAAA PHVEAFTRTL ADAIHSAKE. ........  
>Q4JW46_CORJK
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... ...APSTTPE RMALTVDAGD GFIYAASMGV
 TGAQDEVSSS AEELVAVREA TDLPVAVGLG VTGKHAANIA SYADGVIVGS
 AL........ .......... .......... ........  
>Q2B9F7_9BACI
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ......AVTV
 KG.TTGARRD QEHLQKVKSV SRLPVLAGFG ITPEHVKAMN QICDGVIVGS
 .......... .......... .......... ........  
>Q4FUL2_PSYAR
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........V
 TGSATLDTDD VAQVQAIKAE TDLPVCVGFG IRAASAKAIG AHADGIIVGS
 ALDIDGNDAT AVAQQKIMAK MTELREALDS L.......  
>TRPA_STRCO
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........V
 TGTRASVGAQ AEDLRRTRAT TDTPVCVGLG VNAAQAAEVA GFADGVIVGS
 AF........ .......... .......... ........  
>Q3C471_9CLOT
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .....APTSE DRMKEIVQDA EGFCVSSTGV
 TGKRNSLAGN LEGMQQLRTY TEIPLVIGFG INSEMMDKLK NICDGFIIGS
 AVKIEAGLED RSSVERVSKF IEKLYE.... ........  
>Q5GMK6_9BACT
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ........EA
 GEYKASLDAL DIATIFLL.. ....APTSTD KRIETVSRHC TGFVY.YVSR
 TGV.TGEQAR VEDVRAIKQH TDKPVAVGFG ISPEHAAEIA RYADGVIVGS
 AIVRDSPETA PKVGEFAKSL ADAAK..... ........  
>Q3N2T6_9DELT
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... ........SA IAQSASGFIM
 TGVTGGGEPD LTELELRSRC DGIPVCVGFG ISPEHARAVS PLADGVVVGT
 AFEREAHQND SAVASKVGEA VGALKAAL.. ........  
>TRPF_PYRAB
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ....ADLILL
 TGAGSGKMHD LRVTRIVAE. .EIPVVVAGG LKPENVEMVI KLVKGVDVSS
 GVERNGKK.. ..DEELVREF VRRAK..... ........  
>TRPA_WOLSU
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........I
 TGSGREEPPL IEEIRAIN.. PEIPLYLGFG VNEHNAKEKS KEVDGVIVGS
 AL........ .......... .......... ........  
>TRPA_GEOKA
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .....APTSK QRIERIASAA QGFCVSSLGV
 TGVRETLPET LGDLREVKRH SRVPVAVGFG ISPEQVAMLK EVCDGVVVGS
 AL........ .......... .......... ........  
>TRPA_AGRT5
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 ....TGSAPD PSLISRIKAH TELPVCVGFG VTADHAKAIG AVADGVVVGS
 SLTKDGQATA DTVPA.VTTL VKGLSTGVRA ........  
>Q9FQ77_MAIZE
 .......... .......... .......... .......... ..........
 .....LDACG ADVIELG... .VPFSDPYAD GPVIQASAAR ALKEVTPELS
 CPV...VLFS YFNPIVRWGL ADFAAAVKEA GVHGLIVPDL PYGNSCA.LT
 LRTEAIKNSL ELVLLT.... ...TPSTPAD R.MEEITRAS RGFVYLATVV
 TGPRANVNTR VQSLQEVKQV TDIPVAVGFG ISPEHVKQIA EWADGVIIGS
 AM........ ......VRQL GEAAKEGLKR LE......  
>Q3E2U7_CHLAU
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........V
 TGARQTLAGN LTDLIAVRQQ TNLPLVVGFG ISPAHIAEVA RIADGAIVGS
 AL........ .......... .......... ........  
>Q2NFE5_METST
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 ...TTGARSN VEHIKRIRKH TDIPLCVGFG ISPEHVKEVL DAADGAIVGS
 AL........ .......... .......... ........  
>TRPA_LISMF
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .....TDIAL IPLVSLTSPK ERLEEIAKQA EGFIY.AVTV
 NG.TTGVRSE FDHLAYLKSI SPVPVLAGFG VSIEHVEKFA HVCDGVIIGS
 .......... .......... .......... ........  
>TRPF_PYRFU
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... ........AN RLLSEISR.. ..YNADMVLL
 TGAGSGKLHD LRVSSLVAR. .KIPVIVAGG LNAENVEEVI KVVKGVDVSS
 GVEKYGIK.. ..DPKLVEEF VRRAK..... ........  
>TRPA_BACHD
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .....APTSN KRIEKIAARA QGFCVSSLGV
 TGLR..DELD PEFLQTVKTH ASVPVVVGFG IRREQVEALA ENADGVVVGS
 AIKLVGELED ELDPEKLE.. .......... ........  
>TRPA_MYCPA
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... ...APSSTPQ RLALTVEASR GFVYAASTMV
 TGARAVSHAA PELVSRVREI SDIPVGVGLG VRREQAAQIG GYADGVIVGS
 AL........ .......... .......... ........  
>TRPA_RHIME
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 TG.ITGSAPD PGAVARIKAH TPLPVCVGFG VTADHARAIG ASADGVVVGS
 SLTEEGRATE ATVPG.VEAL VRGLAAGVRA ........  
>TRPA_NOCFA
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... ...APSSTEE RLVKTLEASR GFIYAASTMV
 TGARAVSSAA PALCARIRAH SDIPIGVGLG VNGAQAAEIA SYADGVIVGS
 AL........ .......... .......... ........  
>Q4L680_STAHJ
 .......... .......... .......... .......... .........I
 KNMKILDENG ADIIEIG... .VPFSDPVAD GPII...MEA GNRAIKQGVT
 INYIFNELSN NKDEINCKYV LMTYYNIIVE AFVGVY.... GVIIPDLPLT
 QKLKHKISKF DVKVISLI.. .....SMTAN DDIKEIVK.. ...HAEGFIY
 TNATTGHPQL KDKLKHLKAH TDIPVVAGFG ITKEHIKDLA TVADGVVIGS
 EIKRFCQDNN EDTIHYLKQ. ...VRETLDT L.......  
>TRPA_CAMJE
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... ......AKGF IYLLA.SIGI
 TGTKSVEEAI LQDVKEIRSF TNLPIFVGFG INNQDVKRMR KVADGVIVGT
 SI........ .......... .......... ........  
>Q2D6C2_9FIRM
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... ...VAPTTNR RRLARITAAA QAFVY.CVTV
 TG.ITGTSQN IEELKEVREA TELPMVAGFG ISPEQAVKVA KYCDGVVVGS
 ALVKLVETHQ EDSLEPVANL TRQLKQAL.. ........  
>Q7Y1I9_ORYSA
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........V
 TGSRQDVNPR VEHLQEIKQV TDKAVCVGYG ITPDHVRQIA EWADGVIIGS
 AM........ ......VRQL GEAAKQGLKR LE......  
>Q3ABS4_CARHZ
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........V
 TGARDSLPAE ISLLQNVKKL TELPVCLGFG IKPEQIAYIK DYCDGVIVGS
 AL........ .......... .......... ........  
>Q8XVS7_RALSO
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... PAYVRALKAV PEVPLFAVGG ITPANLAEYL SA..GCILGS
 DLYRPGQAAD ET.ADRARRF VQAYR..... ........  
>TRPA_METTM
 .......... .......... .......... .......... ..........
 ..IRTLVDAG ADALEIGFPF SDPIADGTSV LRALNSGMTR LIERIREFTS
 VPVGLLVYYN .....LIYRM GADEFYRRAA GVTGILAADL PPEE..AGDA
 LRAAERYGID QIFIVA.... .....PTTDN QRLKMISEVS SGFH..YLVV
 TGARSREEST LELIERVKGA GSLPVMVGFG VSPEHVRMLA DAADGVIVGS
 AI........ .......... .......... ........  
>Q6CYT8_ERWCT
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... PDYIKALKAV KDVPVFAVGG VTPENLKDYL SA..GCILGS
 DLYRAGQSV. EVTAQKAHAF VNAYKDAVQ. ........  
>Q2J2G5_RHOP2
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........I
 TGSASADSVA VGDVARIKRH TDLPVCVGFG ITPEGARAIA AQADGAVVGS
 AL........ .......... .......... ........  
>Q2KE81_RHIEC
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 ....TGSAPD PGAVQRIKQH TELPVCVGFG VTAEHAKVIG GSADGVVVGT
 SLTKDGKAT. ...PDTVQAV ATLVR..... ........  
>Q2IGW2_ANADE
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........V
 TGARHAVADE IAPLVAVRSR TELPVVIGFG VTPEQARALG PLADGVVVGS
 AIAEGGSR.. RARAERVKRF VR........ ........  
>TRPA_RHOS4
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........I
 TGAAAAQAAD VAEVARIKAA TDLPVIVGFG ITPEAAQDLA GIADGCVVGS
 AI........ .......... .......... ........  
>Q2WJC5_CLOBE
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......TSK DRIAAITKGA KGFV..YCVS
 TNGTTGERKT LEYLEEVRKN VDIPMCIGFG ISKEVVKEVK DYCDGVIVGS
 AI........ .......... .......... ........  
>TRPA_METKA
 .......... .......... .......... .......... ..........
 ..ARALRDGG VDILELG... .VPFSEPIAD GPTIQKAVDE ALREVAEEVS
 VPV...VLLC YYNTLHANGF ERYLSAAAEA GVSGIIVADM PVEESDVHSV
 ARDL...... ......EIDV IYLVAPSTTD ERLKKIERAS GFV...YVIV
 TGARRDSEDT LELVRWVRDH VDVPVAVGFG ISERHVEEVI AAADGAIVGS
 AFIKEIHRSE DIAEERVREL AKELVEGAR. ........  
>P5CS2_ARATH
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... GGVPVIITSG YAAENISKVL R...GLRVGT
 LFHQDAHLWA PVVDTTSRDM AVAARESSRK LQ......  
>Q6RUF7_SOYBN
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... ..IPVIITSG YAAENIIKVL Q...GQRIGT
 LFHKDAHKWA PVKEVDAREM AVAARDCSRR LQ......  
>Q4IB67_GIBZE
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 SGSGSGKLLN VANVQAVLES PELRVFLAGG LNPDNVAESV KAADRVIVSS
 GVEEDGKQ.. ..SLDKITAF IKAAKE.... ........  
>TRPA_THET2
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........L
 VRLAQEIGLE TVFLLA.... .....PTSTD ARIATVVRHA TGFVY.AVSV
 TGVTGMRERL PEEVRRIKAR TALPVAVGFG VSGKATAAQA AVADGVVVGS
 ALVREGRSLA PLLQE..... ...IRQGLQR LE......  
>TRPA_BACSK
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........V
 TGARTLHPQV EAFLKLVKEA SPVPFVVGFG ISYEQVEEMG RHADGVVIGS
 AI........ .......... .......... ........  
>Q2AXV5_9BACI
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... ...LEKVKEH VHLPVVAGFG ITREQIEEMI TICDGVVVGS
 ..KVIELLEN EKREE.ICEL IHAVKETEEA ........  
>Q500R5_PSEU2
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........V
 TG..AGSATT TEAIARLRRH TDLPISVGFG ITPEQAAAIA RLADGVVVGS
 AF........ .......... .......... ........  
>Q3KK58_PSEPF
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .......VSV
 AGVTGAGAAT LEHVEEARRH TDLPISIGFG ITPEQAASIA RLADGVVVGS
 ALID..HIAN ATTPDQVLSL CSALSEGVRK ........  
>Q3PIK0_PARDE
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .....PTTDD RRLPAVVRNT SGFVY.YVSV
 TGITGGPAAN AAEVARIRAA AKLPVVVGFG ITPEAAQAVA GVADGCVVGS
 AI........ .......... .......... ........  
>TRPA_BRUME
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .EAVRHIKKS TDLPICVGFG VTPEQAAAIA THADGVVVGT
 AI........ .......... .......... ........  
>TRPA_RHOBA
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........I
 TGERTALPTN LVDVGWLREQ TELPICIGFG ISPETAAQLA PVSDGLIVGS
 AI........ ...VRRVADA VEKAK..... ........  
>Q4HG12_CAMCO
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .GITGGQSAD QEKIQEIRSF TQLPIYVGFG VKNNTVRNMR KLADGVIVGT
 NI........ .......... .......... ........  
>TRPA_LEPIC
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........V
 TGERGSIASG LEDIRMVRKI VGLPVCAGFG ITSDQSKVIS TYADGVIIGS
 AVQR...... .......... .......... ........  
>TRPA_METJA
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .......VSV
 TG.ITGAEET KELIKRVKKF SKIPACVGFG ISKEHVEEIT EIADGAIVGS
 AI........ .......... .......... ........  
>Q2DBL8_ACICY
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........I
 TGTRTASAED LADIPRVRKA TDMPIAVGFG VTPAQAATVA RFADAAVVAS
 AL........ .......... .......... ........  
>Q35M07_9BRAD
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .......VSI
 TGITGAAAAD SAAVARIKRH TALPVCVGFG ITPETARAIA ANADGAVVGT
 AL........ .VDALRAS.. .......... ........  
>Q424N2_DESHA
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... VSSAKLARLS EKLGAAAVIV
 EGHEAGERPM REILPEVKEA VKIPVIGAGG VDGQDVAEVL RLADGVQMGT
 RF........ .......... .......... ........  
>Q2J8M0_FRASC
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... RLVAGVARGF VYA.ASLMGV
 TGTRAAVGER AADLVAVRAA TELPVAVGLG VTAAQAAEVA GFADGVIVGS
 AL........ .......... .......... ........  
>TRPA_RHILO
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........I
 TGSATGKVA. .AAVNRIKGH TDLPVCVGFG VTAEQARVIG ANADGVVVGT
 AI........ .......... .......... ........  
>Q2RNS6_RHORT
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .PVPWLLAGG LTPENVAEAI KVATAVDVSS
 GVETVRGIK. ..DPERVSAF VKAVREG... ........  
>Q3VT15_PROAE
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .SVHE.ALDA QQKGADYIGL
 SKQKENAPLG PEYIRTVKQS VDIPLIAIGG IGLDNAREVM SNADGLAVIS
 AI...SSAVN PAEAAR.... .......... ........  
>Q2G8S8_NOVAD
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........I
 TGMQQAAQAS IEEVARIKQS ATIPVAVGFG VTPEQAAAIA KVADGVVVGS
 AL........ .......... .......... ........  
>Q39SS2_GEOMG
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... RHGIDVIFLL TPTSDETRIT VTNRARGFIV
 TGVRSGIEAS VANVNIIKEC SKVPVAVGFG ITPEQAGEVA ATADGVVVGS
 AI........ .......... .......... ........  
>TRPA_ACIAD
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........V
 TGAATLDVTE AAEIAKIKTK TSVPVGVGFG ISAASAKAMG QVADAVIVGS
 AFVKP.FATL AIDQA.VEQT VNKVKE.... ........  
>Q49XH9_STAS1
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... ...IKDIKAH TEVPVVAGFG ITAAHVKDII EASDGVVIGS
 .......... .......... .......... ........  
>Q3VCF8_9SPHN
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 ......EAAT PAVVKAQRAV NDVPLLVVGG VTADDFGRWL AAADGFGLGG
 ALYRAGDTVT QVHQ.RAARF VATLKPGAR. ........  
>Q44BZ7_CHRSL
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........V
 TGAASLD.VD AVERQLAREM TDLPLCVGFG IRDDTAAAVG RVADGVIVGS
 AL.VSRIAEN AETPEAIPAA LKAV...... ........  
>Q3JCB7_NITOC
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .........V
 TGASTLDVDD SQRVAKIRHY TTMPVGVGFG IRARSAAQIA SIADAAVVGS
 ALKRIEQYQN EVIPEEVSAL LRTMREAIDA TE......  
>TRPA_DEIRA
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .....ADLAA QHGAPTSTPE RVKLVAEACT GFLYAVSVTV
 TGAREGAALG PRMLDLARQY AQRPVVVGFG VKDAATAQQV QVADGVVVGS
 AF......IN AVAAGRVGAL ADELAAGCRR ........  
