>prot (#) default: single protein sequence description=t0371 /home/ppuser/server/work/predict_h11536
MQIESFKSLL PKYKCIFFDA FGVLKTYNGL LPGIENTFDY LKAQGQDYYI
VTNDASRSPE QLADSYHKLG LFSITADKII SSGMITKEYI DLKVDGGIVA
YLGTANSANY LVSDGIKMLP VSAIDDSNIG EVNALVLLDD EGFNWFHDLN
KTVNLLRKRT IPAIVANTDN TYPLTKTDVA IAIGGVATMI ESILGRRFIR
FGKPDSQMFM FAYDMLRQKM EISKREILMV GDTLHTDILG GNKFGLDTAL
VLTGNTRIDD AETKIKSTGI VPTHICESAV IEL
