C......................................................................
C     SUB OPEN_FILE
      SUBROUTINE OPEN_FILE(IUNIT,FILENAME,CSTRING,LERROR)
      IMPLICIT NONE
C input
C CSTATUS: 'old' or 'new' or 'unknown'
C CACCESS:  'append' 'direct'
C FORM:     'formatted' or 'unformatted'
C CREADONLY: 'readonly'
C IRECLEN: record length
C
      CHARACTER*(*) FILENAME,CSTRING
      INTEGER IUNIT,IRECLEN
C output: lerror is true if open error
      LOGICAL LERROR
C internal
      CHARACTER*200 TEMPSTRING,CTEMP
      CHARACTER*10 CNUMBER
      LOGICAL LNEW,LREADONLY,LRECLEN,LAPPEND,LUNKNOWN
      LOGICAL LUNFORMATTED,LDIRECT
      LOGICAL LOPENDONE,LSILENT
      INTEGER LENGTH,I,J,K
C init
      TEMPSTRING=' '
      LNEW=.FALSE.
      LREADONLY=.FALSE.
      LAPPEND=.FALSE.
      LRECLEN=.FALSE.
      LERROR=.FALSE.
      LUNKNOWN=.FALSE.
      LUNFORMATTED=.FALSE.
      LDIRECT=.FALSE.
      LOPENDONE=.FALSE.
      LSILENT=.FALSE.
      IRECLEN=137
      TEMPSTRING(1:)=CSTRING(1:)
      CNUMBER='0123456789'
C     
      LENGTH=LEN(TEMPSTRING)
      CALL LOWTOUP(TEMPSTRING,LENGTH)
      IF (INDEX(TEMPSTRING,'NEW').NE.0) THEN
         LNEW=.TRUE.
      ENDIF
      IF (INDEX(TEMPSTRING,'UNKNOWN').NE.0) THEN
         LUNKNOWN=.TRUE.
      ENDIF
      IF (INDEX(TEMPSTRING,'UNFORMATTED').NE.0) THEN
         LUNFORMATTED=.TRUE.
      ENDIF
      IF (INDEX(TEMPSTRING,'DIRECT').NE.0) THEN
         LDIRECT=.TRUE.
      ENDIF
      IF (INDEX(TEMPSTRING,'APPEND').NE.0) THEN
         LAPPEND=.TRUE.
      ENDIF
      IF (INDEX(TEMPSTRING,'READONLY').NE.0) THEN
         LREADONLY=.TRUE.
      ENDIF
      IF (INDEX(TEMPSTRING,'SILENT').NE.0) THEN
         LSILENT=.TRUE.
      ENDIF
      IF (INDEX(TEMPSTRING,'RECL=').NE.0) THEN
         CTEMP=' '
         K=INDEX(TEMPSTRING,'RECL=')+5
         J=LEN(TEMPSTRING)
         CTEMP(1:)=TEMPSTRING(K:J)
         J=INDEX(CTEMP,' ')-1
         
         CALL STRPOS(CTEMP,I,J)
c	  J=I
c	  DO WHILE (INDEX(CNUMBER,CTEMP(J:J)).NE.0 )
c             J=J+1
c	  ENDDO
c	  J=J-1

         READ(CTEMP(I:J),'(I6)')IRECLEN
         LRECLEN=.TRUE.
c	  write(*,*)'record length: ',ireclen
      ENDIF

      IF (LNEW) THEN
         CALL DEL_OLDFILE(IUNIT,FILENAME)
      ENDIF

      IF (LNEW .AND. LUNFORMATTED .AND. LDIRECT) THEN
         OPEN(IUNIT,FILE=FILENAME,STATUS='NEW',FORM='UNFORMATTED',
     +        ACCESS='DIRECT',RECL=IRECLEN)
c          OPEN(IUNIT,FILE=FILENAME,STATUS='NEW',FORM='UNFORMATTED',
c     +	       ACCESS='DIRECT',RECL=IRECLEN,ERR=999)
         LOPENDONE=.TRUE.
      ELSEIF (LNEW .AND. LUNFORMATTED ) THEN
         OPEN(IUNIT,FILE=FILENAME,STATUS='NEW',FORM='UNFORMATTED',
     +        RECL=IRECLEN)
c          OPEN(IUNIT,FILE=FILENAME,STATUS='NEW',FORM='UNFORMATTED',
c     +	       RECL=IRECLEN,ERR=999)
         LOPENDONE=.TRUE.
      ELSEIF (LNEW .AND. .NOT. LUNFORMATTED .AND. LDIRECT ) THEN
         OPEN(IUNIT,FILE=FILENAME,ACCESS='DIRECT',STATUS='NEW',
     +        FORM='FORMATTED',CARRIAGECONTROL='LIST',
     +        RECL=IRECLEN,ERR=999)
         LOPENDONE=.TRUE.
      ELSEIF (.NOT. LNEW .AND. LUNFORMATTED 
     +        .AND. LDIRECT .AND. LREADONLY) THEN
         OPEN(IUNIT,FILE=FILENAME,STATUS='OLD',FORM='UNFORMATTED',
     +        ACCESS='DIRECT',RECL=IRECLEN,READONLY,ERR=999)
         LOPENDONE=.TRUE.
      ELSEIF (.NOT. LNEW .AND. LUNFORMATTED 
     +        .AND. LDIRECT .AND. .NOT. LREADONLY) THEN
         OPEN(IUNIT,FILE=FILENAME,STATUS='OLD',FORM='UNFORMATTED',
     +        ACCESS='DIRECT',RECL=IRECLEN,ERR=999)
         LOPENDONE=.TRUE.
      ELSEIF (.NOT. LNEW .AND. .NOT. LUNFORMATTED 
     +        .AND. LDIRECT .AND. LREADONLY) THEN
c          OPEN(IUNIT,FILE=FILENAME,STATUS='OLD',FORM='FORMATTED',
c     +	       ACCESS='DIRECT',READONLY,RECL=IRECLEN)
         OPEN(IUNIT,FILE=FILENAME,STATUS='OLD',FORM='FORMATTED',
     +        ACCESS='DIRECT',RECL=IRECLEN,ERR=999)
         LOPENDONE=.TRUE.
      ELSEIF (.NOT. LNEW .AND. .NOT. LUNFORMATTED 
     +        .AND. LDIRECT .AND. .NOT. LREADONLY) THEN
c          OPEN(IUNIT,FILE=FILENAME,STATUS='OLD',FORM='FORMATTED',
c     +	       ACCESS='DIRECT',RECL=IRECLEN)
         OPEN(IUNIT,FILE=FILENAME,STATUS='OLD',FORM='FORMATTED',
     +        ACCESS='DIRECT',RECL=IRECLEN,ERR=999)
         LOPENDONE=.TRUE.
      ELSEIF (.NOT. LNEW .AND. LUNFORMATTED .AND. LREADONLY) THEN
C          OPEN(IUNIT,FILE=FILENAME,STATUS='OLD',FORM='UNFORMATTED',
c     +	       RECL=IRECLEN,READONLY)
         OPEN(IUNIT,FILE=FILENAME,STATUS='OLD',FORM='UNFORMATTED',
     +        RECL=IRECLEN,READONLY,ERR=999)
         LOPENDONE=.TRUE.
      ELSEIF (.NOT. LNEW .AND. LUNFORMATTED .AND. .NOT. LREADONLY) THEN
         OPEN(IUNIT,FILE=FILENAME,STATUS='OLD',FORM='UNFORMATTED',
     +        RECL=IRECLEN,ERR=999)
         LOPENDONE=.TRUE.
      ELSEIF (LNEW .AND. LRECLEN) THEN
c          OPEN(IUNIT,FILE=FILENAME,CARRIAGECONTROL='LIST',STATUS='NEW')
         OPEN(IUNIT,FILE=FILENAME,CARRIAGECONTROL='LIST',STATUS='NEW',
     +        RECL=IRECLEN,ERR=999)
         LOPENDONE=.TRUE.
      ELSEIF (LNEW) THEN
c          OPEN(IUNIT,FILE=FILENAME,CARRIAGECONTROL='LIST',STATUS='NEW')
         OPEN(IUNIT,FILE=FILENAME,CARRIAGECONTROL='LIST',STATUS='NEW',
     +        RECL=IRECLEN,ERR=999)
         LOPENDONE=.TRUE.
      ELSEIF (.NOT. LNEW .AND. LREADONLY) THEN
         OPEN(IUNIT,FILE=FILENAME,CARRIAGECONTROL='LIST',STATUS='OLD',
     +	      RECL=IRECLEN,READONLY,ERR=999)
         LOPENDONE=.TRUE.
      ELSEIF (LUNKNOWN .AND. LAPPEND) THEN
         OPEN(IUNIT,FILE=FILENAME,CARRIAGECONTROL='LIST',
     +        STATUS='UNKNOWN',ACCESS='APPEND',RECL=IRECLEN,ERR=999)
         LOPENDONE=.TRUE.
      ELSEIF (.NOT. LNEW .AND. LAPPEND) THEN
         OPEN(IUNIT,FILE=FILENAME,CARRIAGECONTROL='LIST',
     +        STATUS='OLD',ACCESS='APPEND',RECL=IRECLEN,ERR=999)
         LOPENDONE=.TRUE.
      ELSEIF (.NOT. LNEW) THEN
         OPEN(IUNIT,FILE=FILENAME,CARRIAGECONTROL='LIST',STATUS='OLD',
     +        RECL=IRECLEN,ERR=999)
         LOPENDONE=.TRUE.
      ELSE
         OPEN(IUNIT,FILE=FILENAME,CARRIAGECONTROL='LIST',
     +        STATUS='UNKNOWN',RECL=IRECLEN,ERR=999)
         LOPENDONE=.TRUE.
      ENDIF
      IF (.NOT. LOPENDONE) THEN
         WRITE(*,*)' ERROR in OPEN_FILE: file not opened'
         WRITE(*,*)'  unknown specifier combination !'
         STOP
      ENDIF
      RETURN
 999  IF (.NOT. LSILENT) THEN
         WRITE(*,*)' ERROR: open file error for file: '
         WRITE(*,*)FILENAME
      ENDIF
      LERROR=.TRUE.
      RETURN
      END
C     END OPEN_FILE
C......................................................................

