>query
 MDELELRIRK AEKLVQDAKK EFEMGLYERC CSTAYYAMFH AAKAMLLGYG
 RDSKTHRGTI YLIWECREEL GLSDDDCSKL SRAFDLREES DYGIYKEVSK
 DLAIKILKDA EIFVQKAKNA VNKNR     
>Q5JEG1_PYRKO
 .ELARLSIRK ARSFLESSRK NLEMGIYDGA LVMAYLAMFH AARALLFKDG
 WREKSHACIS AYLREFYVKP GLLDVKWVYL DYVRNLRHQT QYDVGFSPDP
 EEITDILPKI EEFIGVVEKL V....     
>Q5JE09_PYRKO
 .EEIEKHIKI AEEELSSAYL LLENGKLRDS ISRAYYSMFH AAKALLLLKG
 INPRKHSGVI RMFGLHFVDS GFIERPYAKL TYAFSLRSKA DYDVYYEPTH
 EEAENVVETA ERFLERIKSV LEE..     
>Q5JG24_PYRKO
 .....LSIKR AEEWLEEAKR NREFGSYRTS LMASYLAMFH AARAVLFRDG
 WREKSHYCVA RYLEEFYVKT GLEGYWVELL DRMRELRHED QYDVSYTPEP
 DEVKDALKVA EKFIEVIKSL IGEEQ     
>Q2RI66_MOOTA
 IDLCRWRLEK AERTFKEGEQ LLDVGFYNGA INRFYYAAFH AVRALLALKK
 LDSAKHSGVI SLFNREYVKT GVISKEASKL STIFAMRSEA DYDDFKSFSL
 QEAADARKAV RSLIDEV... .....     
>Q2D163_9FIRM
 .ELALWRIEK ADTTFEEGEI SFENHFYEGA INRFYYASFH AVRSLLATKG
 LDSPKHKGVI SLFNREFVKP GLMSIQSSKI RRLFDMRAVA DYRDFATFTE
 EQVREARDDV RALIDEAISF LQKE.     
>Q5JE57_PYRKO
 .DEIRALLRK AEERLAASRE LFERGHYAFA ISSAYYVMFY CARALLLSKG
 ITPKSHAGVH AQLGKEFVKT GEMPRLYTGY SKALNMRHTA DYDAFVEYTE
 RDAREVLRYA EEFLAFTKS. .....     
>Q2RIN3_MOOTA
 ..LILYRMER AKEAIAEAEL LFSEGHIRTS VNRLYYACFY AVSAILLAKG
 YSSAKHSGIR SLFHQKIVKA GLVNPSAGTL NRLFDARQKA DYADLVKFEA
 DIVAPWFDEV KSLVHQIETL VVKE.     
>Y605_METJA
 .EEIQALIEI AEENLSAAKI LFENKLYRDA VARAYYAIFH SAKALLLTKN
 LNPKKHAGVI KMFGLYFVNE GYIEEIYGRI TKSYNLRWKA DYTTDK.PTE
 EEAESIIYEA EMFVDRIKKA LKE..     
>YA00_THEMA
 ..IIEYWRRR ARECLDDAKL LLKNERLHSA VNRIYYALFY QVSALLLAKG
 LSFSKHSGVL AAFNREFVKT GKVNKELGKY NRMFEHRKTG DYGELVEFEE
 ENVKDWIRKA EGFLDAIEKL I....     
>Y142_METJA
 ..ELEKLIEK AEKSLEASEN LYNSEFYDFA VSRIYYSMFY CVKALLLTKE
 INPKKHSGVL KMFAKEFIKT NELDVEFEYI NEAYNYRQTA DYDATIEIKK
 EEAEYLLHKG HIFLNKTKKL ISKN.     
>Q973U8_SULTO
 .DIAEEFLRR AKDYLRASEL LFQQGFYDAS ALNSEVSAQL SLKGLLYKLG
 VEPSRTHGIR ELLSLVYTRL GFIRDNREKL IILENIRGKS QYG.LPPVSK
 DEAEIALFIT KEILKIVESL WN...     
>Q2FRS1_METHJ
 .EEISLFIRR AQETYTVACE LHQNHHYNDA VSRAYYSMFY AAKAVLLTKD
 IITRTHRGTI SQLNSNFVRV GFEEMVWKYL PLSETLREK. ..........
 .......... .......... .....     
>Q2CXJ9_9FIRM
 .DLVLWRLEK AEKTFEDAEL LLERDSFASA INRYYYAAFY AIRALLATRE
 LDSPKHSGVI SLFNREFIKT NLLSKKASKI TKVFDLRS.. ..........
 .......... .......... .....     
>Q2S649_SALRD
 .......LQK ANQALDDASY LLEDDRVEAA MNRAYYAAFH AARAALLTEG
 EEPTSHAGIL SRFSYHFVRT GRISEEVGKL ARAETDRNRA DYDAFSVFEI
 QAAEDLVGDV SQFIEAVGQV IKNHR     
>Q2DP10_9DELT
 .......LQR GNDSLKSAEA LIELDLTLDG LSRAYYAALH YARALLLSID
 VVPKSHKGAL TLFSLHFIKS GIIPKEIGVI SILQKIREDS DYEIGTYYDK
 NEALRLLDDT RLFCTTVAEV LKK..     
>Q2FRF2_METHJ
 .......... .......... ......YEDA ISRSYYALYY AAKALLSSKG
 IITKTHKGLI TQISDHYVNN GLVDHQWHTL AYTESLRESA DYSTGEQITE
 EISLDVIEES KK........ .....     
>Y978_GLOVI
 .........R AEQSLQAARI LADEALFDVS VSRSYYAMFY CARASLLALN
 LSSKSHSGTI SLFGQHLAAA GRLPIEIHRL IDAERLRILG DYG.......
 .......... .......... .....     
>P95880_SULSO
 ....RKLLTT AKDYLKASEL SFEHNLYEAS ALNSEISAQL S...LIFKLG
 IEPPRTHGIR ELLSLIYAKL GFTKENREKL IILENVRGKS QYG.LPPVSR
 DEAEIALSTA QEILKLVESL WN...     
>Q7NKQ2_GLOVI
 .......... .......... .......... .......MFY CASAMLLQLG
 ARPKSHAGTI SEFGRRCVMA GIASEERDEL ILAERRRNAA DYGTQAEIDA
 HIAERLLETA GRWVERTPRQ ITE..     
>Q8TMN6_METAC
 ......SLSI AERFLHSAQK NLEIEEYEMV QLAAYNSAFH SARALLFSKG
 YTERSHSCLG IALNHLYKEE FDLLKLINIF DKMRVSSHNV QYGTFVTFEE
 .......... .......... .....     
>Y1304_METJA
 ...AKLFIKR AEEDLEVAKV LLKTNHYPDS VYHSQQCVEK AVKAVLILNG
 IIFRRHSGV. ..FRNVIYEM KIEDSWKEKL PKIESLRYPE PYNPLEEYTK
 EDAEECLKDA ENVLEVIKDF LKE..     
>Q975T4_SULTO
 ........KR SLEYLKASEE AFINGLYNAS GLMSQISAEL AIKATIAFLG
 YSFPETHEIR KLLSLKDEIS EFIKAKRGEL ILLEDARQRG QY.FSYGLGK
 DDAEICLNTA REVINLVRKV WG...     
>Q6LZU2_METMP
 ......HLDK AKHNLAFVNQ NIKSGNFQDS IVGLYYAVYH AALALVAKKG
 FISRSHNATM IFLIKNYTNL QLIDDDATFY TDLKSERQKA SYSTDAMFNE
 SKVLELQKKS IDFVNKVEDI I....     
>Q3W085_9ACTO
 ...AQEFLGV ADALLALGQR RREQMPLRSA VSRYYYAMFQ AARGVVFLDG
 DDKNAHSELP KSLPQKF... ...PRRAYHL NELKDARNDA DYDPYP....
 .......... .......... .....     
>Q96XM5_SULTO
 ....RWF.KS AKLTLESAKH DVSGGFYNWA CFKSQQAAEF AVKAYFYGIG
 .QPKTGHTIS SLLNLLNAPQ DLIDK.AKYL DKLYPDVWEE ETPAYY.YTK
 KEAEEAIKYA EEIIKYVEEL W....     
>Q3C5D0_9CLOT
 LDVIKLDISN SQAYINEFEK VKESKLYDAS VS........ AARALLILKG
 VDTTKDRLIF KEFISHFVDT GLLDYKLGDL DSLENHYEEV KY........
 .......... .......... .....     
>Q8ZUH5_PYRAE
 .......ITM AERTLSSARL DASHGEYNWA CFKAHQAAEF ALKALLYGVG
 RPARGHSLTH RLLDKFYVPT RCVDAWSEGI PYEY...... .......FSK
 SDAETAIKAA EGVLEFVRGV W....     
>Q96ZS6_SULTO
 .EKASLLCRR ALSYLKVAKD VFHEGLYDVA ATNCQISAEL LIKSTYLFLG
 FVYPETHNIR KLLSENLTKL EEIGRKRKEL NLVELSRFEG QYS.PIDVDS
 DLASDCLDTV EIILPLVKKI WGE..     
>Q97XR7_SULSO
 .EEAEKWLRQ ALEDLATAKD TITTGHYYAS AFWAEQAAEK ALKALLIAGG
 KIERTHD.LN ELLEIIKEEI GLIRSEVIKL TLHYTISRYP DAANTIPYSK
 EDAEELVKKA EKVIEWVK.. .....     
>Q972G7_SULTO
 ......SLSK WEVLYKEALK DIEVGNYNKA ASAIYFSIRK AVEEVLIRMK
 LNIPRRDDKL ANVLKH...L GF.DEEAELF MELYNLRKKA DYSD.ENIDR
 NEITKAIEKY ERIYQQLTKL .....     
>O58139_PYRHO
 ..EYERWIVE AKRTLSSAYS DLKEGYYEWA SFKAQQAAEL AVKAILRGLG
 FAPIGHS..I TRLLKDLSGS LNLDIPREIL YFAMELRYPD AYPEGSPFEE
 DIAKELVKYA EKIIKFVEVV VDE..     
>Q5SKK3_THET8
 MNRARDWMRQ AERDLEHAQK SLELGHWEWA CFAAHQAAEK ALKAVYFALG
 AEAFGHALTH LLAGLH.ERL NLLRRCALVL DRLYPTRYPD SWEAGAPYGE
 EEARDALLCA GEILRFGQSV L....     
>Q8WYY7_HUMAN
 ....EKRLQE AQLYKEEGNQ RYREGKYRDA VSRYH..... ..RALLQLRG
 LDPS...... .......... .......... .......... ..........
 .......... .......... .....     
