>prot (#) default: single protein sequence description=t0367 /home/ppuser/server/work/predict_h24493
MDELELRIRK AEKLVQDAKK EFEMGLYERC CSTAYYAMFH AAKAMLLGYG
RDSKTHRGTI YLIWECREEL GLSDDDCSKL SRAFDLREES DYGIYKEVSK
DLAIKILKDA EIFVQKAKNA VNKNR
