>prot (#) default: single protein sequence description=t0352 /home/ppuser/server/work/predict_h4684
MTTHDRVRLQ LQALEALLRE HQHWRNDEPQ PHQFNSTQPF FMDTMEPLEW
LQWVLIPRMH DLLDNKQPLP GAFAVAPYYE MALATDHPQR ALILAELEKL
DALFADDASL EHHHHHH
