>query
 MTTHDRVRLQ LQALEALLRE HQHWRNDEPQ PHQFNSTQPF FMDTMEPLEW
 LQWVLIPRMH DLLDNKQPLP GAFAVAPYYE MALATDHPQR ALILAELEKL
 DALFADDASL EHHHHHH   
>Q57KF1_SALCH
 MTTHDRVRQQ LHTLETLLRE HRHWRQDAPQ AHLFTSTQPF FMDTMEPLEW
 LQWVLIPRMH TLLDNAQPLP EAFAVAPYYE MALAADHPQR EAILAVLQDL
 DALFARDKS. .......   
>Q32CC6_SHIDS
 MTTHDRVRLQ LQALEALLRE HQHWRNDEPQ PHQFNSTQPF FMDTMEPLEW
 LQWVLIPRMH DLLNNNQPLP GAFAVAPYYE MALATDHPQR ALILAELEKL
 DALFADDAS. .......   
>Q74S42_YERPE
 MSTENKVRQS LQDIEFAMRE TDLWQTVPPE AEAFESNEPF SIDTMAAEQW
 LQWVFLPRMY ALLELNGPFP TRFAITPYFE EALSGDGRPD YALLAQLRCL
 DDLLN..... .......   
>Q87MD3_VIBPA
 MTTSTKLVEL LYQLEAQLQK HELWQQTMPS PEALQSVEPF AIDTLDPHEW
 LQWIFIARMH ALVESSQPLP RGFSIEPYFA EVWKQE.PQY AELLNTIRTI
 DEL....... .......   
>Q5QXS7_IDILO
 .......... .......... .GLWQSHHPP VQALESQQPF AVDTLEFHQW
 LQFIMLPRMW ALVDSKRPLP EGIAVSPMAA HIYRSELEQY EQLIALIREF
 DVLLSGTDPL Q......   
>Q7N8Q5_PHOLL
 MSTAKQILHK LQLIEEAMRE IDLWQSHPPK PEAFESVEPF SIDRMLAEEW
 LQWVLIPRMY ALLEQGLALP TAFAIAPYFE ESYKEDTTGR YQQLFHLRAL
 DRLFMQD... .......   
>Q35ZS1_9GAMM
 .......... .......... .GLWSTSAPS DEAMASTAPF ACDLMSLEQW
 LQFIFIPRMQ ALIDAGQPLP SKIAIAPMAE HVWSEQA.AL APLIGVLNEL
 DMLLNE.... .......   
>Q4ZY70_PSEU2
 .......... .......... ...WDTTPPS EQALASQEPF SVDTLEFAQW
 LQWIFLPRMK VILERDLPLP NASGILEMAE MVYAGCMSET RQLQAHLARF
 DQLIT..... .......   
>Q4IS28_AZOVI
 .......... .......... .GMWASSLPS DEALSSEQPF CIDTLVFEEW
 LQWIFLPRMK VIVEENRTLP ASSGILPMAE LAYRERLAEV ARLLGAIGEV
 DRLIS..... .......   
>Q3NUP2_SHEFR
 .......... .......... .QLWSDTSPP VSALTSTAPF SCDVMAFEQW
 LQFIFIPKMT ELVVQRQPLP TNMALAPMAE HVWQGMHYGD V.LIAQLQQF
 DTLLSQ.... .......   
>Q2SKS8_HAHCH
 .......... .......... .GLWREDQPH EDALASVTPF CADTLEFHEW
 LQFIFIERMK VIVEYRAPMP PRSGIEPAAE MAYQGRLGQV AGLLASLRQV
 DEAINN.... .......   
>Q47Y02_COLP3
 .......... .......... .NLWQIPQPS AAELSSNAPF CCDTLAFGQW
 LQFIFIPKIT MMIHQQQSLP TKISLTPMAE EAFTHLSTSA KPLIDVIQKI
 DKALAEKVS. .......   
>Q2X9X3_PSEPU
 .......... .......... ...WDDEPPS DEALASTVPF AVDTLSFEQW
 LQWIFLPRMK IIIELGHPLP NASSILVMAE TVFTDRPEQS RELRRLLAAF
 DQLIA..... .......   
>Q36RJ6_MARHY
 .......... .......... .GVWQTESLP PEAFQSTQPF CLDTMDFTQW
 LQFVFLEKMK ALVEAGHALP EASGIAPMAE EHFRGREQSG RELISALEEM
 DRLLSS.... .......   
>Q5E789_VIBF1
 MTTSLELSTL LEQLALQLEH HGHWQRTSPS IADLSSTEPF AIDTLSASEW
 LQWIFIPKMN YLIENNKPTP KGVSIAPYIE EALK.DIEGY NEIVRLCHAI
 DAL....... .......   
>Q6LN18_PHOPR
 .......... .......... ...WESAPPS NTALASAEPF AVDTLSCSQW
 LQWIFIPRMT QLIALKQPLP QHFELSPYVE EAMKHDSGVN .IILGVTREL
 DNLF...... .......   
>Q3Q6T4_9GAMM
 .......... .......... .ELWSEQTPS AVAMASTAPF ACDLMPLEQW
 LQFILLPRMQ TLIETGAPLP TQIAIAPMAE HVWQ.DMPQR QALIGVLNEL
 DMLLNE.... .......   
>Q2C037_9GAMM
 .......... .......... HSHWQLTPPD EQLLTSTEPF AIDTLDCHQW
 LQWIFIPKFG QLIALQLPLP TQFEISPYIE EAMKEKVGVN .DILSVTRQL
 DLLFKQ.... .......   
>Q9HV98_PSEAE
 .......... .......... ...WSESSPA PEALASPEPF CVDTLALEQW
 LQWIFLPRMK LILESDSALP QASGILAIAE VAYAQRGEEV AGLLAALGEF
 DRLIG..... .......   
>Q33TR4_9GAMM
 .......... .......... .QLWQDQPPS AEAMADPTPF ACESMTFEQW
 LQFIFLPKMG EIIAVNGALP SQIALTPMAE HVWQGRAEMR V.LITIINQL
 DEHLS..... .......   
>Q2NRK1_SODGM
 MTLHQQVRQR LFDIEQAMHD AEIWQPQPPV RAAFDSVEPF CIDTMEAQQW
 LQWVLLQRMH ALLDRDAPLP ERFALTPYFE EAL....PEA FALLTQLRQL
 DCLLGGDA.. .......   
>Q4K605_PSEF5
 .......... .......... .GLWDDAVPS AEALASTQPF AVDTLEFEQW
 LQWIFLPRMK MILEQDLPLP NASGIQEMAE MVFSTRQGRD QQLRVLLKEF
 DQLI...... .......   
>Q6D8F0_ERWCT
 MSRENLVRQS LFDIERALRE SPFWQVVPPE DGAFNSTEPF CLDTMRPEEW
 LQWVFLPRMH AVLDSDLSLP AELALLPYFE EALEGTPEQT AAVLLRLGLL
 DELFRSDV.. .......   
>Q3P0W0_9GAMM
 .......... .......... .NLWSDSEPS PAALASTAPF SCDTMAFEEW
 LQFIFIPKLG AIVDAKQPLP SQMHLAPMAS QVWQAN.PVY QPIIEQLIAM
 DDFIN..... .......   
>Q3IIR4_PSEHT
 ..MYQQTQAY LVQLRALLKK HQLWQNEPIA AEALQSNVPF CHDTMAFEQW
 LQFVFIEKVE QLIIDKQPLP RNFAIAPMAQ MTLASKKGS. GEIITLLTAL
 DAFLGE.... .......   
>Q9CNF4_PASMU
 MHMHQQTKMH LQQLQLNMQS LGLWQMTPPP ESAFLSEQPF ALDTMSPTEW
 LQWIFIPRMY ALIESEAGLP NKISITPYLE EALKE.MDGL ADLLSPISEI
 EKLL...... .......   
>Q3EFL5_ACTSC
 .......... .......... ..LWQSVPPA EEAFLSEQPF AIDTMSATEW
 LQWIFIPRMH ALLDSEHPLP TQIAVVPYIE EALKE.QERL AELLRPIIEI
 EQLL...... .......   
>Q3QG29_9GAMM
 .......... .......... ..LWRDEMPT AQALASQAPF GCDLLAFEEW
 LQFIFLPRFR VLLETRQPLP AAMSILPMAL HVW.GTHADK DALLIILANL
 DDAVNGK... .......   
>Q65TN2_MANSM
 MTIHLQTKKH LQQLQFAMQS LDLWQTVPPA EEAFLSTEPF AIDRMTATEW
 LQWIFIPRMY ALLESGTELP AQIAISPYIE EALKE.TDNL SLLLSPIIEI
 EQLL...... .......   
>Y1436_HAEIN
 .......... .......... .NLWQTMPPA AEAFLSEEPF SIDTMSAEEW
 LQWVFIPRMQ ALLESGSALP NKIAISPYIE EAMKE.FNEL QQLLTPLVAL
 EELXNNN... .......   
>Q9KTL5_VIBCH
 .......... .......... .QLWQATPPS SQALVSQEPF AVDTLLPHEW
 LQWIFLPKMQ QAIAQNA.VP RGFALEPYFS EVWQGEARYQ A.VLAVIQQI
 D......... .......   
>Q3CPS9_ALTAT
 .....QVEKL LSQLAEALKT AEQWTYSPPS QWAMQSELPF ACDRMGFAQW
 LQFIFIPKMN ELLQEEKPLP TRMALMPMAQ EWYTTGQPTR EPVLDVLAQI
 DLAF...... .......   
>Q44BS0_CHRSL
 MTSHEALMEA LERLVATLRS VDMWRVEEPP AAAFDSQQPF CVDTMELPQW
 LRYVFVARLE TLAETEAPLP ATCSVAPAID TWLKEASPSV RRVVTAVAEV
 DRIVTE.... .......   
>Q7VM61_HAEDU
 .......... .......... HKQWQVTAPS LDQLANDQPF CLGSLTATEW
 LQWIFIPRMH ALLDADADLP RNFSITPYLE EALKQEA... ..........
 .......... .......   
>Q7MIF5_VIBVY
 .......... .......... ...WDEIPPE PALLQSEMPF AVDTLAPQQW
 LQWIFIARIQ QMMAQGASLP KGFLLTPYFE EAWKEQRDTQ T.LLSILRTI
 DE........ .......   
