>query  (#) H.s_Atrium_SK3 /nfs/data5/users/ppuser/server/work/predict_h19881
MDTSGHFHDS GVGDLDEDPK CPCPSSGDEQ QQQQQQQQQQ QPPPPAPPAA
PQQPLGPSLQ PQPPQLQQQQ QQQQQQQQQQ QQQQPPHPLS QLAQLQSQPV
HPGLLHSSPT AFRAPPSSNS TAILHPSSRQ GSQLNLNDHL LGHSPSSTAT
SGPGGGSRHR QASPLVHRRD SNPFTEIAMS SCKYSGGVMK PLSRLSASRR
NLIEAETEGQ PLQLFSPSNP PEIVISSRED NHAHQTLLHH PNATHNHQHA
GTTASSTTFP KANKRKNQNI GYKLGHRRAL FEKRKRLSDY ALIFGMFGIV
VMVIETELSW GLYSKDSMFS LALKCLISLS TIILLGLIIA YHTREVQLFV
IDNGADDWRI AMTYERILYI SLEMLVCAIH PIPGEYKFFW TARLAFSYTP
SRAEADVDII LSIPMFLRLY LIARVMLLHS KLFTDASSRS IGALNKINFN
TRFVMKTLMT ICPGTVLLVF SISLWIIAAW TVRVCERYHD QQDVTSNFLG
AMWLISITFL SIGYGDMVPH TYCGKGVCLL TGIMGAGCTA LVVAVVARKL
ELTKAEKHVH NFMMDTQLTK RIKNAAANVL RETWLIYKHT KLLKKIDHAK
VRKHQRKFLQ AIHQLRSVKM EQRKLSDQAN TLVDLSKMQN VMYDLITELN
DRSEDLEKQI GSLESKLEHL TASFNSLPLL IADTLRQQQQ QLLSAIIEAR
GVSVAVGTTH TPISDSPIGV SSTSFPTPYT SSSSC
