>query  (#) single sequence description=yachdav /nfs/data5/users/ppuser/server/scr/tst/tagape
SAIHHPNEPS VKIKWWLLGL VAILAVGLFW FFHTPAVETT AVQEFQNQMK
QLQSKYQSQN EKLWKRGTTF LEKHLNSSLP RPQPAILLLT AAQDAAEVLK
CLSEQIADAY SSFRSVRAIR IDGAGKAAQD SDLVKHEVDQ ELTDGFKNGQ
NAAVVHRFES LPAGSTLIFY KYCDHENAAF KDVALVLTVL LEEKTLEASL
GLKEIEEKVR DFLKVKFTSS STASSYNHMD PDKLNGLWSR ISHLVLPVQP
ENTLKAGSCL
