>prot (#) default: single protein sequence description=t0382 /home/ppuser/server/work/predict_h14020
MSKLDLHQMT TQDLVALFAK VTVEQDDALL GNQISRFNRL FGVMAEIADE
LKARDGDQRT ALLSLFEYPN MQVRLQAAKL TLAVAPVKAR EQLEAIVSSK
WFPQAGDAGM CLDLLDDGTF KPK
