>query
 MSKLDLHQMT TQDLVALFAK VTVEQDDALL GNQISRFNRL FGVMAEIADE
 LKARDGDQRT ALLSLFEYPN MQVRLQAAKL TLAVAPVKAR EQLEAIVSSK
 WFPQAGDAGM CLDLLDDGTF KPK       
>Q34DV9_RHOPA
 MKRTNLVEMS TPALVMRFAH MGIAQDEAML QGDTAKFSRL FVQMDLISKE
 LKRRDGDQRR ALMTLYDHPN MQVRLKAAKH TLAVASAEAR QQLEAIAESK
 WFPQAGDAGM SLWNLERGVF KP.       
>Q34DV8_RHOPA
 LPGEDLQQMS VEGLVKRLVE IGVAQDAALL GAEYAKFNRL FDRMQQVSAE
 LKRRDGDQRR ALLALYDHPN MQVRLKAAKH TLAVAPVEAR QQLEAIAGSK
 WFPQAGDAGM SLWNLDRGVF KP.       
>Q3WW52_9RHIZ
 ..RQNLARFT SEHLVMRFAE IGIEQDNALL RNEIGSFNKL YDEKAAILAE
 LKSREGDQRT LLLRLYSHPN MQVRLNAAKA TLAIEPNEAR KQLEAIAASG
 QGPQAGDAGM SLWTLDEGIF KP.       
>Q36Y47_RHOPA
 MSGTSNSTMT AGELLDRYIE LSIQQGTAID LSDGSQINRL GSKIFRINDE
 LKSRSGDQRR ILFGLLSHQN PYVRYNAATS LIRIFPVEAR NVLQTIADSK
 WYPLAGHAGM YLHMLD.... ...       
>Q3STG0_NITWN
 .......... VQGLIARFAE IGMAQYDAIY VINTIKYNRL YAEMKRVWTE
 LKEMPGDQRT ALLPLLSHTN VQVRLMAAHS LLALYPGLAR RTLETIRDSG
 IEPQNGSAAN AIRRLDEGSY VP.       
>Q6I7K6_MYXXA
 ........MK LEDLVEQFAQ NVAGQNEAIL RGDAKIGNKH ARKYGAAVDK
 LLANGNAGRD ALAVLLKHER LDVRVMAAAH LLRYRTDGAK AVLEE.AAKG
 QGLAPFGAQQ ALKRWEEGTW ...       
>Q3WW53_9RHIZ
 .......... .......... .......... .......... ...MMIISDE
 LKRRPGDHRR YLSSLYQHPN TKVRAKAAIH TLAVLPEEAR KVLEEVGSLK
 GYSGPMDARG ILRALDEGTY VPE       
>Q3STF9_NITWN
 .......... VKNLVAQFVE IGVAQYDAIN VIDNAMYNRL YKKMERIRAE
 LRKMPGDQRR ALLPLLSHPN VQVRLKAAHS L......... ..........
 .......... .......... ...       
>Q2DJR3_9DELT
 .........K LQILIKRFAV AAKAHYVAME EMDAERAERQ AVVISRLFEG
 IVREGDAGRD ALLALTDDDN PAVAGMAAVY SMRYSPERCI RMLRRLAAEE
 .GLLGFRAAM ALQKWEAGEW ...       
>Q39XB3_GEOMG
 .......... ......RFAA AAEAHAAAME AMDENKVNRH AFVLQGLYRE
 IVLTGEAGRE GLLALVDSDR KAVAGMAAVY SLRYCPERAI TVLRRLSAEE
 .GLLGFRAGM ALERWERGEW ...       
>Q3WLW7_9RHIZ
 .........T LEQWTEEFVR RLKKQAEADR ADDVPTYNKL HKKVVEALNA
 ILGAGPRGRD VLENLLSHET PQVRMWAAGQ VMKWDPDKAI PVL.......
 .......... .......... ...       
