>query
 MEIQEISKLA IEALEDIKGK DIIELDTSKL TSLFQRMIVA TGDSNRQVKA
 LANSVQVKLK EAGVDIVGSE GHESGEWVLV DAGDVVVHVM LPAVRDYYDI
 EALWGGQKPS FAVGAAKPWS AVLEHHHHHH
>Q3K695_PSEPF
 LKGDELVKVA VAALEDVKAQ DIQIIDVRDK QSITDYMIIA TGTSNRQINA
 MLDKVREEVK KNGAKPLGEE GKGDSDWVLL DLDLVIVHMM TASARQFYDL
 ERLWAGAEQS RAADA...KH HSPENTHEH.
>Q9HX22_PSEAE
 MQTEQLVQVA IDALEDLKAQ DIVTLDVRDK TSVTDYMVIA CGSSSRQVKS
 LADNVLTKAK ENGVKPLGSE GLESGEWALL DLGDVVVHVM LPATRQFYDL
 ERLWQGAEQS RA........ ..........
>Q48DL6_PSE14
 MSSEEVINVA IAALEEVKGA DILTIDVRDK TSIADYMLIC TGTSNRQLNA
 LVDNVRDKVK AAGLKSLSEE GKGDSDWVLL DLGDVIVHVM TAAARQFYDL
 ERLWQGAEQS RAASAA...H HTP.......
>Q2WZ58_9GAMM
 MQSAELKQFV VDKIDDLKAR DIVVIDVSKQ SNITDYMVIC SGTSKTHVKA
 IAENLVVEAK AAGIPPIGVE GRDSSEWVLV DMGDVILHVM QDQTRDFYQL
 EKLWSE.... .......... ..........
>Q4J3V4_AZOVI
 MQNEQLVQLA IDALEDLKAK DITVIDVRGK TSVTDFMVVA SGTSGRHVKS
 LAENVLEKVK AQDVRPLGSE GLEGGEWALL DLGDVVVHVM QVATRQFYDL
 ERLWQGAEQS RA........ ..........
>Q7P0P8_CHRVO
 MEIQEISKLA IEALEDIKGK DIIELDTSKL TSLFQRMIVA TGDSNRQVKA
 LANSVQVKLK EAGVDIVGSE GHESGEWVLV DAGDVVVHVM LPAVRDYYDI
 EALWGGQKPS FAVGAAKPWS AV........
>Q2SA29_HAHCH
 METENLKEIV IKALEDIKAK DISVLDVKDR TSVTDYMVIA SGTSNRHVKS
 IADNVIAEVK ANGGRPLGSE GGAASDWILV DLGDIVVHVM LPSSREFYDL
 ERFWRDSPV. .......... ..........
>Q6D7M0_ERWCT
 MQGQALQDFV IDKVDDLKAQ DIVVLNVQGK SSITDYMVIC TGTSTRHVAS
 IADHVVQSSR AAGLIPLGVE GENASDWVVV DLGDVMVHVL QEESRQLYEL
 EKLWG..... .......... ..........
>Q4BKR5_BURVI
 MDIRKLQRVI VDALEDIKAQ DIKVFNTSHL TELFDRVIVA SGTSNRQTKA
 LASSVRDKVK EAGGEIVSSE GEDTGEWVLV DCGDAVVHIL QPALRQYYNL
 EEIWGDKPVR MKLGGDKGQS ..........
>Q2C1B4_9GAMM
 MQVQELQDFI VDKIDDIKAQ DIVTIDVRGK SSITDVMVIC TGSSNRHVSS
 IADHVNKESK LIDFPPFGIS GEEEGQWVIV DMGNVMLHIM QEDARQVYQL
 EKLWS..... .......... ..........
>Q5KWY1_GEOKA
 MTEQEALQLV VRAADDKKAE QIVVLNMKGI SLVADYFVIC HGNSDKQVQA
 IAREIQDQAE EHGLVVKRVE GFHEAKWVLV DLGDIVVHVF AKEEREYYNL
 ERLWGDAPTE DVAAVLQP.. ..........
>Q8KG28_CHLTE
 ..SELLARRV AELSLEKKGE DVKILDVRGL TSVTDFFVII TADSERKAKA
 VTDYIVDEIK EEGERPMHIE GLDTLRWVLI DYVDVVVHIF QPDDRKFYDL
 ESLWSDAPVT V.VTAPEPSD EQEE......
>Q2B1B8_9BACI
 MSERALLDMA VKAADDKRAE DIVVLNMKGI SLISDYFLIC HGNSDKQVQA
 IAREMKEKSE ELGYTVNRME GFDEARWILV DLGDVVAHVF HKDERSYYNL
 ERLWGDA.PS VDV....... ..........
>Q3J7T3_NITOC
 MSTVELKEFV VSALEALKGH DIQVLDVRKL TTVADYMVIA SGTSNRQVKA
 LANEVIERCE AAGYRTLGVE GESYGEWVLV DMGDVVAHIM LPQVRAFYNL
 EKLW...... .......... ..........
>Q3FNE6_9BURK
 .DIQKLQRAI VDGLEDVKAQ DIVVFDTEHL SALFERVIIA SGTSNRQTKA
 LAASVRDAVR DAGFAKPRME GETNGEWIIV DCGQAVVHIM QPNFRQYYNL
 EELWGDKPVR LKFGAAKP.. ..........
>Q66DE7_YERPS
 MQGKALQEFV IDKLDDLKGQ DIIALDVQGK SSITDCMIIC TGTSTRHVMA
 LADNVVQESR AAGMIPLGIE GQGVSDWIVV DLGEVIVHVM QEESRRMYEL
 EKLWS..... .......... ..........
>Q7MN09_VIBVY
 MLREELKDFL ADKADDMKAE NIVILNVEDK SSVTDYMVIC TGTSKRHVAS
 IADHVADEVK KVGLQPLGME GENEGEWVVL DMGDAILHVM QEEHRQLYQL
 EKLWG..... .......... ..........
>Q4ETZ4_LISMO
 MNSYDTLMLT AKAADDKRAE DILALDMKGL SSFADYFVIC HGNSDKQVQA
 IAREIKEKAL ENQVDVKRLE GFDAAQWILI DLGDVIIHVF HKEERSYYNL
 EKLWGDA.PL VDVSAA.... ..........
>Q65H38_BACLD
 MDQASILKIA AEACDDKRAE DIIALNMQGI SLVADYFLIC HGNSDKQVQA
 IAREIKDQAE ENGIDVKKME GFDEARWVLI DLGDVVVHVF HKEERGYYNL
 EKLWGDAP.. .......... ..........
>Q5XDT5_STRP6
 MKKEELLKIV VEATDEKRAK DILALDLEGL TSLTDYFVIA SATNSRQLEA
 IADNIREKVK EAGGDASHVE GNSQAGWVLL DLTDVVVHLF LEDERYHYNL
 EKLWHEA.PA VALDA..... ..........
>Q88WT3_LACPL
 MDSKELLQLT VEAADDKRAD DIVALDVAEV SLMADYFVIL SADSKRQVQA
 IADNIVDFVR KAGSDVKSVE GRTAGEWVLI DAGDVIVHVF QKDARAHYNL
 EKLWSDAP.. .......... ..........
>Q9PBG4_XYLFA
 .....LLSTV HEAVETLKAK DIVKIDVRGK SSVADYLVIA SGTSTRHVKS
 IADEVVKFAK HLNIIPLGVE GKREAEWVLI DLGNVIVHVM LPRVREFYAL
 ERLWSVGNQL TSTENAD.WE A.........
>Q44HK1_CHRSL
 MQTEALKTLV MNTLEELKAR DVAELDVASL TSVTDTMIVA SGTSSRHVGA
 LAESVVESVK EAGYRPLGVE GRQGSDWVLV DLGELVVHVM LPETRQLYDL
 ERLWSDLPSD GAV....... ..........
>Q2J3J4_RHOP2
 LTAEETLQLI LSRLDDMKAE EPIAIDIRGK SAMFDYVVVA SGRVNRHVGA
 IAENVAKALK EAGITKIHVE GLTNCDWVLM DCGDVVLHVF RPEVREFYNI
 ERLWTQGPQP AK........ ..........
>Q28VG8_JANSC
 .SSEELLERI LTSLTDDKAE DVVQIDLRGK SSIGDYMVVA SGRSTRQVSA
 MAEKLVDKLK TDFGLYSKIE GKDSGDWVLI DTADVIVHIF RPEVREFYQL
 EKMWQ...PE APETTPGPGA AAP.......
>Q33PN8_9GAMM
 .QSAELKQFV VDKVEDLKAK DVVVLEVTDK SNVTDYMVVC SGTSKTHVRA
 IAENVVLEAK RANLHIHGVE GRDSSEWVLV DLGDVIVHVM QDKTRDFYQL
 EKLWSEKP.. .......... ..........
>Q5M321_STRT2
 MTKEELLELV VKAADEKRAE DIVALDLYGL TSLTDYFVIL SAMNSRQLEA
 IADNIREKVK EAGVDASHME GDNKGGWILL DLNDVVVHIF TEDERAHYNL
 EKLWHDA.LM VDVSA..... ..........
>Q3PVB7_NITHA
 .DVEETLKLV LSRLEDMKAE ETVTIDLRGR SAFSDYMVIA TGRSNRHVGA
 VAENVAKGLK ETGVKNVHIE GLPNCDWVLI DSGDVIVHVF RPEVREFYNL
 ERLW...... .......... ..........
>Q3N0X6_9DELT
 MDSKSKAFLC AEEADKLKAA DVVLLEVSKY SSFADYFVIC SGKSGRQVQG
 IADSIERSLK EAGIRPLGVE GLREGQWVLM DYGDVIVHVF YEPVRFFYDL
 ESLWSEAETV R......... ..........
>Q8EPV3_OCEIH
 MDKQELIKHV AEACDDKRAE NIVALDMNEV SLVADYFLIC HGSNERQVQA
 IARAVKETVE EKGLSIKRIE GFDQARWVLV DIGDIVCHVF HKDERYYYNL
 EKLWGDANQ. .......... ..........
>Q4UWK4_XANC8
 .....LLATV REAVEELKAK DVVEIDVRGK SSVCDYMVVA SGTSTRHVKS
 IAEEVVKFAK RLDVMPLGVE GEREAEWVLV DLGDVVVHVM LPRVREFYAL
 ERLWGDQRPS DLEEAADDEQ A.........
>Q9KD89_BACHD
 MSNQELLQLA VNAVDDKKAE QVVALNMKGI SLIADFFLIC HGNSEKQVQA
 IAHELKKVAQ EQGIEIKRLE GYEQARWVLI DLGDVVVHVF HKDERAYYNL
 EKLWGDAPT. .......... ..........
>Q67SC2_SYMTH
 .....MAQWA AIAAEGKKAR DVRILDIRSI SVVADYFVIC SGTSGTHVRA
 IVDHVEEELD KKGHKVRHVE GYSGGRWVLL DFGDVVVHVM QEEEREFYNL
 ERLWGDA.VE VAVETPA... ..........
>Q3IJ97_PSEHT
 MDSKQLLAFA IDKIEDMKAR DVIHIDVTAT SDITDYMVVC SGTSKRHVLS
 IADNLAKEAR HAGEEPLGYE GQSDGEWALV DLGDVVVHVM QNEARSYYDL
 EKLWG..... .......... ..........
>Q5E6V1_VIBF1
 LQDKELHDFL FNNVDDMKAE NITTLDVRGK SSITDFMIVC TGTSKRHVSS
 IASNVSDKAK EAGLMPYGID GESEGEWVVV DMGNVMVHIL QEEHRELYQL
 EKLWS..... .......... ..........
>Q2YC52_NITMU
 MTPAKLIKTV VAALDEIKAR DVEVLDVKKL TALFDRMIIA SGDSTRQTRA
 IANNVVEKVK AAGGMVYGVE GENNGEWILV DLGDVLVHVM QTAVRAHYNL
 EELWAHA... .......... ..........
>Q7VWE5_BORPE
 MDIQKLQRAI IDALEDVKAQ DIKVFNTSEL TSLFDRVIIA SATSNRQTRA
 LASSVADRGR ALKLTGITVE GEDTGEWVVV DLGYIVVHVM QPAIRQYYNL
 EEIWGGKPVR VKL....... ..........
>Q41FK1_9BACI
 MTVEQELKLI VNAIDDKRAE DIVVLDMSSI SPIADYFVIC EGNSEKQVQA
 IAREVKEVAH KNELPIKRLE GMDAARWVLA DLENVVVHVF HRDDRDYYNL
 EKLWADAP.. .......... ..........
>Q5P2U1_AZOSE
 MDIRKLQKTV VDALEDIKAK DIEVINTTKL TSLFDRIVVA SGDSNRQTRA
 LSRNVQDKVR EAGGHVVSVE GEETGEWVLV DLGDIVVHIM QPATRDFYNL
 EELWATTPSR VAAGTAH... ..........
>Q47JQ2_DECAR
 MDIRKLQKIV VSALEDIKGK DIEVINTSKL TSMFDRIIIA TGDSNRQVKS
 LANNVQEKVK EAGAEVISTE GEDGGEWVLV DLGDIVVHVM QANVRQYYNL
 EELWSATPQR RKA....... ..........
>Q606I9_METCA
 ISVESLLGIV VAALDEGKGR DVKIIDLRGK TTIAEFFVIA SGTSDRHVRS
 LAGNVEASAK AHALQPFGLE GEDAGEWVVV DLGDVVVHVM KPPVREFYQL
 EKLWAETFPV AA........ ..........
>Q4CHZ5_CLOTM
 LESRELVEKI VSILEEKKAK DLNIIDIREI SILADYFVIC SGTSTTHIKT
 LADEVEEKML EAGIELLHKE GYNSARWILL DYGEVVVHIF HEEDRQFYNL
 ERLWAD.... .......... ..........
>Q484R0_COLP3
 MQTEQLKAFV IEKLEDMKGR DIIALNISDK ASFADYMIIC SGNSNRHVKS
 IAQSVAMECR AQGTEPRGME GNDVGEWALV DLADIIVHVM TDEQRDKYNL
 EQLWAE.... .......... ..........
>Q2RKZ2_MOOTA
 MDAGRVAQLA AQAVLEKKGI DPVILDLQGI TLIADYFVIA SGTSTVQVQA
 IAGRVEEILD AAGVELLHRE GLEAARWVLL DYGAVVVHIF LEEERRFYDL
 ERLWGDAR.R VAIESP.... ..........
>Q9KTF0_VIBCH
 MQGEALKDFL FDKADDMKAV DIVTLDVKEK SSVTDYMIVC TGTSKRHVAS
 IAEHVANEAK LSGLQPLGMN GENEGEWVVL DMGSVMLHVM QEAPRELYQL
 EKLWG..... .......... ..........
>Q8DSI8_STRMU
 MKEKKLLELI VKAADEKRAE DIVVMDLQGL TTLTDYFVIM HATNSRQLEA
 IAENIREKVL KAGGNASHIE GDSKGGWVLL DLNDVVVHIF SEDERYHYNL
 EKLWHEAP.. .......... ..........
>Q310U3_DESDG
 .DGHEKAQRL AALLNDKKAR DLLVFDLRGI SGFTDFMIVG TAGSVRQGQA
 LADYMLDFCK QNNFEFLRVE GYQAGKWILL DMNDVVVNIF QPDSRELYNL
 EGLWADAPQV EAVRNRTGEE ..........
>Q4L6U3_STAHJ
 MNSEELLNIA VDATENKKAE DIVSLNMKGI SDMTDYFVVC HGNNERQVQS
 IARAVKEAAH EQAIDVKRME GYQSARWVLI DLTDVVIHVF HKDERNYYNI
 EKLYQDAP.. .......... ..........
>Q5QYE0_IDILO
 MQAEELREFV IDKIDDLKGR DVQILDVHDK TDVVDYMIIC SGSSKTHVRS
 IAEHVATEAK HAGTPPIGVE GGEQSEWVLV DLGDVVIHVM QDSIRDFYQL
 EKLWG..... .......... ..........
>Q6F840_ACIAD
 .NVQTCLKVV HDALTDVKAK DILELDVSNI SNVADAIIIA SGTSTRHVKA
 LADNVADEAR KSGFRPIGIE GERDAEWILI DLGYVVVHVM LPTARKFYDL
 ESLWRNAPEA TA........ ..........
>Q2IMF9_ANADE
 .........I AAAALDKKAE DVTVLDVRGL TSYADYFVLM TADSDRQASA
 IADHVEQTMK AQGVTKVGVE GYQGGRWILV DYGDVVAHVM GREARGFYDL
 EGLWADA.PR VAVEA..... ..........
>Q3D122_STRAG
 MTEKDLLQLV VKAADEKRAE DIVILDLQPV TSVADYFVIM SASNSRQLEA
 IADNIREQVK GNGGDASHLE GDSKAGWVLL DLNSVVVHIF SEDERQHYNL
 EKLWHEAP.. .......... ..........
>Q3GEA2_9FIRM
 LKEEELAQAI AVYCLDEKAV DVVILDVSEL TIIADYFVIA TARSRVQVQS
 IVEMVQERLK EFDILPSRVE GVEQGSWAVM DYSSTILHVF QPEDREYYDL
 ENLWGDAK.. .......... ..........
>Q3SG63_THIDA
 MNIEDKTRLV VAALEDIKAR DIAVLDTSKL TSLFERMVIA SGDSNRQTRA
 LADNVREKVK EAGEHVGGME GEESGDWVLL DLGEVIVHVM LPAVRAHYNL
 EELWGAGEAA RVRKATR... ..........
>Q49Y33_STAS1
 MKSDQLLKLA VEATENKKAE DIISLNMQGI SDMTDYFVVC HGNNEKQVQS
 IARAVKDAAN EAEIEVKRME GFNDARWILI DLANVVVHVF HKDERDYYNI
 EKLYRDAP.. .......... ..........
>Q5Z019_NOCFA
 .EAIEMAEVA ARAADEKLAS DVVVLDVSEQ LVITDCFVIA SAPNERQVNA
 IVDNVEEKLR RAGHKPVRRE GTREGRWALL DYVDVVVHIQ HNDERNFYAL
 ERLWKDCPPV EGVGEPRPEA A.........
>O67309_AQUAE
 ....EKLKLI KELLENKKAE DIVILDVSKL TNLADYFVIA TANSTTHARA
 LADYLEEELE KRGIEIDHIE GKDYGHWILI DLIDTIVHIF TPETREYYGL
 EWIWADAK.. .......... ..........
>Q3Z9G1_DEHE1
 MESIDIARQM VSIASEKQAE DIVLLDVREL VSYCDYFVLM SGASGRQLSA
 IADTVEKTFK PLKIGPRHRE GDADSGWILL DFGGVIAHIF TPEIRSYYKL
 DRLWENAPKL VSV....... ..........
>Q7DD54_NEIMB
 MNEQELQDLA VNALGDIKAK DISVLETQDK TSLFARMIIA SGDSTRQVKA
 LANNVAVDLK EAGFEILSTE G.DSGEWTLV DAGDLVVHVM LPAVRDFYDI
 DTLWGGEKPS FHAGMQKPWH AA........
>Q34WB3_9GAMM
 ...EQLETLL REALEDIKAE DVVCLDVRGR TPMTDLIVVA TGRSTRHVAS
 VADSVADDLR EHGIRPLGVE GQPGSEWILL DLGDAVLHVM TPEARDFYRL
 ERLWS..... .......... ..........
>Q4FP42_PELUB
 ....DLKDLI LKTLDSNKAL DIISIDLKNK SSMADYMIIA SGTSSRHIQA
 LSEMVLEKLK TNGIKNSKIE GKESGDWKLV DGIDLIVHIF HPDKRKFYEL
 EKIWSEIIPK EKV....... ..........
>Q8DNQ9_STRR6
 MNEKELLELV VKAADEKRAE DILALDVQDL TSVTDYFVIT SSMNSRQLDA
 IAANIREKVA QAGFKGSHVE GDAAGGWVLL DLGAVVVHIF SEEMRAHYNL
 EKLWHEA... .......... ..........
>Q83DY7_COXBU
 MKSAELANLV INTLDEHKAL QITDLDVTTL TDLMDRMIVC SATSKRHASA
 LADKVIRRAK ENGIRPLGVE GEAEAEWILI DLYDVIVHIM LPEVRDFYSL
 EKLWSVTETA R......... ..........
>Q3VW91_PROAE
 ..SELLARRA AELSLEKKCE DVKILDVRGL TSVTDFFVLA TADSERKAKA
 AYEHIVDELK KDDERPLHIE GGDSLHWVLI DYVDVVVHIF MPDERRFYDL
 ESLWGDGKIT V.VEDPAPES SS........
>Q3CG37_THEET
 ...KEKVSKI YNVLEDKKAF DIKILYIGDL TTIADYFIIA TGNSDTHVKA
 LTDEVEKKLW EEGIFVHHIE GYAAGKWVLM DYGDVIVHIF QQEERNFYNL
 ERLWADAK.. .......... ..........
>Q31IE2_THICR
 MDSQQVEALI VSTLEDSKAR DIQVLDVSKL SSFTDKMVIA TGTSTTHVRS
 TGNAVAQAFK EAGEPPMGVE AGPEPDWVLV DLGNAIVHVM TESARAHYQL
 EKLW...... .......... ..........
>Q3IZI6_RHOS4
 .......... LASLDDDKAE DIVQIDLRGR SDMADYMVIC SGRSSRQVAA
 ISEKLMDRVK QQFGRFSKVE GKETGDWVLI DTGDVIVHVF RPEVREFYQL
 EKMW...... .......... ..........
>Q2LSS9_SYNAS
 ........MC VNAILEKKAG RLVILNVKEI SSFADYFIIC DGASDRQVQA
 IAAAVQERMK KCGILPLGVE GESAGKWVLL DYADVIIHIF FQPVREFYDL
 ERLWGDVP.. .......... ..........
>Q6MBT6_PARUW
 .........V AQAIYDKKGF NILVLDVKGI CTMTDYFIIA EGTVDRHVRA
 ISQTIVDQLA KHQHHPYHIE GEREGDWIVL DYTDFVIHLF VPDLREKYAL
 EELWKGGKVD VSIDTSRPE. ..........
>Q3V9Y2_9SPHN
 .SVDALHALI LHQLDEDQAQ ETISIPLAGK SSIADHMVIA SGRSTRHVSA
 IAEKLAQRIK QEAGRPVRVE GLPNADWVLL DAGDVIVHLF RPEVRSFYNL
 ERMWGDAPPV AAAN...... ..........
>Q43JT0_9CHLB
 ...QLLARRI AELSLEKKCE NVKILDLKRL TSVTDYFVII TADSDRKARA
 AADHIVAMLK EDDERPLHIE GLDTPHWILL DYVNVVVHIF MPDERRFYDL
 ESLWSDAPVT M......... ..........
>Y034_HAEIN
 .....LVEFL METLDGLKGT DIVHFDVRGK SSITDNMIIC TGTSSRQVSA
 MADNLITECK KAGFETFGEE GKNTADWIVV DLGQAIVHIM QRDAREMYQL
 EKLWA..... .......... ..........
>Q98EZ9_RHILO
 ......INTV LASLEDSKAE NIVSIDIQGK SSLGDYMVVA SGRSHRHVSA
 VADHLLKALK DAGLGTARVE GLSGADWVLI DSGDIIVHVF RPEVREFYNL
 EKMW...... .......... ..........
>Q5WHH8_BACSK
 ..MNEHLKMA VAALDDKKAM QITALDMRGI SPIADYFIIC HGNSEKQVQA
 IAHELKKVSQ EAGLDIKRLE GYDVARWVLI DIGDVVVHIF HKDERLYYNL
 EKLWGDAAQ. .......... ..........
>Q5FIX7_LACAC
 MTSQEILDFT TKAISDRHGE DTEAYDMRGV SILADYYVIT SAGSNRQLHA
 IVNSIVDAAH ENNYTDYRIE GTRDSNWLLL DLGDVVVNVF TKEAREFYNL
 EKLWANGKQ. .......... ..........
>Q3GHA4_CHLVI
 .DGELLARRA AELTLEKKCE DVKILDLREL TSVTDFFVIV TADSERKAKA
 AAEHVIEELR GEDERPLHVE GLDSMHWILL DYVNVVVHIF MPDERGFYDL
 ESLWSDAPVV A......... ..........
>Q4C614_CROWT
 .SIQNLALTI VQAADDRKGS DISVLKVTEI SYLTDYFVII TGFSRTQVKA
 IAEAIEEKVY QHQQVPRQTE GKQDGNWILQ DFGDVIVHIF LPEEREFYNL
 EAFWGHAE.. .......... ..........
>Q9A2X4_CAUCR
 ..MKALERLI LDRLDDDKAQ DIVHIDLTDK SSVADSLIVA SGRSHRHVGA
 LADHILRALK ENGFGKARVE GLPHCDWVLI DAGDVVVHLF RPEVRSFYNI
 EKIWADAPHR TAAN...... ..........
>Q38VU1_LACSS
 MKSLDLLKIA VKAADGKRAE DIVALNMEGI SLLADYFVMM TGSSERQLDA
 IVDAIEDAEE EAGLMVKKIE GKKGSRWILM DFGDLVINVF MPEERALYNL
 EKLW.DEAPM VDVS...... ..........
>Q9CJS0_PASMU
 MNT..LVDFI IDKLDDLKAT DILRLDVRGK SPITDDMVIC TGNSSRHVSS
 LAQNLITECK QAGFETFGDE GQETADWIVV DLGQAIVHIM QADSREMYQL
 EKLWG..... .......... ..........
>Q4FV91_PSYAR
 ...QECLTLV ENALDDMKAK NITIMDVAAL TDVMERIVIA DGTSKRHVRA
 MADSVGAEAK QAGFMPLGRE GGIDSDWTLI DLGAVVVHMM TPQAREFYDL
 EGLWSSPEQL AELVA..... ..........
>Q3ANY6_CHLCH
 .ESELLAQRI AELALEKKCE VVKILDVRGL TSITDFFVIA TADSERKAKA
 SADHILDELR EEGERPLHVE GLDSQHWILL DYVDVVVHLF LPDERRFYDL
 ESLWSDAPTT .......... ..........
>Q3AIM0_SYNSC
 MDSEKLAELV ADACDDRKAT DIRLIRVDEV SSLADWMVIA GGQSDVQVRA
 IARSVEDRLE EAALLPLRKE GLNEGRWALL DYGDVIVHVL MPDERGYYDL
 EAFWSHGESR .......... ..........
>Q2GCB6_NOVAD
 .....LHDLV LKSLDDDQAQ EVVSIPLEGK SSVADYMVIA SGRSTRQVAS
 MAQKLAERIK QNGFGHVRIE GLPAADWVLI DAGDVVVHLF RPEVRTFYNL
 ERMWA..... .......... ..........
>P73658_SYNY3
 ..TEHLVWTI AQAAEERKAG DLVILKVTDV SYLADYFVIC TGFSRTQVRA
 IADNIEKQVE LHGQLPTHTE GNSESIWVLQ DFGDVLVHTF MPEEREFYKL
 EAFWGHA... .......... ..........
>Q92JT0_RHIME
 ......LQLV LESLEDSKAE NIVTIDIAGK SALGDFMVVV SGRSNRHVMA
 IADHLITDLK DDGLGRARVE GLEGGDWVLI DTGDVIVHIF RPEIRAFYNI
 EKMWA..... .......... ..........
>Q3A1E2_PELCD
 MQAKQQALLC ASYALDKKAF DVRLLDVTGK SSLTDFLLIV SGGSDRQVGA
 IAESIELGMK EHDVMPLAVE GKQEGRWVLL DYGDVMVHVF QQAVRQYYDL
 EGLWTEAP.. .......... ..........
>Q821T2_CHLCV
 .....LLKVV AKIIDNKKGN NPVVLDVRAI SQLTDYFIFA EGNVGVHVKA
 LADTIVEELK QYNVSPLHVE GLSHGDWVVI DYGFIVIHLF ISSIRDHYRL
 EELWKD.... .......... ..........
>Q6Q944_9GAMM
 MPTKSLSNIC NHSLDESKAE DVIILDVKAV SSFADEIIIA TANSNRHATS
 VSNKLVEALK ENKINIIGVE GESSSGWILV DCGDVVINIM RKEQREFYDL
 ESLWGEMMPS .......... ..........
>Q9PLF4_CHLMU
 MDSYNLLKGI VRAIDDKKGR NPVILDVQGI SQLTDYFIFV EGNVGVHVKA
 IADTIVEELK KLKVYPLNVE GLSHSDWVVI DYGFIVVHLF VSSVREQYCL
 EELWKD.... .......... ..........
>Q7CW98_AGRT5
 ......LETV LASLEDSKAE DIVSLDIAGK SALADYMVVV SGRSNRHVSA
 ICEHLLKDMK DEGFGNARIE GLEAGDWVVI DAGDIIVHVF RPEIRVFYNI
 EKMWA..... .......... ..........
>Q40RM1_DESAC
 LQSDQRALLC SEYALDRKAL DVKVLHISKL SSLADYLVLA TGTSDRQVQA
 IAESVRLGLK QHDLQPLAIE GMNEGRWVLL DYGDVMVHVF QQEVRSFYDL
 DGLWSEA... .......... ..........
>Q5NLX3_ZYMMO
 .DPEMLLKLV TDSLDDDQAL EIATIPLAGK SSIADYMVIA SGRSSRQVTA
 MAQKLADRIK AATGYVSKIE GLPAADWVLL DAGDIIIHLF RPEVRSFYNL
 ERMWGDQPVS QSV....... ..........
>Q3NN99_SHEFR
 .......... ....DDLKAK NITVIDVSKR STITDTMIIC TGTSKTHVRS
 IGEHVIVSAK NAGVQPLGVE GRDSSEWVLV DLGSVILHVM QEQTRDYYEL
 EKLWSE.... .......... ..........
>Q6G4Y8_BARHE
 ......LNVI LKSLEDTKAE DIVSIDIQGK SSLADYMVIA SAHSQRHVSS
 VADHLLRTWK DSGYGRASVE GLTEGNWVLI DTGDIIIHLF RPEIRLFYNL
 EKMW...... .......... ..........
>Q8RBA1_THETN
 IEAKEKVYKI CRVLDEKKAF DVKILYIGEL TTIADYFIIA TGTSSTHVQA
 LADEVEKKLG EEGIFVDHVE KDFASEWILM DYEDVVVHIF QQEAREFYSL
 ERLWADAK.. .......... ..........
>Q8YJ76_BRUME
 .......DAA LASLENSKAE SIIPIDIRGR STIGDYMIVA SGRSHRHVTA
 VTDHLVQALR EAGCKEMRVE GLESGDWVLI DTGDIIVHIF RPEVRDFYNL
 EKIWLD.... .......... ..........
>Q3AF31_CARHZ
 ......INIA MDAALDKKGF NLSLLDVSSL TPICDYFLIV SASSTIQVKA
 IVDNIEEKLS EIGLTPYRIE GKNAARWVLM DYGDLVVHVF VEEEREFYDL
 ERLWRTAE.. .......... ..........
>Q3CLG2_ALTAT
 .......... VEKIEDLKGR DIIDLDVSEK SSVTETMLIC SGNSKRHVVS
 IAENVVVEAK QAGNPPLSIE GREVGDWVLV DLGDVVLHVM QDDARDFYQL
 EKLWG..... .......... ..........
>Q3HCY3_TRIER
 ....ELTSTI VNAALDRKGD NIVVIRVSEV SYLADYFVII TGYSNVQVRA
 ISQAIAEKVE ERQVNPLGVE GHSESSWILM DYADVIVHIL KPEERDFYNL
 EAFWGHAE.. .......... ..........
>Q9Z6Z1_CHLPN
 MDSFDLLKVA AKAIDDKKGN NLVVLDVRTI SEFTDYFVFV EGSVNVHVKA
 LANTIVEELK KQKVSPLHVE GITDGNWVVI DYGFIVVHVF VSEIRGKYRL
 EELWKD.... .......... ..........
>Q5GT38_WOLTR
 .DTELIKSTI MSIIDQNKGR DIVTFDVQNK TIIAKYMIIA SGDSSRHVKA
 LAEHVMKSLK Q..YYKMDVE GMDEGNWVIL NFQGIMVHIF RPEVREYYKI
 EELW...... .......... ..........
>Q2RV08_RHORT
 .....MAEIV ETALDEDKAE EIVVIDLAGK SSFADCMVVA SGRSARHVAA
 LAERLTERLR AVGLRV.KVE GLGACDWVLL DAGDVVVHLF RPEVRAFYNL
 EKMWGAPAPA TDAEPADVQD SGPE......
>Q492Z6_BLOPB
 MQSDVLKEFI VNVIYNIQGQ DIACFDISGK TNITDIMIIC TGMSRRHVIS
 ISQEILRKSR SLGLQPYGAE GMSIGEWVLV DLGDLVIHVM QKEIRKLYEL
 EKLW...... .......... ..........
>Q3EHZ0_ACTSC
 .....LTKFL TEKLDALKAI DILTIDVRGK SSVTDNMIIC TGTSSRHVAA
 LAQKLIDESK QAGFDTFGAE GRATADWVVV DFGQAMVHIM QQDSREMYQL
 EKLWA..... .......... ..........
>Q3XT68_9PROT
 ......AHTI QAKLDDKKGE DIVLVDLEGR SGLADFFIIV TGRSTTHVRA
 LADEVDQVAS QLNLPTIGVE GVQEGEWVLM DFGDIVVHIF REEVRAHYNL
 EKLWSAEAPS KALDAENPWH AA........
>Q74ID2_LACJO
 LDSKKLLDLT VEAIDERHGE DTEAYDMQGI SILADYYVVT TAGSNRQLHA
 IVNSIIDKIH EHGKEDYRIE GTRDSNWLLV DMGDVVVNVF TEDARDFYGL
 EKLWSNGK.. .......... ..........
>Q2GLC3_ANAPZ
 .STENLKDLV VAVLDEHSAR DIAALDVRDR CQLTEYIIIS SGNSTSHVKA
 LAEHVKKKV. .AHYSKKHIE GLDEGNWVVI TLNNVIVHIF REEVREYYKL
 EDLWS..... .......... ..........
>Q82XC6_NITEU
 MKSEKLLETA IMALEDLKAS NIHVMDVSKL TSLCTTMIVA SADSTRQTRA
 LASHVQEKVK ATGSMVYGIE GEQTGEWLLV DLGDIIVHIM QPAIRSYYDL
 EGLWSEQ... .......... ..........
>Q2ZDV0_CALSA
 ....EKILQI VRILSQKKAQ DIVVLDISKL TIIADYFIIC SASNIQHVKA
 LVDEIEEKSP A...DILRIE GRESYRWVVV DYGDVILHIF HEKEREFYNL
 ERLWIDAP.. .......... ..........
>Q3YRG1_EHRCJ
 .STEELKNLI TCILDKHKAS NIVTMNISDK SNLAEYLIIA SGESSYHVKS
 LAEKIKKEIK P..YKKFSIE GLKDGNWVVL NCCNILVHIF KPEVREYYQL
 ESLW...... .......... ..........
>Q3NA50_9PROT
 ....EQLKTV IMALEDLKAS DIHVINVSKL TALFNTMVIA SADSTRQTKA
 LAGHVQEKVK AAGRIVYGME GEQTGEWMLV DLGDIVVHIM QPAIRSYYDL
 EGLWAE.... .......... ..........
>Q39QR0_GEOMG
 ....ERALEC ARLALDKKAL DVKILKIGRL SSIADYLVLA SGRSDRQVQA
 IADSVKKGLK KYG.KALDVE GLKEGNWVVI DYGDVLVHVF QEEVRRYYNL
 DELWSSAPTS ...EIPDAW. ..........
>Q3G1J1_9DELT
 LTSRERAIRC AELASDKKAF DIRALDISTI SSIADYLVIA SGGSDRQVQA
 IADSIRIGLK KFG.KVNDIE GESEGKWIVM DYGDVLVHIF HEPVRRYYDL
 DGLWGELELP AAIRTPHGES ..........
>Q3MF77_ANAVT
 .SSGELALTI AEAASDRKAG DILVLRVADV SYLADYFVML TGYSKVQVRA
 IADAIQHEVE KWQRRPLRTE GKVEGSWVLQ DYGDIIVHIM MPKEREFYNL
 EAFWVHAE.. .......... ..........
>Q6AJX9_DESPS
 .SSVELAEIC AQIALDNKAE DIVIVDVQGR VSFTDQFVIM SGRSTRHVLG
 LAENIEAAFR SKKVKASTAE GLEDGMWVLL DFDDIIVHIF YYEQREFYDL
 EGLWNEAPQ. .......... ..........
>Q2BR45_9GAMM
 MQTEKILELV HGALEDMKAK EITDLDVRGR STVTDYMIIA SGTSKRHVAA
 VAEEVVVKVK EAGLMPLGSE GQGASDWILV DLGDVVVHVM MPDARSFYDL
 ERLWG..... VDADA..... ..........
>Q3H332_9ACTO
 ....ELVHTA ARAASEKLAQ QLIAFDVSEQ LAITDAFLLA SASNDRQVKA
 IVDEIEDKLR EIGAKPLRRE GERDGRWVLI DYGEVVVHVQ HEEERQFYAL
 ERLWRDCPAP ADVTAAE... ..........
>Q5FFX7_EHRRG
 .SEEDLKDLV ISILDQHKAT NIVTINIGNI SNLAKYLIIV SGQSNYHVKS
 LAEKVRKAIK P..YEKVSIE GLKEGNWVIA SFHNILVHIF RPEVREYYQL
 ESLWHGQ... .......... ..........
>Q6A9H4_PROAC
 ....ELARVV AYAALDKKGF DIVALDVSEH LAITDIFVVI SAANERQVSA
 VVDAVDKAMH EHKAHRPRRE GERENRWVLL DYIDIVVHVQ HQEERELYSL
 ERLWKDC.PS VDLRLPEDEM SVP.......
>Q2ZY18_STRSU
 .......... .....DKRAE DLVVIDVQGV TSLTDYFVIA SSMNSRQLEA
 IAENIREKVA EVGIKSSRVE GDSNGGWVLL DLGGLVVHIF SEEMRDLYNL
 EKLWHE.... .......... ..........
>Q6IVQ0_9GAMM
 MSKKTLSEIC NNSLTDSKAE DLLVLDVENI SSFADKIIIA TATSNRHALS
 VSEKLVESLK ENKFNILGVE GEIDSGWVLV DCGDIVVNIM KKEQRDFYDL
 EGLWGE.... .......... ..........
>Q2CS86_ECTHA
 MVVEELEQRI RESLDAIKAQ DTVAIDVRGR TPVTDLIVVT TGTSRRHVHA
 VARNLVDEAK AVGLPPLGVE GDENSEWVLI DLGDAVVHVM TQESRDFYRL
 ERMW...... .......... ..........
>Q5WWX1_LEGPL
 ......LEKL LKSLEDIQAI DIKIIDVHKQ TTITDFMVVT SGRSSRHVKS
 IAQKVLEDMK VAGLPCLSST GIEHGDWALI DFGDIILHVM QPEFRHFYNL
 EGLW...... .......... ..........
>Q8G5P0_BIFLO
 .DSINAVRVA AEAADRIKAT DIVAFDVADL LGITDIMMIA GASNERQVLA
 VAEEIEKFLK CSGRQPRSRE GLTEGQWVLL DYGDFVIHVM HEESREFYGL
 ERLWRDC.PA IDLELAHPET A..EHA....
>Q8DJK1_SYNEL
 ....KLAWTA AYAADDRKGV DICLLDVSGV SYLSDYFVII TGLSKTQVRA
 IYQGIEEAAL EHQRQPQHIE GQAECSWVLM DYGDVIVHVQ LPKERQYYNL
 EAFWGHA... .......... ..........
>O86327_MYCTU
 .EAIDMARVA AGAAAAKLAD DVVVIDVSGQ LVITDCFVIA SGSNERQVNA
 IVDEVEEKMR QAGYRPARRE GAREGRWTLL DYRDIVVHIQ HQDDRNFYAL
 DRLWGDCPVV VDLSA..... ..........
>Q2AGS4_9FIRM
 ..TKELAILA AEAAEDKKAN DVQVLDVKEL TIIADYFVIC SGNSEPQVKA
 IARSVEDKLG EEGIHPQKVA GKDNARWILM DYADVIVHIF LEEERQYYEL
 ERLWADAEQ. .......... ..........
>Q65RG9_MANSM
 .....LVDFL VDKLDALKAT EIECIDVRGK SSVTDNMIIC TGSSSRHVAS
 VAQKLIDESK QAGFESFGEE GKAVADWIVV DFGQAIVHIM QGDARQMYQL
 EKLWA..... .......... ..........
>Q7VRA9_BLOFL
 .....LKNFI LNYLDDLKGQ NIICFDIHNK NRITDFMILC TGRSNHHVKS
 IAQSILKKIK SMKQKWNRVE GIEFGEWVSI DLGEIIIHIM KYETRKLYDL
 EKLW...... .......... ..........
>Q818D4_BACCR
 MNDKDLLVLA AKAADDKRAE DMVVLNMQGI SPIADYFIIC HGNSDKQVQA
 IAREIKSKAH EFQIDVQRME GFDEARWVLV DLGDVVAHVF HKDERNHYNL
 ERLWGDVP.. .......... ..........
>Q31RX3_SYNP7
 .....LTLAA ATAADDRKAG DIAILRVSEV AYLADYFLIC SGFSITQVRA
 IARSIEEKLS EDFQRPLRSE GMAEGRWVLL DYGDLIVHIF LPQEREFYDL
 EAFWGHAE.. .......... ..........
>Q7VKA2_HAEDU
 ...QHVIEFL TTTLDDLKAQ DILAIDVRGK SSITDTMIIA TGTSVRHVAS
 TAERLITEAK KAGVQVLGEE GRAVADWVVV DFGQAIVHLL QADARELYQL
 EKLWR..... .......... ..........
>Q9ZCE5_RICPR
 .ETEELKLFI LECLIEKKAE DIEVIDLRGK NKLADYIIFA SGRSTKNVGA
 IAEYVALALK NNACINSNIE GLGKSEWVLI DAGAILINIF YPEVREHFKL
 EEIWK..... .......... ..........
>Q2CDL5_9RHOB
 ..SDSILAAI LTSLDDDKAE EITQIDLRGR SEMGDWMIIA SGRSTRQVVS
 IAEKLTDRLK TELGVQSKVE GKEAGDWVLI DTGDVIVHVF RPEVREFYQL
 EKMW...... .......... ..........
>Q31AQ8_PROM9
 MDNKSLVLMA AKACDDKKAK DIKLIKIDKV SFISEWILIA EGLSDVQVRS
 ITNSVEGELR KANIEPIRKE GFNEAKWALL DYGDLIVNIF QPEIRKFYDL
 ESFWS..... .......... ..........
>Q7URC6_RHOBA
 .DARKLATEA ARVALDNNGQ DVMVLNVSEQ SAEFDFFVIA TGTSRRQLHA
 ISEQTDDALE KLGDRRQGIE GYQESSWIVL DYGSVVVHLF DEETREYYDL
 ESLWADATP. .......... ..........
>Q46LB2_PROMT
 MDSIRLVELA AVACDDRKAG DIKLLKVDKV SSIADWILIT EGLSDVQVRA
 IVNNVEKTIR EADLLPLRKE GINEAKWALL DYGDLIINVF QPNERKFYDL
 ESFWS..... .......... ..........
>Q3W0D1_9ACTO
 ....ELALAA AQAAADKIAQ DILILDVSER LTITDCFVIA SAENERQVKA
 AVDEIEEKLR AMGAKPLRRE GEREGRWVLL DFADIVVHVL RAEERVYYSL
 ERLWKDCPV. .......... ..........
>Q8FN92_COREF
 .ESIRLATIA AQAADEKKAE DIAVLDVSDL LAITDVFVLA SADTERQVAA
 IVEEIEAEMT DAGFEPKRRE GNRENRWVLL DYGVLIIHVQ RHAEREFYGL
 DRLYRDCP.. .......... ..........
>Q4HBV3_9DEIO
 ...QQQLRAI VDAARERRAE DVVVLDLTDV SSTLEYFVIC TATAGLQLNA
 VQENIREKAQ EAGLPRPTVE GPSE.RWLLA FGGSIVVHIM TREAREYYDL
 EGLWSDARV. .......... ..........
>Q5FRT0_GLUOX
 .....MLTVI TTSLDEDKGE DIVVLDLVGR ANFADRMVIA TGLADRQISA
 MAHHIEKKLN EIGIKRILIE GANGSDWVLI DAGDVVVHLF KPESRELYGL
 ERMWGGSEDE VAVG...... ..........
>Q9CIX8_LACLA
 MDSKKLLEVV VKAADDKKAL DIVALDMSEV TFVADYFVIM EAMNSRQLDA
 IADNIEAAEL AGAKAAGHIE GDAKTGWVLI DLGDIVVSVF GHDERGHFNL
 EKLWSDAP.. .......... ..........
>Q82C74_STRAW
 ....ELINTA AQAAADKLAH DIIAYDVSDV LSITDAFLLA SAPNDRQVKS
 IVDEIEERLK ELGVKPVRRE GDREARWVLL DYVDIVVHVQ HSEERVFYAL
 ERLWKDCPEL APADAQATRG KAAEHA....
>Q40US9_KINRA
 ....ELVTTA AAAAVDKLAT DVIALDVSDQ LFITDAFLLA SAPNERQVRA
 IAEAIEEKLL PLGSKPVRRE GEREGRWVLL DFVDLVVHVQ HTEEREYYAL
 ERLWKDCPV. .......... ..........
>Q47MW6_THEFY
 ....ELVTIA ATAAADKLAQ DIVAYDVSDQ LVITDAFLLC SAPNDRQVRA
 IVDEIEERLR QAKAKPVRRE GEHEGRWVLL DYVDLVVHVQ HEEERGYYSL
 ERLWKDCPQI ELPQAAQGVD HT........
>Q2A3B2_FRATU
 MTTDQRLEIV LEALDDLKGI NIQTIDVEHL TDMMDKIVIS TASSTTHAKA
 LAKNLEQELK NNEITILGIE GDNKSDWVLV DIGDIVVHIM LEATRDLYAL
 EKLW...... .......... ..........
>Q3PAA2_PARDE
 .......... .......... ...TIDLRGR SAMADHMVIA SGRNARQVAS
 IAEKLVERLK EQTGRSARIE GKETGDWVLI DTDDVIVHVF RPEVREFYQL
 EKMWADALRS AALDRLRAEH AA........
>Q2JWR3_SYNJA
 .........A ARAAEEKKGG DIVLLDVSQI STLADYFLLI SGYSLTQVRA
 IARAIEEKVE EWQQSPRRIE GQESGSWILI DYADLIVHVF MQEERDYYDL
 ESFWIQA.QR VDL....... ..........
>Q5LHD2_BACFN
 .ETKVLIEKI TEGIQEKKGK NIVIADLTNI DTICKYFVIC QGNSPSQVIA
 IVDSIKEFTR KAGTKPSAID GQRNAEWVAM DFSDVLVHVF LPEARNFYNL
 EHLWADAK.. .......... ..........
>Q747Q6_GEOSL
 ....ERALQC ARFALDKKAL DVKVLEIGRI SSIADYLVLA TGRSDKQAQA
 IADSVKKGLK KYG.KVIDME GLREGNWIVI DYGDVIVHIF REELRSYYDL
 DGLWSAAGQV A......... ..........
>Q4NA43_9MICC
 .SSIAIARVA ARAAADKIAQ DIVGLDVSER LALADVFLIA SAPSERQVNA
 IVDGIEEELG KQDLRPVRRE GRSGGRWVLL DYSDVVIHVQ HEEDRVFYAL
 ERLWKDCPV. .......... ..........
>Q72BL7_DESVH
 MQTKEKKKAI IGWLEEKKAR DIVAYDLAGQ SPFAEALVIV TAGSVRHGQS
 LADHMLAMCN ENNYEYLRME GYQTGQWILV DLNDIIVNVF QPETRGLFKL
 ESLWAKAPV. .......... ..........
>Q4JWT0_CORJK
 .DSIALAGVA ARAAAEKLGE DILVLDVSDR LAITDVFVIV SGDNERMVNS
 IVDEVEYEVG QDGPKPTRRE GRGEGHWVLL DYGNVVVHVQ RKEEREFYAL
 DRLWRDAPQ. .......... ..........
>CG030_HUMAN
 ......IDMM VSLLRQENAR DICVIQVPPE MRYTDYFVIV SGTSTRHLHA
 MAFYVVKMYK HLKCKHVKIE GKDTDDWLCV DFGSMVIHLM LPETREIYEL
 EKLW...... .......... ..........
>Q6AFX5_LEIXX
 ....DILLIA AAAADARSGT DIVALDVSGP LPLTDVFLLV SGRVERTVIA
 IASEVEDRLN EAGIRTLRRE GTSEGRWVLL DFGDLVVHVF HEEDRMYYSL
 ERLWKDCP.. .ALPLPVPER A.........
>Q5PA07_ANAMM
 ....ELKDSV VAVLDEHSAS DIVVLDVAGR CQLTEHMIIA SGNSSTHVKS
 LVEHIKKKVS KSGKVL..VE GLRDGNWVVI SMEGVIVHIF RPEVRSYYRL
 EELWSH.... .......... ..........
>Q2RZI5_SALRD
 .....LAARV ADAMADKRAM NISVIDLREV SSMADFFVLG TGESDLQVKA
 IANGIADHVQ ECGEEPWKRE GTDHLQWVVL DYVDVVAHVF LPDKREHYRI
 DRLWGEA... .......... ..........
>Q5CB94_9THEM
 ..MIDVLRKI LKKISEKGGE NPVVLDMRKT PVPTDYFVIF TANSYTHMRA
 MRDELIDLIK ELSLPLIYYD KGEEYEWLII DAGSVVIHIF TEKGRDFYDL
 EGLWIDA... .......... ..........
>Q72PV0_LEPIC
 .STEDILRII RDIMTDKKCE EVSILNLESV NSYLSYFVIC TVNSAVQANA
 VAREVRKTLK E..YKLSHKE TDKTGGWTLL DFGEIIVHIM TPEKREYYNL
 DRLWRDAK.. .......... ..........
>Q4RHZ6_TETNG
 ......LDVL VSLLRQENAV DICVIKIPEN IQYADYFVVV SGISTRHLRA
 MATKVYKYLK KEKEPSVKIE GKDTEDWMCI DFGNMVVHFM LPETREVYEL
 EKLW...... .......... ..........
>Q2E2D4_ACICE
 ....ELAVAA AEAAAEKLAR DIVAFDVSDR LPITDAFVLA SASNDRQVRA
 VVDAIEERLQ KHRAKPLHRE GEAECRWVLL DYLDVVVHVQ HVEDRLYYGL
 ERLWKDCPT. .......... ..........
>Q7NMH9_GLOVI
 .......... .......... .......... TILADYFVIA TGNSRAQVRA
 IGNAVEEKIK EFARKPVRIE GLGEGSWVLA DYGDVIVHVL LRSEREFYQL
 EAFWGHA.PR VDVALP.... ..........
>Q3X0Q3_9ACTN
 ..TREMAETA AGAANAMFGR ETTLIDLRGL VSYADYFVVT SAETDRQTRR
 IAEEVIDRMA EKGYRPRSRR VDGESPWISL DYLDVVVHIF TDEARDYYRL
 ESLWRSAPQE R......... ..........
>Q6MGS6_BDEBA
 .......EFC ANVLFAKKGI NVRGFDLTQM SAPSEYTLIA SGTSTRHAAA
 MAENIVMAVK EENVHPQSIE GVDEGRWVLV DYGSLIIHVF YDFVRQEYNL
 ENLWREGK.. .......... ..........
>Q72HR8_THET2
 .....LIERI KELLAEKKAE NVVALDLRRV SETLDYFVVA SATSTPHLQA
 LERHLLEKLE EEDLRPRPTA GQS.PRWVVL DYGEVVVHLM TPEAREYYDL
 EGFWADAE.. .......... ..........
>Q73LW7_TREDE
 .......... .KLLRDFKGE NVVVLDLRDK NIWTDFFVVC TVTSAAHSAG
 LEKRVYEFLP EHNLEEYHTK RKDGDEWRLI DLGGIVVHLM SETARNFYSL
 EKIWFDSK.. .......... ..........
>Q4HEM6_CAMCO
 ..MQERVDLI VKILDEKKAE DIKTFDMSEQ DYFVKYVIIA ATLGEKHALS
 LIDELKTKLK AKGEEFLNIE ..SSEEWSVI DLGDILIHLL TPEHRGIYNI
 EEL....... .......... ..........
>Q7MS87_WOLSU
 ...KERAQEI VEILDSKKAE NIELFDLSGS DYLVDYVVIA TALADKHAAS
 LLDTLKTELK PKGETFYATE ..ESDNWIVT DLGDIMIHLF TENHRKKFNL
 EEFLAGLK.. .......... ..........
>Q7VC47_PROMA
 MDSQKVIELA AKAADDLKAI DIQIIQIDKV SSIADWILIT EGLSDVQVRS
 IINSIEDRLK KANIIPLRKE GVNEGKWALL DYGDIIINVF QPNERKFYEL
 ESFWS..... .......... ..........
>O83720_TREPA
 MSANGAASAV AEALCDARAE DVCVFDVSAR CGWADFAVVA TVPGLLH..G
 THRLVCEQAA RFGLREVHRK GLCEEQWRVL DFGSILVHLM SAQARAFYDL
 DRLWQDCLVA R......... ..........
>Q2GCL3_NEOSM
 MESQ.IVSLI LESLSVHKGR DIKIYGGRGI TGC...MVVA SSDSHKHVKT
 LADFVVKLSK EKGISV.KTE GYDLGNWVLI DMGEVIVHIF KDDVRKYYEV
 DALW...... .......... ..........
>Q3Z4F5_SHISS
 .......... .......... .......... ......MIIC SGTSSRHVMS
 IADLIVQESS AAGLLPLGVE GENSADWIVV DLGDVIVHVM QEESRRLYEL
 EKLWS..... .......... ..........
>Q65ZZ0_BORGA
 ......INTL CKIITDFNGI DVIGINVSNI CNWTDFFIIA TFVSFKQMEA
 LYDKIVKFFK ERKIN.LNVQ GKGVYDWTVV SGGNLVIHLM SEKSREYYEL
 EKIWS..... .......... ..........
>Q30PQ1_THIDN
 ..MQNRIEKI TDVLDKNKAE NIEVFDLREK NYFVDYAIIA SSLGSRHTSA
 LLDHLKNELK PA.EKFNAVD ..ESSDWIVV DLGDVLIHIM TPEYRVKYDM
 ESF....... .......... ..........
>Q4D0N4_TRYCR
 ...EDVIEL. LEVLRSLKVR DICAIDVSAK TSNFDYMLLG TCEGPRHIHL
 AAWAVQEADS LKRISKIKRK QTDHT.WEVV PVGRIIVNLM QEPLREEMAL
 ERKWAVTKPL TAANAP.... ..........
>Q3Y0R2_ENTFC
 .......... .......... .......... .......MIC SANSERQINA
 ITEEIIDKEE ENKYEVKRIE GKEGGKWVLI DLGDVIVHVF HAPERNFYNL
 EKLWSDAP.. .......... ..........
>Q6NFW2_CORDI
 .DTIRLAEIA AKAAAEKLAT NIAVIDVSDV MAISEVFVLA SADNERQVRS
 IVEEIEDMLT AEGEEPKRRE GNRENRWVLL DYGMLVIHVQ RNTERDFYGL
 DRLYQDCP.. .......... ..........
>Q9U3Y9_DROME
 .DVEDLVEL. ...LRKENVD DIFVCYVPEN LKYVDHLVVC SGRSYRHMLS
 TAEFVRRMFK IKRGKLPRIE GDKSRDWMAM DLGNIALHIF SPSAREEYDL
 ESLWA..... .......... ..........
>IOJAP_MAIZE
 .DDAECLSFA VKAASEIKAT DIRVLCVRRL VYWTRFFIIL TAFSNAQIDA
 ISSKMRDIGE KQFSKVASGD TKPNS.WTLL DFGDVVVHIF LPQQRAFYNL
 EEFYGNATP. .......... ..........
>Q9NE59_LEIMA
 ..MEDVKE.I ANILSSLKVR DLCCVDVSEK TSNFDYMMFG TCEGARHIHL
 AAWAVQDADK VHRISKIKRQ QTDEL.WEVV PVGRIVVNLM VESFREEMTL
 ERKWASMDPL AAANAP.... ..........
>Q8LAC1_ARATH
 .DAESLAFAV AKVASDVKAG DIKVLFVKPL VYWTRFFIIA TAFSRPQIDA
 IGSRMRDLAE KKYGKVANGD VKPNS.WTLL DFGDVVIHLF LPPQRTFYNL
 EDFYGNAMQ. .......... ..........
>Q7VJ93_HELHP
 MQGKERIERI TTLLADKKGE DIEVFDLCDK DYIVDKVIIV SAMIGKHSFA
 LLDYLKSELK PQGEVFYATE EESE.DWVVA DLGDIMIHIF TPNHRKKFNL
 EEF....... .......... ..........
>O51725_BORBU
 LKVNDINDLC .KIISDFNGI DVIGINVSDI CNWTDFFIIA TFVSFKQMEA
 LYIDKIIKFF KEKKINLNAE GKGVYDWTVV SGANLVIHLM SEKSREYYEL
 EKIWS..... .......... ..........
>Q4HLQ9_CAMLA
 ..MQERINNI VQILDDKKAD LIETFDMQDK DYFVKFVVIA TTMGERHALS
 LIDDLKTNLK SKGEEFLNIE ..SSEEWTVL DLGDILIHLM SETYRAKYNI
 EEF....... .......... ..........
>Q8LGB8_ARATH
 .........V EKILADVKAD NVTVIPTHNH CFWADFTVIA TGRSDWHLRN
 IAQALVYRAK QKQKGAKHVQ GYN.SKWIVI DYGKFVVHAL DEKARGYFNL
 ESLWS..... .......... ..........
>Q4HR33_CAMUP
 ..MQERITAI TQILDEKKAE DIEIFDMRGG EYFVSFVIIA TTLGEKHALS
 LIDELKTKLK IRGEEFLNVE ..SSEQWSVI DLGDILIHLL SQEHRGIYKL
 EELLKDLK.. .......... ..........
>Q7Q7Y3_ANOGA
 .......... VTVLRLNSAI NIFVCTVPKD IKYVDYMCIV TGRSVRHMRG
 MAEFVRKKMK RHPSDIIKIE GESSSDWMAL DLGNIALHIF STKAREQYDL
 ESLWS..... .......... ..........
>Q9ZJJ8_HELPJ
 ..MNQRIEMI TALLDEKKAF DITHIDLSKT PYLVEDVIIA TTLANKHALS
 LLDALKNTLK PLGEVFYQID .ESNGEWIIL DLGDLMIHLF TEECRKKFDL
 EGF....... .......... ..........
>Q445Y4_SOLUS
 .......... .......... .......... .......MIC TGANQRQIQA
 IAEEVGLQLK HKARELANVE GYTQGEWVLA DYGDLVIHIF TPKSRDYYDL
 ERLWRGAK.. .......... ..........
>Q54B26_DICDI
 .......... .......... DFCVIDISKK CTWAEYLVIA SSDSTRLLSN
 TEKDIMQAFK .HRFEQLHPA TNNSDQWRVV DLNPIVIHLF ETQTREYYDL
 ENLW...... .......... ..........
>YM62_CAEEL
 ......VENV VGALTDQRAK DVFVVK.SEE TEMTPYTIIC SAFNSRQASA
 ISENLRSLLK IDGVSHARRS TKRSNGWYVS EVERVQVHVM SEECREKYDL
 EAIWAG.... .......... ..........
>Q2QV70_ORYSA
 .....LLELV EKVLRDVRAG DVRVFPVGEG GSCADYMVVA TGRSDWHVRN
 IAQALLYKAR .......... .......... .......... ..........
 .......... .......... ..........
>Q60MW0_CAEBR
 .DDVDFVETI VGALGEQKAR DVFVVDDKEM TPYSHRVIVC SVFNSRQAAA
 ISENLREILK MENEQSYGSS TKRSKGWYVS EIEGVQIHVM SEDCREKYDL
 EAVWSG.... .......... ..........
>Q3QCG9_9GAMM
 .......... .......... .......... .......... ..........
 .......... ..NITILGSE GRDTSEWVLV DLGEVILHVM QEQTRDFYQL
 EKLWQE.... .......... ..........
>Q6CLH6_KLULA
 ......LETI SKYLNDKLAT DIVVFDTAHS SSMASYVLIG TVKSFRHLQN
 CNDELIKFIK ETFDEVPKSE GLDESGWIDS NVDGLFINIM TEERRDDLNL
 EELY...... .......... ..........
>YMY8_YEAST
 ......LRKI ADLLTGKLGD DFLVFDLRKK SPLGDFMVIC TARSTKHCHK
 SFLELNKFLK HEFCSSAYVE G......... .......... ..........
 .......... .......... ..........
>Q6BXN8_DEBHA
 .......... .........E DIELFDLTQL NQPTDYMIIC TGKSEKHIYK
 ASNELRTYIK HNYNLIPKIE GM........ .......... ..........
 .......... .......... ..........
>Q6FPT1_CANGA
 .......... .........R DILVFDLKNR LKMCDYVIIC TAMSTKHCER
 SYVEINKLLK NEYGVSGYVE GQ........ .......... ..........
 .......... .......... ..........
