>prot (#) default: single protein sequence description=t0354 /home/ppuser/server/work/predict_h7052
MEIQEISKLA IEALEDIKGK DIIELDTSKL TSLFQRMIVA TGDSNRQVKA
LANSVQVKLK EAGVDIVGSE GHESGEWVLV DAGDVVVHVM LPAVRDYYDI
EALWGGQKPS FAVGAAKPWS AVLEHHHHHH
