>query
 MTQETALGAA LKSAVQTMSK KKQTEMIADH IYGKYDVFKR FKPLALGIDQ
 DLIAALPQYD AALIARVLAN HCRRPRYLKA LARGGKRFDL NNRFKGEVTP
 EEQAIAQNHP FVQQALQQQS AQAAAETLSV EAEAAESSAA
>Q5F755_NEIG1
 MTQETALGAA LKSAVQTMSK KKQTEMIADH IYGKYDVFKR FKPLALGIDQ
 DLIAALPQYD SALIARVLAN HCRRPRYLKA LARGGKRFDL NNRFKGEVTP
 EEQAIAQNHP FV........ .......... ..........
>Q5E5C2_VIBF1
 .......... MENSEKLANS KEVIAYIAER FPKCFILEGE AKPLKIGIFQ
 DLAERLPKVS KTQLRAGLRQ YTSSWRYLHG VKPGASRVDL DGNPCGELEE
 EHIEHAK... .......... .......... ..........
>Q3EIL5_ACTSC
 LLNEQATEAQ NQPEVQKLSS NKEIAYLAEK FPLCFSVEGE AKPLKIGLFQ
 DLAEALQDVS KTQLRHALRQ YTSNWRYLHG CRLGAERVDL QGNPSGVLEQ
 EHVEHA.... .......... .......... ..........
>PROQ_SALTI
 .......... MENQPKLNSS KEVIAFLAER FPHCFSAEGE ARPLKIGIFQ
 DLVERVGGLS KTQLRSALRL YTSSWRYLYG VKPGATRVDL DGNPCGELEE
 QHVEHA.... .......... .......... ..........
>Q3CMN0_ALTAT
 ..NYTQLEYL MDNPQKFSNS KEVINFLSES FPACFSVTGD AKPLKIGIFQ
 DLAQRLEEVS KTLLRSSLRH YTNSWRYLHS VKEGAFRVDL DGQQAAPIEK
 EHADHAQ... .......... .......... ..........
>Q3QEN9_9GAMM
 .......... MESTEKLTDT NAILAYLYET FPLCFVAEGE TKPLKIGLFQ
 DLAERLSKVS KTQLRVALRR YTSSWRYLKC IKAGAVRVDL DGNPCGELEQ
 EHIDHAQ... .......... .......... ..........
>Q5QX59_IDILO
 .......... MSEPEKLTKS KDVIAYLAEQ FPDCFTIKGD AKPLKIGIFE
 DLAKRLEKVS KTRLRTALRH YTNSWRYLYS VKTGAQRVNL DGEQVEAVTE
 EHQQHAQ... .......... .......... ..........
>Q4QJS5_HAEI8
 .TQLSSQVTD VQTEVQKTNA KAIITYLAEK FPLCFVLEGE AKPLKIGLFQ
 DLAEALQDVS KTQLRQALRQ YTSNWRYLYG CREGAVRVDL QGNPAGVLDA
 EHVAHA.... .......... .......... ..........
>Q480J6_COLP3
 .......... METEIKRTST KDIIAYLTEK FPECFSIKGP VKPLKIGIFQ
 DLAEKLDDVS KTRLRQALRH YTSSWRYLKV IKVGNSRVDV DGKDVAEIDE
 DQAAYA.... .......... .......... ..........
>Q7NYF7_CHRVO
 .......... .......... .....MIADH IYGKFDVFRQ FRPLALGIHE
 SLIAALSQFD PALISRVVAN HCRKPRYLKS LARGGKRFDL NGKPQGEVSA
 EEKRAAE... .......... .......... ..........
>PROQ_HAEDU
 .......... .......... KEVIAYLADK FPLCFSIEGE AKPLKVGLSQ
 DLAEALEKVS KTLLRQVLRS YTMSWRYLAC CKANAQRIGL QGENVGIVDE
 AQAEHA.... .......... .......... ..........
>Q47JP0_DECAR
 .......... .......... .......... ...QFDVFRN FSPLAIGIDK
 QVFAQLPEVS KKALRLAMRS HTISTRYLKE MEKGTVRLNL DGTPAGEVTD
 ENRQHA.... .......... .......... ..........
>Q5P4U5_AZOSE
 .......... .......... .......... .......FRD VRPLALRIDK
 AIAARFPELD RKVIRSAMRL HTASTRYLKV MEKATARFDL DGKPEGEVTE
 EQRAHAK... .......... .......... ..........
>Q3IH05_PSEHT
 .......... ....METTNK NEVLEFLYQE FPQCFKQKDG IKPLKVGIFK
 DIAERIEKVS KTQVRQALRK YTSNWRYLEA VTKSEFRIDL DGNQAEKVEQ
 EHIDHAQ... .......... .......... ..........
>Q4LBT9_SODGL
 .......... ...AKKLRRG QEAIAGLVAH WPQLFSLEQP .NPLKIGIYK
 DIKARKLELT RAKAGASLMF YTQTPVYLET VCVGGSRFDL SGQPCGAITE
 KQKAYAQ... .......... .......... ..........
>Q2A0A1_9VIRU
 .......... .......... .......... .....SPTKP AKPLKIGIYQ
 DIKGRELGLT RAKASAALMF YTQTRAYQEA VQVGDSRFDI NGQPCGEITE
 EQKAHA.... .......... .......... ..........
>Q2BMU8_9GAMM
 .......... ...APKAKSK NRAANMAAEA YPKTFD.RKN VRPLKIGIQE
 DLIA.DEKVA KNKIKRALAS YVRSLNYYRS LREGAERIDI NGEAAGQVTK
 EESDHAKD.. .......... .......... ..........
>Q4B2Z6_9BURK
 .......... .......... ....EKLFEL YPKMFGA..Q FLPLKLGVFQ
 ELLAQHPDFN RDELKVALGL HARSTRYLES VAAGLPRHDL QGEPVEPVAP
 EHVHHA.... .......... .......... ..........
>Q8KGY3_RHILO
 .......... .......... .....YLSAK WPAAFNPKAP .RPLKIGIHR
 DIRVLDGELS DDELRRALLA YTKMARYLAR LDAGAARIDL NGKPAGMVSD
 ADAATAK... .......... .......... ..........
>Q44CW3_CHRSL
 .......... .......... .......... .......... .QPLKTGIHL
 DLVAREP.WP EKLVRRALAC YVHLPRYLKA VRAGVMRVDL DGQAVEAVTE
 GEARHA.... .......... .......... ..........
>Q471S4_RALEJ
 .......... .......... ...IGKLQKR FPLAFPKNPA PKPLKVGIFE
 DLLASTLGLD EAMLREAVRT WCRGTRYWTC MVEGVERVDL AGQPAGQVTL
 ADAKRAQQQ. .......... .......... ..........
>Q3XCA0_METFL
 .......... .......... .......... .......... ..PLKIGIHK
 ELLAKASELE EAAITEAVKT WCRGTRYWAS IVEGAPRIDL EGNPAGEVTA
 RDAAQA.... .......... .......... ..........
>Q5WW03_LEGPL
 .......... .........K LQVIDWLIEN FPNAFFKKGN VKPLKIGIFD
 DLIERLPPFS KKSLREALSY YSASPAYLSC QKPDTARVDI YGNEVDVVTP
 EQAKYA.... .......... .......... ..........
>Q8GPS6_PSEAE
 .......... .KPSLQTKPS EQDPAMLQKH FPLAFPVNPA PKPLKEGIFK
 D.AEQHLELS SEQLKQGIAA WCRGSRYWAS MTENAPRLDL SGQAVGMVTA
 AQALHAK... .......... .......... ..........
>Q4BAX4_BURVI
 .......... .......... ...IGKLQRR FPRAFPKNPA PKPLKVGIWD
 DLAAQSVGLS EAELREAMST WCRGNRYWSC LVEDAVRVDL QGNEAGRVTH
 DDAARA.... .......... .......... ..........
>Q3JMK3_BURP1
 .......... .......... ...IAKLQKR FPQAFPRNPA PKPLKVGILE
 DLVASALGLS EAELRDAMRT WCQGNRYWTC LVEGAVRIDL AGGEAGRVS.
 .......... .......... .......... ..........
>Q9I0Q4_PSEAE
 ....QAKPAQ TKSSAGRAKK REAVERLQRH FPLAFPKSPA AKPLKQGILQ
 D.AQQHLELT AEQLKQAIAT WCQGSRYWSC MVEDAPRLDL QGQVAGKVTA
 EQAVY..... .......... .......... ..........
>Q5ZZ78_LEGPH
 ........TA VINKAQKNQS KRARSDLAAN FPEAFDNSLR IRPLKIGIMS
 DIAEKAEQVS KSKLREAVVL FTRRLDYLAC LKAREVRIDL HGNPVAEVTE
 EEAEHA.... .......... .......... ..........
>Q2A1R1_FRATU
 ..QEILVTVD IEKERQKEEA R.LLKWLCHR FPKCFDPI.N KKPLKIGISE
 EIEIIYQNVD KMVLRNVLRR YVGDTRYHKA VFELKQRFNL QGQPVEDYAP
 EHVEYSK... .......... .......... ..........
>Q68JD7_ECOLI
 .......... .......... .ECVEKIKAL FPHLRAEGGG FIPLKIGINN
 DISAFLAEHP ETELTMAVSC ITSRRVYLQR TAAGVPRYGL DGHPKGQVSD
 SEAQSA.... .......... .......... ..........
>Q9JN19_9RHIZ
 .......... .......... .......... .......... ..PFRIGIDT
 DIEKRLAGLS D..LRKALRR YTHSAAYLYA TAPEALRHDI VGKPCEPVSE
 DDRLNA.... .......... .......... ..........
>Q326X0_SHIDS
 .......... .......... .......... .PGLFDGDTP .RLLACGILE
 DVAQRDIPLS HKKLRRALKA ITRSESYLCA MKAGACRYDT EGYVTEHISQ
 EEEAYA.... .......... .......... ..........
>Q9F577_ECOLI
 .......... .......... .......... FPELWTDEKK NLPLKSGILQ
 DVLADNPDVD LTEWNCAVQV MTFRWQYLQC TVPGATRYDL YGKPAGTVKK
 AHATYAQ... .......... .......... ..........
>Q2DG08_ACICY
 .......... .......... .......... .......... ....AAGLAA
 RLIEAGVDAD ELLVRAALAH HVRRPGYLER MAAPDSRHDL DGNPVEPVSA
 RHRDHA.... .......... .......... ..........
>Q4BMM9_BURVI
 .......... MAGATKTSLI KSTRRALKER YPAVFG..GK WRPLCVGVVD
 MLVADMGDAP RRDLHRAIAA RAGKLEYLTA VAGGGPRYDL QGNERGHVTA
 HEQEYAK... .......... .......... ..........
>Q7WTH9_ECOLI
 .......... .......... .......... .......... FLPLKIGITN
 DFAAFLTEHP ETELTLAISC ITTRQVYLQR TAAGIPRYGL DGLPAGQVSE
 .......... .......... .......... ..........
>Q9EUJ8_SALET
 .......... .......... .......... .......... .......LFE
 DASRRGIPLS HKKIIRALKA IARSEAYLSA MKAGACRYDT EGYVTEHITV
 EEEQYA.... .......... .......... ..........
>Q84KP7_CYAME
 .......... ....MKKNIV KKCLEMFSDT FYEQFS.... .KNIKLGIHE
 DTA......N RSKLAELLRF YTKSPDEYTS LKEYVSRMKE GQKAIYYITG
 ESKKAVENSP FL........ .......... ..........
>Q9GYX4_PARTE
 .......... ....IKKNIT KKCIEMITEK FYEQFS.... .KNLKLGIHE
 DSA......N RTKLSEFLRF HTSKSDYIGK MKEGQKDIFF .......ITG
 ESKASVAASP FV........ .......... ..........
>Q4LC21_SODGL
 .......... ...AKKLRQG QEAIASLVAN WPSLFDL.GY PKLLKVGILD
 DIKARELDLT RAKASATLMF YTQRVFYQQA .......... ..........
 .......... .......... .......... ..........
>Q65AF9_YERPE
 .......... .......... .......... .......... ..........
 DIRRRGLEIS VKTLKRCLAA VTRSDAYLGA MTVGAWRKNL AGEP......
 .......... .......... .......... ..........
>Q967E1_DENKL
 .......... VKKCMELFNE VAEDKDNYKT FYEQFS.... .KNLKLGIHE
 D......STN RAKLAELLRY HTSSSDDMTS LKEYVSRMKE GQKDIYYITG
 ESKDQVSNSA FV........ .......... ..........
>Q4PPC0_9STIC
 ISRETLQQNK ILKVIKKNIV KKCLEMFAEK FYEQFS.... .KNLKLGIHE
 D......ATN RTKLCDLLRF HTSKSDYLAR MKEGQKDIYY .......ITG
 ESRAAVQNSP FL........ .......... ..........
>Q2RVS9_RHORT
 .......... .......... .......... .......... ..........
 DLVARDPDPD EAAIRRGLGN ICRCTGYVKA VREGASRLRE AGRAAAQ...
 .......... .......... .......... ..........
>Q2TTU4_ECOLI
 .......EQQ KKTGRKKKKK KKNNRWNHEF IRHSLDCVKK TFPFKIGISK
 DVMAFISGLT VKEWNCAVRM ITGGYKYLQR IVAGTPRYGL DGKVHGTVTE
 EEALYAQ... .......... .......... ..........
>Q86LK1_9EUKA
 .......... VKKCIELFND ISENKDDYKK FYEAFG.... .KNIKLGIHE
 D......GEN RQELAELLRY YTKSPDEMVS LKEYASRMKE NQKSIYYITG
 ESKESVQTSP FL........ .......... ..........
>Q26582_SCHMA
 .......... .......... .ELFEEIAEK FYEQFS.... .KSIKLGIHE
 D......SVN RAKLSELLRF YSSSGDEMIS LKDYVSRMKP EQQDIYYITG
 ESKQAVMNSP F......... .......... ..........
>Q5DK83_9STRA
 .......... VKKSLELFNE LAEDNDKYKK FYEAF..... CKNLKLGIHE
 D......STN RAKIAKLLRY HTKSGEEMTS LDDYISRMT. ENQPIYYVTG
 ESKRAIENSP FL........ .......... ..........
>Q7XR98_ORYSA
 .......... .......... KKCIEMIADK FYEAFS.... .KNLKLGIHE
 D......SQN RGKLADLLRY HTKSGNELTS LKDYVTRMKE GQKEVYYITG
 ESRKAVENSP FL........ .......... ..........
>Q4UDU8_THEAN
 .......... .....ELTEK KEDFK....K FYEQFS.... .KNLKLGIHE
 D......NAN RSKIAELLRF ETKSGDELVS LKEYVDRMKS DQKFVYYITG
 ESKQSVASSP FL........ .......... ..........
>Q2N193_PLADU
 LQQSKILKVI RKNIVKKCI. .ELFEEIAEK FYEQFS.... .KNLKLGIHE
 D......SVN RKKISDLLRF YTSSGEEPVS LKDYISRMKE NQKSIYYITG
 ENRDAVENSA FV........ .......... ..........
>Q2MM10_9EUKA
 .......... VKKCLDLFSE IAENKDDSKK FYDAFS.... .KNLKLGIHE
 DSA......N RAKLAEFLRF YTSLNDYVTR MKEGQDQIYY .......ITG
 ESRAAVESSP FL........ .......... ..........
>Q6XE36_9EUKA
 .......... VKKCLELFNE ISEDADQYKT FYEQF..... AKNLKLGIHE
 D......STN RNKIAELLRY HTSSGEEYTS LKDYVTRMPE NQQHIYFITG
 ETKDQVKNSP FV........ .......... ..........
>Q3FYV8_9DELT
 .......... .......... RQETALMHSL LSRLADNLQS VKPLKAMGRE
 QLAERMLEAD TVKLNRALRK QVSSKATLKS LQE....... ..........
 .......... .......... .......... ..........
