>prot (#) default: single protein sequence description=t0360 /home/ppuser/server/work/predict_h29402
MTQETALGAA LKSAVQTMSK KKQTEMIADH IYGKYDVFKR FKPLALGIDQ
DLIAALPQYD AALIARVLAN HCRRPRYLKA LARGGKRFDL NNRFKGEVTP
EEQAIAQNHP FVQQALQQQS AQAAAETLSV EAEAAESSAA E
