>query  (#) default: single protein sequence resfilename=o15r4ypx description=eef1g_hs /nfs/data5/users/ppuser/server/work/predict_h25747
MAAGTLYTYP ENWRAFKALI AAQYSGAQVR VLSAPPHFHF GQTNRTPEFL
RKFPAGKVPA FEGDDGFCVF ESNAIAYYVS NEELRGSTPE AAAQVVQWVS
FADSDIVPPA STWVFPTLGI MHHNKQATEN AKEEVRRILG LLDAYLKTRT
FLVGERVTLA DITVVCTLLW LYKQVLEPSF RQAFPNTNRW FLTCINQPQF
RAVLGEVKLC EKMAQFDAKK FAETQPKKDT PRKEKGSREE KQKPQAERKE
EKKAAAPAPE EEMDECEQAL AAEPKAKDPF AHLPKSTFVL DEFKRKYSNE
DTLSVALPYF WEHFDKDGWS LWYSEYRFPE ELTQTFMSCN LITGMFQRLD
KLRKNAFASV ILFGTNNSSS ISGVWVFRGQ ELAFPLSPDW QVDYESYTWR
KLDPGSEETQ TLVREYFSWE GAFQHVGKAF NQGKIFK
