>prot (#) default: single protein sequence description=t0364 /home/ppuser/server/work/predict_h22472
MPALITYRTT VQEDWVDYNG HLRDAFYLLI FSYATDALMD RIGLDADSRG
QSGNSLFTLE AHINYLHEVK LGTEVWVQTQ ILGFDRKRLH VYHSLHRAGF
DEVLAASEQM LLHVDLAGPQ SAPFGHTTVC RLNHLVEQQE GAQAPQYMGR
TIKLPA
