>query  (#) default: single protein sequence resfilename=zadcgwyo /nfs/data5/users/ppuser/server/work/predict_h19860
QQSKVAPSSA ASRPVLSSRS DQSQKNEVFL DVVERLSVLI ASNGSLLKVD
VQGEIRLKSF LPSGSEMRIG LTEEFSVGKS ELRGYGPGIR VDEVSFHSSV
NLDEFESHRI LRLQPPQGEL TVMRYQLSDD LPSPLPFRLF PSVQWDRGSG
RLQVYLKLRC DLLSKSQALN VRLHLPLPGG VVSLSQELSS PEQKAELAEG
ALRWDLPRVQ GGSQLSGLFQ MDVPGPPGPP SHGLSTSASP MGLGPASLSF
ELPRHTCSGL QVRFLRLAFR PSGNANPHKW VRHLSHSDAY VIRI
