>pdb|pdb|1h8a_A TRANSCRIPTION/DNA
VDKHSDEYKI RRERNNIAVR KSRDKAKMRN LETQHKVLEL TAENERLQKK 
VEQLSRELST LRNLFKQL 
>pdb|pdb|1h8a_B TRANSCRIPTION/DNA
DKHSDEYKIR RERNNIAVRK SRDKAKMRNL ETQHKVLELT AENERLQKKV 
EQLSRELSTL RNLFKQL 
>pdb|pdb|1h8a_C TRANSCRIPTION/DNA
NPELNKGPWT KEEDQRVIEH VQKYGPKRWS DIAKHLKGRI GKQCRERWHN 
HLNPEVKKTS WTEEEDRIIY QAHKRLGNRW AEIAKLLPGR TDNAVKNHWN 
STMRR 
