>query  (#) default: single protein sequence resfilename=k5l1xw0h description=eef1b_hs /nfs/data5/users/ppuser/server/work/predict_h25745
MGFGDLKSPA GLQVLNDYLA DKSYIEGYVP SQADVAVFEA VSSPPPADLC
HALRWYNHIK SYEKEKASLP GVKKALGKYG PADVEDTTGS GATDSKDDDD
IDLFGSDDEE ESEEAKRLRE ERLAQYESKK AKKPALVAKS SILLDVKPWD
DETDMAKLEE CVRSIQADGL VWGSSKLVPV GYGIKKLQIQ CVVEDDKVGT
DMLEEQITAF EDYVQSMDVA AFNKI
