>query  (#) AambivalensDoxB /nfs/data5/users/ppuser/server/work/predict_h20442
MSLKDLVISL FQLDKDWTTR IVMAMLVMGV IWGLLGVIDS LMVRIQESTW
GTYGVLAMTS QEYYAGITLH AERDLFGFAE QVEFALFIYF TIKLLNLQPR
AKWLLNTAFI AINISMMFME GPIVVFPTFN DNYFSATDWY YISPMGIPPY
SEYVVSPLFF IGWLLLDAFT YMASVWIIYH CYIASKSLKE KLPVALVFFL
MNTLLYAIGY SGVTAADIWD ILAYAGIVGL NPIANQIAFW IFGHAVVYMA
WLPAVAALYL LIPTLANKPL YSDRMARISA LLYLIFSNNV PVHHLYMVNL
PVAIKVLQEI LTYAVVVPSM MTFLNLWATA KGAQVNFNVI TAFVATSFAG
AIAAGVTGIA NATIAFDSIV HNSMWVVGHF HAMILLSIVP AAMAVLYFMI
PMMTGRQWYS SKMAWIHYIG YTIGASILII GFEMIGFYGV VRRAEIYPRV
PGLVFAENLA TAGALIAEIA TLVWFVNLVA TLVKGRTARL EGLSLGQLIN
TVAMSLDWSS AGFKLNNFNK IGKTMNSKAL GAYWALGIIG ALIIVISTIP
LALGGDMYNA MPWAWIILLT LGIILISYPV LKGAKSL
