>prot (#) default: single protein sequence description=t0361 /home/ppuser/server/work/predict_h31002
MATLTEDDVL EQLDAQDNLF SFMKTAHSIL LQGIRQFLPS LFVDNDEEIV
EYAVKPLLAQ SGPLDDIDVA LRLIYALGKM DKWLYADITH FSQYWHYLNE
QDETPGFADD ITWDFISNVN SITRNATLYD ALKAMKFADF AVWSEARFSG
MVKTALTLAV TTTLKELTP
