>prot (#) default: single protein sequence description=t0374 /home/ppuser/server/work/predict_h9426
MQLSHRPAET GDLETVAGFP QDRDELFYCY PKAIWPFSVA QLAAAIAERR
GSTVAVHDGQ VLGFANFYQW QHGDFCALGN MMVAPAARGL GVARYLIGVM
ENLAREQYKA RLMKISCFNA NAAGLLLYTQ LGYQPRAIAE RHDPDGRRVA
LIQMDKPLEP
