>query
 MTSSEPAHGA TPKRSPSEGS ADNAALCDAL AVEHATIYGY GIVSALSPPG
 VNFLVADALK QHRHRRDDVI VMLSARGVTA PIAAAGYQLP MQVSSAADAA
 RLAVRMENDG ATAWRAVVEH AETADDRVFA STALTESAVM ATRWNRVLGA
 WPITAAFPGG DE        
>Q9Z5J4_MYCLE
 MTSIEPSAPA TPKRTPVSQD SDNAGLSEAL VVEHSTIYGY GIVLALSPPN
 ANSLVVDALI QHRQRRDDII VMLTARRVSP PVAASGYQLP MLVGSAADAA
 RLAVRMENDG ATAWRAVAEH AETADDRTFA AMALAQSAVM AARWNKMLGA
 WPITTTFPGS NE        
>Q73VU9_MYCPA
 .......... ......SGKD ADNAALCDAL AIEHSTIYGY GIVSAMSPPS
 VNDMVVEALE QHRQRRDDVI AMLTARKVTA PVAAAGYQLP LVVGSPADAA
 RLAARMENDG AGAWRVVAEH AETGDDRAFA ATALVQSAVM AARWNRVLGA
 WPITTSFPGG ND        
>Q47RV6_THEFY
 MTGTLDPTPS ......GEAG AATAALRDAL LAEHAAVYGY SFAAAHTDAD
 LRSLCLSHLE KHRAWRDTLH SALVARDAVP PGGEDAYQLP EHTG.PEELR
 SFAAGLEETT AQAYLELAA. VPDAGLRDLA GRALGEATL. ..RMLALGGQ
 LSAFPGFPGG ..        
>Q5YSC1_NOCFA
 .......... .........D AERQALLDAL RAEYAAVYAY GVIAAYASPE
 RAGLIAEHTA AHRARRDATA DALRAAGADV PSPDAAYGVP FPVQDPVAAA
 RLAETVETDA TVAWRAVVEQ GDSEATRRLG VEALTEAALR LAAWQAILGT
 PS..PALPG. ..        
>Q82K48_STRAW
 ..SASTGTTG TPK.AESTES AELRALQAAL GAEHAAVYGY GVVGGKIGQA
 RRADARAAYD AHRARRDELA RSVRDLGGTP QAAAAGYALP FAVPDATAAV
 RLAAELEERV AGVYSDLV.R AGTGARRRSA AEALREAAVR AVRW......
 SGESVAFPG. ..        
>Q3GXA5_9ACTO
 .......... .......... AELDALQIAL AAEHAAVYVY GALSRSATPE
 LFASVVRAYD AHRARRDRLT ATILDEGAEP VAAEPAYELP .RLDTPAQVD
 RAALAVERAC AATYAYLVEH .TVGEQRRSA VGALNEAAV. ..RELVFRGT
 PEMFPG.... ..        
>Q6NGM8_CORDI
 .......... .......... .DRESLKKAL DWEYSAIYGL GVALAHSPAG
 TRTAVSDAIT AHRDRVELLE SAESFPNETI PRPEAAYEFP EP.HDAQSSR
 AFFDSLEADS AAWWLHALSE SHSATWRALC ASLAAQSA.. ..........
 .......... ..        
>Q5NZC8_AZOSE
 .........A AQADTRQGDP AADARILNAL AAEHEAIAAY GAGSGLLRAP
 MRDLALQFQG HHKAHVDLLA QTVTKLGGKP AESRQKYDFP VATLKAADVL
 RFASGLEQGA VSAYLGAVPL FANPDLAKAA ASILGDEAMH WAILRQALGE
 DPVPSAF... ..        
>Q7V8N5_PROMM
 .......... .......... .......... .......... ..........
 .......... .......DIH DALVARGVVP QYGVSGYRLD FAVQHPEEKG
 RFVMAIEADG A......... .......... .......... ..........
 .......... ..        
