>prot (#) default: single protein sequence description=t0385 /home/ppuser/server/work/predict_h1409
MTSSEPAHGA TPKRSPSEGS ADNAALCDAL AVEHATIYGY GIVSALSPPG
VNFLVADALK QHRHRRDDVI VMLSARGVTA PIAAAGYQLP MQVSSAADAA
RLAVRMENDG ATAWRAVVEH AETADDRVFA STALTESAVM ATRWNRVLGA
WPITAAFPGG DE
