>query  (#) default: single protein sequence resfilename=gatpzvh6 description=nox2-cterm /nfs/data5/users/ppuser/server/work/predict_h24809
RSQQKVVITK VVTHPFKTIE LQMKKKGFKM EVGQYIFVKC PKVSKLEWHP
FTLTSAPEED FFSIHIRIVG DWTEGLFNAC GCDKQEFQDA WKLPKIAVDG
PFGTASEDVF SYEVVMLVGA GIGVTPFASI LKSVWYKYCN NATNLKLKKI
YFYWLCRDTH AFEWFADLLQ LLESQMQERN NAGFLSYNIY LTGWDESQAN
HFAVHHDEEK DVITGLKQKT LYGRPNWDNE FKTIASQHPN TRIGVFLCGP
EALAETLSKQ SISNSESGPR GVHFIFNKEN F
