>query  (#) default: single protein sequence resfilename=lhxbrtda description=nox2 nterm /nfs/data5/users/ppuser/server/work/predict_h24398
MGNWAVNEGL SIFVILVWLG LNVFLFVWYY RVYDIPPKFF YTRKLLGSAL
ALARAPAACL NFNCMLILLP VCRNLLSFLR GSSACCSTRV RRQLDRNLTF
HKMVAWMIAL HSAIHTIAHL FNVEWCVNAR VNNSDPYSVA LSELGDRQNE
SYLNFARKRI KNPEGGLYLA VTLLAGITGV VITLCLILII TSSTKTIRRS
YFEVFWYTHH LFVIFFIGLA IHGAERIVRG QTAESLAVHN ITVCEQKISE
WGKIKECPIP QFAGNPPMTW KWIVGPMFLY LCERLVRFWR SQQ
