#!/usr/local/bin/perl
#
#########################################################
#  Quote2Html
#  ==========
#  Script to parse xml file that contains quotes and then
#     distribute this content all over pp
#  Run this whener you change Quotes.xml
#  Guy Yachdav yachdav@maple.bioc.columbia.edu  20040211
##########################################################
#
#

use XML::Twig;
use CGI qw(:standard);
use XML::XPath;
use strict;
use warnings;

my $xmlFile = shift @ARGV;
my @services  = ('PREDICTPROTEIN','PROSITE','SEG','PRODOM','MAXHOM','MVIEW','PHD','PHDSEC','PHDACC','PHDHTM','PROF','PROFSEC','PROFACC','GLOBE','CYSPRED','CONF');

# buffers for holding text
my $svc_namebuf;
my $svc_desbuf;
my $svc_quotebuf;
my $svc_infobuf;
my $svc_adminbuf;
my $svc_donebybuf;
my $svc_urlbuf;
my $svc_verbuf;
my $svc_copyrightbuf;

#print start_html;
print "<h2>Quotes for methods</h2>","\n";
print "<ol>";
print "\n";
foreach my $svc(@services){

    $svc_namebuf = '';
    $svc_desbuf = '';
    $svc_quotebuf = '';
    $svc_infobuf = '';
    $svc_adminbuf = '';
    $svc_donebybuf = '';
    $svc_urlbuf = '';
    $svc_verbuf = '';
    $svc_copyrightbuf = '';

# initialize parser with handlers for node processing
    my $twig_handlers = {
	"QUOTES/SERVICE/$svc/NAME"  => \&service_name,
	"QUOTES/SERVICE/$svc/DES" => \&service_desc, 
	"QUOTES/SERVICE/$svc/QUOTE" => \&service_quote,	 
	"QUOTES/SERVICE/$svc" => \&service_info,
	"QUOTES/SERVICE/$svc/ADMIN" => \&service_admin,
	"QUOTES/SERVICE/$svc/DONEBY" => \&service_doneby,
	"QUOTES/SERVICE/$svc/URL" => \&service_url,
	"QUOTES/SERVICE/$svc/VERSION" => \&service_version,
	"QUOTES/SERVICE/$svc/COPYRIGHT" => \&service_copyright,

    }; 
    my $twig = new XML::Twig( TwigHandlers=> $twig_handlers);    
    $twig->parsefile( $xmlFile ); 


    print "<li><a NAME=\"quote_pp\"><strong><font SIZE=\"+1\">",
    $svc_namebuf,		
    "</font>: </a>";		 
    print " <cite>$svc_quotebuf</cite></strong>";
    print "\n";
    print "<ul>";		
    print "\n";
    print "<li> Author:\t$svc_donebybuf" if ($svc_donebybuf ne '');
    print "\n";
    print "<li> Contact:\t$svc_adminbuf" if ($svc_adminbuf ne '');
    print "\n";
    print "<li> URL:\t\t$svc_urlbuf" if ($svc_urlbuf ne '');
    print "\n";
    print "<li> Copyright:\t$svc_copyrightbuf"if ($svc_copyrightbuf ne '');
    print "\n";
    print "<li> Version:\t$svc_verbuf"if ($svc_verbuf ne '');
    print "\n";
    print "<li> Description:\t$svc_desbuf" if ($svc_desbuf ne '');
    print "\n";
    print "</ul>";
    print "\n";
#    print "</pre>";
}
print "</ol>";
#print end_html;


# handle name element
sub service_info {
 my( $twig, $info ) = @_;
 foreach my $node ($info){
     $svc_infobuf .= $node->text( );
     $svc_infobuf .="<br>";
 }
}

# handle name element
sub service_name {
 my( $twig, $name ) = @_;
   $svc_namebuf = $name->text( );
}

# handle description element
sub service_desc {
 my( $twig, $des ) = @_;
  $svc_desbuf= $des->text(  ) . "\n";
}

sub service_quote {
    my( $twig, $quote ) = @_;
    $svc_quotebuf= $quote->text(  ) . "\n";
}

sub service_admin{
    my ( $twig, $leaf ) = @_;
    $svc_adminbuf= $leaf->text();
}

sub service_doneby{
    my ( $twig, $leaf ) = @_;
    $svc_donebybuf= $leaf->text();
}

sub service_url{
    my ( $twig, $leaf ) = @_;
    $svc_urlbuf = $leaf->text();
    
    $svc_urlbuf = "<a href=\"$svc_urlbuf\">$svc_urlbuf</a>" if ($svc_urlbuf ne "");
}

sub service_version{
    my ( $twig, $leaf ) = @_;
    $svc_verbuf= $leaf->text();
}
sub service_copyright{
    my ( $twig, $leaf ) = @_;
    $svc_copyrightbuf= $leaf->text();
}
