>prot (#) default: single protein sequence resfilename=d0lg43nk description=loctar test10 /nfs/data5/users/ppuser/server/scr/tst/85042
MSQQNTSGDC LFDGVNELMK TLQFAVHIPT FVLGLLLNLL AIHGFSTFLK
NRWPDYAATS IYMINLAVFD LLLVLSLPFK MVLSQVQSPF PSLCTLVECL
YFVSMYGSVF TICFISMDRF LAIRYPLLVS HLRSPRKIFG ICCTIWVLVW
TGSIPIYSFH GKVEKYMCFH NMSDDTWSAK VFFPLEVFGF LLPMGIMGFC
CSRSIHILLG RRDHTQDWVQ QKACIYSIAA SLAVFVVSFL PVHLGFFLQF
LVRNSFIVEC RAKQSISFFL QLSMCFSNVN CCLDVFCYYF VIKEFRMNIR
AHRPSRVQLV LQDTTISRG
