>query  (#) default: single protein sequence resfilename=pstcd0xz description=98 /nfs/data5/users/ppuser/server/work/predict_h9135
MFNKSFGTPF GGGTGGFGTT STFGQNTGFG TTSGGAFGTS AFGSSNNTGG
LFGNSQTKPG GLFGTSSFSQ PATSTSTGFG FGTSTGTANT LFGTASTGTS
LFSSQNNAFA QNKPTGFGNF GTSTSSGGLF GTTNTTSNPF GSTSGSLFGP
SSFTAAPTGT TIKFNPPTGT DTMVKAGVST NISTKHQCIT AMKEYESKSL
EELRLEDYQA NRKGPQNQVG AGTTTGLFGS SPATSSATGL FSSSTTNSGF
AYGQNKTAFG TSTTGFGTNP GGLFGQQNQQ TTSLFSKPFG QATTTQNTGF
SFGNTSTIGQ PSTNTMGLFG VTQASQPGGL FGTATNTSTG TAFGTGTGLF
GQTNTGFGAV GSTLFGNNKL TTFGSSTTSA PSFGTTSGGL FGFGTNTSGN
SIFGSKPAPG TLGTGLGAGF GTALGAGQAS LFGNNQPKIG GPLGTGAFGA
PGFNTTTATL GFGAPQAPVA LTDPNASAAQ QAVLQQHINS LTYSPFGDSP
LFRNPMSDPK KKEERLKPTN PAAQKALTTP THYKLTPRPA TRVRPKALQT
TGTAKSHLFD GLDDDEPSLA NGAFMPKKSI KKLVLKNLNN SNLFSPVNRD
SENLASPSEY PENGERFSFL SKPVDENHQQ DGDEDSLVSH FYTNPIAKPI
PQTPESAGNK HSNSNSVDDT IVALNMRAAL RNGLEGSSEE TSFHDESLQD
DREEIENNSY HMHPAGIILT KVGYYTIPSM DDLAKITNEK GECIVSDFTI
GRKGYGSIYF EGDVNLTNLN LDDIVHIRRK EVVVYLDDNQ KPPVGEGLNR
KAEVTLDGVW PTDKTSRCLI KSPDRLADIN YEGRLEAVSR KQGAQFKEYR
PETGSWVFKV SHFSKYGLQD SDEEEEEHPS KTSTKKLKTA PLPPASQTTP
LQMALNGKPA PPPQVEKKGQ
