>query
 MTDWQQALDR HVGVGVRTTR DLIRLIQPED WDKRPISGKR SVYEVAVHLA
 VLLEADLRIA TGATADEMAQ FYAVPVLPEQ LVDRLDQSWQ YYQDRLMADF
 STETTYWGVT DSTTGWLLEA AVHLYHHRSQ LLDYLNLLGY DIKLDLFE  
>Q81EC0_BACCR
 .....QSALH QLKVAIDTSI DMLNQYSEND LKIQPIHSKR SLFEMCAHLS
 LICHADLLIL NGIPEKELHT FYIEQQTMIE GYNLLSKTFL SYSQIELAEV
 M..TAYWGIS YSRFEWLLEI VAHFYHHRGQ IHILLCEHMN DPRIPLFE  
>Q6HJQ2_BACHK
 .....QSALH QLKVAVDTSI QMLDQYTEID LKIAPIQSKR SLFEMCAHLS
 LICHADLLIL NGSTEKELRT FY.LEHTPET ITTLLSKTFL SYSQEELVEI
 ..KTSYWGVS YSRFEWLLEI VAHFYHHRGQ IHILLCEHIK DPNVPFFQ  
>Q2E676_BACCE
 .....QAALH QLKIAIHTSI KMLNQLTESD LNIKPIQHKR SLFEMYAHLA
 LICHADLLIL NETPQEELHT FYEIQQTMLQ GYDLLSETFL SYSHEELAHI
 T..TAYWGVS YSRFEWLLEI IAHVYHHRAQ IHMLVTEHIQ DPSVALFE  
>Q65L71_BACLD
 .......LFH ELETGIRSTC HLLKKVKESD WSYRPADRMR SLKELASHLT
 AIPEADLAIM QEKEEDVIAR IYGALQSADQ MAAAMQKGFD AFQTYMTSDF
 LTKKTYLDEG MTQSRWLTET LTHIFHHRAQ LFNYLKQLGY DVNMDLY.  
>Q2BCT9_9BACI
 .......... .....VHTTQ KVLDQLTDES LSQEVTAQNW TLGRIAWHTA
 TVMASQTGLA FEAPAKD... .YPVPQSAKF ISDIYQKASS ALAHEQWTDL
 SEEKDFFGQR MSNGQLLFFI IQHQIHHRGQ MTILMRQAG. ........  
>Q5L3J2_GEOKA
 ...WVQYFLS HRHV....TM ELIHKIDEAH YDYKPTPTSM TAKQLATHM.
 ..LFSFYNFA NTAKHGDPSL FRQKIEEPET NLAKLAETYE SMSDDDFDRT
 LDLTAIFGTQ MSTVQFLQLA MDHEIHHKGQ LFVYVRGMGH .TDLPLF.  
>Q9KBN5_BACHD
 .......... ........TE KVIAALTDES LDKRFSENGR TLRRLAWHIS
 TIPE..YLTE FGFELEEVEM PANVPTKAKE IADAVSRSAQ RWTDESLSYV
 QDA...WGEP LSKAELLSLF IKHMIHHRGQ MTVLMRQAG. ........  
>Q72ZL3_BACC1
 .......... .......STQ KMLDVLTDES LSQEIAPGHW TLGRVAWHIV
 VILSGTGLKF EGETKD.... .YPVPTSAKT IADGYRKVNT AFVEALQSEW
 TDKTTFFGRP MPNSIFLMTL INHQNHHRGQ MTVLMRQAG. ........  
>Q9K6P3_BACHD
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 ........IS MTPRKLLTHT MTHEFHHKGQ IVVMLRQLGH VP......  
>Q65GP1_BACLD
 .......... ........TE ELIQKIDEKH LDYKPTETSM PAKELVTHM.
 ..LQSFYTFA SAAKEGNGEP FKKKPEETGT SLSELAKTYE SFTDEELDRE
 VDLTGVFGRK VAGEQLLQLA IGHEIHHKGN LFVYVREMGH .TDLPLY.  
>Q81L63_BACAN
 .......... .......STQ KMLDVLTDES LSIAPGHWMR VAWHIVTAIP
 VILSGTGLKF EGETKD.... .YPVPTSAKT IAAEYRKVNA AFVETLQSDL
 ATINDFFGRP MPNSIFLMTL INHQNHHRGQ MTVLMRQAG. ........  
