>prot (#) default: single protein sequence description=t0369 /home/ppuser/server/work/predict_h9685
MTDWQQALDR HVGVGVRTTR DLIRLIQPED WDKRPISGKR SVYEVAVHLA
VLLEADLRIA TGATADEMAQ FYAVPVLPEQ LVDRLDQSWQ YYQDRLMADF
STETTYWGVT DSTTGWLLEA AVHLYHHRSQ LLDYLNLLGY DIKLDLFE
