>query
 MDAMKYNDLR DFLTLLEQQG ELKRITLPVD PHLEITEIAD RTLRAGGPAL
 LFENPKGYSM PVLCNLFGTP KRVAMGMGQE DVSALREVGK LLAFLKEPEP
 PKGFRDLFDK LPQFKQVLNM PTKRLRGAPC QQKIVSGDDV DLNRIPIMTC
 WPEDAAPLIT WGLTVTRGPH KERQNLGIYR QQLIGKNKLI MRWLSHRGGA
 LDYQEWCAAH PGERFPVSVA LGADPATILG AVTPVPDTLS EYAFAGLLRG
 TKTEVVKCIS NDLEVPASAE IVLEGYIEQG ETAPEGPYGD HTGYYNEVDS
 FPVFTVTHIT QREDAIYHST YTGRPPDEPA VLGVALNEVF VPILQKQFPE
 IVDFYLPPEG CSYRLAVVTI KKQYAGHAKR VMMGVWSFLR QFMYTKFVIV
 CDDDVNARDW NDVIWAITTR MDPARDTVLV ENTPIDYLDF ASPVSGLGSK
 MGLDATNKWP GETQREWGRP IKKDPDVVAH IDAIWDELAI FNNGKSALEH
 HHHHH     
>Q83PG4_SHIFL
 MDAMKYNDLR DFLTLLEQQG ELKRITLPVD PHLEITEIAD RTLRAGGPAL
 LFENPKGYSM PVLCNLFGTP KRVAMGMGQE DVSTLREVGK LLAFLKEPEP
 PKGFRDLFDK LPQFKQVLNM PTKRLRGAPC QQKIVSGDDV DLNRIPIMTC
 WPEDAAPLIT WGLTVTRGPH KERQNLGIYR QQLIGKNKLI MRWLSHRGGA
 LDYQEWCAAH PGERFPVSVA LGADPATILG AVTPVPDTLS EYAFAGLLRG
 TKTEVVKCIS NDLEVPASAE IVLEGYIDPG EMAPEGPYGD HTGYYNEVDN
 FPVFTVTHIT QREDAIYHST YTGRPPDEPA VLGVALNEVF VPILQKQFPE
 IVDFYLPPEG CSYRLAVVTI KKQYAGHAKR VMMGVWSFLR QFMYTKFVIV
 CDDDVNARDW NDVIWAITTR MDPARDTVLV ENTPIDYLDF ASPVSGLGSK
 MGLDATNKWP GETQREWGRP IKKDPDVVAH IDAIWDELAI FNNGKSA...
 .....     
>Q44G50_CHRSL
 ...MKYRDLR DFIAALEARG ELTRVTAEVD PYLEITEICD RTLRAGGPAL
 LFENVKGHAM PLLGNLFGTP ERVALGMGQD STAALREVGE LLAFLKEPEP
 PKGFRDAWEK LPIFKQAMSM GPKTLRKAPC QEVILEGDDV DLDRLPIQHC
 WPGDVAPLVT WSLVVTKGPN KTRQNLGIYR QQKLGKNRLI MRWLSHRGGA
 LDFQEWQSAH PGEPFPVAVA LGADPATILG AVTPVPDNLS EYAFAGLLRG
 SRTELVKCGH ADLEVPASSE IVLEGYIYPD DTAPEGPYGD HTGYYNEVET
 FPVFTVERIT HRRDPIYHST YTGRPPDEPA ILGLALNEVF VPILRKQFPE
 IVDFYLPPEG CSYRMAVVTM KKQYPGHAKR VMMGVWSFLR QFMYTKFVIV
 LDDDVDARNW EDVIWAITTR MDPARDTVMV ENTPIDYLDF ASPTAGLGSK
 MGLDATTKWA GETQREWGTP IVMDEAVKRR VDERWGEYGI ..........
 .....     
>Q2BL59_9GAMM
 MATPKYKDLR DFIHMLEQRG ELKRIKQEID PNLEMTEISD RTLRAGGPAL
 LFENPKGYDY PVLANLFGTP ERVAMGMGEE TVEALRDVGK LLSQLKEPEP
 PKGMKDAWEK LPIFKQVLNM GPKVVKGAAC QKHVLEGDRV DLYKLPIQTC
 WPGDAGPLVT WPLVITRGPN KERQNLGIYR QQLIGRNKLI MRWLAHRGGA
 LDFREWKQQR PGEKFPVAVA LGADPATILG AVTPVPDTLS EYAFAGLLRG
 GKTEVTQCIG SDLQVPASAE FILEGYIDPD EMADEGPFGD HTGYYNEVDS
 FPVFTVERIT HRSNPIYHST YTGRPPDEPA ILGVALNEVF VPILQKQFPE
 IVDFYLPPEG CSYRMAVVTM KKQYPGHAKR IMLGVWSFLR QFMYTKFVIV
 CDDDINARDW NDVIWAITTR MDPQRDTVMI DNTPIDYLDF ASPVSGLGSK
 MGMDATNKWE GETDREWGEP IVMDEEVKAK VDSIWGELGI LD........
 .....     
>Q3QIP4_9GAMM
 ...MSFKDLR SFISHLEECG ELKRVSYPVD PYLEMTEIAD RVLRAGGPAL
 LFEQPKGHSM PVLANLFGTP KRVAMALGKE DPLALRDVGE LLAFLKEPEP
 PRGFKDAIAK IPMFKQALNM PPKTVSRAPC QEVVMTGDDV DLTKLPIQHC
 WPGDVAPLVT WGLTITKGPR QKRQNLGIYR QQLLGKNKLI MRWLSHRGGA
 LDFRDFQEKH PGENYPVVVA LGSDPVTILG AVTPVPDSMS EYAFAGLLRG
 ERTEVVKALS CDLEVPATSE IILEGYIAPG EMAEEGPYGD HTGYYNETDS
 FPVFTVTHIS HRKDAIYHST YTGRPPDEPA MLGVALNEVF VPILRKQYPE
 IVDFYLPPEG CSYRMAVISI RKQYPGHAKR VMMGAWSFLR QFMYTKFIVV
 VDEDVNCRDW QDVIWAITTR MDPTRDTVMI DNTPIDYLDF ASPVAGLGSK
 MGLDATNKWE GETNREWGTP IVMDEAVKRR VDDIWDELGI E.........
 .....     
>Q2Y5S4_NITMU
 ...MKYKDLR DFLAQLERQG ELKRVAVEID PHLEMTEICD RLLKAGGPAV
 LFEKSRGHDI PVLGNLFGTP KRVAMGMGQD SVEALREVGK LLAYLKEPDP
 PKGLKDAWEK LPVLKQVLNM APKELSRASC QEIVWEGKDV DLGKLPIQTC
 WPGDAGPLIT WGLTVTKGPH KTRQNLGIYR QQVIAPNKVI MRWLAHRGGA
 LDFRDFTLAN PGQPYPIAVA LGADPATILG AVTPVPDSLS EYQFAGLLRG
 AKTEIVKCLT HDLQVPASAE IVLEGYIHPD ETAVEGPFGD HTGYYNEQET
 FPVFTIERIT MRRDPIYHST YTGKPPDEPA ILGVALNEVF VPLLQKQFTE
 IVDFYLPPEG CSYRMAVVSM KKQYAGHAKR IMFGVWSFLR QFMYTKFIIV
 TDDDVNIRDW KEVIWAITTR VDPARDTLIV ENTPIDYLDF ASPVSGLGGK
 MGLDATNKWP GETSREWGKP ITMDEVVKAR VDGMWTDLDL ..........
 .....     
>Q34US2_9GAMM
 ..PMKYRDLR DFISKLEADG ELRRVDVEVD PRLEMTEVCD RTLRAEGPAI
 LFQKPKGYRM PVLGNLFGTP RRVALGMGAE DVSALREIGE LLAFLRQPEP
 PKGLRDAWSQ LPVFRKVLDM GPKKVRRAAC QEVVVEGDDV DLGRLPVQTC
 WPGDAGPLIT WALVVTRGPE KERQNLGIYR NQVIGRNRTI MRWLAHRGGA
 LDFRDWQRER PGEPFPVAIA LGADPATILG AVTPVPDSLS EYGFAGLLRG
 SKTELVKCLG PDLQVPASAE IVLEGHIHPD DTAPEGPFGD HTGYYNEVDH
 FPVFTVDRIT HRRDPIYHST YTGRPPDEPA ILGVALNEVF VPILRKQFPE
 ISDFYLPPEG CSYRMAVVTM KKQYPGHAKR VMLGVWSFLR QFMYTKFVIV
 TDDDVNARDW KDVIWAMTTR MDPKRDTVMI DNTPIDYLDF ASPVSGLGSK
 IGFDATHKWP GETDREWGRP IVMDDETRAR VDALWPKLGL ..........
 .....     
>Q3K4W3_PSEPF
 ...MKFKDLR DFVQQLEQRG ELKRIQIPVS PVLEMTEVCD RTLRAKGPAL
 LFEKPTGYDI PVLGNLFGTP ERVAMGMGAE SVSELREIGK LLAFLKEPEP
 PKGLKDAWSK LPIFRKIIAM APKVIKDAPC QEVVIEGDDV DLAMLPVQTC
 WSGDVAPLIT WGLTVTKGPN KDRQNLGIYR QQVIGRNKVI MRWLSHRGGA
 LDFREWCEKH PGQPFPVSVA LGADPATILG AVTPVPDSLS EYAFAGLLRD
 SRTELVKCRG NDLQVPATAE IILEGVIHPG EMADEGPYGD HTGYYNEVDS
 FPVFTVERIT HRIKPIYHST YTGRPPDEPA ILGVALNEVF VPILQKQFPE
 ITDFYLPPEG CSYRMAVVTM KKSYPGHAKR VMLGVWSFLR QFMYTKFVIV
 TDDDINARDW NDVIWAITTR MDPKRDTVMI DNTPIDYLDF ASPVSGLGSK
 MGLDATHKWP GETTREWGRV IVKDDAVTQR IDAIWNQLGI ..........
 .....     
>Q3JEK5_NITOC
 ...MKYKDLR DFIAKLEAEG ELKRITVEVD PYLEMTEICD RVLHAGGPAL
 LFERPKGASM PVLGNLFGTP RRVAQGMGED SVAALREVGK LLAFLKEPDP
 PRGMKEAWRA LPIFKKVLDM APKIVRSAPC QEVILEGSQV DLSQIPIQTC
 WPGDIAPLIT WGLVVTKGPY KERQNMGIYR QQVLGPNRVI MRWLAHRGGA
 LDFQAWQQAH PGKPFPIAVA LGADPATILG AVTPVPDTLS EYAFAGLLRG
 SKTELTRCLG SGLQVPASAE IVLEGYLKPG DEANEGPFGD HTGYYNEVEK
 FPVFTIERLT HRRHPIYHST YTGRPPDEPA VLGVALNEVF IPILQKQFPE
 IVDFYLPPEG CSYRLAVVTM RKQYPGHAKR VMLGVWSFLR QFMYTKFVIV
 TDEDINARDW KDVIWAMTTR MDPARDCVII ENTPIDYLDF ASPVSGLGSK
 IGFDVTHKWK GETQREWGQP ITMDNAVKKR VDEMWDGMGL ..........
 .....     
>UBID_HAEDU
 ...MKYRDLR EFLNLLEQQG ELVRVKQEID PYLEMAEIAD RTLRKAGPAI
 LFENPKGYQM PVLCNLFGTP KRVALGMGQE NTQALRELGK LLAFLKEPEP
 PKGFKELLGQ LPQWKQILNM PSKTRDNAAC QQIVIEGDAV NLYDLPIMHC
 HEEDIAPLIT WGLTITQGPH KKRQNLGIYR QQLIAKNKLI MRWLSHRGGA
 LDFQEWKATY PDKPFPVSVA IGADPATILA AVTPIPDTLP EYAFAGLLRG
 HKTEVIKSIS NQLDVPASAE IVLEGYIDVN ETALEGPYGD HTGYYNEQEY
 FPVFTVTHIT MRKDAIYHST YTGRPPDEPA VLGEALNEVF IPILQKQFPE
 IVDFYLPPEG CSYRLAVVTI KKQYAGHAKR VMMGVWSFLR QFMYTKFVIV
 CDDDINARNW KDVIWAITTR CDPSRDTTLI ENTPIDYLDF ASPIAGLGSK
 MGIDATNKWN GETIREWGKP ITKNQQVVQH IDELWDQLGL ..........
 .....     
>Q7NQN3_CHRVO
 ...MKYADLR EFIAQLEQKQ LLKRIKTPVS PHLEMTEIGD RVLKAGGPAL
 LFEQPRRYDF PVLANLFGTP ERVAMGMGAD DVMQLREIGR TLAYLKEPEP
 PKGLKDAWDK LPLLKQVLSM APKEVKKAPC QDIVWEGEAV DLGKLPIQHC
 WPGDAAPLIT WGLTVTRGPN KKRQNLGIYR QQVIGKNRVI MRWLAHRGGA
 LDYREFRQQN PDTPYPVAVV LGCDPATILG AVTPVPDTLS EYQFAGLLRG
 SRTELAQCLG SDLQVPARAE IVLEGHIHPN DMALEGPYGD HTGYYNEQDS
 FPVLTIDRIT MRENPIYHST YTGKPPDEPA ILGVALNEVF VPILQKQFPE
 IVDFYLPPEG CSYRMAIVSI KKQYPGHAKR VMMGCWSFLR QFMYTKFIVV
 VDDDVNTRDW KEVIWAITTR MDPVRDTTLI DHTPIDYLDF ASPISGLGGK
 MGLDATNKMP GETSREWGTP IVMDDAVKAR VDALWSELGL ..........
 .....     
>Q5X0U5_LEGPA
 ...MKYSDLR DFIAQLESRE LLKRIDYPVS PHLEMTVVSD KVLRSGGPAL
 LFTNTPNYNM PVLTNLFGTV ERVALGMGEE SIVALREIGK LLAALKEPDP
 PKGFKDAFSK LPLLKQALNM APKYVSGAEC QTHVWEKDEV DLTLLPIQTC
 WPGDVAPLIT WGLVTTRGPH QSRENMGIYR QQLLSKNKLI MRWLSHRGGA
 LDYQAWQQEY PQERFPVAVT LGADPATILA AVTPVPDTLS EYAFAGLLRG
 QRTRLTRCIG NDLHVPASAE IVLEGYLEPG NEAPEGPYGD HTGYYNEVQS
 FPVFTVERIT HRDKPIYHST YTGRPPDEPA ILGVALNEVF IPLLQKQFPE
 IVDFYLPPEG CSYRLAVVTI KKQYPGHAKR IMMAVWSFLR QFMYTKFVIV
 CDDDVDARNW QDVIWAMTTR MDPSRDTVMV ENTPIDYLDF ASPVSGLGSK
 MGMDATSKWP GETQREWGKP ITMDEDVLNR VNSYWSLLGL ..........
 .....     
>Q5P5M6_AZOSE
 ...MKYQDLR DFIVQLEERG ELKRISAPVD THLEMTEIAD RVLRAGGPAL
 LFEQPVTRAM PVLANLFGTP QRVALGMGGD WQTPLREVGS LLAFLKEPEP
 PKGFRDAWEK LPVFRQVLNM APKEVRSAPC QEVVWEGADV DLARLPIQHC
 WPGDVAPLIT WGLVVTRGPG KKRQNLGIYR QQVLSRDRVI MRWLAHRGGA
 LDFRDHQQAS SGEAFPVAVV LGCDPATILG AVTPVPDSLS EYQFAGLLRG
 AKTELVKCMG SDLQVPASAE IVLEGVIHPG DTAAEGPYGD HTGYYNEVSE
 FPVFTIDRIT MRRDPIYHST YTGKPPDEPA MLGLALNEVF VPLLQRQYPE
 IVDFYLPPEG CSYRLAVVSI RKQYPGHAKR VMFGIWSFLR QFMYTKFIIV
 VDDDVAIRDW KEVIWALTTR VDATRDTVLV DNTPIDYLDF ASPVASLGSK
 MGLDATNKWP GETTREWGRP IVMDDVVKAR VDAMWDELGL ..........
 .....     
>Q602K0_METCA
 ....KYRDLR DFIARLEAEG ELRRIGASVD PNLEITEICD RTLKSEGPAL
 LFEHPKGSAV PLLGNLFGTP RRVALGMGEV SVGALRQVGV LLASLKEPEP
 PKGMRDAFEK VPLYRQVLHM APKEVRNAPC QQEVLRGSDI DLGRYPIQTC
 WPGDAGPLIT WPLVITRGPY KARQNLGIYR QQVIGRNKTI MRWLAHRGGA
 LDFRDWQEAR PGEPFPVAVA LGADPATMLG AVTPVPDTLS EYGFAGLLRG
 ARTEVTPCIL SDLQVPASAE IVLEGFLYPG ETAPEGPFGD HTGYYNEVES
 FPVFTIECIT QRHSPIYHST YTGRPPDEPA VLGVALNEVF VPILQKQFPE
 VVDFYLPPEG CSYRLAVVSM KKQYAGHAKR VMFGVWSFLR QFMYTKFVIV
 VDDDVDARNW KDVVWAMTTR MDPARDLTLI ENTPIDYLDF ASPVSGLGSK
 VGFDATHKWP GETNREWGRP ITMDAAVRRR VDEIWDSLGI F.........
 .....     
>Q2SYC8_BURTA
 ...MKYKDLR DFIHSLEQRG ELRRITQPVS PALEMTELCD RVLRAGGPAL
 LFDAPDGYRF PVLGNLFGTP RRVALGMGVD ADDSLRDIGR LLSALKEPDP
 PKSLKDAGKL LSLAKAVWDM GPKTVSAPPC QEIVWEGDDV DLHKLPIQTC
 WPGDAGPLLT WGLTVTRGPN KTRQNLGIYR QQLIGRNKLI MRWLAHRGGA
 LDFREFALKH PGQPYPVAVV LGADPATALG AVTPVPDTLS EYQFAGLLRG
 ARTELAKCLT PGLQVPARAE IVLEGFIHPY EHALEGPYGD HTGYYNEQEW
 FPVFTVERIT MRRDAIYHST YTGKPPDEPA VLGVALNEVF VPLLQKQFSE
 ITDFYLPPEG CSYRMAIVQM KKSYAGHAKR VMFGVWSFLR QFMYTKFIVV
 VDEDVNVRDW KEVIWAITTR VDPARDTVLV ENTPIDYLDF ASPVAGLGSK
 MGLDATNKWP GETQREWGRP IEMDAAVKAR VDRLWTEIGL ..........
 .....     
>Q3FS24_9BURK
 ...MAYRDLR DFITQLEHLG ELKRVQAEVS PYLEMTALCD RTLRAGGPAL
 LFENPTGHNT PVLGNLFGTT RRVALGMGVN DVSELRQFGH VLASLKEPEA
 PKGFKELMGL GSLVKTLWAM APKELRSAPC QEIIWEGADV DLARLPIQHC
 WPGDVAPLIT WGLVITQGPH KARQNLGIYR QQVLARNKVI MRWLAQRGGA
 LDFKEHAALN PGQPYPVCVA LGADPATILG AVTPVPDSLS EYQFAGLLRG
 SRTELVKALG SELRVPAFAE IVLEGHIYPD EHALEGPFGD HTGYYNEQDW
 FPVFTIDRIT QRRDPIYHST YTGKPPDEPA MLALALNELF VPLLQRQYPE
 ITDFYLPPEG CSYRLAVVQI KKSYPGHARR VMFGIWSFLR QFMYTKFIVV
 VDDDVNIRDW KDVIWAITTR VDPTRDTLLA DSTPIDYLDF ASPVSGLGSK
 MGLDATNKWP GETSREWGRP LTMSADVTAR VEQVWQTLGL ..........
 .....     
>Q2WAT7_MAGMM
 ...MPYESLR DFIARLEKAG RLKRVSAPVS PHLEMTEIQT RLLAEGGPAV
 LFENVSKYSM PVLVNLFGTV ERVAWGMDRE PHQ.LREVGE TLAFLKQPEP
 PGGWREALEM LPLAKTVMAM RPKTVGSAPC QQVVLTGDQV DLSQLPIQGC
 WPGEPAPLIT WPLVVTQGPN PDGDNLGIYR MQVTGKNTTL MRWLKHRGGA
 QHFQRWGQEK R.QPMPAAVV IGADPGTIIA AVTPVPETLS EYQFAGLLRG
 KKLELVDCKT VPLKVPAEAE IVLEGHVMLD EHGPEGPYGD HTGYYNSVEE
 FPVFRISAIT MRRDPIYLST FTGRPPDEPS VLGEALNEVF IPLLAQQFPE
 IVDFWLPPEG CSYRIAVVSI KKAYPGHAKR VMFGIWSFLK QFMYTKFVIV
 VDDDIDARNW KDVMWAISTR MDPARDITVV EGTPIDYLDF ASPESGLGGK
 LGLDATNKWP PETHREWGEK IKMSGDVVDR VSQRWAEYGL PGSGK.....
 .....     
>Q7WML9_BORBR
 ...MKYRDLR DFLAQLERQG ELKRITAPVS TRLEMTEIAD RVLRAGGPAL
 LFENARHADM PVLANLFGTP RRVAWGMGAD DVGALRETGE LLASLREPEA
 PKGLRDALAK VSMLKALWDM SPKTVRSAAC QEIVWEGADV DLGRLPIQTC
 WPGDVAPLLA WGLVITRGPN ARRQNLGIYR QQPLGPNKLI MRWLSHRGGA
 LDFRDHAQAH PGKPFPIAVA LGADPATILG AVTPVPDTLS EYQFAGLLRG
 SRTEVVKALG SDLSVPASAE IVLEGHLLPA EMALEGPYGD HTGYYNEQDW
 FPVFTVDRIT MRRNPIYHST YTGKPPDEPA VLGVALNEVF VPLLRRQLPE
 IVDFYLPPEG CSYRLAVVSI RKQYAGHAKR VMFGLWSVLR QFMYTKFIVV
 VDEDIDPRDW TEVVWAMTTR MDPVRDTVLV ENTPIDYLDF ASPVSGLGGK
 MGLDATNKWP GETSREWGTP IHMDEAVKRR VDAMWDTLGL ..........
 .....     
>Q87KI0_VIBPA
 ...MSFKDLR EFIDHLEQKG RLKRITHPVD PAYEMTEISD RTLRAGGPAL
 LFENPIGYNV PVLTNLFGTP ERVAIGMGRE DVKELREVGK LLAYLKEPEP
 PKGFKDALEK LPVFKQVLNM PAKRLRKAPC QDIVWQGDEV DLDKIPVMSC
 WAEDVAPLLT WGLTVTKGPN KKRQNLGIYR QQKIAKNKII MRWLAHRGGA
 LDLRDWMETN PGKPFPVSVA FGADPATILG AVTPVPDTLS EYAFAGLLRG
 SKTEVVKSIS NDLEVPASAE IVMEGYIDPN EFADEGPYGD HTGYYNEKEK
 HHVFTITHIT MRKDPIYHST YTGRPPDEPA VLGVALNEVF VPILQKQFPE
 IEDFYLPPEG CSYRMAVVTM KKQYPGHAKR VMMGVWSFLR QFMYTKFVIV
 CDESVNARDW NDVVKAMTEH MDPVRDTLMI DNTPIDSLDF ASPVVGLGSK
 MGLDATIKWD AE........ .......... .......... ..........
 .....     
>Q491V9_BLOPB
 ...MKYKDLR DFIKILEHRG DLKRIKFPIN PDLEITEIAD RTIKSGGPAL
 FFENPTGYTI PVLCNLFGTP NRIALGMGKE SILSLRDVGK LLAFLREPEL
 PTGVHDFFSK IPHFRHILHM PIKRVSTAPC QENVWCNQDV DITHMPIMRC
 WPQDVSPVIT WGITITRGLK SKRQNLGIYR QQVLSKNKII MRWLSHRGGA
 LDFQEWHKNT SERRFPITVA LGADPATLIG AVVPIPDTLS EYAFSGLLRG
 CRTEVIKCIS CDLDVPANSE IVLEGYLERD ETAIEGPFGD HTGYYNTTAK
 FPVCTITHIT QRNNPIYLST YTGRPPDEPA ILGMAMNEMF IPIIQKQFPE
 ITDFYLPPEG CSYRLAIVTI KKQYIGHAKR IIFGIWSFLK QFMYTKFIIV
 CDDDINARDW NDVVWAITTR MEPDRDTIIV KNTPIDYLDF SSPISGLGSK
 IGMDATNKWP GETEREWGIP IKMHDTVRHY IDSIWDKLDI ..........
 .....     
>Q3S0U0_RALME
 ...MQYKDLR DFMSQLEQRG ELKRVAAPVS PNLEMTEICD RLLRANGPAV
 LFEQPRRYKV PVLANLFGTT QRVAQGMGAS SLEDLRDIGR VLSVLKEPEP
 PRGLREAGKL FTLAKSVWDM APKRVSSPAC QEIVWEGNDV DLARLPIQTC
 WPGDAAPLIT WGLVVTKGPH KKRQNLGIYR QQVISRNQVI MRWLAHRGGA
 LDFREHALAN PGKPFPIAVA LGADPATILG AVTPVPDTLS EYQFAGLLRG
 SRTALASCIT SELSVPASAE IILEGHIQPD QHALEGPYGD HTGYYNEQDW
 FPVFTIDRIT MRRDPIYHST YTGKPPDEPA VLGVALNEVF VPLLQKQFPE
 ITDFYLPPEG CSYRMALVRM KKQYAGHAKR VMFGVWSFLR QFMYTKFIVV
 VDDDIDVRDW KEVIWAITTR VDPTRDTVMV DNTPIDYLDF ASPVSGLGSK
 MGIDATDKWP GETTREWGTP ITMAPEIKAR VDQMWGSLFE EGPGK.....
 .....     
>Q9ABB7_CAUCR
 ...MAYRSLR EFIDVLEAKG ELVRVKEPVS SVLEMTEIQT RLLATGGPAV
 LFEHVSRSEM PALANLFGTV KRVAMGLGGE PRETLREVGE LLAFLRQPQP
 PKGLKDALDM LPLAKTVMSM RPGTVKKAPV QEVVLTGDQI DLSKLPVQTC
 WPGEPAPLIT WPLVVTKGPS KDRENLGIYR MQVLSKDKCI MRWLAHRGGA
 QHYARHKKAG SKEPLPACAV LGADPGTILA AVTPVPDTLS EYQFAGLLRG
 AKVDLVPAKT VPLMVPAHAE IVIEGHVLLD EYADEGPYGD HTGYYNSVEK
 FPVFQVTAIT MRKDPIYLTT FTGRPPDEPS VLGEALNEVF IPLIRQQFPE
 IVDFWLPPEG CSYRIAVVSM KKAYPGHAKR VMLGVWSYLR QFMYTKWVIV
 VDHDINARDW KDVMWAISTK MDPARDITVI EHTPIDYLDF ASPESGLGSK
 IGLDATDKWP PETKREWGEE IRMDQAVVDK VSDMWGRLGL PGDGK.....
 .....     
>Q7VRJ3_BLOFL
 ...MTYKDLR NFIKTLEYQG ELKKIDFPVD PNLEITEIAH RTLKSQGPAL
 LFTNPIGHSI PILCNLFGTI SRIELGIGIK NILSLRDIGK LLAFLKEPQI
 PTGFRDFLSK IPNFRQILNM PIKHVSNAVC QENIWNAQDI DITQMPIMKS
 WPGDISIAIT WGITITQGFT NKRQNLGIYR HQVLSKNKII IRWLAHRGGA
 LDFQEWYTHS SEKKFPIAIA LGADPATLIG AAIPIPNTLS EYAFSGLLRG
 SKTAVTKCIS SNLYVPAYSE IILEGYINRD DIAVEGPFGD HTGYYNSTEK
 FPVCTITHIT HRNNPIYHST YTGRPPDEPS ILGMAMNELF IPIIQKQFPE
 IIDFYLPPEG CSYRLAIVTI KKQFLGHAKK IIFGVWSCLN QFMYTKFILV
 CDDDINARDW KDVIWAISTR MDPARDIIIA ENTPIDYLDF SSPISGLGSK
 MGIDATNKWP GETQRTWGKP IQMNNSIQSR INDIWDQLHI PCNEK.....
 .....     
>Q5GSQ6_WOLTR
 .....YNNLR DFIEALEKKR DLIRIKKEVS TILEMTEIHR RVSLNKGPAI
 IFENVVKSVI PVLVNLFGTI ERIAFGLNIS PGE.LRDLGK LLAFLQSPEP
 PKNLKDVIKM FPLLKVVLSM RSKIVNKAPC QEVVLTGDDV DLSLLPIQTC
 WPNEPAPLIT WPIVITKGPT EDKQNLGIYR MQVMDKKTTL MRWLAHRGGA
 SHHKRWKENG RSIKFPAAAV IGSDPATLIA AVTPVPETLS EYQFAGLLRK
 KPLELVNCKT ISLQVPAHAE IVLEGYVSLD SYRNEGPYGD HTGYYNSVEQ
 FPEFNITAIT MRKNPIYLST FTGKPPDEPS ILGEALNEIF VPILINQFPE
 IVDFYLPPEG CSYRIAVVSV KKSYPGHAKR IIMGIFSFLK QFLYTKFIIV
 VDDDINIRDW KEVMWAISTR MDPVRDTVMI ENAPIDYLDF ASPESGLGGK
 MGFDATNKMP PETKREWGKK IEMSEEIVKK VTEKWDEYGL TDD.......
 .....     
>Q2GIE2_ANAPZ
 ...MSFRDLR GFLDFLEKKG ELVRVGEEVS PVLEITEIHS RLIRSAGPAV
 VFENVVNSGI PVVANLFGTI ERISYGLGIE SCG.LRDVGR LLAFLRMPTP
 PESFRDLLGM FPILRNVVSA RTTVVKKAKC QEVVLTGDDV DLRKFPIQTC
 WPGDVAPLIT WPIVVTHGPT NTRENLGIYR LQVVSENTAI MRWLRHRGGA
 QQYFRWKKEG KG.DFPVAVV LGADPATTIA AVTPVPETLS EYQFAGILRK
 RPTELVNCIT VPLRVPANAE IVLEGYVSAS ELLDEGPYGD HTGYYNSVEK
 FPKFVIKAIT MRNSPMYHST FTGRPPDECS VLGEALNEII IPMMISQYPE
 IVDFWLPPEG CSYRVAIVSI KKAYPGHARR IVMGVLSFLR QFMYVKFVIV
 VDDDICVRDW KDVIWAISTR MDPSRDMMYI EDAPIDYLDF ASSETGLGSK
 VGFDATNKIY PETKREWGVK IEMSKEIIDK VTSRWGQYGF E.........
 .....     
>Q4UJY9_RICFE
 ...MSFKDLP EFLKFLEKNG ELKRISTPVK TDLEITEISR RVLAQGGPAL
 LFENVIKSDI PVLTNLYASI NRICMGLKLK SPKELRELGV LLAFLKQPQP
 PASFKETLSM LPLAKRIFAM SPKTISKAAC HEVVV..DKP NINILPIQKC
 WPDDISPLIT WGIVVTKGPT KDKYNLGIYR MQVISENKLL MRWLKLRGGA
 EHHKRWKEAK K.EPFPAAIV IGANPAVTLA AVTPIPENIS EYNFAGLLGN
 EKIELVQCKT IDLKVPAHSE IVLEGYVSLE EYLPEGPFGD HTGYYNDVEE
 FPVFTVTAIT MKKNPVYLST YTGKPPDEPS ILGEALNEIF IPILQQQFPE
 IVDFWLPPEG CSYRIAVVSI KKSYPGHAKR IMLGIWSYLR QFMYSKFIIV
 VDDDIDVRNW QEVIWAIATR SDPRRDTSFI DNSPIDYLDF ASPDSGLGSK
 MGIDATDKIY PETNRKWGKK IEMSQEVIDK VDSMWDGLKI ..........
 .....     
>Q8D380_WIGBR
 ...MKYVCLR SFIKILEKHK KIKRIFVPIS PNLEITEISH RTINKEGPAL
 IFENPKGYKM PLLCNLFGTT ERVAMAMGGK DIKYIRKLGK IISFLKTPEA
 PKNIKDILNI APKFKAMLHM FTKKVNNAPC QEEIFSGSDV DLTSIPIMKC
 WPNDIGPLIT WGLTITKGPY KKRQNIGVYR QQVIEKNKII MRWLPHRGGA
 LDFLSWKNSK KADKFPVAIA LGADPATILS AVTPIPDNLS EYSFAGLLRK
 NKTEVIKCIS SDLEVPAYSE IILEGYLD.D KIAEEGPYGD HTGYYNEIER
 FPILNITHIT KRKDSLYHST YTGKPIDEPS VIGMALNELF IPILQKQFPE
 IIDFYLPPEC CSYRISVVSI KKQYLGHANQ IMMGIWSILR QFMYTKFIIV
 CDDDIDIRNW KDIMWSISTR VDPYRDTLLI KNTPIDYLDF ASEKKNLGSK
 IGIDATNKWP GETTRNWGVP IKMDKIIKDK IDLIWDDLNI F.........
 .....     
>Q377A5_RHOPA
 ....PFPDLR AFLAYLESRG QLLRIRRPVS VVHEITEIHR RVLADNGPVL
 LFEQAKRSPI PIVVNLFGTV ERVAWGFGVL P.EHLQQLGE ALAEMRDPTP
 PQSIVDALSK LPMARAAMAM RPKTAKITPA QQVVWKGDEI DLGQLPIQVP
 WSREPAPLIT WPLVFTRSPE NGADNVGVYR IQVLGKDRVI MRWLAHRGGA
 KHHHQWQ..K LGRDMPVAIV IGADPAMILS AVLPLPENLS EIKFSGLLRG
 ERPQLANCVS VPLQIPADAE IVIEGIVSAT ETAPEGPYGD HTGYYNSVEQ
 FPVMKITAIT MRRDPIYLST YTGRPPDEPS RLGEAFNDIF LPVAKRQFPE
 IVDLWLPPEA CSYRIAVASI KKRYPGQARR LMMGLWSMLP QFSYTKLLII
 VDDDINVRDW ADVMWAVSTR SDTSRDMVSI TDTPIDYLDF ASPKSGLGGK
 LGIDATNKIG SETAREWGEV LTMDDAVVKR VDAMWSSLGL ..........
 .....     
>Q3AB56_CARHZ
 ...MAFRDLR EFIAELEKRG ELKRIKVPVS PELEITEITD RVSKAYGPAL
 LFENVSGYDI PVLMNAFGSY ERMKLALGVD RLDDIGE..E FLSLLNPDDI
 PVTMFEKLKM LPKLARLSNF APKIVKSGPV KEVIIK.DNP DLNKFPILKC
 WPQDGGRFIT LPLVITKDPE TGRRNVGMYR MQIYDGRTTG MHWHMHKDAA
 ..HFYQKAKR LGKPLEVAVA LGGDPATIYA ATAPLPPSID EFLFAGFIRK
 EPVELVKAET VDLEVPAHAE IVIEGYVDPD ELRLEGPFGD HTGYYSLTDY
 YPVFHVTAIT HRKNPIYPAT IVGKPPMEDC YMAKATERIF LPFLKLLLPE
 IVDINLPLEG VFHNCAIVSI RKRYPGHARK VMNALWG.LG QMMFTKMIIV
 VDENVNVQNL SEVMWKVFNN IDAKRDLMIV EG.PLDILDH ASPLPNYGSK
 LGIDATKKWP SEGHRPWPDD IEMDPEIKAL VDRKWSDLGL ..........
 .....     
>Q8YXV1_ANASP
 ...MA.RDLR GFIKILEERG QLQRISALVD PDLEIAEISN RMLQKGGPGL
 LFENVKGASF PVAVNLMGTV ERICWAMNMQ HPQELETLGK KLSMLQQPKP
 PKKISQAIDF GKVLFDVLKA KPGRDFFPAC QQVVVQGDDV DLNTLPLIRP
 YPSDAGKIIT LGLVITKDCE TGTPNVGVYR LQLQSKNTMT VHWLSVRGGA
 RHLRK..AAE RGKKLEIAIA LGVDPLIIMA AATPIPVDLS EWLFAGLYGG
 SGVQLAKCKT VDLEVPADSE FVLEGTITPG EILPDGPFGD HMGYYGGVED
 SPLIRFQCMT HRKDPIYLTT FSGRPPKEEA MMAIALNRIY TPILRQQVSE
 IVDFFLPMEA LSYKAAIISI DKAYPGQARR AALAFWSALP QFTYTKFVIV
 VDKDINIRDP RQVVWAISSK VDPTRDVFIL PNTPFDTLDF ASEKIGLGGR
 MGIDATTKIP PETDHEWGAP LESDADVAAM VERRWAEYGL ADLQ......
 .....     
>Q8FX00_BRUSU
 .....YDCLQ SFLTELEKRG DLVRIARPVS LVHEVTEIHR RVLEADGPAL
 LFENPVDAEI PLLANLFGSE RRIAWGLGRL PEE.LPLLAE MLAELRAPKP
 PRSAGEIWEK LPMAKAALNM RPRQVSRAPV HGLVMEGASV NLDTLPIQWC
 WPGEPAPLIT WPLVITRAPD DPSVNVGIYR MQKLGENRLI MRWLAHRGGA
 RHHRMWQ..K RGEDMPVAIA IGVDPATILA AVMPLPEGMS ELAFSGLLGG
 RRPCVTQGRT VPLMVPANAE IVLEGRVSAT QTAPEGPYGD HTGYYNSVEA
 FPVMQVTAIT MRKKPVYLST YTGRPPDEPS RLGEVMNQLF VPVVRKQFPE
 IADLWLPPAA CSYRAMVVSI DKRYPGQARR VMMGLWSMLP QFSYTKLIIA
 VDPDIDVHNW DDVMWALATR FDASRDVVTL SDTPVDYLDF ASPRSGLGGK
 LGLDATNKIG PETDREWGKV LAMNEETIAR VDAIWDELGL ..........
 .....     
>Q8U7Q5_AGRT5
 ......SDLR GFIRLLEERG QLRRIRQPVS LVHEITEIHR RVLADGGPAL
 LFEQPVDHKM PLLANLFGTR QRIEWGLGLE .TGGLPALGQ KLTELREPRP
 PKSMAEAWSK LPLLRAALSM RQRNVSRAPV QEKVLTRDAV DLARLPVQWC
 WPGEPAPLIT WPLVITRSPD DDDINVGIYR MQVLGPDRVI MRWLAHRGGA
 HHHRLWQA.. RGLDMPVTVA IGADPATILA AVMPLPDHIS ELGFSGLLRG
 AKSRIAKALT VPMPVPANAE IVLEGTVSAT ETAMEGPYGD HTGYYNSVEA
 FPVMTLSAIT MRRDPIYLST YTGRPPDEPS VLGEAMLEIF LPLVKRQFAE
 IVDLWMPPEA CSYRVMVASI DKRYPGQAKR VMMGLWSMLP QFSYVKLIIL
 VDPDIDVRSW TDVVWALSTR FDASRDTTII NDTPIDYLDF ASPKAGLGGK
 MGLDATRKLP PETEREWGRV LSMTPDVVAK VDLVWRDLGL ..........
 .....     
>Q2D3T9_9FIRM
 ...MAYQDLR DYMKTLENKG LLKRITTEVS ADLEITEITD RVCKSSGPAL
 LFENVKGYKM PVITNMMGSM EMIKLALQVD DLDDIGK..E IMTFLNPPEL
 PSSFLDKLKT LPKLAQISSF LPKNVRSGPC KEVIIK.DKP SLAVLPVLKC
 WPMDGGPFIT LPLVFTKDPE TGRRNVGMYR MQVFDETTTG MHWHKHKDGA
 ENHRKQKQKK ..QRLEVAVA LGADPACIFS SIAPLPPAID EMLLAGFLRK
 EPVEMVKCET VDIEVPARAE IILEGYVDPD ETRWEGPFGD HTGYYSLADD
 YPVFHLTCIT HRKDPIYPAT IVGQPPIEDN FIGKAIERTF LPLMRLQLPE
 IVDINMPPEG VFHNCVIVSI KKRYPGHAKK VMNALWGM.G QMMFAKLIIV
 VDEHVDVQNP SQVAWRVFNN IDARRDVMIV .DGPLDALDH SSPAPYYGAK
 MGIDATKKWP AEGHREWPDD IVMSEEIISL VDRKWKSYGF ..........
 .....     
>Q2AF17_9FIRM
 ...MAYRDLS DFIKTLEREN ELVRVGVEVD PVLEITEITD RVVKNGGPAL
 LFENVKGSDF PVLINAFGSI RRMELALEAE S...LDDIGD RINQYLQLPT
 PENFLDKLKM LPLLKELGDF LPRTVKKAPC QEVV..EENV DLGSLPILKC
 WPGDGGRYIT LPLVFTKDPG TGRQNVGMYR LQVFDKKTTG MHWHIHKDGA
 ENYRKHLGNR ..EKMEVAVA IGADPATIYA ATAPLPAGID EMLFAGFLRK
 EPVEMVKCRT VDLKVPANAE IILEGYVKPG ELRKEGPFGD HTGYYSLVDE
 YPVFHVQAIT RRNQPVYNAT VVGKPPMEDC FMAKATERIF LPLLKMQLPE
 IVDMNLPLEG VFHNCAIISI KKSYPGHAKK VMHALWG.LG QMMYTKMIIV
 VDEDVDVQDL STVAWKVFNN IDARRDVVIV .DGPLDALDH SSPVRHYGSK
 MGIDATKAWP EEGHREWPPE IEMNKKIKKL VDKRWQEYGI ..........
 .....     
>Q5P9G8_ANAMM
 ...MSFAGLG EFVSFLEARG CFVHVQGEVS SVFEITEIHR RLVAAQGPAV
 LFKNVVPCSI PVLVNLFGTV ERVALGLGVE PCG.LRGIGE LLAFLRSPTP
 PESFRDLLTM VPMLRNVVAA RTRVVKKAPC HEVVMVGDDV DLRKLPIQTC
 WPGEPAPLIT WPIVVTRGPS ASRENLGVYR MQVVSKNSTI MRWLRHRGGA
 QQYRRWVKEG RG.DFPAAVV IGSDPATLIS AVAPVPDTIS EYQFAGILRK
 HPTELVECIT VPLKVPSNAE IVLEGVVSAD EFLEEGPYGD HTGYYNSVEK
 FPKFTVTAIT MRSSPIYMST FTGRPPDECS VLGEVLTELL IPMLKLQYPE
 ITDFWLPPEG CSYRVAVVSI KKAYPGHARR IVMGVLSYLR QFLYVKFVIV
 VDEDICVRDW KDVIWAMSTR MDPARDTMFI ERSPIDYLDF ASPEEGLGSK
 VGFDATNKIH PETTRLWGIP LKMSEDITER VTSRWAEYGF ..........
 .....     
>Q3G952_9FIRM
 ...MAYKDLQ EFIQVLESEG ELKRISVEVD PELEITEITD RVSKNYGPAL
 LFEKVKGSDM PVLINAFGSE KRMALSLQVD KLDDLA..TE IMGLLEIADS
 PQSLLDKVKV LPKLAQLSSF LPRMVKSGAC QEVV..DLNP SLDKIPVLKC
 WPEDAGRFIT LPQVYTKDPE SGKRNVGMYR LQVFDGQSTG MHWHTHHDGA
 ENYRKNCQ.. RGQATEVAVA LGGDPAITYA GTAPLPKDID ELIFAGFIRK
 KPVELVKCKT VNLEVPADAE IVIEGYVDPY ERRIEGPFGD HTGYYSLADE
 YPVFHVKCIT HKKNAVYPTT IVGKPPQEDC YMALATERIF LPLLKLQLPE
 VVDMHLPMEG VFHNCVLVAI KKSFPGHARK IMSSLWGM.G QMMFAKFIIV
 VDEDVNVQNV SEVMWKVFNN VDPRRDTMIV EG.PLDVLDH SAPLPLIGSK
 MGIDATKKWM SEGHREWPKD IVMSPEIKEM VSRRWSEYGF E.........
 .....     
>Q67P44_SYMTH
 ...MAFRDLH EFIAACEQRG WLKRIKAPVS PYLEIAEITD RVSKGGGPAL
 LFENVEGSRF PVLTNTLGSM ERICLALGVN HLDEIGQRIR ..DLLKLPTS
 GGGLLDKLGQ MKLLDVARST APRLVNRAPC QEVVLTGDDV DLYKLPILTT
 WPKDGGPFIT LTNVITRDPV TGGRNIGMYR MQVYDRRTTG MHWHKHKDGQ
 RHFDAYQ... .GTRMPVAVA LGGDPATIYS GSAPLPPVIP ELMFAGFLRG
 EPVELVKCKT IDLEVPAHAD FILEGYVDTA ELRPEGPFGD HTGFYSPVDP
 YPVFHVTAIT HRRDAIYPAT VVGKPPQEDA YLGKATERIF LPLLQLFMPE
 IIDYNMPVEG GFHNCVLVKI KKRYPGHARK VVHGLWG.LG LMMLSKCIIV
 VDEHIDLNNY SEVFWYVSGN IDPKRDI.FF AEGPVDDLDH AAPVWRYGSK
 MGIDATRKWP EEGHRPWPEE IEMSPEVKER VTARWKEYGF ..........
 .....     
>Q92Z11_RHIME
 .....FSDLQ DFAAMLERRG RLLRISRPVS LVHEVTEIHR RVLLAGGPAL
 LFERPVDCDI PLLANLFGTL ERIEWGFGLP AGG.LPGLAE MLAELREPRS
 PQSLSDAWGK LPLLKAALAM RPRNVSSPPV QDTVWRGAEA DLSRLPIQWC
 WPGEPAPLVT WPLVITRAPD DPSVNVGIYR MQVLGPNRLV LRWLAHRGGA
 RHHRMWQQRR ..EDMPVAVA IGSDPATILA AVMPLPESMN ELAFAGLLKA
 ERQPVAQAVT VPLSVPANAE IVLEGVVSAD ETAEEGPYGD HTGYYNSVER
 FPVMSLSAIT MRHRPFYLST FTGRPPDEPS KLGEAMMELF LPLVKRQFPE
 IIDLYLPPEA CSYRAMVVSI DKRYPGQAKR IMMGLWSMLP QFNYTKLIVA
 VDPDIHVRNW SDVIWALSTR FDASRDVTIL NDTPIDYLDF ASPKPGLGGK
 LGLDATRKVG PETNREWGRV LEMPAEVVGK IDQFWAELGL ..........
 .....     
>Q7V8F5_PROMM
 ....ASQDMR DFLALLEQRG QLRRITAPVE PDLELAAITD RVLGLGGPAL
 LFENVIGSSM PVAVNLMGTL ERVVWSMGLD NAQQLEDLGT RLALLQQPRP
 PKGLQETRQF ASVFWDLIKA RPDLDLTPPC HQQVLRGDAL NLDNLPLIRP
 WPGDASGVIT LGLVITKDPE TGVPNVGVYR LQRQSPKTMT VHWLSVRGGA
 RHLRK..AAA MGQKLEVAIA IGVHPLLIMA AATPIPVQLS EWLFAGLYAG
 EGVRLTGCKT LDLKVPSHSE VVLEGTITPG EELEDGPFGD HMGFYGGVES
 SPLVRFHCVT QRRDPIFLTT FSGRPPKEEA MLAIALNRIY TPILRQQVSE
 IVDFFLPMEA LSYKLAVIAI DKSYPGQAKR AAMAFWSALP QFTYTKFVVV
 VDANINVRDP RQVVWAIAAQ VDPQRDLFVL ENTPFDSLDF ASEHLGLGGR
 MAIDATTKIG PEKRHEWGEP LSRDADLESR VDARWQELGL EDLG......
 .....     
>Q7VBP5_PROMA
 ......QDMR DFLSLLEKKG QLRRISKPVD PDLELAAISD RVLSMGGPAL
 LFENVIGSSM PVAINLLGTI ERVVWSMGLS SQDELEGLGK KLSYLQQPEP
 PKGIKKTIEF GGILWDLLQA RPDLDLTPPC HQRLLKGEDV NLDKLPLIRP
 WPGDAGKIIT FGLVITKDPE TNTPNVGVYR LQQQSINTMT VHWLSVRGGA
 RHLRK..ASA MGKKLEVAIA IGVHPLILMA AATPIPVTLS EWLFAGLYAG
 KGVRLSNCKT VNLQVPSHSE IVLEGTIAPG EEMNDGPFGD HMGFYGGIEK
 SPLIRFHCIT SRKDPIYLTT FSGRPPKEEA MLAIALNRIY TPILRRQINE
 ITDFFLPMEA LSYKLAIISI DKSYPGQARR AAMAFWSALP QFTYTKFVVV
 VDSTINVRDP RQVVWAISSL VDPQRDLLVM ENTPFDSLDF ASENIGLGGR
 LAIDATTKVG PEKNHEWGNP LIHSSNLSKK IDERWNELGL SDL.......
 .....     
>Q2JUS0_SYNJA
 ......RDLR RFIALLESRG QLRRISAEVD PDLEIAEIAD RLLACGGPAL
 LFERVKGSSM PLLINVLGTV ERICWALGME QPRELEELGK KLALLYQPRP
 PKNFAQALEL GQALFRVFQA RPSRDLFPPC QQVVLLGEAV DLTQLPLLRV
 YPGDAGRVLT LGLMVTKDPE NGIPNVGVYR LQLQSRNTMT VQWLSVRGAT
 RHLRK..AAA LGRKLEVAVA IGVDPAVILA AATPLPVDLS EWLFAGLYAG
 EGLHLARCKT VDLEVPAHAE IVLEGTITPG EVAPDGPAGD HIGYYGPRNE
 QPLIRFHCLT HRRDPIYLTT FSGKPPKEND MMALALNRIY TPILRQQVPE
 IVDFFLPMEG LGYKVAILSI DKAYPGQARR AALAFWSALP QFSYTKFVIV
 VDKDINVRDP RQVLWCLCSR VDPQRDVFIL PDNPFDALDF ATEKRGLGGK
 MGIDATTKLP PETDTPWRQP LAPDPQVARL VDRRWAEYGL ADL.......
 .....     
>Q7NCG9_GLOVI
 ......RDLR TFLQLLESRG QLRRISAPVE RDLEVAEIAN RLLAAGGPAL
 LFENVKGSPF PVAVNLLGTV ERVVWSMGLE EQQQLEALGE KLGKLQKPRP
 PRSLQDALEF APLLFDVIKA RPGRVLFAPC QQVVLEGKAV DLDRIPMIRP
 YAGDAGRILT FGLVITHDPE DGTPNVGIYR LQQQSRDTMT VHWLSVRGGA
 RHLRK..AAE RGQKLPVAIA VGVDPLLVMA AATPIPVELS EWVFAGLYAG
 EGVQLAQCRT SDLLVPAHSE FVLEGTITPG EVLPDGPFGD HMGYYGGVED
 SPLVRIHTVT HRHDPIYHTT FSGRPPKEEA MIAIALNRIY TPLLRAQVPE
 VRDFFLPMDA LSYKLAVLSI KKAYPGQARR AAMAFWTALA QFTYTKFVIV
 VDEDIDIRDP SQVVWAIASK VDPERDLFVI PRTPFDTLDF ACERIGLGAR
 LGIDATTKIP PETDHAWGEP LRADPATAEQ VSKRWAEYGL ..........
 .....     
>Q2DYL3_ACICE
 ...MPFADLP EFLDALERDG DLVRITAPVD PYLEITEIVD RVVRNGGPAL
 LFENVIGYDM PLAMNVFGTP RRMAKVFGA. ..AELDDVGR RIAGLLQPGL
 PQGFAGVRDV FSRAMQLRAV PPKRVRSGAC QDIVLRGEDV DLTRLPALHT
 WPKDGGPYFT LGLTHTKHPE TGQRNVGLYR LQRFDRRTIG MHWQIHKDST
 AHHA..VAER RGERLPVAVA FGCDPVLSYV ASAPLPADID EYAFAGFLRG
 ERVELVECVS VPLEVPASAQ VVLEGWIEPG ERRPEGPFGD HTGFYTPVEP
 FPVLHVETVT MRKTPIFQAI VVGRPPAEDA FLGKATERIF LPLVKLLIPD
 IVDLDLPIEG VFHNCVIVSI EKRFPKHAHK VMHAIWGA.G MLSLAKLIVV
 VDADCNVHDY RDVAWRAFGN VDYAHDLVQA VG.PVDHLDH ASYQQFWGGK
 IGIDATAKLP GEGHRGWPEM IVQDRDIVER VSRRWAEFGL P.........
 .....     
>Q82E07_STRAW
 ...MAYDDLR SLLRALEREG DLKRIKAEVD PYLEVGEIVD RVQKAGGPAL
 LFENVRGSAM PLAMNVFGTD RRLLKALGLK S...YGEITD KIGGLLKPEL
 PHGFVGVREA FGKLGAMTHV PPRKVKDAPV QEVVLRGDDV DLDQLPALFT
 WPQDGGSFFN LGLTHTKDPE SGIRNLGLYR LQRHDKRTIG MHWQIHKDSR
 NHYQ..VAAR RGERLPVAIA FGCPPAVTYA STAPLPGDID EYLFAGFIQG
 KRIEMVDCKT VPLQVPAQAE VVLEGWLEPG EMLPEGPFGD HTGFYTPQEP
 FPALKIDCVT MRKRPLLQSI VVGRPPTEDG PLGRATERFF LPLLKIIVPD
 IVDYHLPEAG GFHNCAIVSI DKKYPKHAQK VMHAVWGA.H MMSLTKLIVI
 VDSDCDVHDL HEVAWRALGN TDYARDLTVV EG.PVDHLDH ASYQQFWGGK
 AGIDATRKWP EERDGGWPEM VLSDAETAAK VDRRWKEYGL ..........
 .....     
>Q89D16_BRAJA
 .DVPRFRELS DFLRFIEGKG QLRRIREPVS VVHEITEIHR RVIGEHGPAL
 LFERPIPSGM PLLTNLFGTV ERTAWGMGIT PDR.LEELGA MMAELRAPRP
 PHGVRDAWRK LPLARAALAT RPRSRAAAPV QDRAAMGEDI DLTKLPAQIC
 WPGEPAPLIT WPLVITAPPA SPAANVGVYR MQILGRDRAI VRWLAHRGGA
 RHHQQWKAV. .GRDMPVAIV IGADPATILA AVMPLPETIS ELRFAGILRG
 ERPELTPCLT VPLEVPATAE IVIEGFVSAT ETAAEGPYGD HTGYYNSVEQ
 FPVLRVTAIT SRQQPIYLST FTGRAPDEPS RIGEALNRLF VPLIRQQFPE
 VTDCWLPPET CSYRVAIASI KKRYPGQARR LMLGLWSMLP QFSYTKLLIV
 VDDDIDIRDW REVMWAVATR SDSSRDLVAL SDTPIDYLDF ASPKSGLGGK
 LGIDATTKMP PETEREWGEP LAMDSAVIAK VDAMW..... ..........
 .....     
>Y1612_AQUAE
 ....KYRDLH DFIKDLEKEG ELVRIKEPLS PILEITEVTD RVCKGGGKAL
 LFENPKGYRI PVLTNLYGSE KRIKKALGYE N...LEDIGW KLYRILKPEV
 PKTFLEKIKK LPELKKLNDA IPKVVKRGKV QEEVIMGD.I NLEDLPILKC
 WPKDGGRYIT FGQVITKDPE SGIRNVGLYR LQVLDKDKLA VHWQIHKDGN
 HHY..WKAKR LGKKLEVAIA IGGEPPLPYV ASAPLPPEVD EYLFAGIIME
 RPVELVKGLT VDLEYPANAE IAIEGYVDPE ELVDEGPFGD HTGFYTPVDK
 YPQMHVTAIV MRKDPIYLTT IVGRPPQEDK YLGWATERIF LPLIKFNLPE
 VVDYHLPAEG CFHNFCFVSI KKRYPGHAFK VAYALLG.LG LMSLEKHIVV
 FDDWINVQDI GEVLWAWGNN VDPQRDVLIL KG.PIDVLDH ATNEVGFGGK
 MIIDATTKWK EEGTREWPEV IEMSPEVKKR IDEIWDRLGI E.........
 .....     
>Y209_ARCFU
 ...MAYEDLR EFIGRLEDKG ELARVKHEVS PILEMSEVAD RTVKAGGKAL
 LFERPKGYDI PVFMNAFGTE RRMKLALEVE R...LEEIGE RLLSALEFR.
 PSSFMDALKG VGMLKDFMSF IPKKTGKAPC KEVVAE.... SLDKFPILKC
 WPKDAGRFIT FPVVITKDPE TGEMNAGMYR MQVFDGKTTG MHWQIHKHGA
 EHFRK.MAEK GGGKIEVAVA IGVDPATLYA ATAPLPSGIS EFMFAGFIRK
 ERLKVTECET VDLLVPANAE IILEGYVRVD EMRVEGPFGD HTGYYTPPEP
 YPVFHITHIT HRENPIYHAT VVGKPPMEDA WLGKATERIF LPILRMMHPE
 IVDINLPVEG AFHNLAIVSI KKRYPGQAKK VMYAIWGT.G MLSLTKIVVV
 VDDDVNVHDM REVVWAVTSR FDPARDVVIL PPSPTDSLDH SAYIPNLAGK
 LGIDATKKWR DEGEREWPDV VEMDAETKRK VDAIWNEI.. ..........
 .....     
>Q44AI8_SOLUS
 ...MAYQDLR EFVRALEKNN ELKRIKVEVD PILEITEFAD RAVKQGGPAL
 LFENPKGYKI PVLINSFASM RKMELAL... EVKSVEEVAQ RIVEFLEMRM
 PEGLIGKLKM LPKLAEMGAF FPKIVGKGPC QEVVKT.DGF SLLDFPVLQC
 WPDDGGRYIT LPLVFSRNPE TGKRNCGMYR MQVYDERTAG MHWQTHKQGA
 EHARRMQHQG K.KRMDVAVA IGADPATMYS AILPLPPDLD EMMISGFLRG
 SPVEMVKCQT CDLEVPANAE IVLEGYVELG ELRTEGPFGD HTGFYSLADE
 YPVFHVTCVT HRKDPIYVTT IVGPPPMEDY YMGKAIERIF LPLMRMQLPE
 VRDISMPAEG IFHNLILVSI RKSYPGHARK VMHSIWGT.G QAMFSKVIVV
 VDEDVDVQNY SEVAWKAFNN IDPERDIQFV MG.PVDSLDH ASRLVNYGSK
 MGVDATRKWP GEGTRPWPDV ITMDSEVKRR VDDLWKKAGL ..........
 .....     
>Q2JFP3_FRASC
 MELMAWADLR AFLAHLERRK DLRRVTVPVD PRLEVTEIVT RVVRERGPAL
 LFESPAGADM PLAINVFGTE ERMAAALGVE ...ALDDIGE RLGALLRPQL
 PIGLSGLREA FGKAASLASV PPRRVRTAPC QDVVLKGPDV DLFRLPGVHA
 WPNDGGAFLN LGLTHTKHPE TGARNLGMYR LQRHDARTVG MHWQIHKDSN
 AHH..AVAER RGERLPVAIA FGCDPAVTYA ASAPLPADLD EYLFAGYLRG
 ERVEMVDCLS VPLRVPANAQ VVIEGWLEPG ERLPEGPFGD HTGFYTPVEP
 FPALHVDVMT MQRDPVFQTI VVGRPPQEDG PMGKATERIF LPLVRMMIPE
 IVDYDLPEAG VFHNCCIVSI EKRYPKHAQK VMNAVWGA.G LLSLSKLIVV
 VDADCDVHDY HEVAWRAFGN VDYAHDL.IT TIGPVDHLDH AAYEQFWGGK
 VGVDATRKLP SEGYRRWPEE IVMDEAVRER VTRRWKEYGL ..........
 .....     
>Q3XLE5_9PROT
 .DPKHFKDLS SFCDFLESQG ELVRIREEVD PHLEMTEIST RLLAEQGPAV
 LYERVSGYAM PVLNNLFGTE RRVGLAIGAD .LHQLEELGE LLAYLRQPDP
 PGGVGGLLGT ARKLSSVRHM PTRSKKSAPW QQVVYQGAAV DLTRLPIQGC
 WPGDVAPLIT WPVVITRGAD QGAVNLGIYR MQLLGKNRLI MRWLKHRGGA
 QHSRSYR... ..KPMPVAVA IGCDPGTILA AVTPVPDTLS EYAFAGLLME
 QSVTVVTGQE SGLPIPYSAE IVLEGTVDLN DLADEGPYGD HTGYYNEVER
 FPVFTVQRIS MRRNAIYLST HTGRPPDEPS VLALALNRVF VPLLKKQFPE
 ISAFHLPAEA CSYRVAVIAI NKQYAGHAFR MMAGVWGFLR QFLYTKYLIV
 VDSSVDCHNW DAVMAAVGRH VDARRDLQQL TNTPIDYLDF ASPVAGLGGK
 LGLDATRKSG AE........ .......... .......... ..........
 .....     
>Q3J0P5_RHOS4
 .....FPDLR AFLDWCARKG DLSRIAEPVS LRHETTAVAS KILRGGGPVL
 RFESLRDTSM PLVANLFGTR ERVAAGLGL. GLEQIPELGA FLAALRAPAP
 VAGMRDALSR WPQLQAALNT RAKIVRSAEA QEVVHEGAAV DLGMIPVPTC
 WPGDAGPLVT WPVVLTRPEE TLHYNAGVYR AQVIGRDRLI MRWLAHRGGA
 GHCRSWM..R AGEPMPVALA LGCDPALLLA AALPLPEQVS ELTFSGVLRG
 ARTPLVAGRT VPLMVPATAE IVVEGWVHPG DMAPEGPFGD HTGYYNSVED
 FPVLRVSAIT HRKDPLYLTT HTGRPPDEPS VIGEVFNDLA MPVFRQQIPE
 VKDLYLPPAA CSYRIAIVSI DKRYPGQARR VMMALWGMLA QFSYTKMVIV
 VDEDINPRDW DDVAWAMATR MDPSRDVVLL EKTPMDYLDF ASPEPGLAGK
 IGIDATNKIG PETHREWGEV MTQSPEAEAF ADRLIAKLRI ..........
 .....     
>Q2RMA5_MOOTA
 ...MAHQDLQ AYLAYLEAHK LLHRVKVEVD PIFEIAAISD RVVKRGGPAL
 LFERVKGSTL PVATNLFGSI DLVKAALEVT DLEEPAR..R LRALLELPAD
 SGGWLDKLRF LPRLAELGRY LPRRVKEAPC QEVRVEP..P SLEELPVLQL
 WPGDGGRFLT LPLVFTHDPL TGRRNVGMYR MQVFDAVTTG MHWHIHKDGA
 EHLR.....R SGDRLEVAVA LGADPAVIYA ATAPLPPGLD EMLLAGFLRR
 EPVEMVPALT VNIDVPARAE IILEGYVDPG ETRLEGPFGD HTGYYSPADN
 YPVFHLTCLT RRRRAVYPAT VVGPPPMEDA YLGKVTERLF LPLIQLQLPE
 VVDINFPPAG VFHNCVIVAI RKAYPGQARK VMHALWGM.G QMMFTKLIIV
 VDADVNVHDL QEVAWRVLGN IDPRRDAVIV .DGPVDILDH AAPRRGFGSK
 MGLDATRKLP EEGSRPWPEE ARAAREVLEL IDRRWQEYGL ..........
 .....     
>Q3N0M8_9DELT
 ....AFRNLQ DFIADLERAG ELLRIKAPVS SDLEITQITD LASKSGGKAL
 LFENVEGSRF PVLTNAFGSE RRICMALG.. .VSHLDELAR RLKSFIEMKP
 PKSLADALRL IPLGLELLRF LPRKTRKAPC QEVVTTGRDV DLSMLPVLKC
 WPSDGGPFVT LPVVITRSLV TGKRNAGMYR LQVYDRKTTG MHWHIHKDGS
 HYFQEF..RE RGKRMPVAVA IGTDPAVTYA ATAPLPRGID EMMLAGFIRR
 KPVPMVRCLT VDLEVPAESE FVLEGYVDPG ELRVEGPFGD HTGYYSLVGE
 YPVFHVTALT HRRNPVYFAT VVGRPPMEDC FLAKATERIF LPLLNAVFPE
 IGDYWMPWEG VFHNITVLSI RKEYPGHARR MMSAIWG.QG QMSFCKAAVL
 ADPSVDLGHP RRVLEHILNN IDIESDITL. SEGILDVLDH SAPEPLFGSK
 IGIDATRRLP GEKERPAARP VGALPD.... .......... ..........
 .....     
>Q2IMW7_ANADE
 ..AMAYRSLR EFLARLDEAG ELVRITEPVH PVLEMAALAD RAAKQGGPAL
 LFERPG..TL PVAMNLFGTR RRASWALSCE D...FEEHAS ELRALLRTAP
 PQSFWDKLKM LPKLGKLAAM APKHVSSGAC QEVV..DREP DLRTLPVLTT
 WPHDGGPFIT LPQVITRDPE TGIRNVGMYR LQVLGPRRLA MHWQLHKTAT
 AHYRAYQQ.. RGERMPVAIA LGGDPALTYC ASAPLPPNVD EYLFAGFLRG
 ASVHTVTGVA TGLDVPADAD LVIEGFVDTA ALVREGPFGD HTGFYSLADD
 YPALDVVAIT RRKDAVYPAT VVGPPPVEDQ WLGKATERMF LPLMQIVAPE
 IVDICMPVEG VFHNLCLVSI KKEHPGQAKK VIHGLWGS.G QMAQTKTLVV
 FDEDVDVQDV SQAAWRAFAN VDVKRDL.VI ADGPVDVLDH AASGFAYGGK
 IGVDATRKWR EEGGREWPEV CVHPPEVIAR MDALYDRL.. ..........
 .....     
>Q97BP5_THEVO
 ...MTFEDLH EYLDYLAKKN DLVTITEEVD PNLDLTYILS EEERMGGRTI
 LFKNVKGSQV PAVGNLFSTN EKLKAVLGDD PYSIGVKIAD I...VKPPRD
 SESF..IGKG LEMMRELSGL RPKVSNSIPS GYSELE..KV DLYRYPICKT
 WPDDGGPFIT LPLVITKDPS TGIRNMGMYR MQVYDSETTG MHWHIHKGGS
 ENFLKEK..E KGKAMDVAVV IGSDPLTIFS AVAPLPNGID EFMFRGLISR
 KRSELVKGKT VDLEYPRNFE IVLEGYIDPS ETRVEGPFGD HTGYYSLEEE
 FPVFHVKNII ERNDRIYPTT IVGKLWHEDV VLGKAVERMF LPLIQMVLPE
 VVDINTMEEA VFHNMVIVSI KKRYPGHAKK VMFALWG.LG QLMFSKIIVV
 VDDDINIHNR KELIWAMTTR IDPDRDVIII PGTVTDSLDH AAPLFNYGSK
 MGIDATKKDK SEGTRRWPDV LEMPKDVVDK VRQIMK.... ..........
 .....     
>Q6L2Q2_PICTO
 ...MVFDNLG EYLNFLRERN DLVEVNDPVD TDLELTWILS EEQRIGKRSM
 IFKNVNGYDI PVAGNLFASD EKIEYILGDK PFNIG...TK LKNLVRIPDN
 TESM..ISRG LEMLKELSGL KPHIGSRKDS EFNVLE..KV DLNRYPICKT
 WPDDGGKFIT MPMVITKDPE TGQRNVGTYR MQVYDSETTG MHWHIHKGGA
 EQMSKYK... ..KPMDVAVV IGSDPLTFFS SVAPLPNGID EFSFRGLLAR
 KRMDLIKGET VDLEYPRNSE IVLEGYVDPS ETRLEGPFGD HTGYYSLQEQ
 FPVFHIKKII EKKNPIYTTT IVGKLWHEDV RIGKAIERLF LPLIQIQIPE
 IVDLNTMEEG VFHEMIVVSI KKRYPGHAKK VMFSIWGT.G QLMLSKIVVI
 VDDDINIHDR SQVLWAIATR VDPASDVLII PGTLTDSLDH TARTFNYGSK
 MGIDATKKLK GEYNRTWPDV LSMTGDIEKK ADDIISKL.. ..........
 .....     
>Q9RXI1_DEIRA
 ..ARQFPDIQ SFMRVLEERG ELLRVREPVS RDLEITEISD RLVKKGGPAV
 LFENVVGSDY PVVMGLMGTR ERMALAVGVN D...LDELAQ KIRALIDLGG
 GGSRFGLLSN LPKLRDAMNL PPRRVKTAPV QEVVWRGDEV DLSKIPVLKC
 WPEDGGPFVT FPLVITKDPE TGERNMGMYR MQVMSKNTTG MHWQRHKTGT
 RHLEK..ARQ RGQRLEVAVA IGGDPALIYA ATAPIPPGLN EFAVAGYLRG
 QRYPVVKGLT VDLEVPANAE FVLEGYVDPQ EWVVEGPFGD HTGFYTLADL
 YPLFHVTCVT MRQNPVYPAT IVGRPPMEDA YLIEASERLF LPAAQLIVPE
 IVDYHMPPAG VAHNLVVVSI KKDFPGQAYK VANGLLG.LG QMMFAKVIVV
 VDADVKVNDM DAVWREVAAK AVPGRDTL.T GRGPIDVLDH SSRGWGYGGK
 LIIDATTKRP EET....... .......... .......... ..........
 .....     
>Q3WKI0_9RHIZ
 ....SFADLG SFLSLLESRG QVQEIDASVS MQLEITELHR RVIAAKGPVL
 RLSKPRASRF PVVTNLFGTT ERVASGLGT. NLAGLKTLGE LLAWMRAPRP
 PTTLREARLM LPAARGALLA RPRIVTPS.. ..RNWHDAER DFSILPVQRC
 WPDDAGPLIT WPVVVTRPPD PAAYNLGVYR MQVISPDRAI LRWLPMRGGA
 AHHWLWQAQA A..EMPVAVI IGADPATMIS AVMPTPDGVS ELALAGMINN
 RRMAVAPCAS IPLHVPASAE IVLEGVVSPG DMALEGPFGD HTGYYNAPAS
 YPVFQLKRIC VRDDAHYLTT CTGRAPDEPS VLGEALIEVF KPLLRQQIPE
 IVDAWLPPEA CSYRIAVVSI AKSYPGQARR VMMGFWSLLP QFSMTKLVIV
 VDDDIDIRSW PDVMWAIATR MDPSRDLMRV DRTPIDQLDF ASPLEGLGGK
 LGFDATRKIG SETSREWGKE LRMSTDIERQ VSLRWTEF.. ..........
 .....     
>Q3P8C6_PARDE
 ....SFPDLR AFLSWLEARG ELARIAEPVS LRHEMTAVQL ACLRRGGPAL
 RFDRPQGARI PVVANLFGTR ARVAAGLGLQ PDE.IAGFGE FLAALRSPAP
 VEGMRDAMSR WPMLRAALAT RPRLLRHGPV QEEELPG... .LDSLPVQTP
 WPGDGGPLIT WPVVLTRPQD STRYNLGVYR AQVLAPDRLI LRWLAHRGGA
 AHHRSW..AR AGEPMPVAIA LGADPALLLA AALPLPETVS ELGFSGVLRG
 ARSELVAAQT VPLMVPARAE VIVEGWVHPG ETAPEGPFGD HTGYYNAVEP
 FPVMRVSRIT CRSDPLYLST VTGRPPDEPS VIGEVFNDLA LPVIRAQIPE
 ITDLWLPPAA CSYRMAVVAI DKRYPGQARR VMMALWGMLP QFSYTKLVVV
 VDRDIDVRSW DDIAWAISTR MDPGRDVMLI DRTPMDYLDF ASPVEGLAGK
 LGLDATTKIG AETAREWGRV MQLDPKHEAR AEALLD.... ..........
 .....     
>Q4H950_9DEIO
 ......PDLQ SFLRLLEERG ELVRVSIPVD RELEITEIAD RLVKQGGPAV
 LFEHVKGSPF PLVIGLLGTR ERTARALGVA D...LDDLAR KVRHLMDLKG
 GGGLSGLLGN VGKLRDALHL PPRRVRSGPA QEIIWTGDEV DLSKLPVLKC
 WPLDGGPFIT LPLVMTRDPE TGERNMGMYR MQVMGRNVTG MHWQRHKTGT
 RHLEK..ARR LGQKLPVAVA LGGDPALIYA ATAPLPPGLD EYALAGYLRG
 ERYPVMRGVT VDLDVPANAE FILEGYVDPE EWAVEGPFGD HTGFYTLPDR
 YPRFHVTAIT MRRNPVYPAT IVGRPPMEDA YLIEASERLF LPAAQMILPE
 IVDYHMPPAG VAHNLVVVSI KKSYPGQAYK VAQGLLG.LG QMMFAKVVVV
 VDEDVQVNDF AAVWREVTAR AVPGRDTL.I TRGPVDVLDH SSRGWGYGGK
 LIIDATTKLP EESREELGRE GRVEPLFVPR V......... ..........
 .....     
>Q41SR8_FERAC
 ...MTFDDLK EFIKYQESNG DLVRVNEEVD PELELTYILS EEERIGKKTM
 LFNNVKGSKM PVIGNIFSSD KKIEAILGDT PYNIG...LK LKNLVRIPDD
 TESM..ISRG LEMLKEMSGI KPKVYNRKNS EFEVVE...P HLSDYPITKN
 WPGDGGRYIT MPVVMTKDPD TGTRNVGTYR MQVYDDETVG MHWHIHKGGA
 EHMDKYRNE. .GKIMDVAVA IGVDPLTFFS SIAPLPNGID EFSFRGILAK
 KHLELIKGET VNMEYPRSSQ IVLEGYIDPS ETRIEGPFGD HTGYYSLEEA
 FPVFHVKKVV QKLEPVYSTT IVGKLWHEDV RIGKAIEKMF LPLIQIQIPE
 IVDMNIPEET VVSNMIVVSI KKRYPGQAKK VMFAIWGT.G QMMFTKIVVV
 VDDDVDVHDM KQVMWAMTTR IDPVNDVFMV PNTPTDSLDH PARLFNLGSK
 MGIDATKKSP AEYNRPWPDT LSMTPEIERK ADELLKKL.. ..........
 .....     
>Q97ZL5_SULSO
 ...MAFKDLR EYIEFMKKKG KLIEVDDEVS VDLEIAEITR KATYAHLPPL
 LFKRVKNYEW KIVSNIFYSI ESLYEIFGTN KLESISE..G FLSNLSNM..
 PITFFDKIKS LREILGLGKV MPK.AKSPSF KE....EKNL DLTKIPAIKT
 WPKDAGRYLT FSITITKDPE TDVHNLSVYR VQILNEKEAI IHWQAFKRGA
 LTAKKYLEKG ISK.IPIAVV TGVDPAIAFT AASPVPHGID KYMFAGILRG
 EGIDVAE.LD NQLLVPSHSE VVLTGYVDLN DMRLEGPFGD HMGYYTPADY
 YPVFKLERVY IREDPIFHVT SVGKPPLEDA WIGKAVERIF LPFAKMLVPE
 LIDMNLPEYG LFTGIGIFSI KKYYPGQAKR VMMALWGT.G QLSLLKIIIV
 VDQDIDVHDI NQVIYAIAAN VDPKRDVWVI ENALTDSLDP SVPFPPLGSK
 LGIDATRKFK EEMGKEWPEE VRSDEVVAKK ADQILNKI.. ..........
 .....     
>Q2DMF9_9DELT
 ...MAYRCLH EFLARLEEMG ELHRVTVEVD PVLEIAEITD RMCKSGGKAL
 LFERVKGSAF PVATNLFGSY RRVCEALDIS ELGQLSRLME ELLPLQPASS
 GQTIDDLHS. ....PALSRF TPLLANNGDC QAVA..DYSP DLRKYPLLKS
 WPGDAGRFIT LPLVFTRDPE TGTQNCGMYR VRVFDENSAG MHWNPGSGGA
 GHYGKYQS.. RGERMPIAIA VGGDPALIWS ASLPLPGAVD EMAFAGYIRN
 EPVSMVRCLT SRIMVPANTE MVIEGYLDPG EVRDEGEFGN HTGYYTTAGN
 VPVVHVTCIT HRNGMIYPAT VVGPPPMEDC YLAKATERLL LPLSRRQVPA
 IVDINLPMEG IFHGCAVVAI QKEHAGQARQ VVQELWRT.G WLRKAKLLVV
 VDADVPVNDL SLVGWKVVNN AEWPRDLIIA D......... ........GR
 MGLDATGKLA EETDGIRRQE IRKDEVISKL VERKWREYG. ..........
 .....     
>Q971Y9_SULTO
 ...LAFSDLR EYINYLRSKK KIIEIEDEVD PILEIAEISR RATYSKLPPL
 LFKNIKGYPW SVITNIYYSI EAFYDLFNTN K...LEEITE SFLDKMSGSL
 PVSFSNKIRN LFDILKLGKI LPKSKKPA.. ...FKEDNNL NFNKIPALKT
 WPKDAGRYLT FSILITKDPD TGVHNLSVYR IQLLNEREAI VHWQALKRGS
 LTAFKYKEKG ITK.IPAVIV NGVDPILAFV SASPVPPGLD KYLFAGILRN
 EGVEVHE.LD NGILVPSTAE TVFEGYVDLN DLRLEGPFGD HLGYYTPQDY
 YPVFKLERTY SRDNPIFHAT SVGKPPLEDA WIGKAVERLF LPFIRILIPE
 IVDMNLPEFG LFTGIGIFSI KKHYPGQAKK TMMSIWG.LG QLSLLKMVII
 VDADVNVHDL NEVLYAITTT VNPSRDVVII DNIITDSLDH TTPSPPLGSK
 IGIDATRKFK EELGKEWPEE VSSDENVVKR IMPLWEKI.. ..........
 .....     
>Q5SLC0_THET8
 .....FRNLR AYLEALERRG ELHRVRVPVS AELEIAEIAD RVVKAGGPAL
 LFERVVGKDF PVAIGLFGTR ARTAFALGVE DLDELARKVE ALLALEP..G
 KGGLSALLGL LPKLPLLRGF FPRRVRRAPV QEVVWRGEEV DLRRLPVLKC
 WPLDGGPFLT LPLVITKDPE TGELNLGMYR MQVLDPRSTA MHWQLHKVGR
 RHLEK..AKR LGRKLEVAVA LGGDPVLTYA ATAPLPPGVS EFHLAGFLRG
 APIELARGVT VDLPVPAEAE FVLEGYIDPE ELVEEGPFGD HTGFYTPVDL
 YPRFHVTAVT HRKGAIYPAT LVGVPPMEDA YLIEATERLF LPALRLVLPE
 VVDYHMPPEG VAHNWVNVSL RKAYPGQAYK VAYGMLG.LG QMMFAKVIVA
 VDADVPVKPG FAALLEALKH ALPGRDTLLL .RGPVDVLDH SSRAFAFGGK
 LVIDGTRKLP EEG....... .......... .......... ..........
 .....     
>Q4J8Y6_SULAC
 ...MGFKDLR EYIEFLRRNK NILEISDEVS TELEIAYLTR EATYSKMPAL
 LFTNVKNFPW KVITNIFNSL NVFYNIFGSN KLEEIS..GK FLDEFLG.QL
 PTTFFEKIRS FAEMSKLGKV FPK..SKKPV FE...LHEEY SLDKFPALRT
 WPKDAGRYFT FSITITKDPD TEVHNLSVYR IQLVNQKEAI VHWQAFKRGS
 ITANKYLKKG ITK.VPVAII NGVDPITTFV AASPVPPGLD KYLFAGILRQ
 EGVEVTR.LD NGILVPANAE SVIEGYVDLN DVRLEGPFGD HLGYYTPADF
 YPTLKVERIY VRDQPIFHAT SVGKPPLEDA WIGRAVERLF LPFLKMIVPE
 LVDMNLPEYG LFTGIGIFSI RKTYPGQGKR AMMALWG.VG QLSLLKMIIV
 VDEDVNVHDI NQILYAISST VDPKRDVLIV DNVLTDSLDH TTPHPPLGSK
 IGIDATRKFR EEVGREWPEE VSDDPEVVKR MEKILKKI.. ..........
 .....     
>Q8ZWD1_PYRAE
 .....FSDLR EFLKALEERG WLKRVSEPLS PELEIPEVLR QVMYARGPAV
 LFESVRGFPW RVVGNLFGSL DRIRLALG.. ...ELEEAGR RLLEPMASPP
 PLTLADKFRA AVELFELGRY APRAVRGGPV KEVV...EEP NLLSIPAFKT
 WPKDAGQYIT FGVLITRD.S RGVYNLGVYR VQILNEREAV VHAQIHKRAA
 DLF....ASS PG.CVDAAIA IGGDPAFLLS GIMPTPYPLD EYLFAGVLRG
 GGLEVTKGVA TDLYIPARAE AVIEGCVDVK DLRREGPFGD HYGVYDQGGL
 YPVFKAKALL RREDPIYYGT VVGRPPLEDA YMGKAVERVF LPVLRFLLPE
 VADLNLPEFG LFQGIAIVSI KKRFPGHGKK VMFALWGLGH MMSLTKVVIV
 VDHDVNVHDL NEVLFAVAQR VDPQRDVVIV PGAHVDVLDT GSPVPGYGSK
 LGIDATRKLP EEGGRPWPEE VAPDPEVAAR VKAVVEQL.. ..........
 .....     
>Q7M8N0_WOLSU
 ........MR SYLDLLKEHN LLRVIDEPLD IHLEIPHIAY VEVKKESKAL
 LFTRPKEFET PVVMNLFGSE ELVKILVG.. ...EVEEIAQ SVGEFVQFKP
 PKGWAQTLAM LPKLARLRHV VPKKLKKGLC QQVIKQGEEV DLYELPILTT
 WEKDGGPFIT MGQVYTQDLE GRVQNLGMYR LQLYEKNRLG LHWQIHKDST
 HFFNQYKAA. .GQKMPVSIA IGGDPLYTWC GTAPLPYGVF ELLLYGFIRG
 RRAELVSCLT NPLFVPFDAD FVIEGWVDTS KMRLEGPFGD HTGFYTPIEP
 YPELEVSAIT HKKNPIYVAT VVGKPPLEDK YLGYPTERIF LPLLKTTAPS
 LIDYYMPENG VFHNLILAKI APSYPGHAKQ IMHAFWG.VG QMSFVKHALF
 VDEDAPLRED EALMNHVLAR FHPSR..LLL SDGVCDALDH ASPEYALGGK
 LGVDAT.... .......... .......... .......... ..........
 .....     
>Q74G15_GEOSL
 ...MANGDLH DFLAELERLG DLHRVAAEVD PVLEVAAITD RVSKGGGKGL
 LFERVKGSRF PLVTNVFGSA GRVAAALGA. ..ATLDDLTA RMESLLAAVP
 PAKTASPLEA MASLAEMRRF APMIVEKAPC QEVV...EAP DLLRYPFPHS
 WPGDGGRFIT LPLVVTRDPE TNTPNCGMYR VRVVDGASAG IRWYAGKGGE
 LHCRRH..RE RGERMPVAVA IGGDPAAILA AILPLPEGFD EMLFAGFLRG
 RPLELARCRT SDLLVPAGAE LVLEGYVEPG ETVMDGAFGN HTGFYAPAAS
 VPLMRLTCIT RRADCLCPAT VVGRPPMEDC YLAKAAERLL LPVLRMRWPE
 IVDINYPLEW IFNGGAVLSL RECSSSRVRR IVTELWSS.G LAGPGRLLVA
 VDEGTRVDDP ADVAWRAMNA VDWRTDLIIA ER......DA AAAWPGLGSR
 LAIDATRSAA ...RRYGAEE LVPDRETARR VDSRWREYGF ..........
 .....     
>Q7VIV7_HELHP
 .......DSH QLITFLQSHN ELTIIDEPLD IYLQIPQLAY LEVKKTSKAL
 LFTNPKTFDI PVLMNIFGSH QRLNLLVDKP IPQIATHIQH LLRF....SP
 PKGIKEIFSR LKELAHLRFV FPKTKSKGLC QDTIIIGEEI NLFNLPILTT
 WEHDGGAFIT MGQVYTQSID GKAKNLGMYR LQVYDEKHLG LHWQIHKDSQ
 HFFHQYKQA. .GEKMPVSIA LGGDPLYIWC GQAPLPMGIF ELMLYGFIRS
 KKPVLCPCIT NPLFVPNDVD IVIEGWVDTT QMRDEGPFGD HTGFYTPIEP
 YPVLEVSAIT MRKKPIFPAT IVGKPPLEDK YMGYLTERVF LPLLQTTAHG
 LKDYHMPENG VFHNLIFAKI KPDYPSHSKQ IMHNFWG.VG QMSFVKHAIF
 VDENAPLTDY EALGTYILER FSPN..NLLI TEGICDALDH ASPHFAHGGK
 LGVEAI.... ........TP VHKPSFIALN DECLWKKFAP LFPQATALKQ
 YFTH.     
>Q8F3S3_LEPIN
 ...MKIKSTS EFVKELQIQN ELLIIEEEVD PILELAEIQR RVVAKRGPAI
 LFKNVKGSRF SVVTNLYGSE RRMKIAFGEE PVRFIRKIAT TIQHILPPTP
 AK....IWDL RNIAFQVLKV GLKRVGSAPV LENTLD.... SLYELPTLMS
 WPKDGGRFVT LPLVYTESPK TGKGNLGMYR IQIYGPMETG MHIQIHRGGG
 NHY..YEAEK EGHFLPVHIY AGGPPALTIA AVAPLPEEIS ELILASLLLG
 EKLKIQKNTN VPLPVVADAD FLIQGVIPPK IRKPEGPFGD HYGYYALKHD
 YPIVQVKRIY HRKNAIWPAT VVGRPPQEDH WIAEYLQDLL SPLFPVVMPA
 VKKVWAYEES GVHSLAAAVV KERYQGEAFT GALRILG.EG QLSLTKVLFI
 TDQDVDLKNF RETFITVLER MNPITDLHIF ANISQDTLDY TGPAVNQGSK
 AIF....... .......... .......... .......... ..........
 .....     
>Y396_HELPY
 ........MR DFLKLLKKHD ELKIIDTPLE VDLEIAHLAY IEAKNGGKAL
 LFTQPKTFGM PVLMNAFGSF KRLDLLL... .KTPIESLQQ RMQAFLHFNA
 PKNFTEGLKV LKDLWDLRHI FPKKTTR.PK DLIIKQDKEV NLLDLPVLKT
 WEKDGGAFIT MGQVYTQSLD HQKKNLGMYR LQVYDKNHLG LHWQIHKDSQ
 LFFHEYAKAK V..KMPVSIA IGGDLLYTWC ATAPLPYGIY ELMLYGFMRG
 KKARVMPCLS NSLSVPSDCD IVIEGFVDCE KLELEGPFGD HTGYYTPIEP
 YPVLEVKTIS YKKDSIYLAT VVGKPPLEDK YMGYLTERLF LPLLQMNAPN
 LIEYYMPENG VFHNLILAKI HTRYNAHAKQ VMHAFWG.VG QMSFVKHAIF
 VNEDANLRDT NAIIEYILEN F..SKENALI SQGVCDALDH ASPEYAMGGK
 LGIDATSK.. .......... .......... .......... ..........
 .....     
>YCLC_BACSU
 ...MAYQDFR EFLAALEKEG QLLTVNEEVK PEPDLGASAR AALGDKSPAL
 LFNNIYGYNA RIAMNVIGSW PNHAMMLGMP KDTPVKE... ..........
 .....QFFEF AKRYDQ.FPM PVKREETAPF HENEITEDIN LFDILPLFRI
 NQGDGGYYLD KACVISRDLE FGKQNVGIYR MQVKGKDRLG IQPVPQHDIA
 IHLR..QAEE RGINLPVTIA LGCEPVITTA ASTPLLYDQS EYEMAGAIQG
 EPYRIVKSKL SDLDVPWGAE VVLEGEIIAG EREYEGPFGE FTGHYSGGRS
 MPIIKIKRVY HRNNPIFEHL YLGMPWTEDY MIGINTCVPL YQQLKEAYPE
 IVAVNAMY.. THGLIAIVST KTRYGGFAKA VGMRALTTPH GLGYCKMVIV
 VDEDVDPFNL PQVMWALSTK MHPKHDAVII PDLSVLPLDP GSNPSGITHK
 MILDATTPVA PETRGHYSQP LDSPLTTKEW .......... ..........
 .....     
>Y1571_AERPE
 .......... .......... .LRRVSVEAS PILEIPEILR RIMYRGGYAV
 LFEKVKGHEF RIAGNIFCSL DVVRQALGVE R...LEVIGE RLFEPLKGPP
 PLGIGGKLRS LGEVLSLGKY MPKAVGRAGF TANVLEGREA SFNLIPAFKV
 WPKDGGRYLT YALVHVRDPV RGVMNMGVYR VMIAGDKEGV VHWQIHKRG.
 .MQAQQDSVE KGERIPAALV IGSDPGTLLT GAMPVPYPID KHLFAGVVRG
 EGLPVYRLP. NGIHVPANAE IVLEGYIDLE DLREEGPYGD HFGYYDPSRL
 FPTFRLERVW HREEPIYYGS VTGKPPLEDV VIGKFAERIF LPAIQTLLPE
 VVDIDLPPHG VFQGMAFVSI RKRYPGHGKK ALLALMG.LG QLSLTKIIVV
 VDHDINVHDV NQVIWAVSSH VDPQRDVLVV PHSHTDELDP ATPTPMYGSK
 LGIDATRKLP EEGGKQWPEE VAPDPETVRL VEGRWGEYGL ..........
 .....     
>Q9PHW8_CAMJE
 ........MK EFIQILKEND LLRVIEEPVD VDLEIAHLAY IEAKKGGKAL
 LFKNPKQYKF PVLMNTFCNK KALNLAFGRD YKEVAEEISK LI....KLHI
 PTSFKAKMDF FMNLLSFKNI PPKRLK.... KNKALYDYEI SLEELPILKT
 WEDDAGKFIT MGQVYTQNLD KTQNNLGMYR LQMSDKNELL IHWQIHKDGA
 NFYHEYKNAG F.KKMPVSIA IGGDPLYIWC SQAPLPKGIF ELLLYGFIKK
 TPAKITPCE. NGIFVPYDSD VVIEGYVDLE EFKIEGPFGD HTGFYTPAEL
 FPVMKVEKIY AKKDAIYQAT VVGKPPLEDK IMGLGTERIF LPLLQTSVPD
 LIDYNMPENG VFHNLILAKI DAKYPAHAQQ IMHAFWG.VG QMSFVKHAIF
 VDKNAPLKDY DALIPYMLDR FNTKK..ILI SEGICDQLDH ASPNSCFGGK
 AGLDACEEIQ VE........ .......... .......... ..........
 .....     
>Q30S89_THIDN
 .......... ..IELLKKNG ELRIVDTELD IYLEIPHLAY AEVKKGGLAL
 LFTNVKKFDE EILMNVFGSY SRCELLFGRT IESVADEITK LL....HMKP
 PSGFLNKISM ASELFSLKNI FPKKLSRGEC QKIKYLENEI DLYKIPVLTT
 WEQDGGPFIT MAQVYTQSFD GEMVNVGMYR LQVYDKNHLG MHWQIHKDSS
 HFFDQYQKA. .GKKMPVTIA IGGDPLYTWC ATAPLPYGVN ELLMYGLIKK
 ESAKLVKSLT NPLYIPHDVD YVIEGWVDTN EMKIEGPFGD HTGYYTLEES
 YPVMEVSAIT TKKKPTYLAT VVGKPPLEDK YMGWATGKIF FPLLKTTAPD
 LLDYHMPENG GFHNLILAKM QPHYKGHAKQ FMHAFWGA.G QMSFVKHAIF
 LDEKAPKLDY DAVTSYILDR FTPKS..LFI TEGILDALDH SSDEALIGGK
 LGIDVTA... ..ANRVEAPN LLGDEELLIR VKEL...... ..........
 .....     
>Y085_CHLTR
 .......SLR SLVDYLRSQH ELIDIHVPVD PHLEIAEIHR RVVEREGPAL
 LFHQVKGSPF PVLTNLFGTR RRVDLLFPDL SSDLFEQIIH LLSSPPSFSS
 LWKHRSLFKR GI...SALGM RKRHLRPSPF ....LYQDAP NLSQLPMLTS
 WPEDGGPFLT LPLVYTQSPE NGVPNLGMYR MQRFDKETLG LHFQIQKGGG
 AHFFE..AEQ KKQNLPVTVF LSGNPFLILS AIAPLPENVP ELLFCSFLQN
 KKLSFVKHPQ SGHPLLCDSE FILTGEAVAG ERRPEGPFGD HFGYYSLTHD
 FPIFKCNCLY HKKDAIYPAT VVGKPFQEDF FLGNKLQELL SPLFPLIMPG
 VQDLKSYGEA GFHALAAAIV KERYWKEALR SALRILG.EG QLSLTKFLWI
 TDQSVDLENF PSLLECVLER MNFDRDLLIL SETANDTLDY TGSGFNKGSK
 GGVGAPIRSL PRRYR..... .......... .......... ..........
 .....     
>Q39TU3_GEOMG
 ....PINDIR SYIAALEAHG VLHRVKAEVD WKFELAHISK VNEEQKGPAL
 LYENVKGNTI PVFTSAFTTP ERIAICLEQD PSLSMCQLSR ..........
 .........K WMELTTKQMI KPTFVKNPPV MENIIEEKDV DLENFPAPWF
 YPDDGGRFFT SGYLVTQDPD TGWTNLGTYR SQILGKNILG SQIISGKHGD
 FHMKKYQ..E RGEKMPVAYV VGGDPILFLA SSTLVSAQTD EYDVGGALRG
 RPIEVFKSDL TGLTLPANAE IIVEGWMDPE ELMEEGPFGE YTGYYSGNKP
 KPVIRVKRII HRNKPIFWST TVGKPINDTH MVQSITATLW HDLETMKVPG
 IQSVYFPAAA TGRFWVVASV KQMYPGHSNH VADAINGSTT GHYGVKGIII
 VDHDIAADDM DRVWWALAVR FDPKRSTQII TRGRSTPLDP GLPIEARDSR
 IILDATIPYE WK...NKPNE IFMDRTVLQK VSDRWNEYG. .FTGASPVAE
 .....     
>Q4HKG7_CAMLA
 ........MQ KFVNILKENN LLKIIDEPVD VDLEMAHLAY EVKKEDSKAL
 LFTNVKDYDY PVLLNTFCNE KALNLAF... .TRSYEDVAS EITSLLKMHI
 PQSFGAKLNF FKTLFGLKNI PPKRIKK... DGEFNYKSLN SLYDMPILKT
 WEKDAAPFIT MGQVYTQSID GKQNNLGMYR LQVVDEKTLL MHWQIHKDAS
 HFFHEYKKA. .NKKMPVSIA IGGDPLYIWC AQAPLPKGIF ELLLYGFIKK
 KPAILAKCKS NDLFVPYDSD FVIEGFVDPN EFLPEGPFGD HTGFYTPIEP
 CPVLKIENIF AKKNAIYQAT VVGKPPLEDK YMGLGTERVF LPLLQTNAPD
 LMDYNMPENG VFHNLILAKI EAKYPAHAKQ VMHTFWG.VG QMSFVKHAIF
 VDENAPLKDY DKLIPYILDR FDEEK..LLI SEGICDQLDH ASSTYCYGGK
 AGLDAC.... .......... .......... .......... ..........
 .....     
>Q2DK85_9DELT
 ...MGYRTLQ ECVKDLESTG KLLRINLEVD PNLEMGAIQR RVYQAEGPAL
 LFTNVKGCRF PMLGNLFGTL ERTRYIF.RD TLDDIRRLVE M.....KVNP
 MALVKDPFGY AGTVPAALHL LPKKVSGGPV LANKTT.... .IDQLPQLKS
 WPDDGGAFIT LPQVYSESPG LRHANLGMYR VQLSGGQEIG IHYQIHRGIG
 VHHAE..ALE RGVPFRVNIF VGGPPSLTVA AVMPLPEGMP ELSFAGLLGG
 RRIEMV.CRP GELPMPAQAD FCITGVIDSD KTLPEGPFGD HLGYYSLVHD
 FPVLRVENVY HRSDAIWPFT TVGRPPQEDT SFGAFIHELT GPLIPTVVPG
 VHAVHAVDAA GVHPLLLAVG SERYVPYAPE IANAILG.QG QLSLAKYLLI
 CAQEIDIHDI PAFLRHILER VDWRRDLHFQ TRTTVDTLDY SGTGLNKGSK
 VVIAA....A GEKRRDLAVE L......... .......... ..........
 .....     
>Y454_CHLCV
 ...MAMSSLR RLVSLLRSQN DLIDIFAPVD PYLELPEIHR RVIENQGPAL
 LFHNVQGASF PVLTNLFGTQ KRVDQIFSKV PKGLIPQVIH LL......SS
 PPKLSQLWKH RNLLLRGLSL GLRKARFLKF PHKKM..ASV DLHQLPMLTS
 WPEDGGAFLT LPLVYTESPS SKIPNLGMYR MQRFDRDTLG LHFQIQKGGG
 MHF..YEAEQ KNENLPVTVF LSGNPFLILS AIAPLPENIS ELLLCTFLQG
 SKLHYKNDPD TPHPLLYDSE FILIGEGICN ERRPEGPFGD HFGYYSLQHD
 FPAFKCRKIY HRKDAIYPAT IVGKPYQEDF YLGNKLQEYL SPLFPMVMPG
 VRQLKSYGEA GFHALTGAVV KERYWKESLA TSLRILG.EG QLSLTKFLMI
 TDHHVDLDNF PKLLETILSR IVPERDLIIF SETSNDTLDY TGPKLNKGSK
 AIF....... .......... .......... .......... ..........
 .....     
>Q4HT05_CAMUP
 ........MR RFIELLKQNE LLKIIDEPLD VELEIPHIAY IEAKKEGKAL
 LFTQPKAYKY PVLMNTFCNQ KALNLALTRD ....YEEVAS ELANLTKLHI
 PTSLKAKFDF FTKLSKLRFA PPKRLQ.... KEKALYHYEI SLEDLPILKT
 WSLDAAPFIT MGQIYTQNPD KTQNNLGMYR LQVSGENELL MHWQIHKDGA
 NFCREYKEAG LSK.MPVSIA IGGDPLYIWC AQAPLPKGIF ELLLYGFIKR
 QNARLTPCE. NGIFVPYDSD FVIEGYVDLE IFKIEGPFGD HTGFYTPPEL
 FPVMKVDKIY AKKDAVYQAT VVGKPPLEDR VMGLGTERIF LPLLQTTTPD
 LLDYKMPENG VFHNLILAKI DTHYPAHAQQ IMHALWG.VG QMSFVKHALF
 VDKDANLEDY EGLIPYILNR FDVEK..IYI SQGICDQLDH ASPNACFGGK
 AALDAT.... .......... .......... .......... ..........
 .....     
>Q2UP67_ASPOR
 ......HSFR AFVEALKADD DLVEINTEID SNLEAAAITR LVCETDDKAP
 LFNNLKGMGK NGLFRILGAP .......GSL RKSKRDRYGR LARHLALP.P
 TASMKEILDK MLSASQLPPI DPKIVETGPV KDNSLEGDEI DLTALPVPMV
 HKSDGGKYLT YGMHVVQSPD GKWTNWSIAR AMVKDKNHLT GLVIEPQHIW
 QIHQMWKKE. .GKDVPWALC FGVPPAAIMA SSMPIPDGVT EAGYVGAMTG
 RALELVKCDT NHLYVPANAE IVLEGTLSIT ETADEGPFGE MHGYVFPGHK
 CPVYKVNKIT YRTDAILPMS ACGRLTDETH TMGSLAAAEI RKICQLAGLP
 ITDTFSPFEA QVTWVALKVD TKLAPKELQK WVGDVVFNHK AGYTIHRLVL
 VGDDIDPYEW KDVMWAFATR CRPNADEMFF EDVRGFPLIP YTGSPTKGGK
 VVSDALMPTE YTTGADWEAE HSYPEEIKAK VRANWEALGF ..........
 .....     
>Q40QG4_DESAC
 ...MGYANLQ SCVRDLEKHG QLIRITDPVD PYLEAGAIQR RVYAAQGPAL
 LFTNVTGSRF PMLGNLFGTL ERTRFIF.RD TLTTVQRLVD .....AKLDP
 SAVFKRPWAF AKAPVGAWHL LPKKVKTGPI LQHQTT.... .IDQLPQLVS
 WPDDGGAFIT LPQVYSEHPS HPGSNLGMYR VQLSGNKEVG LHYQIHRGIG
 VHHR..SAKD RSEKLPVNIF VGGPPSMTVA AVMPLPEGMP ELSFAGLLGG
 QRIQMVQ..P GALPFPAQAD FVICGHIDPS RTRPEGPFGD HFGYYSLTHD
 FPVVEVKAVY HRPDAIWPFT TVGRPPQEDT SFGAFIHELT GDLIPTVLPG
 IHAVHAVDAA GVHPLLLAIG SERYTPYSQE LLTQANAILG QLSLAKYLFI
 TNHELDIHDI GGFLSHALQR CDWQRDLHFQ TCTTMDTLDY SGQGLNSGSK
 VVVAASGPAR RSLTSEIPPE IHLPDGFRA. .......... ..........
 .....     
>Q39WY9_GEOMG
 ...MGYRNLQ DCVFDLEARG DLVRIDVETD PNIEIGAIQR RVYQAGGPAL
 LFTRVKGCRF PMLGNLFGTM ARTKFIF.RD TLDDIRRLVE L.....KINP
 TAVLKNPKEY AGAPLAALRL LPRQVSRGP. ....ILGHRT TIAELPQLKS
 WPMDGGPFVT LPQVYSESPK RPGSNLGMYR VQLAGNDEVG VHYQIHRGIG
 VHHAE..AIE RGEPLRVNIF VGGAPSMTVA AVMPLPEGLP ELSFAGLLAG
 HRLAMV.CRR GELPMPAEAD FVITGTIDPN KTLPEGPFGD HLGYYSLAHP
 FPVLRVENVW HRDDAIWPFT SVGRPPQEDT TFGAFIHELT GALIPEVLPG
 VKGVHAVDAA GVHPLLLAVG SERYVPYERE LLTIASAILG QLSLAKYLFI
 TDNPPDIHHI DEFLTFILER ADWRRDLHFH TRTTIDTLDY SGSGLNEGSK
 VIVAA....A GPKRRDLPTE V......... .......... ..........
 .....     
>Q9F2B6_THAAR
 .......DLR YFINQCAEAH ELKRITTEVD WNLEISHVSK LTEEKKGPAL
 LFESIKGYDT PVFTGAFATT KRLAVMLGLP HNLSLCESAQ ..QWMKKTIT
 SEGL...... .........I KAKEVKDGPV LENVLSGDKV DLNMFPVPKF
 FPLDGGRYIT MVSVVLRDPE TGEVNLGTYR MQMLDDKRCG VQILPGKRGE
 RIMKKY..AK MGKKMPAAAI IGCDPLIFMS GTL.MHKGAS DFDITGTVRG
 QQAEFLMAPL TGLPVPAGAE IVLEGEIDPN AFLPEGPFAE YTGYYTDPIP
 KPVLEVQQIL HRNSPILWAT GQGRPVTDVH MLLAFTATLW TELEQMRIPG
 IQSVCVMPES TGRFWSVVSV KQAYPGHSRQ VADAVIASNT GSYGMKGVIT
 VDEDIQADDL QRVFWALSCR YDPARGTELI KRGRSTPLDP ALDPNGTTSR
 ILMDACIPYE WK...QKPVE ARMDEEMLAK IRARWHEYGI ..........
 .....     
>Y328_CHLPN
 ...MSF..LR RHISLFRSQK QLIDVFAPVS PNLELAEIHR RVIEDQGPAL
 LFHNVIGSSF PVLTNLFGTK HRVDQLFSQA PDNLIARVAH LISSTPKLSS
 LWKSRDLLKR ISSL....GL KKARFRRFPF ....VSMSSV NLDHLPLLTS
 WPEDGGAFLT LPLVYTESPT LTTPNLGMYR VQRFNQNTMG LHFQIQKGGG
 MHL..YEAEQ KKQNLPVSVF LSGNPFLTLS AIAPLPENVS ELLFATFLQG
 AKLLYKKTND HPHPLLYDAE FILVGESPAG KRRPEGPFGD HFGYYSLQHD
 FPEFHCHKIY HRKDAIYPAT VVGKPYQEDF YIGNKLQEYL SPLFPLVMPG
 VRRLKSYGES GFHALTAAVV KERYWRESLT TALRILG.EG QLSLTKFLMV
 TDQEVPLDRF SVVLETILER LQPDRDLIIF SETANDTLDY TGPSLNKGSK
 GIF....... .......... .......... .......... ..........
 .....     
>Q462H3_KLEPN
 ...MAFDDLR SFLQALDDQG QLLKISEEVN AEPDLAAAAN ATIGDGAPAL
 WFDNIRGFDA RVTMNTIGSW QNHAISLGLP PNTPVKK... ..........
 ......QIDE FIRRWDNFPV TPERRANPAW AENTVDGDDI NLDILPLFRL
 NDGDGGFYLD KACVVSRDPN FGKQNVGIYR MEVKGKRKLG LQPVPMHDIA
 LHLHK..AEE RGEDLPIAIT LGNDPIITLM GATPLKYDQS EYEMAGALRE
 SPYPIATAPL TGFDVPWGSE VILEGVIEGR KREIEGPFGE FTGHYSGGRN
 MTVVRIDKVS YRSKPIFESL YLGMPWTEDY LMGPATCVPL YQQLKAEFPE
 VQAVNAMY.. THGLLAIIST KKRYGGFARA VGLRAMTTPH GLGYVKMVIM
 VDEDVDPFNL PQVMWALSSK VNPAGDLVQL PNMSVLELDP GSSPAGITDK
 LIIDATTPVA PDLRGHYSQP VQDLPETKAW AEKLTAML.. ..........
 .....     
>Q5WAQ6_BACSK
 .....YENLE ECILDLEKHG HLVRIEEEVD PYLEMAAIQR RLYREGGPAV
 LFERVKGSKY RAVANLFGTM ERSKFLF.RK NWHKVEQVIA L.....RDDP
 MKAAKRPLQQ LGNGLSALKA LPMRKPGL.. ..NGSQLEEI SLSDIPFVHS
 WPNDGGAFVT LPQVYSEDPD KPGANLGMYR VQLNGNDEVG LHYQIQRGIG
 VH..QAKAAK RGEPLKVSIF IGGPPAHTLS AVMPLPEGLS EMLFAGLLAG
 RRFRY..GYV DGYAVSHDAD FVITGDIYPD ETKPEGPFGD HLGYYSLTHP
 FPVMKVHKVY ARKNAIYPFT VVGRPPQEDT TFGALIHELT GDAVTQELPG
 VKEVHAVDAA GVHPLLFAIG SERYTPYQKT MANAILGF.G QLSLAKYLFI
 TDKPISTHDE AAFLQYILER IDLRRDIHFQ TNTTIDTLDY SGTGLNSGSK
 VVLAAY.... GEKLRELCTA I..PSELKE. .......... ..........
 .....     
>VDCC_STRD7
 ...MAYDDLR SFLDTLEKEG QLLRITDEVL PEPDLAAAAN ATGRIGAPAL
 HFDNVKGFDA RIAMNVHGSW ANHALALGLP KNTPV..... ..........
 ....KEQVEE FARRWDAFPV APERREEAPW RENTQEGEDV DLSVLPLFRL
 NDGDGGFYLD KAAVVSRDPD FGKQNVGTYR IQVIGTNRLA FH.PAMHDVA
 QHLRK..AEE KGEDLPIAIT LGNDPVMAIV AGMPMAYDQS EYEMAGALRG
 APAPIATAPL TGFDVPWGSE VVIEGVIESR KRRIEGPFGE FTGHYSGGRR
 MPVIRVERVS YRHEPVFESL YLGMPWNEDY LVGPNTCVPL LKQLRAEFPE
 VQAVNAMY.. THGLMVIIST AKRYGGFAKA VGMRAMTTPH GLGYVAQVIL
 VDEDVDPFNL PQVMWAMSAK VNPKDDVVVI PNLSVLELAP AAQPAGISSK
 MIIDATTPVA PDVRGNFSTP AKDLPETAEW AARL...... ..........
 .....     
>Q7UZ32_RHOBA
 ..ALKHRSTR DVVEDLRSGD RLITVDDEVD PNLEMAEIQR RVYLRGGPAI
 LFTNVRGCKF PMASNLFASL DQ.ARYLFRD TLERVRRLIE V.....KLDP
 SALPKSPMRY AGVPMTALTM LPRFTRSGAV QAN.....QC RLSELPALKS
 WPMDGGSFVT LPQVLSADPE APRVNLGMYR VQLAGENQVG LHYQIHRGIG
 VHHR..AAMD RNESLQVAIT VGGSPAMSLA AVMPLPEGLT ELTFAGALSG
 RRVRMIRG.. SHAPVYADAD FAIVGQVDPT ATMPEGPFGD HLGYYSLQHP
 FPFMKVEHVW HRKDAIWPFT VVGRPPQEDT TFGQLIHELT DPIIPTVIPG
 VKAVHAVDAA GVHPLLLAIG SERYMPYLKA QANAILGN.G QLSLAKYLWI
 TDDPDDIHDI GSFIQHILRR VDWRRDLHFH TKTTIDTLDY SGTGLNQGSK
 LVVAAT.... GQSTRELATE I......... .......... ..........
 .....     
>Q5QL39_GEOKA
 ...MRAKTFR TWLEYMQSTE RLAVIDKRVK LKYEVASIAK KL..DGKKAV
 YFTQVEDYSI PVVSGICTTR QQFAEALETD QSGLIP...K FIQAVSNPLP
 YRLVD..... .......... ....KKDAPV KENVILKNID LMEILPIPIH
 HEKDSGHYIT AGLLIVRDPL TRKQNVSIHR LQVSSKDRLG ILILPRH...
 TFHLYRQAEE AGKPLECAIA IGVDPITLLA SQASTPFGID ELEIASALRG
 EPLEVVRCET VDIDVPAHAE IVLEGKILPR VREPEGPFGE FPKYYGSRSD
 KEVVQITGIT HRNHPIFHTI VPAG.YEHLL LGGIPREASL FQSVKQTVPS
 VKSVHMSLGG TCRYHAIISI KKRNEGEAKN AILAAFANS. ..FDIKHVVV
 VDEEIDIFNM EEVEWAIATR FQADRDLIVI HGAQGSKLDP STN.NGVGCK
 MGLDCTVPLD SE........ .......... .......... ..........
 .....     
>Q3FXU5_9DELT
 .....YRNLQ QCVADLERRG MLVRIEAPLD PNLEIGAVQR RCYQRGGPAL
 LFTNPVNCRF PLLGNLFGTL ERTRFIF.RD TLDDIRRLVE L.....KVDP
 FSLLKHPLDL LKAPCAAWHL LPTFSSRAPV MECRTT.... .LSRLPQLVS
 WPKDGGAFIT LPQVYTENPS KGSSNLGMYR VQISGNNQVG LHYQIHRGIG
 GHHAE..AIA RGEPLKVNIF VGGPPAMTLA AVMPLPEGMP ELSFAGLLGG
 QRIPMARMEG .QLPVLAEAD FCIRGLVHPD RTLPEGPFGD HLGYYSLAHE
 FPYVQVEEVL HRRDAIWPFT TVGRPPQEDT SFGAFIHELT GPLIPTVVAG
 VKEVHAVDAA GVHPLLLAIA SERYVPYAPR IANAILG.QG QLSLAKYLFV
 AAQDLHTHDV ASFLGHMLER ADWRCHLHFQ TATTIDTLDY SGSGLNQGSK
 LVI....... .......... .......... .......... ..........
 .....     
>Q9K605_BACHD
 .....YQNLQ ECINDLEKHG HLIRIREEVD PYLEMAAIHL KVYEAGGPAL
 LFENVKGSNY QAVSNLFGTM ERSKFIFRQT .WQSAENVVA L.....RNDP
 MSALKHPFAH ARTALAASKA LPLKKSRLPA GF.....EEI TISDLPLIQH
 WPDDGGAFIT LPQVYSEDPD KPGANLGMYR VQLTGDQEVG LHYQIHRGIG
 VH..QTKANQ KGEPLKVSIF VGGPPAHSLS AVMPLPEGLS EMTFAGLLSG
 RRFRYSYCIS HD......AD FVITGEIPPG DTKPEGPFGD HLGYYSLIHD
 FPVMKVHKVY AKQGAIWPFT VVGRPPQEDT SFGALIHELT GDAVKLEIPG
 VKEVHAVDAA GVHPLLFAIG SERYTPYQKT IANRILGT.G QLSLAKYLFI
 TDKPLDTHKE EEFLTYLLER IDLHRDIHFQ TNTTIDTLDY SGTGLNTGSK
 VVIAAY.... GDKKRELCQE V......... .......... ..........
 .....     
>Q2RLH4_MOOTA
 ...MPYADLR QFLERLEAEG QLVRVKEPVQ AEPDLSSIGR AAANEQAPAV
 LVENIKGYYQ KVALNVHGSW ANHALMFELP KDMPVKE... ..........
 ..QFMEISRR WDNF....PV PVRRVSSSPV KEIKHHEQIN LFELMPLFRV
 NKFDGGFYLS KAAVVSRDPE DQKQNVGIYR IQVKGKDLLG IQVLPFHDIA
 IHLRK..AEE RNQPLPVAIA VGNDPVLTFV ASTPMAYEES EYEMAGALRG
 EPFEVIKAET SNLDVPAGAE LILEGEILPR RRSPEGPFGE FPGSYSGVRM
 QAEVKIHTVT HRVDPIFENL YLGVPWTEDY LQALNTSIPL YKQIKASMPE
 VVAVNAMY.. THGIGVIIST NCRFGGYGKA VAMRLLSTPH GMPYSKIIIV
 VDDFVDPFNL EQVMWALTTK VRPDKDVILI HNAPGMPLDP SSDPPGMHTK
 LIIDATTPVP PDVSRE..VE LVDTPAKTAL WEKILKEL.. ..........
 .....     
>Q3A066_PELCD
 ...MGYRNLT DCVRDLERTG QLRRIDVELD GELEIAAVQR RVFQAGGPAL
 LFTRVKGCAF PMLGNLFGTM QRTRFLFR.. ..DTLPLVQR LLAF..KTDP
 AEWLKSPGSW PGALRGALHL LPRKVGGGPV IRCRTR.... .IDKLPGLKS
 WPKDGGPFIT LPQVYSESPG WRHSNLGMYR VQLAGNREIG LHYQLHRGIG
 IHHAE..ALK RNQPLRVNIF VGGPPCLTVA AVMPLPEGMP ELCFAGLLGG
 RRIALIN.RA GQLPMPAEAD FCISGTIVPD KLLPEGPFGD HLGYYSLQHD
 FPVLAVDAVY HRPDAIWPFT SVGRPPQEDS VFGAFIHELT GPMIPELVPG
 VHAVHAVDAA GVHPLLLAIG SERYLPYERE LLTQANALLG QLSLAKYLLI
 VARQLNIHDV AAYLRHLLER VDWRRDLHFQ TRTSIDTLDY SGPDLHQGSK
 VVIAAAGP.. .......... .......... .......... ..........
 .....     
>Q9S4M7_9FIRM
 ...MAYKDLR EFLEVLEQEG QLIRVKEEVN PEPDIAAAGR AALGKNQPAV
 FFEKIKGYKY SVVTNVHGSW QNHALMLGLD KNT....... ..........
 ..STKDQFYE LNRRWDKFPV PPNVVKRAPC KENVIDKDIN LFEILPLYRI
 NEQDGGFYIS KASVVTADPD FNKLNVGTYR IQVKDRDRVG IQALAMHDIA
 VQLEK..AEA ENKPLPIAIT IGNNPLVTFM ASTPVGYNQN EYEFVGALQG
 VPMDIVKSDL YDLYVPAGSE VVLEGHIIPR VRTVEGPFGE FPGSYSGARL
 QCEVKIDRIT HRTNPIFENL YLGIPWTEDY LMALNTSVPL YKQLKETMPE
 VVAVNAMY.. THGIGVIIST KVRYGGYAKG VAFRLLSTPH GMPYSKIVIV
 VDEFVDPFNL EQVMWALTTR VHPGKDVSII ENCPGMPLDP STNPPGMHTK
 MIIDATTPVP PE........ .......... .......... ..........
 .....     
>Q729N0_DESVH
 ...MTYRNLS SCLIDLERNG HLIRIDTEVD ARLELAAIQR RAFRAKAPAM
 LFTRVKGCRF PMVANLYGTR DRIRFIF.RD TLRAVEGIFR L.....KIDP
 FDLFRHPQRY LGVPRSLWGM MPRTVRRGPV LECRTT.... .VRELPQLVS
 WPMDGGGYVT LPQVYTESPD RPHSNMGMYR VQLTGDREVG LHYQIHRGIG
 YHHAE..ALR RGEPLRVNIF VGGPPAMTVA AVMPLPEGIA EVLFAGALGG
 FRIPMIR.RA GGLPILAEAD FCISGTIAPH .QKPEGPFGD HLGYYSLAHD
 FPVLRVDAVH HRRDAVWPFT TVGRPPQEDT VFGEFIHELT AALVPQVFAG
 VHEVHAVDAA GVHPLLLAVG SERYVPYAQE LITCGMALLG QTSLSKYVII
 GDHDLSAHDI PAFFTHMLER TDFSRDLHFI TRTTIDTLDY TGISLNQGSK
 VVWAA..... .......... .......... .......... ..........
 .....     
>Q4IDN9_GIBZE
 .......DFR KFLDILRQDG DLAEIDKEVD PHLEIGAICR RVSEIRDKAP
 LFNNVKGST. DGLWRIFGN. ...AASLRKD DKEKFGRVAR NLGLP....A
 AATWKDISDH FISWKTAKPI PPNILPTGPC KQNKIFGSDV DLESLPVPYL
 HKGDGGKYLT YGIHVLQTPD KSWTNWSIFR GMVHNKNHLT CLVGTGQHNA
 IIRDKWLAEG KTE.IPWALA LGVPPIASIV AAMPVPEGVS ESEYIGAVTG
 KPLDMVKCEM NDLLVPASSE IVLEGTMSLV EKGKEGPFGD YLAFDGEGGK
 GPLFRVDAIT YRDNAILPIS CPGNIIDESH TTAQLAAPEV LLLCQEHGLP
 IKEAFAPVET LATWCVLQVD TERLEEFSKR LG.GILFKSK STMLINRVLL
 IGDDVDIYDW DKVMWAFTTR CRPGHDTYHF EDVPSHPLPY MTQIPGTGGK
 VISDCLLRSE YDRPRDFKAE TSYPSHIKTK VLNNWGAMGF ..........
 .....     
>Q46EJ8_METBA
 .......SFR TFINQLKENG KLVEILQPVS PRFEASKIA. ...KNTKSPV
 LFHDISGSK. .VIMNLLGSR DELSSMLGVP KEKIIKKLSE V........S
 PEG....... .......... EVRLVSESPT FEVI..EDQV DLTKLPILTH
 FEKDGAPYIT AGIVVSE..Y GGTINASIHR LMLAGKDKLA VRLVPPRHTY
 LLHKK..AAE KSEPLPVAIV LGCDPTIIYA TSTRVPVG.K EFEYAAALRG
 APVELFEC.A NGVKVP.HAE IVLEGYIDPR ERVDEGPFVD ITGTYDVVRK
 EPVIHITRII HRKDPIYHGI LPAGP.EHLL MMGVPYEPRI YRAV.GEVTT
 VKNVVLTEGG CCYLHAVVQI EKQTEGDGKN AIMAAFAAHT SL...KHVVI
 VDEDINIFDP NDVEFAIATR VKGDMDILII PNVRGSSLDP RGAPDGTTTK
 VGIDATKVLV EKENFERA.. .......... .......... ..........
 .....     
>Q3G4Q7_9DELT
 ...MASPDLQ HFIATLERRN ELAAIDAEVD PLLEIAAITD RVCKSNGPAL
 LFRAPTGSRF PVATNLFGSP RRVCLALGVD H...LKHLTE RMSALLGGIP
 APELSSLDRQ IAGLADFSRF SPH...ASPK PDPRLTAAAP DLGLFPFLQS
 WPGDGGRYIT LGQVYTRHPE SGHQNCGMYG AQLRGPTELA LRWKQGSGAG
 RHLERY..RR RGVPMPVAIT LGGPPAMTLS ALFPLPGELD ELTFAGFLAS
 SPLRTTACRT VPLMVPAACE LLIEGYVNPA ETVREGPFGN HTGSYSPATD
 ASLMRVTTIS HRPHAIIPAT VVGPPPMEDC WMARAWERLL LAFLQRLIPG
 IAEICLPLQW VFHQSAIISL ENPTPAMVRE TASRLWET.P WFTASRLLIF
 VDAGTAPDDL GTVAWSAINS CDVDGDMI.. .......... ...RDSSGLR
 TALDAT.... ..GCRMARQR IQPDEAVARR IARRWKEYGL E.........
 .....     
>Q39ZW7_PELCD
 .DPTAINDLR QFLALLEAQE DLRRISVEVD AELEIAAITD RVCKAGRRAL
 LFERVRGYRA PVATNLFGAP RRAAWALNVQ HADEAA..GR LIRGLEQVPG
 ....EDAETR LRRLLQQPQF APRRQSRGDC HQVVMT..RP DLSRIPALRS
 WPGDGGRYLN LPQIYSRHPD GGVGNCGMYR CQILGPRQIA VHWKESSDAA
 RHCSAWHA.. RNLPMPVSIA LGGAPAMMFA ATFPLPPDID EAALAGLLCD
 RPMAMATSLS SDLSIPAAAE YILEGLVHPG ETVEEGPFGN HTGFYQPRTR
 VPLLRVTSVS HRYDPILVTT VVGPPPMENC YLGKLAERLL LPLLRIDHPA
 IVDIHMPVEG IFHGATLIAV QPGTSG..KS LLQDLWQNGP LHSSRLLVVA
 TADEI..RNP ATFFWRTLNR LDAKRDLLVR D......... ........GR
 LGIDATR... ...DPAGLQV LRPDAQIRSL LQRRWAEYGL ..........
 .....     
>Q2ULG1_ASPOR
 ....AAKDFR RFIQELEDEG ELLTITKEVD PHLELAAIVR KVCETGERAP
 LFTNPKGRKD DGLFRVIGA. ...SIGYSKR PGMQLCRLAK SLGL...PSS
 ATG.HEIVQK INEAKTKPPI PCRKLESGPV KDHIIHGDDI DLTQLPVPLL
 HEHDGGKFIT MGMHVVQSPD GKWTNWSISR GMVHGKRELV GLVIPKQDIG
 TIFNLWK..E KGEDMPWAVC FGVPPAAIMV GGMPIPKWTN EPEFIGALTD
 APVDIVKCET NDLWVPANAE IVLEGVVSIS ETAPEGPMVE YNGLVFPGHK
 CPIFKVNTIT YRHDPILPIC VAGRAPDENS TIWCTMQAAV LNICQKAGLP
 INMVWCPFES CLWFVLQVNH SKNMEEFCRK LGHVVFGSKP GWFIPK.IFL
 VNDYIDPTNL PDVIWAEATR CEPGRHEFIF NEYSNIPLIP YVTH.GLPSK
 TGMNKTLPW. KEGSFQGA.. ..YPEDVKKK VLDNWTAYGF ..........
 .....     
>Q5P026_AZOSE
 ....PIQDLR EWLGRVEEMG ELVRVKQPVD RDEEMSAVGY LLAKQDSPAV
 LFEQAAGFEA RLLWNILGSV KRVALTLEEP VDTPVVELIR LA........
 ....KDKLKR ........RI PPREVSRAPV YENTLTGDQI DLNLLPIPKH
 WPLDGGRYAT ADAVITRDPD SGYINIGTYR MMLQGKNQVG LYMSPGKDAR
 LH..ITRAWE RGESIQVAAA WGIDPLFMMV GSQTFPKNVS EYEFAGGIKG
 QAIPVVRGTT TDLLLPANAE LVIEGIIRPG SVKPEGPFGE FPGYYGRPEA
 CPLVEVTAVH YRSKPILTNA LMADYPEQSG FFSVVRSAIW DDLDKLGIPG
 IHGVYAHPAA GGFGVTVISL EQRYAGHAAQ ALALAAQCPG GAYYTKLIIA
 VDEDIDPTDM DQVIWAMASR CNPIDDIDIL RNTWSTWLDP TQNPPPYGSK
 ALINACKE.. ...HRHLPKR TTLSRSTYDK VASRWQELGL PGPSVRAFEE
 EH...     
>Q3WTU3_9RHIZ
 ....PYKDLR EFLAQVEAIG ELKTVK.GAS WDLEMGCLAE LIYHNDPPAI
 CFEDIPGYPF RCVSGLTNSS QRLAITLGFP LSKNPLDIVQ ..........
 ........SY RDRMKVHEPL PPRFVSSAPI YENVLRDDEI DILKFPIPKL
 HELDGGRYAT DDLVIMQDPE DGWVNIGTYR SMVHDARSLG LWISPGKQGR
 QIRDKYFAQ. .NKPCPVLIC IGHDPLLFLA SGNELAYGLS EFDYAGGHRG
 VPFEVVKSDV HGLPMPAHAE IVIEGEMHPG ELRMEGPFGE FTGYYSNPSP
 QPVVRIQHIY HRNNPIMTMA SPMQPPSDFS FSKCVTKSIW DEVERAGLSG
 VRGVWCHEAG GARMFNIISI KQRYPGHARQ ALHLAASCQS ASYLGRWVVV
 VDEDIDPTNT FDVLWAISTR CDPAQDVDFI RRAWSGPLDP MNEADGTNSR
 GLIDACRPF. .ERLKTFPPV ARASDKFRNE IAEKFKHY.. ..........
 .....     
>Q92XP8_RHIME
 ........MR DFVRKLQERG DLLVVEREID PAHELAAVTH LAQKKWAKPV
 MFTNVKGTRF PVVTNVYSTR ERLGEVIGID AGDFCRQWSR LSAEMREPLV
 PA........ ........NQ PPGY...... .......DEV KLSDLPLITY
 SDRDGAPYFT SAMFIARDPD TGVANLSYHR SMFISDNELR CRLAPRHHLT
 IYHEK..AEK MGKPLEAAML IGPPAHAFLT AAAPLAYDVD ELEVAARLRG
 KPIEMRRCNH IDLEVPSETE VVIEGRFLPN ERRPEGPFGE FMGYYVPVGP
 NAVFEVLGVT VRKDAIFHSI LCG.SPEEVL TLELSVSANI YQRLSAALPG
 IVNVTCQP.. .FVNHAVVQI EPQFEGHARQ VMLATIGAEP ..IWAKQITV
 IDTDVDIYSM DDVQWAILTR CRPDKDTMII PETPSFYRDE AKDHWG...R
 LLVDATKPWG REEEFERKR. LRMVNDIR.. .......... ..........
 .....     
>Q89PF1_BRAJA
 .......DLR AWLAYLAERG KLAIAREGVA LADELAAIAK RLERDS..AV
 LFPRPDGHAI PVVANLFAGR DWVAESIGVT EDQLLPQ... LLAAASHPLP
 T......... .......... ..HEVASGPV QEVVHEDIDL .LRQLPVPKH
 NERDSGPYIT AGLLIARNPK TGVQNVSIHR CQISGKNRIG VLLLPRH...
 TFSYYRLAEE LGQALEIAIV IGAHPALLLA SQAIAALDED EMAIAGALLG
 EPVDVVKCRT NSVRVPAHAE IVIEGRILQG VREPEGPFGE FPQYYGPRAN
 REVIEVDAIT HRKAPIFH.T IVGGGFEHLI LGGVPREATL LQHLRRSFPG
 VIDVRLTRGG TCRYHLAIKI DKANDGEPKN VMMCAFGAH. ..YDIKQVIV
 VDKDVDISSC EEIEWAVATR FQADRDLMVV SGALGSKLDP TT.DNGISAK
 MGLDATAPV. .......... .......... .......... ..........
 .....     
>YD539_YEAST
 ........FR DFIQVLKDED DLIEITEEID PNLEVGAIMR KAYESHLPAP
 LFKNLKGASK D.LFSILGCP ARIAHHLGLD PKTTIKEIID YLLECKEKEP
 .......... .......LPP ITVPVSSAPC KTHILSEEKI HLQSLPTPYL
 HVSDGGKYLT YGMWILQTPD KKWTNWSIAR GMVVDDKHIT GLVIKPQHIR
 QIADSWAAIG KANEIPFALC FGVPPAAILV SSMPIPEGVS ESDYVGAILG
 ESVPVVKCET NDLMVPATSE MVFEGTLSLT DTHLEGPFGE MHGYVSQGHP
 CPLYTVKAMS YRDNAILPVS NPGLCTDETH TLIVATEAKE LAI..ESGLP
 ILDAFMPYEA QALWLILQAL KTTPEEFCKK VGDIYFRTKV GFI.VHEIIL
 VADDIDIFNF KEVIWAYVTR HTPVADQMAF DDVTSFPLAP SRSKTMKGGK
 CVTNCIFRQQ YERSFDYITE KGYPKGLVDK VNENWKRYG. ..........
 .....     
>Q976Y9_SULTO
 .........R KFIEEVRRLN LLREIK.GAN WNLEIGAITD LNAKKNKYTL
 LFDEIVDYPF RVLTGTLLDS RRVSLALGFS PN........ ....LNNLEL
 VLKLRERLNY A..YKEYRSY EPLEVSDAPF LENVDKDDSV NLLKFPAPKW
 HEMDGGRYIT ADAVITSDSD SNWVNVGTYR VMLVDKNRLA IFIEASHHGR
 LHIEKYLS.. KGKKAPIAIS FGPPLSLLIF AGMEVPLGVS EYNFAGAVIG
 ERFRVFRGEV TGLPIPADSE IAVEGYI.TG ELTDEGPFGE FMGYYAGGRK
 SPVIDVKRVY YRQDPILLGT APSIPPYDYS YFRCPIRSAM IWLERAGVPN
 IKGVWAHEVG FSRAFIVISI KQSFAGHATM VGHLVSTSPL GAYGGRYVIV
 VDDDIDPSDL NQVVWAMCTR SDPATSIDVI KNVTSTPLDP MAEKEYSSSR
 AIIYAVKPFS RLIRNEFPIE VKPSEELSKK VMEKWSEI.. ..........
 .....     
>Q8J0Q7_NECHA
 ...LPHMDFR AYVETLEADD DLVQINDECD PHLEVGAIIR KVVENDAKAP
 LFNNVKGRDV NGLWRILGAP NSLRSNLK.. .....QRYGR LARHLGLP.P
 DSSMKTILDK MVAAKTTTPI PPKVVETGPC KEFRLTPNQF DLTKLPAPLL
 HQSDGGKYIT YGMHIVQSPD GKWTNWSIAR AMVHDRNHLV GLVMPPQHIG
 QIHEMWKKE. .GHDMPWALA FGVPPAAIMA SSMPLPDGLS EAEYIGSLVG
 TPLEVAKCET NGLYVPANSE IVFEGTCSIA ETAPEGPFGE MHG.......
 .......... .RVCPLMPML NSGML.DQST NLSLAMCSPV TPHYDRPSRG
 CRD.WFPPQS QVTWVALQVD TQKLEELCRK VGDLVFRHKV GLT.IHRLLL
 VGDDIDVYDF KDVIWAFCTR CRPGMDEHHF EDVLGFPLIP YMSHPNKGGK
 VVSDCLLPVE YTTGKNWGAD FKSPEEVQER VCGRWEALGF ..........
 .....     
>Q5P480_AZOSE
 .........R EFIEACVRSG DAVRIRQEVD WDNEAGAIVR RVCELGEAAP
 FMENIKDYPF SYFGAPLSTY RRMAISLGMD PASTLPQIGA LKRTNSEPIE
 PVVIDR.... .......... .....RDAPC KENILLGDDV DLTKLPVPLV
 HDGDGGRYVT WHAVITRHPV RGDVNWGMYR QMMWDGRTMS GAVFPFSDLG
 KALTDY.YLP RGEGCPFATA IGLSPLAAMA ACAPSP..IP EPELCGMLSG
 EAVRLVKCET NDLEVPADAE IIIEGMILPD YKVEEGPFGE YTGYRTSPRD
 FRVFRVDAIT YRNNATMTIS NMGVPQDEGQ LLRSFLGLEL EKLLKSQGIP
 VTGVYMHPRS THH.MMIVGV KPTYAGIAMQ IAQLAFGSKL G.PWFHMVMV
 VDDQTDIFNW DEVYHAFCTR CNPERGIHVF KNTTGTALPH ATPHDSIGSQ
 VLFDCLWPVD WDKTNDVPSV VVYPQDIQDK VTNSWTDYGF ..........
 .....     
>Q4I8M4_GIBZE
 .......DFR SFVEVLRKDG DLADIDQEVD PNLEVGAVVR RVSETNAKAP
 LFHNVKGTR. NGLWKMFGN. ...AASLRND SKFRYGRIAR SLGLP....P
 DSNWKDILEK MRLATTRDPL PPNILSTGQC KQNKIFGDDI DLTNLPVPLL
 HQGDGGKYLT WGVHILETPD KSWTNWSVFR GMVHDKRRLS CLVIPGQHNS
 MIRDQWLKLG KDE.VPWALS LGAPPAATIA ASIPIPPGVS ERDYVSSLAG
 KPLDMVKCEL SDLLVPANSE IILEGTFSLK DKALEGPFED YIGFEGEAGN
 QPLFTVDAIT YRDGAILPVS VPGRLTDESH TTASMASVQL LEALQQHDLP
 IKDAVAPLET LATWCILQVD SKKLAEMKTN TIGNIAFNSK ATMLINRILL
 IGDDVDIHDW ADVIWAYTSR CRPGIDEYVF DEVMGLPLTP Y.RKYGRGS.
 .......... .......... .......... .......... ..........
 .....     
>Q4J782_SULAC
 .......NIR DFIERVRELG LLREVK.GAS WDLEIGAITD LNAKRRKFTL
 LFDEIKDYPY RVLTGALLDY RRVSLALNLP ANSDIELV.. ..........
 .KKLRERLAY AS..KEYANY SPREVSDSPL LENVDVGEKV DLFKFPSPKW
 HEHDGGRYIT ADAVVTKDPE SEWVNVGAYR VMLVDKNRLA IFIDSPHHGR
 IHMEKYL..R QGKKCPIVIS FSPPLDLFIF SGMEVPQGVS EYNFSGAVTG
 KRVDVLRGED TGLPIPAESE IAIEGYI.TG ELTDEGPFGE FMGYYAGGRK
 NPVIEVKRVY YRNDPILLGT TPGIPPYDYS YFRCPIRSAM IWLERIGIRD
 VKGVWAHEVG FSRALVVVAI KQAFAGH..Q TMLGILAISP LTSYGRYVIV
 VDEDIDPSDL NQVVWALCTR TDPANSIEVV KNVPSTPLDP MAEKEYVSSR
 AIIYATKPF. ...NKSFPLE IKVSEDLVKK IKENWSEI.. ..........
 .....     
>Q2NEA4_METST
 .......... .........D DIIEISEEVS TEYEITSILK KHPTD...TV
 IFTNIKDSNM NIISGICNTR DKIAKSINTS VDKITENIIK ATENPTKITN
 IKNFDEVYSN ........NM .......... ........DV DLSKIPILKH
 YPKDKGKYIT AGVVIAKDPE NGQTNASIHR MLVNSNDELG IRIVPRQ...
 LYTYYKKAEE LNKPLEIAIA IGLNPSTLLA STTSIPITEN ELEVANTFKE
 GNLTLVKCET VDIEVP.ECE ILLEGKILPN ERKIEGPFVD LTDTYDKIRE
 EPIIKLTRMH YKDNPYYHAI LPAGN.EHKL LQGLPQEPRI YNSVKNTLPT
 VQNVVLTEGG CCWLHAVVSI KKQTEGDAKN VLMAALSAHP SL...KHCVI
 VDEDINIFDA VDVEYAIATR VKGDDDIIII PKARGSSLDP VAQIDGTTTK
 IGVDATKSF. .......... .......... .......... ..........
 .....     
>Q3KAN6_PSEPF
 ......QDFH VFIDAYRRQD DVLTITHPLS ADQDVTALVD ALATQGDPLL
 ICENVGNLGV PVATNLFASR RRIARLFGVS AAQ....... ..........
 .......LHE TFQIRANQPI APRYVETGPV LDEVFEGETL DLALLPMLKH
 FDSDRGPYIT NAIIIAEDPQ TGIANMSYHR SMRHARQALA TSL..HSRGH
 LWRMLQTARE RGEELRVAMV VGAHPLFMLA AAARLPYGSD ERAVAGGLFG
 APLELVKTPR YGIGVPAYAE FVLEGAIDPT AYAEEGPFGE FSGYSSDRST
 NNVLRVDTLL RRKDAWLVDV MGGRYAEHLT LARLPREAEM SEKLKARFPA
 VTAVHYPNSG T.HFHCYVAL DQSRDGEARQ IMLAL...LG WDPYLKTVIA
 VDSDIDLTDD SQVLWALATH FQPHLDIFTI DGLPGSPLDP SSSVNGTTSR
 MGLDATRGSA FD.....GIK AQLDQDVLER ARQLLE..GL P.........
 .....     
>Q3AE98_CARHZ
 ...MA.ASLR SFLEQLKRQN SLYLVKKPVN PRFELGALLK KT..KGTVPM
 FFQNIEGYDV PAVGGIVGTR ENFAQALRIN KSELLAKITE AITNPGE...
 .......... .......... .TRLLPSGPV QENVLT.KGF DIGKFPIPTF
 HEKDSGAFIT AGIVVAKDPI YGRRFTSIRR MQLNGPNNLS ILIESP...G
 LIEQYYEFER RGQAMEVAIV LGVHPAITLS SQLPTQTGLD KYNVASRLIG
 EPLPVVKCKT IDLEVPADAE IVLEGRMLPY VRHPEGPFGE LMGYYGPQTM
 QPVVEVTAVT FRNNPIFQVI FPS.SYEHKL PNALMREVVL FNHVRHVVPT
 VQDVHLTMAG GGRCHAIISI KKTAEGQGKQ ...AIFAALA SNKDVKHVVV
 VNDDVDIFDP EDVEWAIATR VQADQDIIII PGAQGTPLEP SHNLRGVSAK
 MGIDATYPLA EEERF..... .......... .......... ..........
 .....     
>Q6BJQ8_DEBHA
 ........FR DFLQVLKNEN DLVEITHECD PNLEVGAIMR KVYEEKLPVP
 LFKNLKKDPK SNLFNIVGDH ARIALHLGLD SQTPMTKIID YLANTKKPLP
 PVLLEDA... .......... .....SGAPC KKNKISGDVI RLNALPAPTL
 HHGDGGKYIT YGMFVLQTAD KTWTNWSIAR GMIYDDKHLT GLVMNPQHIR
 RVADTWAEIG MGDSVPFALC FGVPPASILV SSMPIPDGAT EADYIGALVG
 EPLSVVKCET NDLHVPADSE MVFEGTLNLN KMVEEGPFGE MHGYCFPGHP
 CPLYTVDTIT YRDDAILPVS NPGLCTDETH TLIGGLVSAE CKQMALEHPK
 LKSVIMPHEG VALWLALKVN TKELAKFCKL IGDYYYSSKP GFILQE.IVL
 VGDDVDIFDF RKLFWAYATR HTPGDDQYMF NDYRAFPLAP PRIKTLKGGN
 CVTDCL..FP KQYEPEGVDF VTYDEAIKEK VRKNWSAYG. ..........
 .....     
>Q5NWH2_AZOSE
 ....AYEDLR EWIVEAEKLG EVHVI.QGAT WQKEIGMAAD LAMHSDAPCV
 IFDDVPGCEH RVLVNFFGSR KNMTLGFPTD .......... ....LSRLEL
 SQAFLE.... .NSLRDMEPL PHEIVEYGPI FENVLMGDDI DITKFPTPQW
 HEHDGGRYIG TGSYITMDPD EKWLNAGTYR VMIHDKKTVG FYISPGKHGR
 IHRDKYEA.. RGEPMPTAIV VGGDPLTFLM ACSEVPYGVC EFDMVGAMRG
 KAQKMVRGKV TGIPIPANAE LVIEGYVHPT RRKKEGPFGE WTGYYSDVRE
 EPVLEIKAIY HRNNPIILGC PPLCPPDEMA RYRAVTRSAL LEIEKAGVPD
 ITAAWAHECG GARMLLAVAI KQRYPGHVKQ VGHIASQCHV GAYAGKYVVV
 VDDDVDASNL EEVMWAVVTR SDPATSIDII TNSWSTPLDP RLTPNYTNSR
 AIIDACRPFH WRDRF..... .......... .......... ..........
 .....     
>Q92X26_RHIME
 ...MEFQDVR YFLREYQKPE DVLTIEDCIT DDQDASAFIW KLNQQGAPLL
 HFRNVEGVGG EVIANTFGSR ERIARMFGTS Q......... ..........
 .....DRLHE AYQARSRQAL PPRLVDGGPV TECV.EEHDI DLGTLPMLKH
 FATDRAKYIT SGIIIAEHPE TGAGNLSYHR AMIHSKNELA TSL..HSRGH
 LWRLLNMAKD RGEKLKAAMV IGAHPLFMIA ASARLAFGED ERDVAGGLIG
 EPLEVVRTPK YGIRVPAYAE IVLEGVIEPE AQVAEGPFGE FTGYSSDRST
 NNLFRVETFL RRKDAILVSV AGGNSSEHLN LGRIPREAEM VEKLKQRFPS
 VTAVHYPASG T.HFHAYVAL NQTRPGEARQ IMLGL...LG WDAYLKTVIA
 VDADVDITRD SDVLWAMSAH FQPHKDVVII EGLPGNALDP SASGIGTTSR
 MGLDATR..G PDFHGVLAR. ..IDEAAFDR ASAILAKFGR P.........
 .....     
>Q46WQ2_RALEJ
 ......QDFH QFLAAYREPD DVLQIREPVS ADQDPTALVW ALAAQGHPAL
 LFEQVDGLGT PLVTNLFASR ERVGRMLGGV PPS....... ..........
 ......AIHA EYQARSRRMV APRVLEGGAV TGHV.ETRHI DLRTIPAIRH
 FASDRGPYIT NAILIAEDPE TSVGNASFHR SMLHSPTEIA TSL..HSRGH
 LWRMQQRAAQ LGKPLPVAMV IGAHPLFMLA GAARLPFGVD ERHVAGGLLG
 APMEAVRTPR YGILVPAHAE IVLEGVIDPE ARVEEGPFGE FTGYSSDRST
 NNLLRVESVM RRTDAWLVDV VGGNSAEHLN LGRIPRESEM VEKLRERFPS
 VTAVHYPSSG T.HFHAYVAL RQSRPGEARQ VMLGL...LG WDPYLKTVVA
 VDEDVDITRD DEVLWAMATH LQPHLDVVVV DGLPGSALDP SASGVGTTSR
 MGLDATRGPN FDGVRARIDA AAMDRA.... .......... ..........
 .....     
>Q73ZG6_MYCPA
 ...MAFRDLR DYIQTLTDKE EVKTIR.GAH WDLEIGCLTE LLAEKEGPAP
 LFDNIEGYPY RVFTNFMGTV PRCAVALGLP PWTPA..... .......MDI
 VKAWKDLS.. ....KSIDPV APVLLSTGSV LENVLEGDDV DLNMFPTPRW
 HDGDGGRYIT ACMVITKDPD TGWVNVGTYR GCVQGKDRLS LWMLGNRHAL
 AIAQKY..WH RGQACPIAVV VGCDPILTTA AAIAAPSGVC EYDVAGGLRG
 SGVEVLAAPG TGLPVPAHAE IVLEGEMPPE ESVPEGPFGE WTGYFTHAGN
 ETVVRVQRIL HRDSPI.... ILGAPPMIPT VQAVPLYSAS VTWDHLEASG
 VQNIKGVWAY ARQLMMVISI EQTGTGDAMH ALLAAAGRKR TGGMDRYFVV
 VDEDIDITDI NHVLWALFTR VDPTESIHVL .RTPTTAIDP AKRDAGDLSM
 GIIDACKPFA WKDS..YPRA NRFDDNYRAA IRDRWQ.... ..........
 .....     
>Q5JI90_PYRKO
 ........LR EILSRFE... DLVVIKEPVK KELE...ITR YLLKYPDRPV
 LFEDVEGWK. .VAGNIWSTR KRIATYLNTT REELIHLIAE AMENPRQY..
 .......... .......... ..KEVKEAPF LKN..STKDF SLKKLPIPKY
 YPRDGGQYFT SAMVIAKD.D NGFVNVSFHR MMVRDEKTAA IRLVPRHLYA
 MWKEK...AE NGEDLDVRIV VGNPVHLLLA GSVSTAYGVS ELEIASAMSG
 KPLEVI..EL GGIPVPIESE FVFEARITP. ELVDEGPFVD ITGTYDIVRR
 QPLVVFEKMY HVDDPIFHAL LSGG.YEHYM LMGLPKEPQI YASVKRVVPK
 VHGVRLTEGG AMWLHAVVSI TKQHDGDGKN AILAAFAGHP SL...KRVIV
 VDEDINIYDD REVEWAVATR FQPDRDLVIV PNARGSSLDP SAEK.GLTAK
 WGIDATKPLG RKEEFERARV .......... .......... ..........
 .....     
>Y963_PYRHO
 ...MVMKMLR EIVESFE... DLVVIDKPVK KELELT...K FLLKYKDKPV
 LFKDVEGWE. .VAGNLWSSR ERIAKFLNTD NKGLL....E LLYEAMEKPK
 PFSVVEKAEF LKNR...... .......... .......EKV NLLELPIPKY
 YPKDGGPYLT SAMVIAK... KEFVNVSFHR MMVLDEERAV IRLVPRHLYS
 MW...KDSVE HGEELEVRIV LGNPVHLLLA GATSVAYGVS ELEIASAISG
 RPLEVIN..L DGIPTPVDSE FVFKAKI.TD EVADEGPFVD ITGTYDIVRK
 QPIVIFEEMY HVDDPIFHAL LPGG.YEHYM LMGLPKEPQI YASVKKVVPK
 VHGVRLTEGG CMWLHAVVSI TKQHEGDGKN AILAAFAGHP SL...KRVVV
 VDEDVNIYDD REVEWAIATR FQPDRDLVII PNARGSSLDP SG.KDGLTAK
 WGIDATKPLD KKKEFE.... .......... .......... ..........
 .....     
>Q348U0_RHOPA
 ......PDLR SWLRQLEACG RLALARSGVA LIDELAAVAK TLERDT..AV
 LFPQPGQHAI PVVANIFADR SWVADSLGVP TDQLLTR... ..........
 ...FQDAVRH ........PL PWVEVDEAPA QQVIHREVDL .LTQLPIPKH
 NEHDSGPYIT AALLIARNPV TGIQNVSIHR CQVSGPDRIG VLLLPRH..T
 LHYFK.MAEQ AGQALEIALV IGVHPACILA SQAIAAVDED EMEIAGALLG
 HPIEMVKCRT NQVRVPAHAE IVIEGRILPK LREPEGPFGE FPQYYGPRAD
 REVIQVDAIT HRANPIFH.T IVGGGMEHLV LGEIPREATL LEHLQRSFSS
 VRDVRLTRGG VCRYHLVVKI DKTSNGEPKN IIMGAF...G GHYDLKQVVI
 VDMDVDIDDP HEIEWAIATR FQADRDLLVV SGAQGSKLDP TSDG.GISAK
 MGLDATKPIE AE........ .......... .......... ..........
 .....     
>Q5A8L9_CANAL
 ........FR DFIQVLKNEG DLVEIDTEVD SNLEVGAITR KAYENKLAAP
 LFNNLKQDPG NILFRILGCP ARIALHLGLD SQTPMKEIVD FLVANRNPK.
 .......... .......KFI PPVLVEKSPH KKHHLTHEQI DLTKLPVPLL
 HHGDGGKFIT YGMWVLQTPD KSWTNWSIAR GMVHDSKSIT GLVINPQHVK
 QVSDAWVAAG KGDKIPFALC FGVPPAAILV SSMPIPDGAT EAEYIGGLCN
 QAVPVVKCET NDLEVPADCE MVFEGYLDRD TLVNEGPFGE MHGYCFPQHT
 QPLYRVNHIS YRDEAIMPIS NPGLCTDETH TLIGGLVSAE TKYLISQHPV
 VEDVFTPYEA QALWLAVINI QEKLQTNAKE LSNLVGDFLK VCSILHEVIL
 VGDDIDIFDF KQLIWAYTTR HTPVQDQVYF DDVKPFPLPF ISQGPLIGGK
 CVTSCIFPTD PDFKFVTCNF NGYSEEVKNK VFQNWEKY.. ..........
 .....     
>O86002_SPHAR
 ..ARSISSLR DFLELLEDAG QAITWSDAVM PEPGVRNIAV AASRNGAPAI
 VFDNITGYPK RLAVGVHGSW DNIALLLGRP KGTTIREL.. ..........
 ..FFEIAGRW GDQEAQISFV PEAQ...APV HECRIEQDIN LYDVLPVYRI
 NEYDGGFYIG KASVASRDPN FGKQNVGIYR LQIQGPDTFT LMTIPSHD..
 MGRQIMAAER EGVPLKIAVM LGNHPGLAAF AATPIGYEES EYSYASAMMG
 APIRLTKS.G NGIDILADSE IVIEAELQPG GRELEGPFGE FPGSYSGVRK
 APIFKVTAVS HRRDPIFENI YIGRGWEHDT LIGLHTSAPI YAQLRQSFPE
 VTAVNALYQH GLTG..IISV KNRMAGFAKT VALRALSTPH GVMYLKNLIM
 VDADVDPFDL NQVMWALSTR TRAD.DIIVL PNMPAVPIDP SAVVPGKGHR
 LIIDATSYLP PDGEAHLVTP PTGDEALSKR IREM...... ..........
 .....     
>Q399W1_BURS3
 ......QDFH HFANAYRERD DVLTLAQPLS ADQDVTAVAS LAARGRHEML
 VCERVDGLST PLVTNVFASR TRIGRLFGVE AN........ ..........
 ..GLFDAWQQ ....RANAPV APVVVPHGSV LDQVTEGDAV DLAQLPMIRH
 FETDRGPYVT NAVIVAEDPV TGVANLSYHR SMPHARNALA TSL..HSRGH
 LWRMLQTAKA RGDTLKVAMV IGAHPLFMLA AAARVPFGAD ERAIAGGLFG
 APLQLVRTPR HGIGVPAAAE FVLEGTIDPD AHAEEGPFGE FTGYSSDRST
 NNVLRIDAMM RRKDAWLVDV VGGPYAEHLT LARLPREAEM SEKLKARFPS
 VTAIHYPNSG T.HFHCYVAL KQSRDGEARQ IMLAL...LG WDPYLKNVIA
 VDSDVDITDD AQVLWAIATH FQPHRDLFVV DGLPGSPLDP SSSSDGTTSR
 MGIDATRRFD GVRARVGDAA MQRAAQVIA. .......... ..........
 .....     
>Q9F2B3_THAAR
 ...MAYSDLR AFLADLG..D DLLRIRDEFD PRFEAAALL. RTLPAEGPAV
 LFENVRAYPA RIAGNLIASR SRLARALGTT ADALPR.... ..........
 .........T WLERKEHGIA PIQARDAAPV KEVIHRHPDD LLSLLPILTH
 HEKDAAPFIT TGVVLCTDPE TGRRGMGIHR MMVKGGRRLG ILLANP...P
 IPHFLAKAEA AGKPLDVAIA LGLEPATLLS SVVKVPRVPD KMAAAGALRG
 EPVELVRAET VDVDIPARAE IVIEGRILPG VRELEGPFGE NTGHYFSNVS
 .PVIEISAVT HRDNFIYPGL CP.WSPEVDA LLSLAAGAEL LGQLQGLIDG
 VVDLEM.AGG TSGFSVVVAV HRTTAADVRR LVMLALNLDR RL...KTITV
 VDDDVDIRDP REVAWAMATR YQPARDTVVI HGCEAYVIDP SATGDGT.SK
 VGFIATRASG ADSDR..... ITLPPAALAK ARAIIARL.. ..........
 .....     
>Q9I6N5_PSEAE
 .......DFR HFVDHLRRQG DLVDVHTEVD ANLEIGAITR RVYERRAPAP
 LFHNIRDSGA RVLGAPAGAH SRLALHFGLP EHSGPRDIVA MLRAAMRAEP
 .......... .........I APRRLERGPV QENVWLGEQV DLTRFPVPLL
 HEQDGGRYFT YGFHVVQTPD GSWDSWSVGR LMLVDRNTLA GPTIPTQHIG
 IIREQW..RR LGKPTPWAMA LGAPPAALAA AGMPLPEGVS EAGYVGALVG
 EPVEVVRTQT NGLWVPANTE IVLEGEISLD ETALEGPMGE YHGYSFPIGP
 QPLFHVHALS FRDQPILPIC VAGTPPEENH TIGTMISAQL LDVAQNAGLP
 VDMVWCSYEA .ATCWAVLSI DVQRAAFAAR VAETVFGSHA GHLVPK.LIL
 VGNDIDVTEI DQVVWALATR AHPLHDHFAF PQIRVPYLDA EDKARGSGGR
 LVINCLYPEQ FAGQMRAATR HAYPTALRRR VEERWSDYGF ..........
 .....     
>Y1394_METTH
 ........MR NFLDKIGE.. EALVVEDEVS TSFEAASILR EHPRD...LV
 ILKNLKESDI PVISGLCNTR EKIALSLNCR VHEITHRIVE ...AMENPTP
 ISSVGGLDGY RSGRA..... .......... .......... DLSELPILRH
 YRRDGGPYIT AGVIFARDPD TGVRNASIHR MMVIGDDRLA VRIVPRH...
 LYTYLQKAEE RGEDLEIAIA IGMDPATLLA TTTSIPIDAD EMEVANTFHE
 GELELVRCEG VDMEVP.PAE IILEGRILCG VREREGPFVD LTDTYDVVRD
 EPVISLERMH IRKDAMYHAI LPAG.FEHRL LQGLPQEPRI YRAVKNTVPT
 VRNVVLTEGG CCWLHAAVSI KKQTEGDGKN VIMAALAAHP SL...KHVVV
 VDEDIDVLDP EEIEYAIATR VKGDDDILIV PGARGSSLDP AALPDGTTTK
 VGVDATAPL. .......... .......... .......... ..........
 .....     
>Q3C7H6_9CLOT
 ...MENQMLR ATLAQLEKKN LLETCHVEVD PKYELGAVLS HF..NNEKPI
 IFKKVKGSQY PVAGGLFGNR EIYYDMMGTT EKD...RITQ LMDAVANPKP
 T......... .......... ..KTLPKGPV MENIIT.RSI DLQKFPIPKF
 HGGDSSSYIT SGVVVLKDPE TGKVHTSVRR LQMNERNEMS ILVASPLATQ
 ...QYRGFEN QNKPFEVAII LGYDPFLLAS QISSATYGID KYEVDSALRG
 EALELVKCHS VDLEVPAYAE IVLEGIMPPH KREQEGPFGE LMGYYGNQGS
 HPIVEVKAVM HRNNPIMQVA FPCR..EEHL SNGLAREMEL YAYVKN.MVD
 VVDVNVTVSG GCRFHGIVSI KKKSQGDGKS AIIAALASSK DM...KHVVI
 VDEDVNIYSH DEIQWAIATR FQASQDLVMI PGGLGSGLEP SHTLRGVTDK
 LGFDATKPLG E......... .......... .......... ..........
 .....     
>Q2DLY3_9DELT
 ......NDLR DWICLLKREE DLVEIDVPVD EVHAIGPITR SGFKRNLPAL
 HFLNLLHSEA SLLVNAFATR RRLALLLGTE ESQLVQEYIK ..........
 .......... ..RTDRNRWC PPKVAEKAPC KEKKQFHEAV DIRRFPQTVW
 NPCDGGPYFT MGVVRVRNPG NGAANVSVNR LQVKDRNHLT IFTNKERGLG
 ..RAIWNYWE KGEPAPVVVT FGGDPFYLLA AIDTPGVDDD EMALAGGIKG
 QPLEVAYGEI CELDFPAGAE VVFEGVVHPE SYEDEGPFGE VNGYLSEQGI
 APVMEIQAVT HRDEPVFSGT YAGIPPVETT VIQLMIEATL TKTLLKSGVD
 VAQIHIVPGS GGHQAAI.SI RKRNENDLRR VIRFSMAVLP ....IKQVLV
 TDADVDVSIP EQRQWVLSTR FDPAKDIHLI PHAPAINIDP MAQELDTVTK
 MALDATRP.. .......... .......... .......... ..........
 .....     
>Q2CPR7_9EURY
 .......SFR SFLEDLRADG VLEETHEHVS TEYELA...M RATGRG..PM
 LFHNADGH.. VCCINILGSR ELLARALRMD ARNLARDLSA V.........
 ..GFDGHV.. .......... ..REVDSSQF QENILE...P DLMRLPVLRH
 FRGDGGRYIT SGIVVSR..L DDRINACVHR LMVLDRNRLA ARLVPGRHTH
 QMYSR..AIE TGRRLPVAIA IGVDPVVLIA ASTRVPEN.K EFEYASALRG
 DVVEVVTLE. NGVPVP.HAE IVLEGYL.TE KRAPEGPFVD ITGTMDIVRE
 EPVIEITRIM MRDDAIYHAL LPAGG.EHRM LMGVPYEPLI YREASKVV.R
 VRNVLLTEGG CTYFHAVVQI EKQEEEDGLK AIQAAMAAHG SL...KHVLV
 VDTDIDIHDP RELEYAIATR VRGDQDIYMY PNVRGSTLDP RS.VDGMTTK
 VGVDATAKLD .......... .......... .......... ..........
 .....     
>YCOM_RHORU
 .......DLG RIIDRLEALG RLVRVRSEVD PRHDLAGIAA R.FEGGPQAV
 LFEKVAGHAY PVFVGLYWSR ELLGALFDQP ETALPQHVAA SI........
 .......... ..KSWQSAPV DPLVVADGPV LEV..TEAEV DLSTLPIPIH
 ALEDGGPYFD AAVVIAKDPE TGVRNASIQR FQVIGKDRLV INIDAGRHLG
 LYLDK..AAA RGEPLAFTLN VGVGPGVAAA PAEAAPVETD ELGIASAFHG
 APLELVAGTV GPVEMVAHAM WALECEIRPG EVHAEGPFAE VTGYYARVEP
 RPLVRVKRIH RRRAPIFHTL LSGA..EVFN SVGLLGEANV LALLRVQVPG
 VEDVYFSHGG CGFYHCVVKI AQKRAGWAKQ AILATFAA.. .FPPLKMVTV
 VDEDVDIRNG RDVEWAMTTR LDAKTGILVI ENAFGHGLNP TFPNY.LGTK
 VGFDCTRPFP HTPAFDRAKT KAM....... .......... ..........
 .....     
>YPUE_METSM
 .......... .......KDE NIIEITTELS SEFEVAKELR KYPKD...TV
 IIKNVKGYDL PIISGICNTR EKIAKSINCE VSEITQKIIE ASDNPIKVDK
 FTDFSD.... .......... .......... ....YNTTEA NLDKIPILTH
 YKRDGGKYIT AGVVFARDPE TGIQNASIHR MLVLDDKRLV IRIVPR...N
 LYTYFQKAQK LGKDLEIAIA IGMDPAILLA STTSIPIDYN EMDVANAFKN
 GELTLIKC.. GDLEVP.QAD IILEGKISVS ETSAEGPFVD LTDTYDIIRD
 QPIINLSKMH IKKDPHYHGI LSAG.FEHKL LQGLPQEPRI FKSVKNAVPT
 VENVVLTEGG CCWLHAAISI NKQTEGDGKN AIMAALSAHP SL...KHAVV
 VDTDVDVFDP QDIEYAIATR VKGDRDLMIV PNVRGSSLDP VAESDGTTTK
 IGLDATKSLK TLDKFER... .......... .......... ..........
 .....     
>Q88TK2_LACPL
 .......DLR RVLDEIKDDK NYHETDVEVD PNAELSGV.Y RYIGAGGPAM
 MFNNVKGFDT RVLTGLMASR RRVGKMFHHD YQTLGQYLNE ...AVSNPVA
 PETVAEA... .......... ......DAPA HDVVYKATDF DIRKLAAPTN
 TPQDAGPYIT VGVVFGSSMD KSKSDVTIHR MVLEDKDKLG IYIMPGRHIG
 AFAEEY..EK ANKPMPITIN IGLDPAITIG ATFEPPTGYN ELGVAGAIRN
 QAVQLVDGVT VDEKAIARSE YTLEGYIMPN ERIQEDIMPE FPGYDGDANP
 AQVIKVTAVT HRKNAIMQS. VIGPSEEHVS MAGIPTEASI LQLVNRAIPG
 VTNVYNPPAG GGKLMTIMQI HKDNEADEGI QRQAALLAFS AFKELKTVIL
 VDEDVDIFDM NDVIWTMNTR FQADQDLMVL SGMRNHPLDP SERPRGMSSK
 LVIDGTVPFD MKDQFERAQF MK........ .......... ..........
 .....     
>Q3IQ00_NATPD
 .......SFR GFLSALDAAG ELNRIQQPVS WDLEAAAITT RANERDAAIP
 VFETMSGDAA S..ARLVGDP YR......GP PTRPWANVAR GAGIDPRSDS
 TTFFEAMVER LES.....RI EPKTVERAPC KAVVNRGSDA DLLDLPWPYI
 HQGDGGRYSS LHTLVAPDPT TEWGRCGDHR AMIHGTQRAS VRLLAGEQIP
 N.RYYYDYER GGEPMPVAIA IGPPPAVSFT SNLWIPTGRS EFEFAGSIRG
 SAIELVECET NDLYVPATAE IVIEGHIHPD DRLDEGPYGD YLGFMGPRRS
 MPALDVAAIT HRPDPYLPFC VDGSGTGYPF NSSNAIEATI GARAAGFDIE
 RSATWPYTEQ TVF...VFAT EEQYDGYFHD VANFVFTSWG .MLRVDFFIF
 VDADVDPMDP RAVFEAIALH ADPEEDFYQI ERMPKTPLNI YQTPEEKGSK
 AYIDATRAEN AEG....... .......... .......... ..........
 .....     
>Q6LXR1_METMP
 .......... .......... .......... .......VSR ILKENDDKPV
 FIKDVNGY.. PVIGNL.CTR EVIAESLGIE KEDLMKHMVE SMNNEKNGEL
 I..VDESLEK LYI....... .......... ........DD DLEKIPIPTY
 YGKDAGPYLT SGVVIVKDKD EGV.NASIHR ILVRPDGNLA IRMVEQRH..
 LHYIYNKNIG NGE.VDCAIV IGVHPAVLLA ASTSGDVSFN ELKYASALIN
 KPLNLVKCKT VDLEVP.EAE FIIEGKI.TA EMVDEGPFVD ITGTYDVIRK
 QPLIKVTALR RKEDAIFHAL LPGGS.EHKL LMGIPQEPRM YKGIRNTVPS
 LKNVALTQGG CCWLNAVVSI DKKTEGDGKN AILAALAAHP SL...KHVTV
 VDDDINIYDA NDVEYAVATR VQSDKDIIII PGAKGSSLDP SADHKNLTAK
 MGIDATMSLK GKEEFIRAEV PKDDE..... .......... ..........
 .....     
>Q2CGP4_9RHOB
 .......DLQ DHLARLEERG LLTRIACPID KDSELHPLAR WQFQGGIPAF
 LFTDVKGYDI PVVGALAANP EIYAAGLGVP VDEIGAVWVK AMQA......
 .......... ........PI PPEVVTEAPC QEVVMTGEEL TLAALPVPIS
 TPGDAAPYLT ATLVVTKDPE NGIRNMGTYR GQLKARDRLG VRMASRLGGA
 GGYQHWKYKA RGEKMPVAIV IGCAPAVLFT GPQKLPIDQD EMAVAGGLIG
 APVRTVKCRT VDLEVPADAE IVIEGEVAVD YLEPEGPFGE SHGHVALEDF
 NMSMQVTAIT MKAKPVFVSI VSQVTPSESS TLKVAYEPLY FEHLKTVVKG
 IKRVVMHEPL TNIRKVIFLQ FDRSAPQVWR GLQGAAALQA Q..CGKVVIA
 VSEDIEPNNA DAIFWSIAYR ANLSTDLHVT PYRSGGH... .GPKLGRGST
 LMIDATLKAD M......PPL ALPREKYMSR ARQIWEELQL P.........
 .....     
>Q5UWB5_HALMA
 ...MAVNSLR EYLDLLDTTG WLRSFDQPVS WDLEASAATM LANIRDGPVP
 VFESIAG..I ETESKLVGDP YR......GP QTRPWDHFAQ ALGFPSGLSG
 CTYYDRVIAR LNRTKAPRTV ASHR...APC KETVRTGTEV DLLSFPWPYI
 HEGDGGRYSN HHTIVAPDPD TEWGTWSSHR MMIHDSSQAS LLLLAGEQVP
 N.RYYYDYEP RGEPMPVAVV IGAEPTVEST ADMWIPTGRS EAAFAGGLKN
 APVDLVQCET NDLYVPATAE LVLEGHVRPD DRLDEGPFGD YFGYMNPRRS
 MPVFEVDAIT HRHEPRLPFC VVGYGQNSTS TLRLVAAGPD ATVGLRAAGF
 DVAMAVPWRF TSRTVWVIAT DRPYPGYLHE LANFIFTTWG .MLHIDFFVF
 VDAAVDPLDP RAVLTTIALE ADPDADFHQF ERMPKVPLNI YQTPDEKGS.
 .......... .......... .......... .......... ..........
 .....     
>Q38Y45_LACSS
 .......DLR KVLAEIKDPG QYHETDVEID PNADLAGV.Y RYIGAGGPTM
 MFNNVKGFPG RVLIGLQASR QRVATILHHD YKT....LGQ MLEAVTKPVA
 PVEVTR.... .......... .....EQAPA QEVVHLASDA DFDILAAPTN
 TEDDAGPYIT MGVVYGHSVD HQQSDVTIHR MVLEDKDTIG MYIMPGRHIG
 AFLKEYEAI. .NEPMPITIN IGLDPAITIG ATFEPPTGYN ELQIAGALRN
 EAVQVVPGVA VDALGIARAE WIIEAEILPN QSMQEDIMPE FPGYNGSANP
 ANVIKVKAVT HRQDNPIVQT TIGPSEEHVS MAGIPTEASI LSLVDRAIPG
 VLNVYNAPAG GGKLMTIMQI HKDNEADEGI QRQAALLAFS AFKELKTVIL
 VDEDVDIFDW NDVMWTINTR FQADRDIMVL EGLRNHPLDP SERVRGMSSK
 LVLDGTFPYD MQKSFKRAQF ....KEIAD. ....WQKY.. ..........
 .....     
>Q3Y2U5_ENTFC
 .......DLR KVIEELKTPG QYHETDIEID PEAELSGV.Y RYIGAGGPAM
 TFNNIKGFPT RVNIGTMASR KRVGEILHHD YRTLGR.... ..........
 ..FLKDAVEN ........PI KPVKVDKAPA QEVVHLATDA DFNILPAPTN
 TPEDAGPYIT MGVVLGSDPE KTMSDVTIHR MVLEDKDTIG MYIMPGGRHI
 GHFQKQF.EA LNKPMPITIN IGLDPAIAIG TTFEPPTGYN ELWCAGALRN
 EPIQIVDGIA VDEVGIARAE FIIEAEIMPN ETMQEDIMPE FPGYTGDANP
 VQVVKVKAVT HRKDNPIMQT TIGPSEEHVS MAGIPTEASI LALVDKAIPG
 VVNVYNPPAG GGKLMTIMQI RKENEADEGI QRQAAILALS AFKELKTVIL
 VDEDVDIFDM NDVVWTFNTR FQGDKDIIVI PGMRNHPLDP SERFRGISAK
 TIFDGTVPFD MKEHFVRAKF .......... .......... ..........
 .....     
>Y1133_METJA
 .......... .......... .......... .......VSR ILKKYDGKPV
 YIKDVNGFE. .VVGNL.CSR ETLSKIFNVK KEDFI..... ..........
 .FFMLDAMEK EKEGKLKINN KLKEKYIVEI PENIK..... ...NWPIPIY
 YEKDAGAYIT SGVVVVYDKD YG.YNLSIHR ILVKD.DYLV IRMVEQRH..
 LHFLYNKALK EKGYLDVAIV IGVHPAVLLA GSTSADITFD ELKFAAALLG
 GEIGVFE.LD NGLLVP.EAE FIIEGKILP. EVDDEGPFVD ITGTYDIVRK
 QPIIKIEKLY RKEKPIFHAL LPGG.IEHKT LMGMPQEPRI LKGVRNTVPT
 VKNIVLTEGG CCWLHAVVQI EKRTEGDGKN AILAAFASHP SL...KHVIV
 VDDDINIFDI NDVEYAIATR VQGDKDIVII SGAKGSSLDP SSDLKNLTAK
 VGVDATMSLK GREHFERAK. .......... .......... ..........
 .....     
>Q2FSF3_METHJ
 ........MR TFIEQMRTRG LVTDVHDPVS SRYDAP...K RAFSTD.RLL
 FFHNLDGRKA ..VMNLVATR ESLAVALGVA PEILVPRLAS CRYDGKLLDA
 .......... .....GSLPM RP........ .........V NLDEIPIMEN
 YPGEAGRYLN SGVVFSR..Y EGVENASVHR MLKAGKDRLV ARLVEGRHTH
 TLHKK..ALA NGERLPVAIV IGMHPLVLFA SCSRVPESM. ELPFAAELLG
 GEMP.VYTLS NGVRVP.DAE IILEGYIG.N ETAVEGPYVD ITRTYDPERV
 QPVIELTGMY TKPDFIYHG. LVNAGDEHKL LMGAPYEPLI YRSV.AGVTG
 VTDVVLTKGG CGYLHGVVQI KKRTEGDGKN AIMAAFAAHT SL...KHVVI
 VDGDINPGNP SDVEFAIATR VRADRDTLII PGVRGSSLDP SRIGDGLNVK
 MGIDATMELG KEEEF..... .......... .......... ..........
 .....     
>Q5KC95_CRYNE
 .......... .......QKG DIVSITREVD SNLGAAAITR LVYENDLPAP
 LFENVKGSKD ....GLFCT. .......... .......IGA PAALRKDKKT
 C..FGRLAPH LISADKMEPI ELTVLESGPC KQNIIQEKDV QVEALPAPWI
 HKDDGGKYIQ TYDT....PY AINRNFDDLL IKI.....VG MHVI......
 ......QSPD EGKDCPWALC FGVPPAAIMT SSMPIPDGVS EGSYIGTFIG
 ESIPVVKCET NDLLVPATSE IVFEGFLSVT ETAPEGPFGE MHGYVGNSRD
 SPVYKVNCIT HRDDAILPMS ACGRLTDETQ TLIGSLHAVI GEICRDAGLL
 VTECFSPFKY QVTWIALQLM KTTSEELRKK VGDLVFNTKA G.STTHRIVL
 VGDDIDVYDG TDVLLAFSTQ CCPNMDETFF EDVPGFALIP Y.........
 .......... .......... .......... .......... ..........
 .....     
>Q8TYQ8_METKA
 ........MR DFLRCVE..D DLVVVKEELS PEYEVPA... .VLQELDRPV
 VFEGVEGYDI PLVGNLCCSR EYLVRALGAE SDDVLRKLAE AMDSPKEP..
 .......... .......... ...RKERSPS FLEAERGPEF .LKEFPMCRF
 YRTDGGPYLT ASLVVAVEPE EGIPNASVHR MMYLGDGKFA VRVVPRH...
 .LYRYY..EK ADHDLPVAVC LGVDPRTMFA CCARVPYEVS ELDVAAALR.
 .....VYEVD YGIPVPAESE IVMVGRLTP. ERAPEGPFVD VTRTLDERRR
 EPVFEVEKVY TREDPYHPII LPGG.EEHRI MMGGPAEATV LAHVSR.VSE
 VVKVRLTPGG GRWLHAVVSI RKRTEGEAVN AGLAALAAHP SL...KHVVV
 VDEDVDPDDP EQVEYALATR FQADRDLHVV .RGLGSTLDP SAEE.GIMAK
 AVFDATAPVE KRERFEVVEV PVSD.....R VRRILDEL.. ..........
 .....     
>Q5AX16_EMENI
 ........FR SFVEALKADN DLVGINDPID PNLEAAAITR LVCENDEKAP
 LFNNLIGAK. DGFFRILGAP A.......SQ RKSQSERYGR LARHLALP.P
 TASMREILDK MLEADKLPPI PPRVVPTGPC KENVLEGDQI DLTKLPVPMV
 HKSDGGAYIQ TFAYLADPPD .......... .......... ..........
 ........VE EGKPCPLGSS VRRPPAAIMA SSMPILDGVT EAEYVGAMVG
 QPIELTKCDT NDIYVPANSE IVLEGTLSTT DTGPEGPFGE MHGYIFPMHI
 CPKYKVNKIT YRNNAILPMS SCGKLTDETH TMGSLAAAEI RKICQKANLP
 VLDAFAPFIS QVTWVALRID TSKLP..... .......... ..........
 .......... ........TR CKPGVDEVFY DDVRAFPLIL YNGHGGKGGK
 VVSNALMDIE YQGRRNWEAA GSYPEDVKSN VLGKWEKLGF ..........
 .....     
>Q40LE2_DESAC
 .......NFR QHLAWLKSRH QLHTIDQQVD CHLEAAEIVR QLSHQSFPAI
 HLQKLDSSRF SVVANLF... ....FPCGSD DVFSGARDGF CDALAAIPDA
 VPGTLSLAAW LNLLQDQLCS DLKKVET... .......... .LYDLPLLRY
 WPGDAGPYLS LSVAIVRALE .GTIHCGVYR LQFQGPRQLT VHCLPGSRTQ
 QIYRDYQQA. .GQEMPMVVV MGIDPAVLLS ALLPLDTDVD PIGFAGWMQG
 EAISCCASPE HGLPMPSHCE VVLEGVVGRD DPKMDGPHGN FRGTYTTPVL
 CPVMTVDQIW GREDAICPVT VVGPPPAESY CLARARLPYV KWRMTRDFEW
 VTDVKWIETA EYHNALIVQI KD.YCNENGR DVL....FGH QLMGASMVVL
 VDQSADLSCP EQIVWQ.CFN VPWREVVYYH KET....... ..........
 LVVDAT..QI GSRQR..... LESDSQVRRR VEQRLKRWNL ..........
 .....     
>Y2078_AERPE
 ...MEDASLK SF...LEKVG .YRVVDRTLS REYEVARLIA ETQGCGPP..
 LLARIEGVRQ PVAVNVVDTR EKLYKALGVT ........GD SEAYAKIVDS
 T......... .........M RPGRLEDKPP LDEMPEG... .FEGLPAARF
 YEGEAGLYLS SGIVIA..CY EGVCNASIHR LLILGRERAA IRIVPRH...
 LWHLYRKARE RGEDLPATVV VGLHPAVLLA AATSPPLGVF ELGLAAGMLG
 GSMKVYRSPV HGNPVPLGAA MVADVWI.TG EQVEEGPYVD ALLTYDRVRR
 QPVVRLEAAY IKEGEYTH.T IMGGSLEHVN LMGFPREASI WEAVRRALPR
 VRAVRLTPAS GGWLHAVIAV EKQHEGDGKT AIMAAFAAHP SL...KHVVV
 VDSDVDVDDP MQVEWAIATR FQADKDLVII PRARGSTLDP SAA.DGLTAK
 MGLDATKPLD AGMGYERGR. .......... .......... ..........
 .....     
>Q5NWH6_AZOSE
 ......KDLR EALEWFRTQG YLVETDKEVN PDLEITGLQK ..IFDGSLPM
 LFNNVKGMPA RAITNLFGDI RVVEGLFGWE N..SLDRVKK VARAIDHPLA
 PIIIGQ.... .......... .....DEAPV QEEVIT.DDL DVNKLTAIRH
 TPLETELTIG SGISCVVGPY FDGGS..... ..HIGYNRMN FRWQISPGSH
 MWQVMTEHYK DDEPIPLTMC FGVPPSCTFV AYAILPKGCD EIGIAGAIQG
 SPVRLVKCRT IDAYTLADAE YVLEGYLHPR DKRYEGRFHF HPGYMGKAYK
 APTFHVTAIT MRRRESKPII FPGVHTADDA NIDSVRESAI FALCERLQPG
 IVNVHIPYCM TDWGGCIIQV KKRNEGWQRN FLSAILSCSQ GM...RLAIA
 VSEDVDIYSM DDIMWCLTTR VNPRTDILNI PGGRGQTFMP ASNTQFEGG.
 MGIDATVPFG YESDFHRP.. .......... .......... ..........
 .....     
>Q8ZVK9_PYRAE
 .......... .......... ..LRIYNP.. PYGEFT.ISK VLKESEGRTP
 LFKGVKP.GY VGVGNIIDTR AKLYQYLGAK DDE....... ..........
 ........EA YNKLLSAAES PLAVEKVSTW RDVYKTVD.. SLYDLPMVRY
 YEKEARPYIT AGIVIGAGPD .GVYNASIHR FSPVGSRKAV IRLVPRH...
 LYHIYKSSIE RGREVPVAVA WGVHPLVLLA AASSPPYGVF ELTVASRLMG
 .GLKVVE.LD NGALAPFLSS VIIEGFI.TA EQAEEGPFVD IVGVYDRVRL
 QPVVRIERIY VREEAYVHYL LPAGL.EHML LMGFEREAKI WRAVKSVVPR
 VKKVRLTRGG FGWLVAVISL EKSVEGDAKN ALLAAFAAHP SL...KIAIA
 VDSDIDPDDP LDVEWAIATR LRADRGLFVI PYARGSTLDP ALNEEGLTYK
 IGIDATRPLD AD........ .......... .......... ..........
 .....     
>Y1643_ARCFU
 .......... .......... .......... .......... .....DKPVI
 L..NVEGKK. .VAKNFVSSR ETLGKYLGVD AYSIARELSK IED.......
 .......... .......... REAEIRVEPF SSLAMKKVDV NLQELPVIKY
 FPRDGGRYIT AGIVIAQ..R NGVYNASIHR MLLLDESRVA ARLVPPRHTY
 LMWREAVERE EELEVAVVI. .GTHPLFLFA SATRVPSG.K EFSYAAGLMG
 RLTLYRKGE. ..MLVP.DSE IILFGRI.TA ETAKEGPFVD ITGTYDIVRD
 EPVIVFDEMY VKEDYIYYSI TPAG.KEHQM LMGVPYEPVI YRFVSN.VCK
 VKNVITTPGS CHYFHCVVQI EKKSEGDGKN AIIAALAANP SM...KGVVV
 VDDDIDILSY EDMEFAIATR FQPDRDLVVV KGARGSSLDP SADK..TTSK
 WGIDATKPLG KEG....... .......... .......... ..........
 .....     
>Q9HLP3_THEAC
 ...MHGKVLR EFVSDEETAG NVVDVNEDLS PNFEISTLAS .MMEKTGKIM
 RFNSIKNFPF SIITGLFLTE ERMMKILGSA NEDFYRKWAR ITGEGSLPDI
 QIKGSLPADL YP........ .......... ......EDKP NLLSLPVLRH
 YKNDGGRYIT GGIVAARDPN DERINLSFTR IQIISEDRYA F..DAGSHGH
 LWSYLQQSRK SGSSLEMSVI IGAPPIHYLT AAAFMD...D EYRKIG..RI
 FSFDYVKGFR NDVPVPSASE IVIEARYIPN EEYDEGPFAE YTGYMGYDST
 RSVAEVRSLI MRRNPIYVDI MPSNSYEHVN LFSFTRSVGV NRIIRETSPK
 GHDIRIVPNY GSRFLALGYV DPPFPGLAKN TALSAIANDP LWN..KVVMV
 NEGKTDLT.L ERMLLNLAET KNFNRSLTII RDLYTISSDP TARDDGTDSK
 LI........ .......... .......... .......... ..........
 .....     
>Q3IPZ9_NATPD
 ........FR DHLQRLEQDG DALAVESDLH TVDEVAMVGY ESLKHNGPAI
 TYENTAGV.V RLASGAYAGP DRIALAVGLD TGTSYAELLE YTTGLRETTP
 VENGTEPLDA RPAG...... .......... .........I DLGDLGLPVP
 PTCEGG.MAT LGIFAVGGDR TTWSPV...R GRVRGPNRLR VSIPERLG..
 ........EE LGTRARVTVS LGVPCDALLS AYLP...... ..WFTGARQR
 EAFPVARGPD SGMLIPTSSE VVVDGRVVGD AGALEEPLA. ..GWERLLDT
 TTVIAINEIR TRNSPTVPFA SLGAPLSDDI QLAGLLEAA. .KLHRRGVSP
 IEWLLIPPEA RLNFCIVAS. EILYAGFEWQ LANALFTF.. SDSFDKVLIL
 .DTDVPSTDL GKALQDMWVK AHPSHNWIFS TDAPRATAPL YRQDGSTGSR
 LYVDAT..WD ARWDQEYIAP RVGPEEIQAA VRESWTSMGF SD........
 .....     
>Q2JC66_FRASC
 .......... .......... ......EPLS TDVEVAEFER LLGRR..PTT
 LFTQLTDRPG TVLLGHPYPR AVLLAALGTD EGHWLDEVAA RLAGPAPAPA
 AGARPALTEL PG........ .......... .......... .LSALPIIRH
 RPGDVGRYVT AGVGVTTRPD RDGVNLGIYR IQVVGEHEAR IFLDPRTDGH
 ANLGAWTDV. .GEPMPISVF LGADPVHMMV AASRLPNVED DYRVAGMLLG
 RAVRTHGSP. ...PVPESAT HVLHATVRP. ELAREGPFGE FKGYYAEERM
 SNVLDVWEVL AAPGAPMPTI LAGG.ESGLT LMSMQNEYLM YAHLTEIGVP
 VRTVHYPLPA RGEFLALVET DEPT...... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .....     
>Q3HE09_TRIER
 .......... .......... .......... .......... ..LQNGGPAL
 LFENVKGSEH SIAINLLGTE ERVCWAMNIE KPQELETLGK KLGMLQQPKP
 PKKISQAVEF GKVLFDVVKA KPGRDFFPPC QQVVIQGDAL DLNKIPIIRP
 YPGDAGKIIT LGLVIQK... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .....     
>Q5UWB6_HALMA
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... ......MTIA LGVPPAAITT AQTTTPIQSC ..GVTGT...
 ..VPLV..PT NGGLVPSATE VVIETTVV.. DRQPDFRSDR REGWEYVVVS
 GPLLSVESVR ATDTPVIPIS PVGRPADDIQ LTGLATAATL YHRVNNGISP
 VEWVMLPAEA E.LGICFVAS DVLYGGFEWQ LANILFSFS. ..SLFDTVVI
 VDEDVPPQDF GRVLADVWLK SHPARDWTFS PDAPAATRPH YRTDNETGSR
 LYVNA..AWD PRWKETYIAP RVFPGNVRDV ARALWDE... ..........
 .....     
>Q5KEE9_CRYNE
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... ........LV FHGPP..IMA SSMPIPDEVS EAGYIGAFSG
 ASIPVIKCET NNLFVPFTSK IVFEGSFPLP KQPLKFHWEE NARLHLPCHN
 WPVYKANCIT HRDDAILPMS ACRRLTDETH TM........ ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .....     
>Q55097_SYNY3
 .......... .......... .........D PNLEVAQISN RMLQAGGPGL
 LFENVKGSPF PVAVNLMGTV ERICWAMNMD HPLELEDLGK KLAAAPPPRN
 P......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... ..........
 .....     
