>prot (#) default: single protein sequence description=t0356 /home/ppuser/server/work/predict_h21781
MDAMKYNDLR DFLTLLEQQG ELKRITLPVD PHLEITEIAD RTLRAGGPAL
LFENPKGYSM PVLCNLFGTP KRVAMGMGQE DVSALREVGK LLAFLKEPEP
PKGFRDLFDK LPQFKQVLNM PTKRLRGAPC QQKIVSGDDV DLNRIPIMTC
WPEDAAPLIT WGLTVTRGPH KERQNLGIYR QQLIGKNKLI MRWLSHRGGA
LDYQEWCAAH PGERFPVSVA LGADPATILG AVTPVPDTLS EYAFAGLLRG
TKTEVVKCIS NDLEVPASAE IVLEGYIEQG ETAPEGPYGD HTGYYNEVDS
FPVFTVTHIT QREDAIYHST YTGRPPDEPA VLGVALNEVF VPILQKQFPE
IVDFYLPPEG CSYRLAVVTI KKQYAGHAKR VMMGVWSFLR QFMYTKFVIV
CDDDVNARDW NDVIWAITTR MDPARDTVLV ENTPIDYLDF ASPVSGLGSK
MGLDATNKWP GETQREWGRP IKKDPDVVAH IDAIWDELAI FNNGKSALEH
HHHHH
