>query  (#) default: single protein sequence resfilename=i5ngdrf1 description=ser protease /nfs/data5/users/ppuser/server/work/predict_h24518
MDIIFCTPTY CKIMLMIIML ISLRTRCDTN NFLNCSVEKE EGEEEIISTN
LKRINDDMNI LGRILNDERN IKITDIVEML QNEYDDKKKK KKKKKYIYRK
KKSNNKINEI NSVQHFNVKE NILNEKKKNP LNDNFKNPKL RKHSPNNKKN
KNKIGQIKFH IVGYDKKKIT KYLTPSMISS IQKRLMNKNK KTNVNVNMSN
GRVLPFFPKE YFLHSSTHEK KDKMATKKNN KEESIINERL LENLENISLS
RTIKDIRGEE GNERKVKEED NNIKEEGNSF KKYFKGVVKL YVDITEPNLE
MIWQNYPPKS ITGSGFIIEG HLIITNAHNI SYSTRILIRK HGNSGKYEAK
ILYVAHDVDI AILTTDDKTF FDDVYALHFG ALPSLKDEII TIGYPAGGDK
LSVTEGIVSR IDVQYYKHSN YKFLLTQIDA PLNPGNSGGP ALVRGKVVGI
CFQSYKVSNN ISYIIPSTII SHFLLDIHKN KDYTGYAFLG VKYEPLENPS
LREALGLEEM ERKKIIKKNV GILITEVFEG HMSKQDDKYH DMDNKHHNVG
DTHHNVGDTH HNVGDDHTDN LQGDTDYCTY ILNSNIITSD KKNIYSDKKK
KKIYSDNNNN NNNFNYYYNM HGEDEQSCYG LKKNDIILRV DGKDINNDGS
VILRDNETVG FQHLFNEKFI NDLCIIKIVR NKKIKSVMVK LYKVKYLLNQ
HNWDKRNKYF IYGGIVFSIL TRSLYVYTQN PEINKLMLYN NFKKKSKDEI
VVLKNILPTK ITTGYYYTDS IVLRVNNIKV KNLKHLIELI EMTKYTNRLM
YLKNNKHTLQ SYINYYNTKI TSLNINTIIH ILILTTSGQK VPIVLNKRDV
EKYNEEIKKI YSITRDRYVY
