>prot (#) default: single protein sequence description=t0376 /home/ppuser/server/work/predict_h8605
MTASIFSGVI PALMTPCRQD RTPDFDALVR KGKELIADGM SAVVYCGSMG
DWPLLTDEQR MEGVERLVKA GIPVIVGTGA VNTASAVAHA VHAQKVGAKG
LMVIPRVLSR GSVIAAQKAH FKAILSAAPE IPAVIYNSPY YGFATRADLF
FALRAEHKNL VGFKEFGGPA DMRYAAENIT SRDDEVTLMI GVDTAVVHGF
VNCGATGAIT GIGNVLPKEV IHLCKLSQAA AKGDADARAR ALELEQALAV
LSSFDEGPDL VLYFKYMMVL KGDKEYTLHF NETDALTDSQ RGYVEAQFKL
FNSWYADWSK LPGAVQTCKA A
