>prot (#) default: single protein sequence description=t0383 /home/ppuser/server/work/predict_h14724
SNAMNLKREQ EFVSQYHFDA RNFEWENENG APETKVDVNF QLLQHDQENQ
VTSLIVILSF MIVFDKFVIS GTISQVNHID GRIVNEPSEL NQEEVETLAR
PCLNMLNRLT YEVTEIALDL PGINLEF
