>query
 SNAMNLKREQ EFVSQYHFDA RNFEWENENG APETKVDVNF QLLQHDQENQ
 VTSLIVILSF MIVFDKFVIS GTISQVNHID GRIVNEPSEL NQEEVETLAR
 PCLNMLNRLT YEVTEIALDL PGINLEF   
>Q5M157_STRT1
 ...MDLIHEK VFVNRYHYDV RNHEWEKENG VPKTNVEVTF QLHHKDKEAN
 NTSVVAVLQF MIVRDEFVIS GIVSQMNHIQ NRIVNNPKDF SQEEAEYLAA
 PLLDTLQRLT YEVTEIALDR PGINLEF   
>Q3DFR6_STRAG
 ...MEVIREQ EFVNQYHYDA RNLEWEEENG TPKTNFEVTF QLANRDEAAK
 VTSIVAVLQF VIVRDEFVIS GVISQMAHIQ GRLINEPSEF SQDEVENLAA
 PLLEIVKRLT YEVTEIALDR PGVTLEF   
>Q301A7_STRSU
 ...MEIIRDK EFVNQYHFDA RNHAWEKENG IPETKLKVDF QLIEQNRAEN
 RTSMITILRF MIVLDHFVIS GAMSQAVHLP NRLVEEPTEF TDEEKRVLVE
 PLLDILKRMT YEVTEIAFDA PGVNLEF   
>Q97PP5_STRPN
 ...MNLKREQ EFVSQYHFDA RNFEWENENG APETKVDVNF QLLQHDQENQ
 VTSLIVILSF MIVFDKFVIS GTISQVNHID GRIVNEPSEL NQEEVETLAR
 PCLNMLNRLT YEVTEIALDL PGINLEF   
>Q8DUM1_STRMU
 ...MEIVRQK EFVNQYHYDA RNLEWEKENG TPETDVEVTF QLVEKNEELN
 ETTVVAVLQF MIVRDEFVLS GVLSQMVKIK DRLVNQPSEF SQEEVATLAA
 PLLDILKRMT YEVTEIALDK EGVSLEF   
>Q48U42_STRPM
 ...MQLVREK EFVNQYHYDA RNLEWEKENG TPETNFEVTF QLIDKDEQQK
 ETVIVSVLQF VIVKEEFVIS GVISQMVRIL DRLVDKPSEF TQEEVESLAA
 PLLDMVKRLT YEVTEIALDR PGIHLEF   
>Q9CFB8_LACLA
 ..ALTIEREQ EFVNQFHYDA RNYEWEKENG TPETNLNVQF QLVPKEQLEK
 LTGIHAVLTY LIVLDNIVLS GFVSQLNYVR GQIIKEQEEL EQEELAQLAA
 PLFELLKRLV YETTEVALDQ PGINLGF   
>Q837T8_ENTFA
 ...MEIKRQQ EIVEAYHYDM RVPDSE.... .VETDLRVSF SPIEVEEENN
 SSALVARLEF RIVFDEFVLS GAISQINHII DRKIEKQEDI SQEEVDELVR
 PLFSIVERLS YEVTEIALDR PGVQLNF   
>Q38YE6_LACSS
 ...MQTKKDP ISVDAFHFDR VSPDAEPQQN IQVSKIDADD EYLQEAKAGN
 IYQIVTPFQV MPQGSGFAVS GQISRVVQLL D.FFGTPDEI EQKEMMKLSR
 PLIEYIETLT YQVTAVALN. EGIQLQF   
>Q92EM8_LISIN
 ...MDIVTNK IVVEKYNFET QPFENKIELE VHEVEVDGNV ELMAKGKIFK
 IT.....IPF LLVLENFRID GRISRIIQLK D.FFGQFSDL EAKDVEGLSN
 PLIDYIKRLT YDVTEIAFDE PGVSLDF   
>Q5FL89_LACAC
 ...MDFEKQP VTVQSFHYDL VDVAAKSEVN PGIRKLDVSG DDEHSEEEGS
 YYDVAVFFDV IPAPAEFEVS GAIHQIVQIK N.YHGDGTDI SNADWQLLSR
 PLVEYIETLT YEVTQVTFDK P.VNLNF   
>Q74KB9_LACJO
 ...MDFKNTP IVVRSFHYDL NDEQKKNEVN VSLRQVDLED GSQDEGKNGK
 YFEIAVPFEV SPAPGDFTVS GVITRVVQFV D.YFGDGSDL EPSEYQLLSR
 PLVEEIETLT YEITQLTLDH P.VNLSF   
>Q48PZ7_PSE14
 SKAMIFDRQK VFVGSFNFDP RSVLWNTEVG V....LVDSP QLAEELRELT
 LQGMAPSLTY .......... .......... .......... ..........
 .......... .......... .......   
