>query
 MQIHVYDTYV KAKDGHVMHF DVFTDVRDDK KAIEFAKQWL SSIGEEGATV
 TSEECRFCHS QKAPDEVIEA IKQNGYFIYK MEGCN     
>Q2Y5K7_NITMU
 MEMHVYDTWV KAKDGRTMHF DVFTNTRDDK KAIEYAKQWL TSVGEGDATV
 SNRECRFCHS EKAPANVEEA INKDGYFIYK MEGC.     
>Q9I518_PSEAE
 MEVKIFDTHV RTRDGRYLHF DVLVTEELGA RAGEFARRWL AGRGIDEADI
 SQGHCSYCHS EIATAEVAEA IRLHGHYILP LEGC.     
>Q3JBJ3_NITOC
 MQIDVFDTYV TTTEGKRLHF DVFLPTKQGE LARQYAKEWL ESIGIHAKDV
 QQESCAYCHS EAANPKVQQH IKQHGYYIYQ MEGC.     
>Q47UI1_COLP3
 MQIHVFDTHV MTDSGQYIHF DVLVNNENIK EVEQYAKQYL ASLGVKIDNI
 KQSRCNFCHS ELADLEVQDN IANQGHSIIR L....     
