>prot (#) default: single protein sequence description=t0379 /home/ppuser/server/work/predict_h28082
MIRNIVFDLG GVLIHLNREE SIRRFKAIGV ADIEEMLDPY LQKGLFLDLE
SGRKSEEEFR TELSRYIGKE LTYQQVYDAL LGFLEEISAE KFDYIDSLRP
DYRLFLLSNT NPYVLDLAMS PRFLPSGRTL DSFFDKVYAS CQMGKYKPNE
DIFLEMIADS GMKPEETLFI DDGPANVATA ERLGFHTYCP DNGENWIPAI
TRLLREQK
