>query  (#) default: single protein sequence resfilename=s51qafnr description=l1_orf1 /nfs/data5/users/ppuser/server/work/predict_h22591
MGKKQNRKTG NSKTQSASPP PKERSSSPAT EQSWMENDFD ELREEGFRRS
NYSELREDIQ TKGKEVENFE KNLEECITRI TNTEKCLKEL MELKTKAREL
REECRSLRSR CDQLEERVSA MEDEMNEMKR EGKFREKRIK RNEQSLQEIW
DYVKRPNLRL IGVPESDVEN GTKLENTLQD IIQENFPNLA RQANVQIQEI
QRTPQRYSSR RATPRHIIVR FTKVEMKEKM LRAAREKGRV TLKGKPIRLT
ADLSAETLQA RREWGPIFNI LKEKNFQPRI SYPAKLSFIS EGEIKYFIDK
QMLRDFVTTR PALKELLKEA LNMERNNRYQ PLQNHAKM
