>prot (#) default: single protein sequence description=t0368 /home/ppuser/server/work/predict_h26460
MKPLKEVVGA YLALSDAQRQ LVAGEYDEAA ANCRRAMEIS HTMPPEEAFD
HAGFDAFCHA GLAEALAGLR SFDEALHSAD KALHYFNRRG ELNQDEGKLW
ISAVYSRALA LDGLGRGAEA MPEFKKVVEM IEERKGETPG KERMMEVAID
RIAQLGASNQ QKKPGYKAWW EFWS
