>query  (#) NP_002864 /nfs/data5/users/ppuser/server/work/predict_h18221
MNQVTDWVDP SFDDFLECSG VSTITATSLG VNNSSHRRKN GPSTLESSRF
PARKRGNLSS LEQIYGLENS KEYLSENEPW VDKYKPETQH ELAVHKKKIE
EVETWLKAQV LERQPKQGGS ILLITGPPGC GKTTTLKILS KEHGIQVQEW
INPVLPDFQK DDFKGMFNTE SSFHMFPYQS QIAVFKEFLL RATKYNKLQM
LGDDLRTDKK IILVEDLPNQ FYRDSHTLHE VLRKYVRIGR CPLIFIISDS
LSGDNNQRLL FPKEIQEECS ISNISFNPVA PTIMMKFLNR IVTIEANKNG
GKITVPDKTS LELLCQGCSG DIRSAINSLQ FSSSKGENNL RPRKKGMSLK
SDAVLSKSKR RKKPDRVFEN QEVQAIGGKD VSLFLFRALG KILYCKRASL
TELDSPRLPS HLSEYERDTL LVEPEEVVEM SHMPGDLFNL YLHQNYIDFF
MEIDDIVRAS EFLSFADILS GDWNTRSLLR EYSTSIATRG VMHSNKARGY
AHCQGGGSSF RPLHKPQWFL INKKYRENCL AAKALFPDFC LPALCRQTQL
LPYLALLTIP MRNQAQISFI QDIGRLPLKR HFGRLKMEAL TDREHGMIDP
DSGDEAQLNG GHSAEESLGE PTQATVPETW SLPLSQNSAS ELPASQPQPF
SAQGDMEENI IIEDYESDGT
