>prot (#) default: single protein sequence description=t0375 /home/ppuser/server/work/predict_h7366
GSQILCVGLV VLDVISLVDK YPKEDSEIRC LSQRWQRGGN ASNSCTILSL
LGAPCAFMGS MAPGHVADFV LDDLRRYSVD LRYTVFQTTG SVPIATVIIN
EASGSRTILY YDRSLPDVSA TDFEKVDLTQ FKWIHIEGRN ASEQVKMLQR
IDAHNTRQPP EQKIRVSVEV EKPREELFQL FGYGDVVFVS KDVAKHLGFQ
SAEEALRGLY GRVRKGAVLV CAWAEEGADA LGPDGKLLHS DAFPPPRVVD
TLGAGDTFNA SVIFSLSQGR SVQEALRFGC QVAGKKCGLQ GFDGIV
