>novel_seq
 MRPTPMTAIL ALSLAAAAPA MAASLKDIAP YPEAEKGFTR QVIHLPAQAD
 ESAYKLEILA GKTLQVDCNR QRLGGNLEAH TLEGWGYNYY RLDNVSGPAS
 TLMACPDGKK TEAFVPVVGD GFLLRYNSKL PVVVYVPKDV EVRYRVWSAS
 QDVQKAKVE 
>ECOT_PSEAE
 .......... .......... .........P YPKADAGFTR QVIHLPKQDA
 EDAFKVEIIA GKTLEADCNQ QRLGGELEEH TLEGWGYSYY RLDKVSGPMS
 TMMACPGQKK EQRFIPVVGE GFLLCYNSKL PIVVYAPKDV EVRYRIWSAS
 EKVEKAVSE 
>ECOT_PSEF5
 .......... .......... .....EDTAP YPKAEDGFTR QVIHLPKQQH
 EDRYKVEILA GKTLTVDCNL QRLGGKLLEK NLEGWGYPYY RLDQVSGPIS
 TRMACPDGKT REDFVPVTGD GFVLRYNSKL PIVIYAPKDV EVRYRLWSAA
 DKTENARQE 
>Q3KCZ4_PSEPF
 .......... .......... .....EDTAP YPKAEAGFTR QVIHLPQQAQ
 EENFKVEILA GKTLEVDCNR QRLGGTLEEK NLEGWGYPFY RLEKVSGPMS
 TLMACPPGQK KRVFVPVIGD GFTVRYNSKL PIVVYAPQDV EVRFRIWSAS
 DKI...... 
>ECOT_SHIBS
 .......... .......... .....EKIAP YPQAEKGMKR QVIQLTPQED
 ESTLKVELLI GQTLEVDCNL HRLGGKLESK TLEGWGYDYY VFDKVSSPVS
 TMMACPDGKK EKKFVTALGD AGMLRYNSKL PIVVYTPDNV DVKYRVWKAE
 EKIDNAEV. 
>ECOT_YERPE
 .......... .......... .....EKIAP YPQAEKGMSR QVIFLEPQKD
 ESRFKVELLI GKTLNVDCNR HMLGGNLETR TLSGWGFDYL VMDKISQPAS
 TMMACPDSKP QVKFVTALGD AAMQRYNSRL PIVVYVPQGV EVKYRIWEAG
 EDIRSAQVK 
>Q453B5_9BURK
 .......... .......... .....ESIKM FPQAATGQQR VVIALPALEN
 EGDARVELMI GKTLQTDCNQ QWFGGELTAE DVKGWGYTYY RLTDVKGPAS
 TLMACPGQAP QQRFVQVRGD GQLLRYNSRL PLVVYVPDGF DVRYRVWHAS
 KDVQQA... 
>Q2T036_BURTA
 .......... .......... .....EDIKM FPAAQAGQKR EVIVLPAEKL
 EEDIRVELVV GKTIKVDCNQ HWFGGDLKHE TVQGWGYPYY VLADAKGPAA
 TLMACPGQEP QEAFVPVRGS GYLLRYNSRL PIVVYVPKEF EVRYRLWYGS
 NEVARA... 
>Q4UMT9_RICFE
 .......... .......... .....KDIAP YPLPTDSQKR YVIHLPTESN
 EEKLKVELQA TKNAMKDCNR VWFGGKLETK TLEGWGYNYY IIDQVSDPAS
 TMMACPGIKA TIKPVSVLGD ETFLRYNSKL PIVVYAPKEV ELHYVIWHQN
 DIINSAK.. 
>Q33VT7_9GAMM
 .......... .......... .......... FPAPTDGLVQ HILTLPKLAN
 EGDYRLEIAI GRSEEVDCNK HGLSGEITQH TVKGWGYNYY QVDAIHQGPS
 TMMACFDKAK KTAFL.TLPE KLTLAYDSRL PKVFYLPAGA QLRYRIWQAS
 SDYQYSEAK 
>ECOT_SHEON
 .......... .......... .......... FPAPKKGMVQ HILTLPKLEN
 ETDYMVEIQI GQTQLVDCNK HGLNGQLKEL TVEGWGYNYY QVDEISEGPS
 TMMACFELAK KEAFVQ.IPD ELTLRYDSRL PKVFYLPEGA ELRFRTWKAD
 STYQYSK.. 
>Q3X9L5_METFL
 .......... .......... .........P YPQPADGYQR NVIHLPMLAD
 EENTKLELQV GKTMQVDCNH HSFGATVVEH TVKGWGYPYY EVNSIGGPIS
 TRMACPSGTE TSKFV..... .......... .......... ..........
 ......... 
>Q3QDU3_9GAMM
 .......... .......... .......... FPAPAAGMVQ HILTLPALEN
 EGNYMVEVQI GQTKLVDCNK HGLRGELQTR DLQGWGYNYY EVTEIGEGPS
 TMMACFDKAK TEAFVRIPGD .YKFAYNSKL PMVFYIPEGA ELKYRVWRAD
 TVFNTSK.. 
>Q6QDA1_PANCI
 .......... .......... .......LKP YPAASEGMQR HVMVLPPLNN
 EQQYRVELVI GRKMETDCNH YRLAGRLTEE TAKGWGYSYY TATVQPDAIS
 TRMACTDSAK KTILVPAAAQ Q.LIRYNSNL PLVVYAPTDV EVGYRVWQAA
 QQIVPSQV. 
>Q43Q50_SOLUS
 .......... .......... ......DLKA FPPAEKGMTR YVIRLRQEKN
 EAALKVELIV GKTVKTDGNR YFFAGKLETE SIPGWGYDRY ILRKLGPMAG
 TLMAVPNAPQ VERFISGSGE T.MPRYNSRL PVVVYVPEGV EVRYRVWSAG
 A.TQTAKPE 
>Q3NKD7_SHEFR
 .......... .......... .......... YPAPTEGMVQ HVLTLPALND
 EQDYMLEVQI GQNKIVDCNK TKLIGEIDKI SLAGWGYVYY QVDKVMQGPT
 TKMMCTNAKS AE.FI.VLNE AMTLRYDSRQ PKVFYLPEGT ELRYRVWKTV
 SEFE..... 
>Q4D4Y5_TRYCR
 .......... .......... ........AP YPEATPNQKR YVIFLEEKDY
 DSEYKLQLIP GRVMKVDVNR CFIAGSVKEK TIPGWGYNYY VVE..MGPAT
 TLMAVPGSPP VRKFVPMAER PF.IPYNSKL PVVVYMPKEG ELHYRVWTPT
 K........ 
>Q4QFD4_LEIMA
 .......... .......... ........AP YPEPTSQQRR YVIFLDPKGD
 SKEYKVELIP GRVEKVDTNV YRMGGNIEER TIDGWGYPYY IVTLTTMSGT
 LMMPLGDAAL KRPRFVAMNT KNLYRYNSRL PIVVYMPKDG ELRYRIWT..
 ......... 
>Q4QFF0_LEIMA
 .......... .......... ........AP YPEAEAGEKR IIFALDPKGD
 EVEQELQLIP GRVLEMSANH QTLGGSIEQH TVEGFGAKFF HVKLAKQAVS
 TLMAEDHGEK VRKFV.AMSN APMFPYRSRY PVVVYLPKDA ELRYGIWCGG
 QQMQAA... 
>Q4QFD3_LEIMA
 .......... .......... .........P YPAAAPGQVR KVIYLPRQVE
 QQHLRVQIIP GRHENCDDGR YKLTGSVTEE TLQGWGYSYY VV.TLGDIYA
 AHRSSSDPAR ATTFV.ALDE SPVIAYNSKL PIVVYVPEGA ELRYRIWSLA
 QSIQQ.... 
>Q57ZQ7_9TRYP
 .......... .......... ........AP YPEPGPDQTC CIILLEEKPD
 EEEYRVELIP GRVMEDGLAT GTVSGVVREE VIHGWGYSYY VVE.MEPLVT
 TRRSIRSFHR PTRFVPVPTK HF.IRYNSQL PVVVYLPHNT ELRYRVWTPI
 .DMQKVE.. 
>ECOT_PROMM
 .......... .......... ......DLND YPQPIAGHQR WVIQLPGLLA
 KSSWRVQLIV GRTIQLVCNQ YHLAGQLRME RFQG..AEQR MLYSVAGAVS
 TRMVCPDEPK RESFLVLGSK PYLVPYNASF PIVVDVPDGL EVRWRLWKA.
 ......... 
>Q3P493_9GAMM
 .......... .......... .........P KPTANQAV.. HIIKVDTLPE
 ASQYQLQVQI GLNIMQDCNQ RRLMGNQAAK TSQGVTHYYW LESLMEAPMV
 TL.PCIEAKK A.TFVQ.LGE TLLIESGEFS ENVFYLPQQA QLRYRLWRAT
 ETWQYSQ.. 
>Q57ZP2_9TRYP
 .......... .......... .......... .......... ..........
 .....VELLP GRVETVDVNT YYINGCTTEE KFPGLDYTCY RVDLRDTYRS
 RCAVPPEATP EEKFISHRHR K.LIPYNSRK PVVVYLPEDA QLHYRIWTGG
 QEVVAKKAE 
