>query  (#) default: single protein sequence resfilename=q5zeshcf description=q96i38_hs /nfs/data5/users/ppuser/server/work/predict_h25746
MRSGKASCTL ETVWEDKHKY EEAERRFYEH EATQAAASAQ QLPAEGPAMN
GPGQDDPEDA DEAEAPDGGS RRDPRKSQDS RKPLQKKRKR SPKSGLGPAD
LALLGLSAER VWLDKSLFDQ AESSYRQKLA DVAAQAAWPP ALAPWGLCTH
GNQVACHHVT WGIWVNKSSF DQAERAFVEW SQALLLAPEG SRRQGTPNTG
QQVAVPDLAH QPSPPVNGQP PLGSLQALVR EVWLEKPRYD AAERGFYEAL
FDGHPPGKVR LQERAGLAEG ARRGRRDRRG RNILGNKRAG LRRADGEAPS
ALPYCYFLQK DAEAPWLSKP AYDSAECRHH AAEALRVAWC LEAASLSHRP
GPRSGLSVSS LRPNRKMATN FLAHEKIWFD KFKYDDAERR FYEQMNGPVA
GASRQENGAS VILRDIARAR ENIQKSLAGS SGPGASSGTS GDHGELVVRI
ASLEVENQSL RGVVQELQQA ISKLEARLNV LEKSSPGHRA TAPQTQHVSP
MRQVEPPAKK PATPAEDDED DDIDLFGSDN EEEDKEAAQL REERLRQYAE
KKAKKPALVA KSSILLDVKP WDDETDMAQL EACVRSIQLD GLVWGASKLV
PVGYGIRKLQ IQCVVEDDKV GTDLLEEEIT KFEEHVQSVD IAAFNKI
