>query  (#) default: single protein sequence resfilename=3biwxzsa description=rs /nfs/data5/users/ppuser/server/work/predict_h14539
GLSSTEDEGE DPWYQKACKC DCQGGPNALW SAGATSLDCI PECPYHKPLG
FESGEVTPDQ ITCSNPEQYV GWYSSWTANK ARLNSQGFGC AWLSKFQDSS
QWLQIDLKEI KVISGILTQG RCDIDEWMTK YSVQYRTDER LNWIYYKDQT
GNNRVFYGNS DRTSTVQNLL RPPIISRFIR LIPLGWHVRI AIRMELLECV
SKCA
