>prot (#) default: single protein sequence t_ecgo_ecot_spek
MRPTPMTAIL ALSLAAAAPA MAASLKDIAP YPEAEKGFTR QVIHLPAQAD
ESAYKLEILA GKTLQVDCNR QRLGGNLEAH TLEGWGYNYY RLDNVSGPAS
TLMACPDGKK TEAFVPVVGD GFLLRYNSKL PVVVYVPKDV EVRYRVWSAS
QDVQKAKVE
