>prot (#) default: single protein sequence description=t0351 /home/ppuser/server/work/predict_h3632
MILYDAIMYK YPNAVSRKDF ELRNDGNGSY IEKWNLRAPL PTQAELETWW
EELQKNPPYE PPDQVELLAQ ELSQEKLARK QLEELNKTLG NELSDIKLSL
LSLKGDYAEL EHHHHHH
