>query  
MADFKEKIAH HAELAWFIVM LVMVAVFFSW SVIEVTNGSS TSIRYGLPLF
SGLPAQAQQA VLTFEKSPPA NHTSEIINGI LVVNMTAEQN GSFSDVFHPN
VIVAQPGEPI TIILNSPQVI TGFFIRLPDG VVNVNAIPGE PSYVYFVAPN
QPGNYTWREP ELAGYDFSYM TGTLEVV
