>query  (#) gi|146303259|ref|YP_001190575.1| hypothetical protein Msed_0474 [Metallosphaera sedula DSM 5348] /nfs/data5/users/ppuser/server/work/predict_h19793
MESIKLTDIF NVRRNKIVFF TTFVLYFLFY QYVDRILLVS NVLLPQGVNV
IVTTSTPVPP SQMPYPLWGP FLAITTRYFD WAMTPLSLGI SFILSFLVAL
NVTLYVALFS LMRTRTTHKL AVSLGLLATS LSCSCELFTA LIGATVSNIP
FLVSIAFMDT LGELLTIVAG VILTISSLVI ASEITGSNPF AWMKWNHGVV
PALVFTGAMF LIPSSETFFL VRIIDGLLAG GIWGYILSRK LTERINLSQG
VRKTLFLASV VLVSIQFLLF PLMPIWSFSA VSLLAGLLGS LGYTSLKPWV
RLGLLHVIGW SLIMPGPISL ILGSPIPFYN ITGGQAILLW ITAWIFGTPI
AWLAGIQYLQ YIRDKMSQYS LTPSQLRIPQ RSRTDGLTWI ALGGVAVFSQ
IVFFMTHSAY FLDYNGYDLV FLETMTLSAT GLMIAGLVLM GYGGYLMIKS
RYTIPKINRK YFVIASVAYA IVEMLVTKMM IIAPTGYPYP PVLLLTYGEP
MYAPAVTIYV PGIIGFYLYP ASVLALIASS VLSGAIWALV FQTRRRNLGS
LTAFSVLTAC PSCGLSAVGY AVTSVVTASS ALMTFYGDLG FTLASVGILV
GLLVYVIKST TTCRVDVTKI RQS
