>prot (#) default: single protein sequence description=t0350 /home/ppuser/server/work/predict_h1841
MNIERLTTLQ PVWDRYDTQI HNQKDNDNEV PVHQVSYTNL AEMVGEMNKL
LEPSQVHLKF ELHDKLNEYY VKVIEDSTNE VIREIPPKRW LDFYAAMTEF
LGLFVDEKKL EHHHHHH
