>query
 MNIERLTTLQ PVWDRYDTQI HNQKDNDNEV PVHQVSYTNL AEMVGEMNKL
 LEPSQVHLKF ELHDKLNEYY VKVIEDSTNE VIREIPPKRW LDFYAAMTEF
 LGLFVDEKKL EHHHHHH   
>YVYC_BACSU
 MNIERLTTLQ PVWDRYDTQI HNQKDNDNEV PVHQVSYTNL AEMVGEMNKL
 LEPSQVHLKF ELHDKLNEYY VKVIEDSTNE VIREIPPKRW LDFYAAMTEF
 LGLFVDEKK. .......   
>Q65EB9_BACLD
 MSINRLSSLE PIIDAYKTQM LNKQYEAVER PQQTDAAEQL EKTIQGANNL
 LEPSQVHLQF VLHEKLGEYY VKVVDNRTEE VVREIPPKEW LDFYAAMAEF
 MGLIVDK... .......   
>Q5KV86_GEOKA
 MTVERVSSHS ..LSYLYESV RNEKASSMIE PHQQHHTNNL ETTAQDINEF
 LQPSHTSLKF ELHDELQEYY VQIINERTNE IIREIPPKKL LDMYAAMMEF
 VGLLVDKK.. .......   
>Q2B1U5_9BACI
 ....RTTSL. ...DKAVTQV NIEQDTEKDT YRNEDSKEKL GDIIEGMNEF
 LQPSNTSLKF ELHEKLNEYY VTIVDNDTHE VVKEIPSKKM LDMYAAMTEF
 VGLVVDKK.. .......   
>Q47HZ2_DECAR
 .......... PAQGAPSSSA MGQNAPASET TRQKPGKEEL AQMTKAVNDF
 VKPLNSALQF NIDDSTGQTV VKVIDTDTKE VIKQIPSEDM LALAKALDQI
 KGFLVKQK.. .......   
>Q34XE6_9GAMM
 .......... PASESAPASE PARDPARAED PRRGTDPEEV GEAVDRINEF
 VQLVQRDLEF SIDEDTGRTV VKVFDSQSEE LVRQFPPEEI LAIAEHLEEL
 KGLLVRE... .......   
>Q82UA2_NITEU
 MNINAVTAVQ PAMPAARTG. EREMAPAAQP PAETSDPEQV KEAVNQIQQF
 TQALTQNLKF SIDEDTGKTV VKIVDAQTQE VIRQMPSEEA IKIASALGKI
 QGLLFN.... .......   
>Q485N2_COLP3
 .SVNKL..VE SVNEQPKTSV NEQINNDNET P...LSPKQL EKVAQQLQDF
 VGEMNRGLEF SVDKDSGRDV IKVIDKTSGD LVKQYPSEEV LTLVAKLSDS
 VGGFIDAK.. .......   
>Q428V8_DESHA
 .......... .......ESG KNQSQSQGDK GKEELTREDA SKLAEHLNKF
 MVTVNADLRF EMHDGTQRLM VKFIDIKNNQ VIKEFPPHEL LDTLAAIRDY
 VGVLLDKR.. .......   
>FLAG_VIBCH
 .NSRSVSRTD KLSEHFSEQV RARQQESAET QRQRLNEEQL AKMVEQMNEF
 VKSINKGLSF RLDRESGREV VTIYEASTGD IIRQIPEEEM LEVLRRLA..
 .......... .......   
>Q3CDJ3_9CLOT
 ...NKVSETK AMDSSPKPQI QDVLKRKKEG EHLNIREEKL IEMIEQANKF
 LLKPPTELQF SVHEDTKRIS IKIVNTENQE VLREIPPEKL LDMVAKMWEL
 TGLLVDEK.. .......   
>Q8ENI1_OCEIH
 MTVNNIGASK PAVVDIPTNK VALSQTKNEN SHQTVNKVDL EDAVDHMNEL
 LKPIRRNLKF EMHEKLERYY VTVVDSETSE VIKEIPPKKM LDMYAELAEF
 MGFLIDEK.. .......   
>Q3N7W2_9PROT
 .......... PVPPM.DCSI REEPPAAEKV EHDVIQPEQV EAAVNQIQQF
 TRTLTQNLKF SIDEDTGKTV VRIVDMQTQE VIRQIPSEEA IRIAGALGKI
 QGVLFN.... .......   
>FLAG_VIBPA
 .......... .......... ..QAAIEMAE SRQELNREER EKMVEQMNEF
 VSSINKGVAF RVDEESGRDV VTIYEANTGD VIRQFPDEEL LVVLRRLAEH
 TGLLVEK... .......   
>Q2ZH41_CALSA
 .......... ......KEEV NDKLADKNS. .RKELDEDTL IKMINQANKA
 FEAKYTRLEF SIHKETHEIV VKVYDKETNE LIREIPPEKI LDIIAKLWEL
 AGIFVDERR. .......   
>Q9I4N7_PSEAE
 .......... .......... .......... .....SRDDL GLAVSDIQSF
 VQSVKRNLNF SIDDSSGQVV VKVIDGDSGE VVRQIPSEEV LKLAARLDDV
 HSVLFETR.. .......   
>Q2CR29_ECTHA
 .......... .......... .......... ....DDPEAL AKAVERMEKF
 MQQVGRDLEF RVDDATGKTV VTVYVRGTDD VVRQIPPEEM LAIAARMREV
 QGLLFN.... .......   
>Q2XEV0_PSEPU
 .......... .......... ....PNAISA AEHSNDAEKV KSAVSEIEKF
 LSATRRNLEF STDEESGKIV VKVIASETGE LIRQLPSEEA LRIAHNLSDV
 NSILFDAK.. .......   
>Q3C4I7_9CLOT
 .......... .........V MDETQFRENP MKKEVDQERL MPIIDQANKS
 FEAFDRRFEF SFHEKTNAIM IKVIDRNNDE VIREIPPEKL VNMMANMLEV
 AGLLIDER.. .......   
>Q36B54_9GAMM
 .......... ...DAAVSAV ..EQSTEQSA AENEQNPRKL TQVASELSDM
 MSMMRKGLAF KVDENSGQAV VTVLDRDTGD VIRQMPSEEA LKLAEKLSEV
 TGLLMKT... .......   
>Q3IDX2_PSEHT
 .......... .......... ..QSNAATTT QQQQLEREQL EKVAQQLQDF
 MGEMNRSLQF QVDEDSGRDV IKVLDKTTGD VIKQYPSEEV LSLVSKLSET
 AGLLIDQ... .......   
>Q73MN5_TREDE
 .......... ....RAASDV IVQKEAAEQA ENQKVDPNEI SKAVAQIQKL
 CDMCDRKLQF RVNKETNRIV VKVIDANTDK VIREIPSEAI QRLQARILET
 VGLLFDE... .......   
>Q4CGU5_CLOTM
 .......... .......... .......... ....LSQRAI IKAIEKANKA
 INGIHTELEF SIHEKSKEIM VKVIDSETKE VIREIPPEKI LDMVAAMLEM
 AGIIVNER.. .......   
>Q44D66_CHRSL
 .......... ..LDMALAHL RPESATQVAS PSSSLTMSEL AAPIQRVNEV
 MSAYN..IQF DLSEYEGRIV TRIVDRESQE LIRQIPSEEV LRIAEALEQR
 QGRLI..... .......   
>Q2D326_9FIRM
 .SLQEQTSVK RVDEAQGAVD NSFNKSAEYG DKQEVNKGQA EQAIDKLNKT
 METYNTELRF KLHEKSGEYI VKIINPKDDS VIREIPPERV LNMVAYFKEM
 LGIVVDK... .......   
>Q9K6V9_BACHD
 .......... ...SQYAGQV GVQVQETVQL EEYEPSKRDV QHKIDDINKV
 IETLNTGVRF ALHEDLNEYY VTIVDKITNE VVKEIPPKKL LDIYAAMKET
 ISVFFDKK.. .......   
>Q34XE7_9GAMM
 .......... .......... ......AAET ARQEKAAEQV GQAVDRINDF
 VQVVQRDLEF SVHDDTGRTV VRVFDTNSEE LVRQFPADEI LALAEQLDRV
 RGLLV..... .......   
>Q7MIM6_VIBVY
 .......... .......... ..EAAVKMAQ ARQELNREEK LRMVEKMNEF
 ISSINKGLSF RVDEESGRDV VTIYEAKTGD IIRQIPDEDM LDVLAAQATS
 SGLLVDK... .......   
>O33420_PSEAE
 .......... .......... .......... ..DKEQRAAV EEAVSSIEKF
 TQSIRRDLSF SLDDSTGRVV VKVTDSTSGE VIRQIPSEEA LRLAERLDEA
 RSLLFK.... .......   
>Q2X3E7_9GAMM
 .......... .....AIEQT VVQDDIENE. ..QHPDPAKL SQVATELSDM
 MSMMRKGLAF KVDEKSGQAV VTVLDKDTGD VIRQMPSEEA LALAEKLSEV
 TGLLMKT... .......   
>Q2ZC81_9GAMM
 .......... .......... ....QAAEDV KASENKEIEL QQAVDDIATS
 MDFIQKGLAF KIDKELGEPV VRVIDISTGD LIRQIPNEEA LEIAKKLNEV
 TGLLMKT... .......   
>Q428T1_DESHA
 ...NHQKTMM PV.DAYPGQK LERSQEKNEI PREEIPREEV EKAVDKLNRF
 MGLINKGMRF VHEEDEEEIL VRIVDQDSEQ VLKESTPKWV MELLHNLTDV
 AGLFVDQR.. .......   
>Q3NUF5_SHEFR
 .TIIHTTEVD KVLTKTIVET QADANTAAET KKEQSQAEAL AVVVEQLSEV
 MSIMNKGLAF SIDDDSGSAV VKVMDIDTGE LIRQIPNDEA LELAQKLLDV
 KGLLMRT... .......   
>Q3KG35_PSEPF
 .......... PVVDKPSETP ERNTVAPVAD KKQDTDEAKL KLAVQEIEKF
 VQSIKRNLEF SIDEHSGKVI VKVIASETGE VVRQIPSAEA LKLADSLANA
 SHVLFDAK.. .......   
>Q3XBE2_METFL
 .......... .......GSK EAEQQASVA. .....SDADV QSAVEQINEF
 ISPIMQSIQF STDADSGRVV VKVVDSETQK VLRQIPNEEV LAISKTLDKL
 QGLIIRQ... .......   
>Q39YG8_GEOMG
 .......... .......... .......... ......EERA KAAADRINEF
 IESFTRDLKF TIDKDSERVV LKVVDRKSGD VIRQIPSEEA LKIAKALDEL
 KGLIIRE... .......   
>Q748I7_GEOSL
 MNIEATSGTG PSAVAVVPTI VAKSRQDEEE PEKESDEERV KEATERINEF
 IESVSRDLEF SVDKDTNRTV VKVLARESGE VIRQIPAEEV LKIARMLDEL
 KGLIIREK.. .......   
>FLAG_VIBAN
 .......... .......EQL RNRQNQSVEA QREQINKSER AKMVEQMNEF
 ISSINKDLAF RVDEESGRDV VTIYEASTGD IIRQIPNEEM LEVLRRL...
 .......... .......   
>Q3CFX7_THEET
 .......... ......DSGL LEEIKAVKDI LSKPVDDDKL NSALNKENRK
 ISNDHTYFEF SVHKPTNTIM VKIVDSDTNE VIDEIPPEKI LDLVAGLWKI
 AGLFVDRK.. .......   
>Q4ZQS5_PSEU2
 .......... PADAKPVERV AAPAESKGSD LHKDNPKDKV KAAAEDIQKF
 FHAVKRNLEF SIDEDSGKVI VKVIASDSGE VVRQIPNAEI LKLADSLSDA
 NSLLFRAK.. .......   
>Q5WDF1_BACSK
 .......... .......... ..QQQNTKQP P...IDGTKA AAFINETSQQ
 LNKVKRSLNF HIHEELDRIY VQVIDEETNE VVREVPPEKI LDLVAAMLKS
 VGLIID.... .......   
>Q48GD4_PSE14
 ......KSVD KPADTP..SV ERVAATAESK GSDSHDEAKV KAAAEDIQKF
 FHSVKRNLEF SIDEASGKVI VKVIASDSGE VVRQIPNAEI LKLADSLSDA
 NSLLFRAK.. .......   
>Q6LTQ0_PHOPR
 ......SNIQ QSSDKGQTDI RRVEQTASAE KQSEMQRQQL EKVVEQLEEF
 VGTLNKGLAF RIDEESGRSI VTIYDKSSGE IVRQIPDEDI LTLSRQIASH
 SGGLV..... .......   
>Q3SII4_THIDA
 .......... ....APPTAV PNLQRTAADP AAEQPSAMQL KNVVEAINKT
 LQQANKNLEF IVDSETHDPV VKLVDSETGD VIRQFPTEEA LSIARAIDSF
 QGLLIKQK.. .......   
>Q5TK99_PSEFL
 .......... .......... .......KDE PKDAVAEEKL KRAVQEIETF
 VQSVKRNLEF SIDEPSGKVV VKVIASGSGE VIRQIPNEEV LKLANSLNDA
 SSLLF..... .......   
>Q3J8M2_NITOC
 .......... PQSPAADSP. ...QPKTEER EKREEGPQQL VEAVQNINDF
 MQAVRRELQF SIDEATGRTV IKVIDRENGE MIRQVPSEEV MALAQRIAE.
 .......... .......   
>Q2BI10_9GAMM
 .........D KVQRQPVEPQ NNERYQQQAK QTQEVSAEKL EAAIDRLNEM
 MKSGQRSLNF SVDSSSEKVV VQVRDLSTDQ VIRQIPNEEA LRFAESLDRM
 MGLIFNE... .......   
>Q3P160_9GAMM
 .......... .......SSI QAVSNTTLEE SEKKLAPEDL NKIAEELTDM
 LSLMRKGLTF SVDDDSGRQV ISVKDIASGD LIRQIPSEEA LNLAEKLSEF
 TGLL...... .......   
>Q88ES6_PSEPK
 ........LN SVLSAPATQE ARSAQPSSDV PTKEVQRPEL EKAVSDIQEY
 VKASQRQLDF SVDDSTGTLV VKVIATGSGE VIRQLPSEAA LSLARSLAEG
 DGFLLD.... .......   
>Q46QZ6_RALEJ
 .......... .......... .......... .......... .AAVGELVEA
 LKSTSISLRF EIDESTHRVI TKVVDKETGE LIRQMPTVEV LRIASAIDKL
 QGLFVSQ... .......   
>Q2RKF7_MOOTA
 ..VQSQTQKP AVQDTKKINV DSDQEKRRQD GQAGYSRGDL EQAVAKLNTA
 TDLFNIKLRF KLDHEKGEIY VLVIDANEGK IIRRIPPEKV LNVASQMQQM
 VGLLLDE... .......   
>Q7MST6_WOLSU
 .......... ........QI QKEVQELQDS KNVEDLKKEL MQLTEELNRE
 FNPLNMNIKF GFSDDIESLY VTVSERDSNR LIRKIPSDEA IELMVKMREI
 VGIIFDKK.. .......   
>Q884Y6_PSESM
 .......AVQ PASQAPVSDK SVDKPADVKS KDDSQDEAKV KAAAEDIQKF
 FHSVKRNLEF SIDEASGKVI VKVIASDSGE VVRQIPNAEI LKLADSLSDA
 NSLLFRAR.. .......   
>Q3RT17_RALME
 .......... .......... .......... .......... .AAVRKLTEA
 LRAASVSVQF EIDRETNRVV TKIVDKANGE IIRQIPTEEV VRIADALAQL
 QGLFVNQ... .......   
>Q30QT2_THIDN
 .......... .........V KEMQKESTDA PKKIDSKEQV QDLVNQLNKA
 LAPMNTNIKF GVDQQ.DIFY VSVIESETSK MIRRFPAEQA ADFLPKMREV
 TGILFDSK.. .......   
>Q33W59_9GAMM
 MDINTVNSMT PVKANAAEDV EEQSNQAEAA QAEEQSPEAM QKLVEEMSNM
 MSVMRKGLAF KIDEDSGTNI VSVMDIDSGD VIRQIPNEEA LRLAQKLSEV
 TGLLMKT... .......   
>Q4IZ78_AZOVI
 .......... .......... .......... ....VAREEL VEPLKRINEV
 LSSY..GVEF HLSEPGQRVV TEIVDRESGE VIRQIPSEEV LRIAENLERL
 RGILLRE... .......   
>Q97H07_CLOAB
 .......... ......KTQK IEIDAVKNVE NIEIKNEKET KNTGKDIDKL
 LKKDNTHVEY SVHKVFGDLI IKIVDNDTKK VVEEIPPEKI LDMVAKLCQA
 DGVLLDKK.. .......   
>Q893T8_CLOTE
 .......... .......... .......... .......DEA KKAADKLNKL
 FEDKSTYVEY EVYGKSKSIT IKILDNKTKE IVKEIPPRKL IDMVDKLCEL
 AGVFVDKR.. .......   
>Q7NRA6_CHRVO
 .......... ....AAVGQN QQQQAAADSE QKQQSLTKQL EDSVKQLNNT
 ASLYNSSLLF SVDKDTGATV VKVVDKENNK VIRQIPSEEA LRIAKAIGDF
 KGLLLKDK.. .......   
>Q3QJX0_9GAMM
 .......... .......... ..QANAKAEE EKQQVEKEQL AAVAEEMSSM
 MSMMQKGLEF RVDESSGQPV VSVLDIASGD VIRQIPSEEA LKIAQKLSEV
 TGLLMKT... .......   
>Q35ZZ7_9GAMM
 .......... .VNFALNSDV VNALADTANV DQQQEEQTSL TQVASSLTET
 MSMMKKGLEF KVDELEGLPV VSVVDVNSGE LIRQIPSEEA LALAEKMSEI
 AGVLMKT... .......   
>Q3ADF3_CARHZ
 .......... .......... .......... .........L EKELQRLTKI
 VNSFPTELKF EIHQASQELM VKVINAETKE VIREIPPHQV LEIVAEIKKL
 LGILVDTK.. .......   
>Q2L173_BORA1
 .......... .......... .......... .......... .TALDEINSQ
 LQAWSTELKF EMDPDLQKIV VSVRDSESGE VLRTIPSDAV IRIAKMIVKL
 QG........ .......   
>Q3CUP9_ALTAT
 .......... .......... ..QVQEDREL STQELDEALL .....EVNEF
 VQTRNKQLNF SVDEDSGKQV VKVTDSESGD VIRQIPTEEV LSLSRRIQDL
 VGMFFNK... .......   
>Q2AHF0_9FIRM
 .NITQPRTLN KINPESSVFQ KEENSDEKSC KTETLNQKEI NKALEKVNGT
 LKEYNQDLRF EYYEEADRMM VQVVDIKTQE VIKEIPPEEL LDIIAKIKKM
 VGMVINE... .......   
>O67804_AQUAE
 .......... .......ESF RKEIKE.NSK KIQKVSNEEL QKIIEEIKRK
 LDYLNKYLKI EIDKDLEIPV VKIIEKDTNK VIRQIPPDYL LELMKRIDEM
 LGILINER.. .......   
>Q7VYD8_BORPE
 .......... .......... ..QSATQDQY GAPKLPMDR. ..ALEEINAQ
 LKAWSTQLQF EIDPDVHQVV VSIVDAETGD VLRTIPSEAV IRIAKMIVKM
 QG........ .......   
>Q2WUU3_CLOBE
 .NVSQYSNNS PI.DNNSGTI AERKVEKEEI EIKQVDKKEL DKAIKKMNKF
 LEDDKTHAEV AIHKDLGTLI VKIVNDETKD VVLEVPSEKF LDMIAYMCKQ
 VGLL.DKK.. .......   
>Q36S19_MARHY
 .......... ..SPQAATEV ...SKAERLQ ARSEAQRDEL NEAVSQLNDF
 VQNVQRDLQF EVDNEMGQTI VKVVDQSTQE VIRQIPDEVA MRLAEKLQQ.
 .......... .......   
>Q67K37_SYMTH
 .......... .......... ..QTQEEQRK QSQPLSKEQA EELAEKMNSA
 AELFNKAVQF KVVEG.NRIV IKVVDVTTDE VLREFPPERL LEALLAMERS
 LGLLIDEK.. .......   
>Q9ZL92_HELPJ
 .......... .......... .....NTVDE SKTTIDPDKL ELLSERLNEE
 MKRIGTDINF SYNDTIKGLV VSVKDANGDK VIREIPSKEA VELMQRMRDV
 IGIIFDKR.. .......   
>Q2Y9D0_NITMU
 .......... .......... .......... .......... ..........
 ......SLEF SVDTDTDRIV IKIIDNETRE LVRQIPMEEM LALAKTMNQL
 QGLLLRTK.. .......   
>Q5E3P0_VIBF1
 .......... .....ASEAI VAEAEQKLET KKK....EAL HKAVEELNEY
 VKSMDRGLSF RLDEESGRQV ITVFEVSSGD IIRQIPDEKM LEVARDLAAS
 ASGLIAER.. .......   
>Q3G8P6_9FIRM
 .......... .......... .........E PRERIGREKI EEIARNLNEA
 VKFASCHLEF QPYEDSGRFQ VKVVNSLSGE VIKEIPPDYL LDFSIKMKEM
 VGLFVDE... .......   
>Q4HHP1_CAMCO
 .......... ........QT DRSQGQEGDD GQQRGVSEKL ADITKKLNEQ
 MDSLDTNVRF GYSDKIGSMY ISVTEKSTGR EIRQIPSEEA MRLAEYFRDV
 IGMIFDK... .......   
>Q9ZFD5_9GAMM
 ....RTTQPQ WVEQARPAEA ARQVAERNIS IHQDQAEEEL EKMVEELNQK
 VQQQKRSLQF SVDEESGKTI VKVIDLDRDE ILRQIPPEEV IRLAQRM...
 .......... .......   
>Q4HT04_CAMUP
 MEISKAITGQ QMDLTAKSQS LNTADNSKIV ETSKINAEQL KEVAQKLNDQ
 VESLNANVRF GYNDKINSMY LSVTEKSTGK EIRQIPSEEA MRLSEHFREV
 IGMIFDK... .......   
>Q7VI20_HELHP
 .......... .........I KEENAQHQDR ENKKQLENEL RELSKKLNDE
 MKRIDTDIHF SYNENIPGLM VTVKESNGDK VIREIPSKEA IELMKKMREV
 IGVIFDK... .......   
>Q4FF29_9THEM
 .......... .......... .......... ..KKQQEEDV QRAIEEFSKK
 LEKLRKEAEF RYDGELNMVI VKIKDTETGE IIRQIPPEVM VKIAKSINEL
 LGILVDER.. .......   
>Q2SCW1_HAHCH
 .....VATST PDTQAAKQSA AAQPSNDADK QKQQLVREEL REAVTKLNEY
 VQSVQRDLQF ELDEDSGRTV ITVLDRTTKE VVRQIPDDLA LKLARNLQQ.
 .......... .......   
>Q3XP16_9PROT
 .......... .......... .......... .........L EKNVKKLENA
 LSAF.TSLRF AVDRDTEERV VRVVNRQTNE VIRQIPTEEM LTLSRRLRNA
 QSLLLET... .......   
>Q3A5J5_PELCD
 .......... .......... RNRQKVASEP ELA..DSEKL EEVLTKIKAL
 TDDGIYSVRF ENDEQNKELV ISLIDSDSGE VIRQIPPEEV LGVSDKLSDL
 RGSLLDT... .......   
>Q2N2Q4_AERHY
 .......... .......... ..EVKAEEKS SKQDTSEIDV EKEVQNLQEF
 SKLQGWTVNF SVEKDLEQVV IKVMDAETKS MIRQIPSEEL LAISKRIKDL
 VGLLLDK... .......   
>Q4HKG8_CAMLA
 .......... .......... .NQQQTNLNN QDENLN.EKL KNATEKLNNQ
 METLETNVRF AYNDKINEMY VNVTEKDTGR LIRKIPSEEV MKLIEHFKGV
 IGTIFDK... .......   
>Q5QZT1_IDILO
 .........Q DVID.AVSEV QDKVAERTDK AQLNPQSEEV GEMVAEINKS
 PTIRNTSLQF VFDEKGDPPV VEVMDTESGE KIRQIPSELA VKLAKAIEDM
 AGLLFD.... .......   
>Q9KWW8_TREMA
 .......... .......... .......... .......... ..........
 .....KELRY NMNEQLDQVV VTVVDPSTNR IIKEIPSAEV QEMKIRVKNA
 IGSFIDETR. .......   
>Q2BZW3_9GAMM
 ..SESQTSLG NDLP.PTEQV NAVNRTDVDD PLNQNSRSD. QERIKQIEMV
 LQQFNRSLRF YQDEETGEQI ATIVDKASGE VIRQVPAQEL LELNKNLAK.
 .......... .......   
>Q41CG4_9BACI
 ........HL PENVLPYEAT RNVFVEANQE ELAQDHITKF ETAIEKANVQ
 LEAQRTGLKF VKHEKLNEFY IQVVDTNNN. VVQEIPSKKE LDFFAAFMEF
 NQ.LIDKR.. .......   
>Q9R9R7_AERPU
 .......... .......... .......... ....IDKAYI EKQAQELQER
 LDNLSKTINF SLVPELEQPV IKVIDVDTKQ VIRQIPSEEM LLMNKRLQSL
 SGLLFD.... .......   
>Q31FN0_THICR
 ........MQ PELSQVATNP KSPQQASSPT TADEITFNHV QTQAKSLNEK
 MLLLGLSIAF SVDEQTQSSV VTVLDTKTNE VVKQLPSEGS LKMMKHIQDY
 L......... .......   
>Q6AMN6_DESPS
 .......... .......... .......... EQKDLQPEEL ...LDQIKSI
 TEDGLYSVRF EKNVDSNSMV IKILDAKTDE VLRQVPSEEI LNLRKQLAGL
 QGNIIDTKK. .......   
>Q40TS4_DESAC
 .......... .......... ..EQ..ASAA EANKVQPEEL ...LNQIKSL
 TEDGVYSVRF ENDDDANQLV VKVVDSKTDE VIRQVPAEEV LSLSVRLEEL
 RGNIVNT... .......   
>Q31FN1_THICR
 .......... .........M HSSQQEATIR KVQKLSKENL DGLIERVNQD
 LSGYDSYLKF ERNEEAEKMV VFIKSSDTDE VLRQIPSQEF LTVSKNIKNF
 L......... .......   
>Q72C42_DESVH
 .......... ..SDSAISLR QPRPQTGEEA ETKDTSPEKL QERLEALQKH
 LEEQGAPLHF SIVHDAGRVL VEVTQRDSQK VLMRIPPEGV LQVGADGLPS
 LGKLLDRR.. .......   
>Q2LT31_SYNAS
 .......... .......... ..EKSQNNSM QNSELTKDLI SKIQEKIDQL
 ....GISLDF TYGEEDERIA IVVKEKLSGK VIRKIPPEAT QKLYEKMNEL
 VGILFNE... .......   
>Q444G7_SOLUS
 .......... .......... .......... ........QV VQAVKAVNEM
 FGPEN.ELRF QKDPESKRMV VRVVNRKTSE VLSQVPAEYV LRLAQDIR..
 .......... .......   
>Q310Y9_DESDG
 .......... ....RAAAPA MNEAAAGREA ADTAPDVSQV QQAVKRIQER
 LAEKGAGFTF TVDTTGHSVN VTVTDKDSDR VLMRIPAEGV LRLAQEGDSR
 IGTLLNK... .......   
