>query
 MIPFKDITLA DRDTITAFTM KSDRRNCDLS FSNLCSWRFL YDTQFAVIDD
 FLVFKFWAGE QLAYMMPVGN GDLKAVLRKL IEDADKEKHN FCMLGVCSNM
 RADLEAILPE RFIFTEDRAY ADYIYLRSDL ATLKGKKFQA KRNHINRFRN
 TYPDYEYTPI TPDRIQECLD LEAEWCKVNN CDQQEGTGNE RRALIYALHN
 FEALGLTGGI LHVNGKIVAF TFGMPINHET FGVHVEKADT SIDGAYAMIN
 YEFANRIPEQ YIYINREEDL GIEGLRKAKL SYQPVTILEK YMACLKDHPM
 DMVRW     
>Q8Q0F5_METMA
 ..DFKPVTLA DREFFERHSE LYPQTHSSNT FTNMVCWNHF TQYRYAYVNG
 NIIISGTTGG ITRFHPPIGP RD.PELMREL IQLAMKVSDN TPLIFIDPDT
 ALWIRELEPD .LELVPDRDN FEYVYRASDL AELPGKKYQK IRSHLNRFRR
 NCMS.TVEPI TPENLEEVME LLKKWRDWKG CDKNPVLSHE VEAAFYAVEH
 FMELRLRGFL LRVDSEVGAI SIFERLNADT ALIHFEKGLP DCEGIYKAIN
 AETAAALADE VEYINRESDL GVGGLREAKL RYHPHHMVEV YSLK.RPSPV
 .....     
>Q7MST4_WOLSU
 .MQWKPIDIE DRETLEGFFR SEELSVSDFS FTNLYLWHFS RSISYAIIED
 LLCIKTQYHG EHPFFFPLGK GEKRGVIERL MECFESRAIP FTMRSLGEEM
 KDELERLMPE KFEFIYNRDR SDYVYLTEEL IELKGRKFHK KKNHLNRFFE
 LYPDFSYESL SMENVDELLE AWKLWFGRIA DEANEGLKNE YIGIVETLKH
 FGKMSYKGGI LRVKGKIVAF TLGEQLNSDT VVVHIEKADT EYHGAYQAIN
 QQFLANEWSH LTYVNREEDL GIEGLRRAKL SYQPSHLIDK YNVTPKPQ..
 .....     
>Q428G3_DESHA
 MIDFKKIEMR DKEWVKPLLE AADLGGCHQN FTNLFSWSGT YHYQVAQVED
 YLVIKGRLGE TYYYFYPAGT GDVQPVLEAM KKDAQENGHE FIVLGISPEN
 MATLKELYPE HFEYEEMRDS FDYVYQAEKL ATLAGRKLQA KRNHINRFEA
 NHI.WAFELL TPENLAECWE MNLEWCRRND CKDDEQLRAE YCAVKRDFDY
 FTDLELEGGL LRADGRIVAF TMGERLNSDT YVVHVEKAFG EIQGAYQMIN
 REFVRWIRET YIYVNREEDM GYEGLRKAKL SYHPDKMEEK FLAR......
 .....     
>Q8TPW3_METAC
 ..DFKPVMLS DRAFFESHYA FFPQTHSSNT FTNMVCWNHF TPYRYAYVNG
 NVIISCTTEG VTRFHPPIGP RN.PELMREL IRLALDVSDE TPIELIDPDT
 AQWLQELDP. ELALMPDRNN FEYVYRASDL AELPGKKYQK IRSHLNRFRK
 NCSS.TVEPV TPGNLKEVIK FLKKWSEWKG CRKNLVLASE VGAARYAVEH
 FNELPLQGLL IRVDSEIGAI TLYERLNTDT ALIHFEKGLP DCEGIYKAIN
 EETAAVLVSE VEYINRESDL GVGGLREAKL RYHPHHMIEV YSLKRPN...
 .....     
>Q46AN0_METBA
 ..DFKPVTLA DRAFFERHYA LYPQTHSDNT FTSMICWNHF MHYRYAYVKG
 NVILACTAAG VTRLHPPVGP RDPELMKEVI RLALDMGNNN KPLMLIDPET
 AKCMKEIDPD .LILVPDLNH FEYVYRAFDL AELPGKKYLK IRSQLNKFRK
 NY.RHTVEPI TSENREEIME FLVKWCESKR CKNNFTLAHE IEAFSYAVEH
 LTELPLRGLL IRVDSQVGAI SLFERLNANT ALIHFEKGLT DYEGIYKAIN
 AETAAVLASE VEYINRESDL GASGLRKAKL RYHPHHMVEV YSLKRRTH..
 .....     
>Q2D110_9FIRM
 MINFKKVELA DKQWMGPLIT LGEMSSSHQN FTNIFAWSEI YHYRVARVSD
 YLVVKGRLNG EQYYFYPAGK GDPKSVIETM KQDAADCGHK FIMLGVSPEN
 IIVLNSLFPE SFEYKEMRDS FDYVYLLDKL VTLSGNKLHS KRNHINRFKE
 KHV.WSFEQI SSDNLAECWE MNVIWCKENG CHEDKQLADE NCAVCRCFNN
 FNELGLEGGL IRLNGRVIAY TMGEKLNSNT YVIHIEKAFS KIQGAYQMIN
 REFAAFIQEK YMFVNREEDM GYEGLRKAKL SYYPYRMEEK FMAK......
 .....     
>Q30Y00_DESDG
 .VEFKPLTMD VMEEYLTLFS GTPSRASDYS FTNLWGWANE YGLEVGRTP.
 NLFWIRQTRP EVRYWAPVG. .DWNAV.... ...ADWANCP MTFIRVPQQL
 ADLWQAALGD GVQVQEDRDQ WDYLYDAEKL ATLSGNKYHK KKNHVNQFKK
 QY.DWQYHPM TADCIEAVLQ LQQEWCLSRE CEESETLLAE NEAVIRVLEY
 WDTIGLKGGA LYVNDVMVAY TVGEALTDDT LVVHFEKARS EYRGVYQAIN
 QIFVEHEGTG YTYVNREQDL GDEGLRKAKL TYHPADWLRK STVTV.....
 .....     
>Q7MTU7_PORGI
 .IKFKPVEPA DRSAITTITF SSVARICDLA FSNLYCWSFV YGTSWAIVEG
 CLIIRFKSRS HPVYLFPVGP EQVVAAAHRL KAEVVHEDYP LIFMGVTPDI
 HRCIEEHCSA EYYFIEDEAY CDYIYERESL ATLSGKKLQA KRNHINKFVS
 LYPDYTYDPV KDSDAEECLM LAHLWLDSRG ..DQDGRELE VEMVERAFRH
 RQELGLSGGV LRVGGRVVAF CLGSPINTDT FGVHIEKADA MVEGAFAMIN
 REFARSIPDT FRYINREEDL GLPGLRQAKL SYRPAILLPK QTAILR....
 .....     
>Q728P9_DESVH
 ..DFSPVTLD AMQDYLALFA RTPRRASDYS FTNLWGWAEH YGLEW.RFEH
 GLCWLRQTLP EVRYWAPVGP ..WGDIDWAS CTCLGKG... MEFIRVPEEL
 ASLWREVLGD RVTVQETPGQ WDYLYDSADL ADLKGNRFHR KKNHVNGYAK
 AY.GIDYHPL TPDCIEAVIE MQEEWCQWRE CAESESLLAE NEAVIRVLEE
 WDSIGLVGGA LYAEGRMVAY TVGEALDDET LVVHFEKGRG DYRGVYQAIN
 QQFVQYEGAR FRLVNREQDL DDEGLRKAKQ SYYPVDYLRK ..ATVRIAPV
 .....     
>Q7VG15_HELHP
 .MEFKKIELE DRTLLEPFTN QKGRWLSDMN FSNMFMWRHS REISYTFLQE
 HLIVQTRYPH QNPFFYPLGA GDKKPIIESL IQFYKDLSLP LELHSLQSNE
 VEELESYFPH TFEITQRRDR FDYVYNVEEL ITLSGRKFHK KKNHLNRFWL
 TYPQTQYESF SNANLTEVLK VNNMWFEAGN .SEDKGLYFE NLGINDALSH
 FDKLSLRGGL LRCDGEIIAF SFGEEIDDDL ALIHIEKANI AFSGAYQAIN
 QALLKNEFSN HRYVNREEDL GIEGLRKAKL SYQPSFLLEK YDARLK....
 .....     
>Q74EB7_GEOSL
 ....RPLALA DKPLLDALFT ELQPRVSELT FANLYLFRGI HDYRLTRLGD
 ALVVLGRGYG GEAYALPPLS GDVTGALRTL LADG...... FTIYGADDTF
 LERHGA..DA AITVEEDRDG FDYLYLRSDL ADLPGNRFHK KKNRINYFAA
 RHP.FEVRVF GPDHRQGCLA LLDEWRRVRD AAGSTSLDPE TAAAAEAVTL
 SAELGLEGVV IAVEGRVGAF ALGERLNRET AVCHFEKSDP FMEGISQLVN
 REFCR.LFTD CTFVNREQDL GEPGLRTAKL SYHPVELVRK FWLRKTPEP.
 .....     
>Q2DLK7_9DELT
 ....RPLALD DKPMLDGIFA GLQPRVSEFT FANLYLFRSV HAYCLTMVGD
 ALVVMGKGYA GDDYFLPPLT GDIAAALSVL LNDG...... LTLYGADEPF
 VERY..FQGG NVDVAAERNS FDYLHLRSEM AELPGNRFHK KKNRINYFAR
 RHA.YQVELY ADSHREGALQ LLDEWYRVRS EVASGSLLPE TEATRDALAM
 AGQLGLAGVV VLVEGKVRAF VLGERLNSDT SVCHFEKADP FLDGLNQLAD
 REFNRLLFAD CIYVNREQDL GEPNLRESKL SYHPVELIKK FKVRAR....
 .....     
>Q2ZEB3_CALSA
 .MKFYKIDIS DKRIFDEYFK AFQPEIADLT FTNLFMWDPF YDINFTEEDG
 FLLIMAKPYN QPPFLHPVGT NKLPIVIEKA KKYFETQGYK F.MLKRASQK
 TIDMLTQCGM KFESLLERDL SDYVYKVQDL VQLKGKKYHA KKNHINKFLR
 LYGQYEVKKI DDEIVRLCWD FECEWYEKRN GQNDVGLTFE KLAIERAIKN
 FDKLSYEGMI VFIDGKIKAF TFGEPLNKNT VVIHIEKADP DIEGLYTFVN
 NKFLIEFWQN FEFVNREEDL GKEGIRKAKM SYHPFKFAEK FTV.......
 .....     
>Q39XR2_GEOMG
 ....RPLFLA DKPFFAAVFA ELQPRVSELT FANLYLFREA HDYRLTRVGD
 SPVVLGKGYD GEEYFLPPLG GDVAGALRVL LDAG...... MTLYGADEPF
 VSRYLAV..G GVAVEEDRDA FDYLHLRQAL AELPGNRFHK KKNRINYFTA
 RHS.FSVVLY GEAHRDGCLA LLDEWRRVRN GIDSPSLELE TKAGAEALML
 ADRLGLEGVV VLVEGGVAAF ALGERLNRDT SVCHFEKNDP FMEGVSQLVD
 REFNRLLFTD CTWTNREQDL GEPGLRAAKL SYHPDELVKK YRARR.....
 .....     
>Q2FUH4_METHJ
 ..DFHPIELE DKDIFDRIYR DYPIQHSENT FGTLFCWRSY GHYKICEHEG
 CLIIKGETEN YHSYRFPIGP PDVFHATIKL AQNLGEEAPL LILE...PWQ
 YSWMREHYP. TLKLKPDREF FDYVYKSEIL ASLPGQDFLS VRKQLNKFRR
 KCPS.TVELI SESNMDEVLE FLVKWCQQRE CDKYTILKHE KEAINEAVQY
 FDQLGFSGIT VNPKGEIGGI AIFEELNPTT AVVHYEKALP DCEGIYKEVN
 IQTALYLKDR YHYINRESDM GIPGLREAKE RYHPDHMVKL Y.........
 .....     
>Q9ZME3_HELPJ
 ...FEEITLA HKDLFSRFLQ TQKIVLSDVS FTNCFLWQHA RLIQVAVIRD
 CLVIQTTYEN QPFYFYPIGK RPHECVKELL ELEKNLRFHS LTL.....EQ
 KDDLKDNFVG VFDFTYNRDR SDYVYSIEEL IALKGKKYHK KKNHLNQFLT
 NHANFVYEKI SPQNRKEVLE ASKAWFLESQ TDDI.GLINE NKGIQSVLEN
 YESLDLKGGL IRVNGEIVSF SFGEVLNEES ALIHIEKART DIAGAYQIIN
 QQLLLNEFSH LTYANREEDL GLEGLRRSKM SYNPVFLIDK YEAVARN...
 .....     
>Q897C7_CLOTE
 MLQFSPLTLE DKEIFDKYIK PYKFKTSEYS FTNQYLWRKG SDVTYTILND
 VLIIKKVDYD GTTFTQPIGK ENLKEIVDEL IKYRQKHNMD YLFKDAEEEF
 VKDFKELYDN NFTIEEDRDN ADYIYLKEDL KNLSGKKFHS KKNHYNAFIK
 NY.EYRTAKI TESIANECLN TAMEWCRQND CKGY..LLHE ISGIEDVLKN
 FDKLDVMGMA VYVNDKLSAF TLGEKVNSDM AIIHIEKADV NVRGLYPFIN
 RTFIEEYLDD ITYINREQDL GIEGLRKSKL SYNPYKLEMK Y.........
 .....     
>Q73JA0_TREDE
 ..EFAPISLD MQSEMEFYLK RLPDGISELT FLNLYLFRHN YKYQVTKTEK
 LLIIIGEYKG ESFFITPCCT VDVEITKELL AKYKKWMILS KSFL...DNN
 TNVFNLPFLK ELKIEEDRDN FDYVYLRKDL AELKGKDFHK KKTHINKFEK
 SYDKIKIEPL TLENVEDAKK VLEEWNSTKP DSNPENSDYE ..AALEALSI
 LSRTSMMGII LYVWNEPVAW TLAETQNNKT AVILFEKALA SYKGSFQYIN
 YAFAGYLPEY IEFINREQDL GDEGLRQAKM TYKPIKFIKK YR........
 .....     
>Q8RGL4_FUSNN
 ...WQKLTIE SKSSIEEYTK .NRFEICDLS FSNLLLWSIG ENTEYEIEND
 VLTIRSVYMG DVYYYMPIPK NDTPKNIEKM KEKIREILKE NVAIHYFTEY
 WYEK...LKD DFNLQEKRDY EDYIYSYESL STLKGRHYAK KKNRVSNFKK
 SY.QFSYESI SKDNINEVVA FQKKWYEIHS ESSEEILKNE NEGILNLLKN
 YEKLGLKGGF LKVNNQVIAY SLGEALTDKM ILVHTEKALI DYIGSYQAIN
 MIYLQKEWQG YELVNREDDF GDEGLREAKM SYKPLYLQKK YS........
 .....     
>Q30RA1_THIDN
 ..KLKRFTIY TKPIMESYLS KLSVDLSDYT FAANFIWLAN SSGFYAIINK
 SFCLFVMTGG ELTMLLPPL. GKKKNITQAM IKCFEVMNAN NSMLDDFIQS
 ADQANSMFEM LESYIVEKKL VDYVYEVDAL IDLRGNSYHT KRTEINKFMK
 SYPDYVIEKL SAKHKDEIMH LFNKWDRVKY MPKEEGIHQE RHAIKQMIKN
 YDELMLLGLV IYINGELKGF TVGERISHDT ATVIIEKTDF EILGCAQFIF
 REFSKMLKEH YEYINVGDDM GFENLRKVKM SYRPFKLVPK YT........
 .....     
>Q4CDF7_CLOTM
 MLDFKPIELK DRELFHEYLK DYDFLTYEYS FLTLYIWRKM YNTEFAIVDD
 TIVIKKRTAN NGTYFMQPIG ADKSKIADIT LKLNTLRKNN PDFKYLYGDV
 ETPFLEQLHE NFTSHEDKNN FDYIFNSKDL IKLSGKKYHR KKNQYNQFIK
 KY.DYRIEEI SPEVIKNCID LSLKWYDYKS LQ.SEQLKNE QKAIFDIFSN
 IKINNIKGIA VYVNNEIAGF AIGEKLNSKM ATVHFEKGNY NFSGIYPFLN
 KSLVEIFFRD VEFINLQEDL GLEGLRRAKS AYQPIKLEKK YLV.......
 .....     
>Q2LTD5_SYNAS
 ..SFRLLTVS DYSRLKPFFN PLKYPLAIYS LSSLIAWNNE LNPTYYTMED
 NLLLLMTAGT LPEYLLPLSP ..FREVTPPE LAELARRHCL STFCFIPESY
 VEHFLSSIRT LFSLTEQPDY SDYIYLKKDL TELQGKRYLK KRNHINYFRR
 IFLETTIEAL SPVNIPDTLL FLDRWCAKDN PETDPNLGQE SQAARLMLEN
 LELLEARGIA IRIDGEVCAF GIVTSLTDKI KVLNFEKAYS HIRGLYQFLD
 RECACRLFED VEFINKESDM GIPGLAGSKK SYFPVNRVRS YKLSLLN...
 .....     
>Q7MSV6_WOLSU
 ..KLKHFDLS AKEKMERYLQ EVHVDVSDYT FAANYIWLSK SSGFFTIIDD
 TFCLFVLNGS ELSMLLPPLG RSEN.VYRAI FKCFDIMNQN NTILEGFMNY
 IEEGAMLFDS MESYVVEKKL VDYVYRCDDL IELKGNAFHA KRNEINKFKN
 ANPDFRIERL DSRKHEEEIT LLNKWDRIKY MPKEEGIYQE RLAIKRMLKD
 YSELELLGIV IYIKEDLKGF TVGEKIDEST ASILVEKTDF EVLGCAQFIF
 REFCKLLKNE FEHINVGDDM GFENLKKVKM SYRPERLIPK YTL.......
 .....     
>Q6MCQ2_PARUW
 ....EPLNLS HQTLLTQKFR QMSLVISEYS FANLYLFRKQ HEYEV.IFGE
 DIYIKGIDRG KLPFMM.LTS IPHPKVSSEI IFFLNTGYFL FPI.......
 PEEWNLLFDF PLDFSFEDAD SDYLFKVEKL AFFSGRHLSK KRNLVKQLFD
 RY.QIKTAQL TQKNKSDALK ILVNWQDQQT QQEQTDY... .FSCLEAIKL
 LECLNLEGVI IYIDGKPAGF TIGEYLTPTC FVIHFAKGDA NIHGLYQYLY
 QYQAQILSKQ TEWINLEQDL GLPFLRQAKH SYVPDRMILK QRARDKN...
 .....     
>Q8EUN5_MYCPE
 MLSFKRIYMT NEALLELSFS QNEINRIDSS FLNLYTWKYY DSKVYFRVED
 KVIFNNWSNS NITVISPIVS KYEKTLIKEY LIESDLKKCK YCELQFGTFN
 QNDFNIFKKI ELLDTFNSA. ..YLYPTEQL KYMAGKKMQK KRNFINFYKK
 NYSESRIEKF NPELKQEIID F....CSKVS IDKQETREYE IDALKKILE.
 FNPNSSYGST LFYKNKIVGF TYGF.INNDK YEIFIEKGDK ELKGIYQYLL
 SKNLEINNIQ TKLVDRQDDM YSENLAQSKQ SYKPSEVIKM Y.........
 .....     
>Y308_MYCGA
 .....RLDLT NASKLQE..R INQIDSSHYS ALTYYSWSFY GNISYQFHEK
 GISFFGEINT QKVIFAPITK PNQPDDFLDL IKGQIEQLDN LQAIYIDDLT
 GIELEWVKKY DVEIIHES.S TNFLYETKKI MTLSGKSLQK KRNHLNFFIK
 QYE..KDAKI KINREVDLNQ LEKFYLTWND CEDPSAYQSE .LALFRAIKP
 LQDGSLKLTA LYYLDQIIGF CVSYSLNNRC .EIFIEHCDE TYRGSYQYLL
 SNSLRIHHSN DALTDRQDDM GSASISYSKL SYKPEFIIKR YLVKV.....
 .....     
>Q9PPR4_UREPA
 .......... .......... .......... .......... .....QFIGK
 FFIIFAYFDA KKYDWTTL.. ..IPIALEAL KTNFKKEF.L LAINGIQDEN
 YLNNLSQFNF ELIYSW...Y SNFIYETQSL KYFCGKILQK KRNNLNFFIK
 NFKDYEIIKY NPKHLHEVCT FLKEWDVKNF INSKRMLVNS N...SDLLLN
 TQTNPYFMGS LLIKNKIVGF TLVYT.RPNI AEILIEQTDR EIRGMYQYLL
 SQNLIINNIN NWLIDRQDGA WSDNISASKL SYAPKIITKR VNVLIKE...
 .....     
