>prot (#) default: single protein sequence description=t0372 /home/ppuser/server/work/predict_h7307
MIPFKDITLA DRDTITAFTM KSDRRNCDLS FSNLCSWRFL YDTQFAVIDD
FLVFKFWAGE QLAYMMPVGN GDLKAVLRKL IEDADKEKHN FCMLGVCSNM
RADLEAILPE RFIFTEDRAY ADYIYLRSDL ATLKGKKFQA KRNHINRFRN
TYPDYEYTPI TPDRIQECLD LEAEWCKVNN CDQQEGTGNE RRALIYALHN
FEALGLTGGI LHVNGKIVAF TFGMPINHET FGVHVEKADT SIDGAYAMIN
YEFANRIPEQ YIYINREEDL GIEGLRKAKL SYQPVTILEK YMACLKDHPM
DMVRW
