>query  
MKRGTVIALF FVLVIVAALS LEIQYSSYDY IGYNPHNNAG EGVVHAAYSN
ALGSYKGPYV IVYVEAQQWH WDFNPHQKSN TNMTVVPVDE PVLFVIHSVD
VFHEFFIQSA ASNFSLGFNF GAEAVPGYYS YIVLVFPKPG YYHVACAEFC
GLAGVGLGHS WMVGTILATS NVTLAKEVTG GVLPSGEWDP HVVNGTV
