>prot (#) default: single protein sequence description=t0370 /home/ppuser/server/work/predict_h10597
MTTPPARTAK QRIQDTLNRL ELDVDAWVST AGADGGAPYL VPLSYLWDGE
TFLVATPAAS PTGRNLSETG RVRLGIGPTR DLVLVEGTAL PLEPAGLPDG
VGDTFAEKTG FDPRRLTTSY LYFRISPRRV QAWREANELS GRELMRDGEW
LVTD
