>query  (#) default: single protein sequence resfilename=tg6002lb description=e.coli /nfs/data5/users/ppuser/server/work/predict_h3040
MKAILIPFLS LLIPLTPQSA FAQSEPELKL ESVVIVSRHG VRAPTKATQL
MQDVTPDAWP TWPVKLGWLT PRGGELIAYL GHYQRQRLVA DGLLAKKGCP
QSGQVAIIAD VDERTRKTGE AFAAGLAPDC AITVHTQADT SSPDPLFNPL
KTGVCQLDNA NVTDAILSRA GGSIADFTGH RQTAFRELER VLNFPQSNLC
LKREKQDESC SLTQALPSEL KVSADNVSLT GAVSLASMLT EIFLLQQAQG
MPEPGWGRIT DSHQWNTLLS LHNAQFYLLQ RTPEVARSRA TPLLDLIKTA
LTPHPPQKQA YGVTLPTSVL FIAGHDTNLA NLGGALELNW TLPGQPDNTP
PGGELVFERW RRLSDNSQWI QVSLVFQTLQ QMRDKTPLSL NTPPGEVKLT
LAGCEERNAQ GMCSLAGFTQ IVNEARIPAC SL
