>prot (#) default: single protein sequence description=t0380 /home/ppuser/server/work/predict_h29390
MIDEKFLIES NELVESSKIV MVGTNGENGY PNIKAMMRLK HDGLKKFWLS
TNTSTRMVER LKKNNKICLY FVDDNKFAGL MLVGTIEILH DRASKEMLWT
DGCEIYYPLG IDDPDYTALC FTAEWGNYYR HLKNITFKID EIYNY
