>prot (#) default: single protein sequence description=t0384 /home/ppuser/server/work/predict_h32672
MLKLGVIGTG AISHHFIEAA HTSGEYQLVA IYSRKLETAA TFASRYQNIQ
LFDQLEVFFK SSFDLVYIAS PNSLHFAQAK AALSAGKHVI LEKPAVSQPQ
EWFDLIQTAE KNNCFIFEAA RNYHEKAFTT IKNFLADKQV LGADFNYAKY
SSKMPDLLAG QTPNVFSDRF AGGALMDLGI YPLYAAVRLF GKANDATYHA
QQLDNSIDLN GDGILFYPDY QVHIKAGKNI TSNLPCEIYT TDGTLTLNTI
EHIRSAIFTD HQGNQVQLPI QQAPHTMTEE VAAFAHMIQQ PDLNLYQTWL
YDAGSVHELL YTMRQTAGIR FEAEK
