>prot (#) default: single protein sequence description=t0365 /home/ppuser/server/work/predict_h23685
MPVNSILGVF AKSPIKPLQE HMDKVYDCAS LLVPFFEATI TGNWDDAVQI
RKQISLAEKQ GDSLKREIRL TLPSGLFMPV ERTDLLELLT QQDKIANKAK
DISGRVIGRQ LLIPQALQVP FIAYLQRCID AVGLAQQVIN ELDDLLEAGF
RGREVDFVAK MINELDIIEE DTDDLQIQLR RQLFALESEL NPVDVMFLYK
TIEWVGGLAD LAERVGSRLE LMLARV
