>query
 MPVNSILGVF AKSPIKPLQE HMDKVYDCAS LLVPFFEATI TGNWDDAVQI
 RKQISLAEKQ GDSLKREIRL TLPSGLFMPV ERTDLLELLT QQDKIANKAK
 DISGRVIGRQ LLIPQALQVP FIAYLQRCID AVGLAQQVIN ELDDLLEAGF
 RGREVDFVAK MINELDIIEE DTDDLQIQLR RQLFALESEL NPVDVMFLYK
 TIEWVGGLAD LAERVGSRLE LMLARV    
>Q33XI2_9GAMM
 MPVNSILGVF AKSPIKPLQD HIDKVHDCAS ILVPFFDATV AGDWDKAVQL
 RKQISQSERE ADELKREIRL TLPGGLFMPV ERTDLLELLT QQDKIANKAK
 DISGRVIGRQ LLVPEAIQDT FNAYLARCLD AVAQAKQAIN ELDDLLETGF
 RGREVDLVAK MIVELDKIEE DTDDLQIKIR RQLFSIENQL NPVDVMFLYK
 IIEWVGDLAD LAERVGSRLE LMLARV    
>Y1603_HAEIN
 MAMNNILGLF AHSPLKPLQK HSEKVTECSD LLIPFFQTTF SKNWEQAEEK
 RLEISQCERE ADSLKREIRL KLPRGLFLPI DRTDLLELVT QQDKLANYAK
 DIAGRMIGRQ FGIPEEMQEE FLHYVKRSLD AIHQAHRVIE EMDKLLETGF
 KGRELKLVND MIQELDSIED DTDQMQIKLR KMLYTIESRY NPIDVMFLYK
 IIEWVGVLAD QAQRVGSRIE LMLAR.    
>Q3QL05_9GAMM
 MPVNSILGVF AKSPIKPLQE HIDKVHECAN FLIPFFEATT SGDWDTATEL
 RKQINKAEKE ADALKREIRL TLPGGLFMPV ERTDLLELLT QQDKIANKTK
 DISGRIIGRN LVIPAPIQEP FMAYLKRCLD AVAMAKEAIN ELDELLEAGF
 RGREVALVEK MVGELDAIEE DTDALQITVR RGLYAVEEGM SAVDVMFLYK
 IIEWVGDLAD LSERVGSRLE LMLARV    
>Q5E2L2_VIBF1
 MPVNTIMGLF AKSPMKPLQR HVVCVNECCS LLVPFFETCT KGDWEKANEI
 RTQISHLEKE ADVLKREIRL KLPRGLFMPV DRTDMLGLLT QQDKLANLAK
 DIAGRVVGRQ LEIPSSMQDA FLAYVQRCLD AASQAQEVIS ELDELLETGF
 KGREVTLVAE MINKLDIIED DTDELQIKLR QQLMSIEHKY NPIDVMFLYK
 ILEWVGGIAD QAQRVGSRLE LMLSR.    
>Q3EIM0_ACTSC
 MAMNNILGLF AHSPLKPLQR HSDKVTECCS MLVEFVEATF QGDWVKAEAL
 RVQISEAERQ ADTLKREIRL KLPRGLFLPI DRTDLLELVT QQDKLANLAK
 DIAGRMVGRQ FPIPTLLQND FMVFICRALD ATVQAHRVID EMDELLETGF
 RGRELNFVNN MINELDSIED DTDQMQIKLR KMLRDIEQNY NPIDVMFLYK
 IFEWIGVLAD QAQRVGSRIE LMLAR.    
>Q3ILC3_PSEHT
 MQTNAFLGVF AKSPIKPMEE HIRKVHQASK ALIPFFNHVF KEEWQQAEEL
 RLTIRNLERE ADEMKRNIRL QLPRGLFMPV ERTDLLELVT QQDKIANKAK
 DIAGRVIGRE MIIPKVIQID FLAYLTRCVD ATKQASNAIN ELEELLETGF
 KGREVALVEK MLVELDAIEQ DTDEMQIKIR RQLRAVEGEL NPVDVMFLYK
 IIEWVGELAD IAERVGSRLE LMLAR.    
>Q5QVM1_IDILO
 MSVNSFLGVF AKSPIKPMIE HMDEVHRCAY ALKDFFKAVY SKDWKSAEVA
 RATIVKHEST ADDMKRKIRL NLPSGLFMPV ERADLLELVS QQDKIANKAK
 DISGLVTGRE LIIPEPLIKD FDAYLNRCLD ATDKARETIG EFDDLLETGF
 KGRERDLVDN FIIELDAIEA DTDQLQIKLR QDLRKIELDM NPVDAMFLYR
 ILDWVGDLAD LAERVGARFE LMLARV    
>Q7VLQ1_HAEDU
 MAMNNILGLF AQSPLKPLQK HSVKVTECSE LLEPFFEATF KQDWDEAIKV
 REQIIDLERR ADALKREIRL KLPRGLFLPV ERTDLLELVT QLDKLANYSR
 DISGRIIGRQ LVIPEAMQAT FRKFLSRSLD STRQVRKVLA ELDKLLETGF
 RGRELKFVNN MILELDQIED DTDQIQIVLR RTLRGLEQEF NPIDVIFLYK
 CIERVSILAD QAQRVGSRIE LMLAK.    
>Q47Y14_COLP3
 MAKNSILGVF AKSPIKPLVK HIQIVVKCSK QLIPFFEACT AEDWSEAAKV
 RRKLSKLEQD ADALKRQLRL ELPGGLFMPV DRADLLELVS QQDKIANKAK
 DIAGRVLGRK LEIPVTLQAE FTVYLARCID ATEKAAEAIN ELDDLLETGF
 RGREVVLVEK MISQLDAIED DTDDLQVILR KNLLAIEKDL NPVDVMFLYQ
 IIDWVGDLAD LAECVGARLE ILLAR.    
>Q3CTD6_ALTAT
 MPTNTFLGVF AKSPLKPLED HIKVVNKCSQ GLLPFFNSVF AGDWEKAALF
 QKEISNLEKQ ADTLKRDLRI SLPRGIFMPI QRQDVLELLT QQDKIANKAK
 DISGRVLGRH MDIPVIMRES FMAYLERCLD ATKQAKRVIN ELEDLLETGF
 RGREVRLVED MIVDLDKIED DTDVMQVAVR RELLELESQL NPIDVMFLYS
 IIEWVGELAD ISERVGSRLE LMLA..    
>Q9HTY2_PSEAE
 MPTNPFISLF GRSPIGPMQQ HIAKAHECAA GLLPFFRAVI AEDWAQVEQV
 QQDMVRLEQE ADRLKKHVRM HLPKSLFLPV PRSDLLELLS VQDKVANRAK
 DIAGLMLGRR MRIPLPLQGQ MLAYVQRSVD ASAQALRVVN ELNELLETGF
 GGRETSLVES MVEELEAIEN DTDRIQVEVR RELFRLESEL PPVDVMFLYQ
 IIEWIGDVAD RAQRVGNRLE QLLAR.    
>Q824T0_CHLCV
 ..MQTLARLF GQSPFAPLQA HLEVVAFCVQ QMVPIFTALR DGDYKQVQTI
 AKNISDKEYQ ADCIKNDMRN HLPVGLFMPI SRAGLLEIIS IQDSIADVSE
 DVAILLTVRK LHFYPEFEKI FFQFLHKSVE TFDLTMTVIQ EFNKLLESSF
 GGRKADKVRF LVSRVAKAEH ECDVIQREIM QIFFSDEFMI SEKEFYLWLQ
 VIKRAAGISD SSEKLAHRVN MTL...    
>Q5ZXZ6_LEGPH
 ..MGSIFNMF GPSPIKPIEQ HIRKAHQCAK QLYPFFEAVL KNDWDTANKI
 KDKIISIEKE ADLIKRDLRL HLPTGLFLPV ARTDILELLS AQDRIANKAE
 DIAALIISRQ MSIPKKLIPS FMPFLSRCLD ASKQACTAIN ELDELLETGF
 RGSEVKIVEE MIVKLDEIEH DCDERLADIR HKIFELEKEL PAIDVIFLYK
 LVQWIGELAD HAQTVGGRLQ ILIAR.    
>Y681_CHLPN
 ..MQTLARLF GQSPFAPLQA HLEMVVSCVE YMLPIFTALR DGRYEELLEM
 AKLVSDKEYQ ADCIKNDMRN HLPAGLFMPI SRAGILEIIS IQDSIADTAE
 DVAILLTIRR LNFYPSMETL FFRFLEKNLE AFELTMTLLH EFNQLLESSF
 GGRKADKARL LVGRVAKSEH ESDVLQRELM QIFFSDDFII PEKEFYLWLQ
 VIRRTAGISD SSEKLAHRIN MTL...    
>Q83FC5_COXBU
 ....AILDMF GRSPVRPLQQ HMEKVHACFE LLFPFFDALV LQDWERAIEL
 QGAITKLENE ADELKRDFRR HLPKSLFLPV PRSDLLTLLA RQDKIANTAK
 DIPGITLGRK MEIPASLIDK FKNFLAHSIK AFTQARNAIN ELDELLVSGF
 RGKEAAYVDK LIQQVNDIEY QTDQLQIELR QSLFQIEKTL LPVNVIFLYK
 IIEQIGYLAN HAQQTGNHLQ LLMA..    
>Y063_CHLMU
 ..MQVLASLF GRSPFSPLQA HVELVSASIE VLFPLFSAIK EGDYQRVEAL
 AQLVSSKERQ ADGVKNDIRS HLASGVFIPV SRLAMLEIIS TQDSVADCAE
 DIAILLTVKE LRFYPEFEEI FFQFLQKTVQ SFEVVAKAIR EMDLLLESSF
 GGCRAEKTRV LVNEVSNLEH ECDLLQRELM KILFSENFSI ETKDFVLWTQ
 IIKRLSGISN NSEKLAYRVG MTL...    
>Q2BGE3_9GAMM
 ..TNPFLQMF ARSPFQPMQE HIAKAQECAV ELIPFFEAVI KNDWEAAAEV
 QSRIAVLEGE ADAMKKEIRQ GLPKSIFLPV PRTDLLEVVR MQDKIANRAK
 DIAGLMLGRQ MEIPTSLQTD MNDFLRVALQ TSEQALTALK ELDDVVNSGF
 GGHETDVIEK MLDELDVLEH RTDEYERDIR AKLFGIEKDL PPVDVMFLYQ
 VIRLVGDLAD RAQQVGSRLQ LLVAR.    
>Q6MF27_PARUW
 ..MLTILRLF GRSPFAPLQS HMETVACCVH QLPFLYEAIE NRDQPLIENI
 ANEISAIEHQ ADTMKNDIRN HLPKSLYLPI GRESLLDILS IQDSIADTVE
 DIAVVATFKP LEILPSFKEE FKQFLLKNIE TFDGAKLIIN ELHELIESSF
 GGKEAEKVRA MVEDVALKEH EVDLIQRQLL KKIFQSEEAL TYLTFSQWQR
 LIESLASISN LSENLANRVR MVL...    
>Q34WZ3_9GAMM
 .....FSSIF GRSPVSPLQH HMAKVLDCAE ALVPLFKAVS EGDYNAVATA
 QQRVTDLERE ADALKKELRN KLPHSMFMPF DRADFLELLR AQDRIANKAK
 DIAGLVLGRK MQLPEPLVDP FMDFLNRAID ASRQAKNTVD QLDELVETGF
 RGAEVEVVQE MLDKLDAIEH DTDRMQVQLR SLLQKLEPRI PPVDVMFLYQ
 LIERVGTLAD RAQQTGSRLQ ILMAR.    
>Q3XQT0_9PROT
 ..TNPLASLL GRSPFKPMQE HMRKVVLCAQ LVPALFDALE QDDRETLNQV
 KASIFELEHQ ADALKNDLRA HLPNSLFMPV ARRDLLELLE VQDAIADSAQ
 EIAGMLTLRV DLVPPAMCGA FKALAQHCVR TCEKAGEAIE QLDELLETGF
 GGRESERVQR LLGEVGTLES ETDKLGIALC QSLFEREKDL NPVITIMLYQ
 MIREIGELAD NAEKVGDRLR LLIAR.    
>Q2CT82_ECTHA
 .....FARIF GSSPVAPLQQ HMAEVVDCVE VLPELFRASA VGDVQRMRDA
 HRQIVHHEHE ADRLKKEIRA HLPPDLFMPW DRRDFLELLR AQDRIANKSK
 DIAGLMIGRQ MQWPSALIEA TLGLLDQGIE AARQAKASVR ELDELVEAGF
 RGAELEIVES LLEKLDDVEA ETDRMQVQLR SQLFEIERDL YPVDVMFLYQ
 IIEALGTLAD RAQQTGARFQ ILLAR.    
>Q6AJX0_DESPS
 LPTSALSGLL RGSPFKPIQE HMRVVFSCVC QIPPLFDALY HKDDVQLSIF
 AEKIINLETE ADKLKSKFRL NMPKSLLLPV DRKDLLGLIS DQDAIADTTE
 EIAQILLYRD MTVPEELKVL LDELLEATIE ISSDAKAIIE QLDELLEVGF
 GGREFDKVTR MIAGVRRGEH NIDNILHRSR RALFEVENSL DPVSVMFWYE
 ILGLLGKISD LAENLGDRLL LFMSK.    
>Q44IL1_CHRSL
 ...NPFSALF GRSPFEPLLA HIVKTSECAE RLLPFFDATQ AGNWDEAATH
 REAITELEHE ADTLKTELRL NLPNTMFLPV SRSDLLELIS VQDKIANKAR
 DITGIMLGRE MQIPASLAPA MRAYLETAIA TVSQARKALE ELEELLESGF
 GRNVSDVMHD FIRELHELEH KADDQQVQIR RQLFQLEAEL PPVDVIFLYK
 IIEWIGELSD RAERVGSRLQ ILTAR.    
>Q41IP9_METBU
 ..IRSVLNVF AKSPFKPLCL HASKGVETVR KLDQAVNAYC I.NMPLVEEL
 SHEIDNIEHE ADIIKQTIRG QLSSSIMLPV NAEDLLNFLK PQDSIADVAQ
 EAAYMLSLRQ CDMPEGIKDQ LCQLSTETLK TVEIYEKLVD SLSELLETSF
 SKRDVEETLA LVPQIEEMEH ITDLIEKKLV KDIYAHEKEL GAVGVFYLIE
 LVRTIADIAD KTEHAADRLR TMIIR.    
>Q8PS53_METMA
 ..IRSVLDVV AESPFVPLET HARKGVLAVE KLSEAMEAYC TGNQALLDER
 TEEIDVLEHE ADKIKQKIRA SIPSSVRLPV NKKDLLSFLK QQDSIADFAQ
 ASAYWMTLRP CDLPDEIKEG FLELMATSLK TARMYDRLVG ELYKLLATSF
 SKEEIKETLQ LVPEVEKLEH DVDVLETALL KKIFEHESAI GGAGVCHLMG
 LVERIGGIAD KSASAADRLR SMILR.    
>Y1799_ARCFU
 ...RSVGEVF GYSPFRSLAQ HARMCGRAVG LLQQQFEALR RGNYEEVEEL
 REEIDELEHH ADQIKEEIRG NVTKSLMLPV DRHDLLEFLK VQDDILNNCE
 HVGHMVTFRK VSAPEDVWDE FLVLLSKLME IVNNYEEMVE RIMQLVETSF
 SKKEVNRALE YVPIIEQLEH ECDLIQIGLH TKLFNLENS. NPLDIQLMVT
 WVVHLGYVAN AAARASDRFR IMI...    
>Y637_PYRHO
 ..MQVWKKLF AKSPFKPLIR HAEVVVQTVE TLEKALDSWA RGDYENMKEY
 AKKVDDLEDI ADKIKSELRD SITSKLLMPV QRTDILEYLH MQDKIADAAE
 DTAKWLLIKR DSIPNDIKDI ILKMGKESIK AAKLVYEAIK QLDNVLESGF
 AEKEIKKEYK IIKQIEEVES KIDGLDSKLM EIVFTSE..L DWKDGLYILN
 IARTLSNISD KAKDTAERIR VLMNK.    
>Q8U229_PYRFU
 ..MQVWTKLF AKSPFKPLIK HAEVVVETVE TLEKALEAWA KGDYEKMKEL
 AVEVDRLEDV ADRIKMELRE SITAKLLMPV QRSDVLEYLH MQDKIADAAE
 DTAKWLLVRR GNVPEDIKDI ILKMGKESIR AAKLVYEAIK QMDMVVESGF
 SENEIKKEYD LIRQIEEVEN KIDGLDTKLM RLV..LNANI SWTEGIYLLN
 IGRTISNISD KAKDAAERIR IMMSK.    
>Q5JHX5_PYRKO
 ..MQVWTKLF AKSPFKPLIK HAEVALQTVE TLEKALQAWR EGNYEEMKKL
 ALEVDRLEDV ADRIKEEIRD SLSSKLMMAV AREDVLIYLH MQDKVADAAE
 DTAKWLLVKE PNIPEEIKEV ILQMGTESIK AAKLVYEAIV QMDRVIESGF
 AEKEIEREYE IIHEIEGVES KIDGLDTELM RLVFQNAGRM DWSEGFYILN
 IARTLSNISD KAKDAAERIR LMMNK.    
>Q9WY98_THEMA
 .......... .......... .......... .......... ..........
 .......... .......... .......... EKDDFLYIVH KADEILDVVR
 DIVIMLMNRV EDVPENIKEL FAELVENVLD TIRETTEAIE QLRTLAESGF
 SPFEKEKEER EIFDVSMEER EVDTISRNLG KKLYSLKNSM NPVDLIFLNK
 VARLISKIAD QGKDITKRIN SIL...    
>Q8U134_PYRFU
 .......... ....FKLIRD HLTMVGDTLK YTKEMFVQYL QGNIGNAEEL
 LTKVEESETR ADKLRREIEL MLYSGAFIPA NRGDYIRLVE LIDNVADAAE
 SAAHTLIFAK PAVPPEYKEK ILILINESLK TFEYLKEAVV SLET......
 ...DVDRALE YSKSTEAQEE DADKIEYSLL RKIFEDENIS TYAKLI.WNQ
 IITKIGDIAD RAEDASDHIM LMAVK.    
>Q5JGC3_PYRKO
 ......MSLF GGKEFEAIDK HLDVVENALR AFRELVGAYL DGDFNRAKEL
 EEEVSRFETE ADGLRRSIEL MLYEGAFLPV SRGDYVRLSE LIDQVADAAE
 SASHTLILAK PKVPTEVKGD ILGLVDSAIE TFKILKEAVK ALNE......
 ...DVDKALE LAKKTEDAEE SADKIEYDVK EKVFESETIT TYAKLI.WNQ
 VLTKIGDIAD RAEDASDQVM LMAIK.    
>Q9V0M9_PYRAB
 .......... ....FNKLRE HLEAVDATLS AFRQLFVAYL SGDLDKAERL
 LREVEDKESY ADELRRSIEL MLYGGAFIPA SRGDYIRLSE LIDNVADAAE
 SAAHTLMFAK PNIPGDLESE ILRLVDESLK T....YTYLK EAVLALEES.
 ....VEKALE LSKETETQEE RADKIEYDLL RKIFSR.NDI STYAKLIWNQ
 VITKVGDIAD RAEDASDQVM LI....    
>Y1689_METTH
 .......... .........Q HLEKVMECYL KFEELMEAFY RGDCRLVSEL
 TKEIAIKEHE ADEIRRKMEL EFYEGAFLPF DREDRIMLVE SIDKVADVIE
 SAAFTVSLGK VAFPAEFRDD FRAMMKVTGK TIRALHECVE SL........
 ...ETDLGEA MVHEIERFED EADIIERKII TGLYSRQDRI GVVKFLDMKE
 ITRKVANISD RAEDASDRAL IIIAK.    
>Q30US4_DESDG
 ..MNIRIPLF GRSPMTGLVE HYEQIAKGMR LIEESMECYI TGGTKDFNTL
 LREVDDAEEH ADKIKRNIRN HLPRALFMAV DKTLFINYTR SQDNILDAGQ
 EALNWLGMRR IPIPDEFQKE FVFFLHK... .......... ..........
 .......... .......... .......... .......... ..........
 .......... .......... ......    
>Y1389_PYRHO
 ........VF AK.....IRE HLNAVESTLM AFRKLFEVYI RGDVERAEEL
 LKDVEREESR ADELRRNIEL MLYGGAFLPA SRGDYVRLSE LIDNVADAAE
 SAAHSLMFAK PIVPKGLEDE IIRLVDESLK TFEYLKGATL ALED......
 ...SVDDALM LAKKTETQEE DADKIEYDLL RKIFSREDIS TYAKLI.WNQ
 VITKIGDVAD RAEDASDQIM LI....    
>Y914_THEMA
 ...QTIISLF FK........ HIDKVEETLK CVFDLIKKYL E.DTDDIESL
 YLRTQRLESE ADRLRRKTEM EMYSGAFLPN FRGDLLGLIE SVDKVANKAE
 YVADLIVLQK PEVPHELKDL ILSQMEYSLK AYESLKSALK .........F
 LFEDLERVEE FVLAVEKYEH DEDAVERTAL RKLFEMDIER SVK..LEVKE
 LIRSIGDIAD RTEDVSDRAE IILLK.    
