>query  (#) MK1FoxB /nfs/data5/users/ppuser/server/work/predict_h19925
VKRGTVIALF FVLVIVAIIS LEVQFSSYDY IGFNPNYASD HIPAGEGVVH
AQLANALGAY KGPYVIIYVT GQQWHWDFYP HNMVYTNITY VPVGEPVLFV
IHSVDVFHEF FIQAATSNFT IPLNDGAEAV PGYYSYMVFV FPQPGLYHVA
CAEYCGTAAT GLGHSWLVVT
