>prot (#) default: single protein sequence description=t0378 /home/ppuser/server/work/predict_h27447
MLSANQIKFL RSLRERKYRL REQAFAVEGP KLVGEMLPFY RCRMLVGTAA
MLRAVSTPHD AEVVELPESF DFKRISTQTT PQPLMAVFDL PAEPEPVVEG
LTLLLDGVQD PGNVGTILRT ADWFGIRHVW LGTGSADVFS PKVVQASMGA
LARVQPTPLK NTVDTLAYFR RQGIPVYGAF LDGQSLYEAP LPNFTEPAIL
VLGSEGRGIS PEVAAEITDR LTIPASGLSV KGHTESLNVA IATAILCSEW
RRRS
