>prot (#) default: single protein sequence /home/ppuser/server/work/predict_h20587
MRPTPMTAIL ALSLAAAAPA MAASLKDIAP YPEAEKGFTR QVIHLPAQAD
ESAYKLEILA GKTLQVDCNR QRLGGNLEAH TLEGWGYNYY RLDNVSGPAS
TLMACPDGKK TEAFVPVVGD GFLLRYNSKL PVVVYVPKDV EVRYRVWSAS
QDVQKAKVE
