>query
 MRPTPMTAIL ALSLAAAAPA MAASLKDIAP YPEAEKGFTR QVIHLPAQAD
 ESAYKLEILA GKTLQVDCNR QRLGGNLEAH TLEGWGYNYY RLDNVSGPAS
 TLMACPDGKK TEAFVPVVGD GFLLRYNSKL PVVVYVPKDV EVRYRVWSAS
 QDVQKAKVE 
>ECOT_PSEF5
 .......... .......... .....EDTAP YPKAEDGFTR QVIHLPKQQH
 EDRYKVEILA GKTLTVDCNL QRLGGKLLEK NLEGWGYPYY RLDQVSGPIS
 TRMACPDGKT REDFVPVTGD GFVLRYNSKL PIVIYAPKDV EVRYRLWSAA
 DKTENARQE 
>pdb|pdb|1azz
 .......... .......... .....EKIAP YPQAEKGMKR QVIQLTPQED
 ESTLKVELLI GQTLEVDCNL HRLGGKLENK TLEGWGYDYY VFDKVSSPVS
 TMMACPDGKK EKKFVTALGD AGMLRYNSKL PIVVYTPDNV DVKYRVWKAE
 EKIDNAVV. 
>ECOT_PSEAE
 .......... .......... .........P YPKADAGFTR QVIHLPKQDA
 EDAFKVEIIA GKTLEADCNQ QRLGGELEEH TLEGWGYSYY RLDKVSGPMS
 TMMACPGQKK EQRFIPVVGE GFLLCYNSKL PIVVYAPKDV EVRYRIWSAS
 EKVEKAVSE 
>Q3FAN2_9BURK
 .......... .......... .....ESIKM FPQPAAGQQR AVIALPALEN
 EGDARVELMI GKTLQTDCNQ QWFGGELTAE DVKGWGYTYY RLTDVKGPAS
 TLMACPGQAP QQRFVQVRSD GQLLRYNSRL PLVVYVPDGF DVRYRVWHAS
 KDVQHAVTQ 
>Q3KCZ4_PSEPF
 .......... .......... .....EDTAP YPKAEAGFTR QVIHLPQQAQ
 EENFKVEILA GKTLEVDCNR QRLGGTLEEK NLEGWGYPFY RLEKVSGPMS
 TLMACPPGQK KRVFVPVIGD GFTVRYNSKL PIVVYAPQDV EVRFRIWSAS
 DKIGVAIPE 
>Q3Q2P4_9GAMM
 .......... .......... .....EATKM FPAPAAGMVQ HILSLPKLEN
 EDDYMIEIQI GQTQMVDCNK HGLNGELKEL TVQGWGYNYY QVDEIAEGPS
 TMMACFELAK KEAFVRIPGE .LKMRYDSRL PKVFYLPEGA ELRFRTWKVD
 STYQYSK.. 
>ECOT_YERPE
 .......... .......... .....EKIAP YPQAEKGMSR QVIFLEPQKD
 ESRFKVELLI GKTLNVDCNR HMLGGNLETR TLSGWGFDYL VMDKISQPAS
 TMMACPDSKP QVKFVTALGD AAMQRYNSRL PIVVYVPQGV EVKYRIWEAG
 EDIRSAQVK 
>Q2T036_BURTA
 .......... .......... .....EDIKM FPAAQAGQKR EVIVLPAEKL
 EEDIRVELVV GKTIKVDCNQ HWFGGDLKHE TVQGWGYPYY VLADAKGPAA
 TLMACPGQEP QEAFVPVRGS GYLLRYNSRL PIVVYVPKEF EVRYRLWYGS
 NEVARAVEK 
>Q33VT7_9GAMM
 .......... .......... .....DATKM FPAPTDGLVQ HILTLPKLAN
 EGDYRLEIAI GRSEEVDCNK HGLSGEITQH TVKGWGYNYY QVDAIHQGPS
 TMMACFDKAK KTAFLTLP.E KLTLAYDSRL PKVFYLPAGA QLRYRIWQAS
 SDYQYSEAK 
>Q3QDU3_9GAMM
 .......... .......... .....EASKM FPAPAAGMVQ HILTLPALEN
 EGNYMVEVQI GQTKLVDCNK HGLRGELQTR DLQGWGYNYY EVTEIGEGPS
 TMMACFDKAK TEAFVRIPGD .YKFAYNSKL PMVFYIPEGA ELKYRVWRAD
 TVFNTSK.. 
>Q6QDA1_PANCI
 .......... .......... .......LKP YPAASEGMQR HVMVLPPLNN
 EQQYRVELVI GRKMETDCNH YRLAGRLTEE TAKGWGYSYY TATVQPDAIS
 TRMACTDSAK KTILVTLPAA AQLIRYNSNL PLVVYAPTDV EVGYRVWQAA
 QQIVPSQV. 
>Q4UMT9_RICFE
 .......... .......... .....KDIAP YPLPTDSQKR YVIHLPTESN
 EEKLKVELQA TKNAMKDCNR VWFGGKLETK TLEGWGYNYY IIDQVSQPAS
 TMMACPGIKA TIKPVSVLGD ETFLRYNSKL PIVVYAPKEV ELHYVIWHQN
 DIINSAKE. 
>Q3NKD7_SHEFR
 .......... .......... .....EASKM YPAPTEGMVQ HVLTLPALND
 EQDYMLEVQI GQNKIVDCNK TKLIGEIDKI SLAGWGYVYY QVDKVMQGPT
 TKMMCTNAKS AE.FI.VLNE AMTLRYDSRQ PKVFYLPEGT ELRYRVWKTV
 SEFEFS... 
>Q4QFD4_LEIMA
 .......... .......... ........AP YPEPTSQQRR YVIFLDPKGD
 SKDYKVELIP GRVEKVDTNV YRMGGNIEER TIDGWGYPYY IVTLTTMSGT
 LMMPLGDAAL KRPRFVAMNT KNLYRYNSRL PIVVYMPKDG ELRYRIWTVK
 ST....... 
>Q43Q50_SOLUS
 .......... .......... .....DDLKA FPPAEKGMTR YVIRLRQEKN
 EAALKVELIV GKTVKTDGNR YFFAGKLETE SIPGWGYDRY ILRKLGPMAG
 TLMAVPNAPQ VERFISGSGE T.MPRYNSRL PVVVYVPEGV EVRYRVWSAG
 AT.QTAKPE 
>Q57ZQ7_9TRYP
 .......... .......... ........AP YPEPGPDQTC CIILLEEKPD
 EEEYRVELIP GRVMEDGLAT GTVSGVVREE VIHGWGYSYY VVE.MEPLVT
 TRRSIRSFHR PTRFVPVPTK HF.IRYNSQL PVVVYLPHNT ELRYRVWTPI
 .DMQKVEP. 
>Q3X9L5_METFL
 .......... .......... .........P YPQPADGYQR NVIHLPMLAD
 EENTKLELQV GKTMQVDCNH HSFGATVVEH TVKGWGYPYY EVNSIGGPIS
 TRMACPSGTE TSKFV..... .......... .......... ..........
 ......... 
>Q4D4Y5_TRYCR
 .......... .......... ........AP YPEATPNQKR YVIFLEEKDE
 LEEYKLQLIP GRVMKVDVNR CFIAGSVKEK TIPGWGYNYY VVE.MGPMAT
 TLMAVPGSPP VRKFVP.MAE RPFIPYNSKL PVVVYMPKEG ELHYRVWTPT
 K........ 
>Q4QFD3_LEIMA
 .......... .......... .........P YPAAAPGQVR KVIYLPRQNE
 QQHLRVQIIP GRHENCDDGR YKLTGSVTEE TLQGWGYSYY VVT.LGDIYA
 AHRSSSDPAR ATTFV.ALDE SPVIAYNSKL PIVVYVPEGA ELRYRIWTDD
 ASLAQSIQQ 
>Q4QFF0_LEIMA
 .......... .......... ........AP YPEAEAGEKR IIFALDPKGD
 EVEQMLQLIP GRVLEMSANH QTLGGSIEQH TVEGFGAKFF HVKLAKQAVS
 TLMAEDHGEK VRKFV.AMSN APMFPYRSRY PVVVYLPKDA ELRYGIWCGG
 QQMQAA... 
>ECOT_PROMM
 .......... .......... ......DLND YPQPIAGHQR WVIQLPGLLA
 KSDWRVQLIV GRTIQLVCNQ YHLAGQLRME RFQGAEQRMY SVAGAVKVMS
 TRMVCPDEPK RESFLVLGSK PYLVPYNASF PIVVDVPDGL EVRWRLWKAE
 ITQREAI.. 
>Q57ZP2_9TRYP
 .......... .......... .......... .PSPREGERR CLFVLDPLEH
 SKDRMVELLP GRVETVDVNT YYINGCTTEE KFPGLDYTCY RVD.LRDTYR
 SRCAVPPEAP EEKFISHRHR K.LIPYNSRK PVVVYLPEDA QLHYRIWTGG
 QEVVAKKAE 
>Q3P493_9GAMM
 .......... .......... .......... .PKPTANQAV HIIKVDTLPE
 ASQYQLQVQI GLNIMQDCNQ RRLMGEVQKK TSQGVTH.YY WLESLMEAPM
 VTLPCIEAKK AT.FVQ.LGE TLLIESGEFS ENVFYLPQQA QLRYRLWRAT
 ETWQYSQ.. 
>Q2GQW8_CHAGB
 .......... .......... .......... .......... .LIALPSQLA
 E...MLNAQI GAKKNIDCNK R...DSLKDV TFNLAGYNFY ILEVSGSCIS
 TFMGM.DFPE PTGPLAILGD AFLRRYYS.. .......... ..........
 ......... 
>Q44M44_CHLLI
 .......... .......... .......... .......... ..........
 .......... .......... .......... .......... .....SGLGS
 TMMACPGLAE ESAFFKVLAD TYTIR..... .......... ..........
 ......... 
