>query  
 TVFRQENVDD YYDTGEELGS GQFAVVKKCR EKSTGLQYAA KFIKKRRTKS
 SRRGVSREDI EREVSILKEI QHPNVITLHE VYENKTDVIL ILELVAGGEL
 FDFLAEKESL TEEEATEFLK QILNGVYYLH SLQIAHFDLK PENIMLLDRN
 VPKPRIKIID FGLAHKIDFG NEFKNIFGTP EFVAPEIVNY EPLGLEADMW
 SIGVITYILL SGASPFLGDT KQETLANVSA VNYEFEDEYF SNTSALAKDF
 IRRLLVKDPK KRMTIQDSLQ HPWIKPPQF
